Allow admins to invite new users
btcpayserver/btcpayserver pull request #1886
Opened 2020-09-05 10:17 UTC by Kukks

* This refactors the email sending so that all the logic related to users and emails are now contained in one location.
* The Reset password screen has been updated from its ugly plain self to use the same layout as the login.
* An admin can now create a new account without specifying a password. A link is generated that can be given to the intended user to configure the password. If emails are configured, it also sends an email
* An admin can now create accounts that still require the user to verify their if the setting is enabled from the server settings. A link is generated that can be given to the intended user to configure the password. If emails are configured, it also sends an email.
* The above features can be used in conjunction: An email will have to verify their email through a link. Once verified, the user is redirected to setting the password.
* When an email has been verified OR a password has been set, users are now redirected to the login page with the email filled in and a success status message shown instead of a dedicated thank you page.

2020-09-14 03:50 UTC, NicolasDorier commented on BTCPayServer/HostedServices/UserEventHostedService.cs
> +                        goto passwordSetter;
( ͡° ͜ʖ ͡°)

2020-09-14 03:50 UTC, NicolasDorier commented on BTCPayServer/HostedServices/UserEventHostedService.cs
> +                        goto passwordSetter;
I shall pass it, but for that a proper method would have been more readable.

2020-09-14 03:51 UTC, NicolasDorier commented
ACK for me, but it needs a test.

2020-09-14 03:52 UTC, NicolasDorier requested changes
Need a test

2020-09-16 09:50 UTC, Kukks commented
added test @NicolasDorier

2020-09-19 02:15 UTC, merged