App: Simple Point Of Sale
btcpayserver/btcpayserver pull request #1896
Opened 2020-09-09 09:48 UTC by mariodian

resolves #481 

Simple POS that lets you add a final amount in the selected currency. 

The store's logo can be displayed in the header if set (should we use a separate logo per each POS instance instead)?

There is no arithmetics feature because there's a possibly big list of situations that would need to be taken care of (javascript's float issue, negative amounts etc).

![Screen Shot 2020-09-09 at 5 42 58 PM](https://user-images.githubusercontent.com/3636406/92582804-fe775780-f2c3-11ea-8914-cfe2c1c2b493.png)

2020-09-09 09:55 UTC, Kukks requested changes
I see you created this as an entirely new app, but it should only be a new view for the existing POS app. In the past few months, we've split the POS to support loading different views for it (static vs cart) which should allow extending for this new mode. 

A lot of the code here can be removed and reduced to mostly a new cshtml view + css/js stack

2020-09-09 09:55 UTC, Kukks commented on BTCPayServer/Controllers/AppsPublicController.cs
> +        [HttpPost]
I think we can reuse the same submission endpoint as the original POS.

2020-09-09 09:55 UTC, Kukks commented on BTCPayServer/Services/Apps/AppType.cs
> +        SimplePointOfSale
This should not be a separate app

2020-09-09 09:58 UTC, mariodian commented
I did it as a new app, because the old one is in hacky javacsript and this one is in Vue. Didn't want to mix two different frontends within a single app. 

My goal is to rewrite the old PoS into Vue at some point and then perhaps merge these two apps?

2020-09-09 10:00 UTC, mariodian commented
Also, this PoS has no inventory, unlike the old one. Not sure if mixing them together is a good idea.

2020-09-09 10:33 UTC, Kukks commented
> I did it as a new app, because the old one is in hacky javacsript and this one is in Vue. Didn't want to mix two different frontends within a single app.
> 
> My goal is to rewrite the old PoS into Vue at some point and then perhaps merge these two apps?

The views are separate so the hacky version can live standalone while the new one can be in Vue.



> Also, this PoS has no inventory, unlike the old one. Not sure if mixing them together is a good idea.

That's fine, as long as no `itemCode` is passed in the submission, the inventory system won't be used at all.

2020-09-10 03:46 UTC, mariodian commented
Ok, I’ll add it under the existing app and  (hopefully) rewrite the existing pos into vue later.

2020-09-16 09:51 UTC, closed without merging