Rename user param to userId in API key redirect
btcpayserver/btcpayserver pull request #1898
Opened 2020-09-09 17:02 UTC by dennisreimann

This way it is clearer what to expect and it also make the parameteer easier to consume.

2020-09-10 11:56 UTC, Kukks requested changes
Since it is a post (which I completely forgot), we should actually send these props in the body

2020-09-11 19:39 UTC, dennisreimann commented
![Boy, that escalated quickly](https://media.giphy.com/media/XWwIzh5GIWWf6/giphy.gif)

2020-09-11 20:01 UTC, Kukks commented on BTCPayServer/Controllers/ManageController.APIKeys.cs
> +                    return View("ConfirmAPIKey",
Why a new view?

2020-09-11 20:30 UTC, dennisreimann commented on BTCPayServer/Controllers/ManageController.APIKeys.cs
> +                    return View("ConfirmAPIKey",
1. we need to pass through the params in the form body vs. the URL query
2. preparation for adding the „create a new separate key“ button in addition to the confirm („reuse existing key“) button

2020-09-14 03:43 UTC, NicolasDorier commented
tests do not pass

2020-09-14 15:30 UTC, dennisreimann commented
The integration test failures seeem unrelated (rate providers), but I'm still unhappy about how this turned out:
https://github.com/btcpayserver/btcpayserver/blob/a37b442c9607986ab397101526573abc9a4c52c8/BTCPayServer/Views/Shared/PostRedirect.cshtml

I couldn't find a way to apply attributes conditionally and Razor wouldn't let me use the form `action` in addition to the `asp-` attributes.  Couldn't just `if` the opening tag either, so it ended up like this.

2020-09-15 08:31 UTC, dennisreimann commented on BTCPayServer.Tests/ApiKeysTests.cs
> +                //     (await apiKeyRepo.GetKey(results.Single(pair => pair.Key == "key").Value)).GetBlob().Permissions);
Not sure how to test thosee now that they are part of the POST body and we land on an external page.

2020-09-15 08:32 UTC, dennisreimann commented on BTCPayServer.Tests/SeleniumTester.cs
> +
This is related to the ChromeDriver upgrade.

2020-09-15 14:02 UTC, dennisreimann commented on BTCPayServer.Tests/ApiKeysTests.cs
> +                //     (await apiKeyRepo.GetKey(results.Single(pair => pair.Key == "key").Value)).GetBlob().Permissions);
Re-added with 3fe7515bcae457e6f9eec5c3dd6655bf46ccd13d.

2020-09-15 16:05 UTC, dennisreimann commented
Now the PR can be reviewed. The main goal was to update two things regarding the callback the consumer app receives:
- send parameters as POST body instead of as part of the URL query string
- renaming the parameters to be more clear: `user` became `userId`, `key` became `apiKey`.

While working on this I also made some minor UI updates to the confirm view:

![confirm](https://user-images.githubusercontent.com/886/93235217-87d3d180-f77d-11ea-853f-cad25869d3f1.png)

The separate confirm view got introduced to prepare the addition of a third button for the "create a new api key" button use case, which I'd like to tackle in a separate PR.

Also added a non-javascript version for the post redirect view:

![nojs](https://user-images.githubusercontent.com/886/93235340-b2258f00-f77d-11ea-875d-aea18e2e7b41.png)

2020-09-15 16:10 UTC, dennisreimann commented on BTCPayServer/Controllers/HomeController.cs
> +
I saw that there is the `#if DEBUG` conditional. If this also works for the tests or there is something similar for those, wee could use this here too.

2020-09-16 09:58 UTC, Kukks commented on BTCPayServer/Controllers/HomeController.cs
> +
you can use it there for tests

2020-09-16 10:09 UTC, Kukks requested changes

2020-09-16 10:09 UTC, Kukks commented on BTCPayServer/BTCPayServer.csproj
> +    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="85.0.4183.8700" />
remove please

2020-09-16 10:09 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.authorization.json
> +                        "description": "Redirects to the specified url in `redirect` with query string values for `apiKey` (the api key created or matched), `permissions` (the permissions the user co
```suggestion
                        "description": "Makes browser do an HTTP POST request to the specified url in `redirect` with a JSON body consisting of `apiKey` (the api key created or matched), `permissions` (the permissions the user consented to), and `userId` (the id of the user that consented) upon consent"
```

2020-09-16 10:30 UTC, dennisreimann commented on BTCPayServer/Controllers/HomeController.cs
> +
Added, thanks!

2020-09-17 09:37 UTC, Kukks approved these changes

2020-09-17 09:37 UTC, merged