Shopify registering paid transactions, marking orders paid, finishing integration
btcpayserver/btcpayserver pull request #1908
Opened 2020-09-14 04:57 UTC by rockstardev

Fix: #1850

WIP

2020-09-15 07:36 UTC, pavlenex commented
uTACK. Looks good to me @rockstardev, great work. I haven't tested it but according to the video, the workflow is very smooth.

- Would it be possible to add/mention [other integrations](https://docs.btcpayserver.org/WooCommerce/ (Woo, Joomla, etc) in Store > Integrations?
- I think we can use your workflow descriptions for the Shopify Documentation #[668](https://github.com/btcpayserver/btcpayserver-doc/issues/668)

2020-09-15 12:25 UTC, NicolasDorier commented
@rockstardev what happen in case of double spend?

If the order is still marked as paid even if double spent, then it need to have a warning in the integration shopify page.

2020-09-15 12:26 UTC, NicolasDorier commented on BTCPayServer/wwwroot/shopify/btcpay-browser-client.js
> +                            if (invoice.status === "complete" || invoice.status === "paid") {
whant about `confirmed` ?

2020-09-15 15:49 UTC, NicolasDorier commented on BTCPayServer/Services/Shopify/ShopifyApiClient.cs
> +            dynamic parsed = JObject.Parse(strResp);
Please avoid dynamic. Got bit too many time by strange behavior is some situation with it :/

2020-09-17 04:44 UTC, rockstardev commented on BTCPayServer/wwwroot/shopify/btcpay-browser-client.js
> +                            if (invoice.status === "complete" || invoice.status === "paid") {
ca0969ba28f2c938db3cab3d9281a9d02036e461

2020-09-17 05:13 UTC, rockstardev commented on BTCPayServer/Services/Shopify/ShopifyApiClient.cs
> +            dynamic parsed = JObject.Parse(strResp);
b4a2dc79c6d52fd88e7b07b5eecb739dd980bcef

2020-09-17 10:07 UTC, Kukks requested changes
I think the invoice creation part should be changed to use pay-requests which will manage multiple invoices per order on its own. It'll also remove the need to  enable the pay button endpoint which is probably a good thing for merchants.

2020-09-17 10:07 UTC, Kukks commented on BTCPayServer/wwwroot/shopify/btcpay-shopify-checkout.js
>      const BTCPAYSERVER_URL = "FULL_BTCPAYSERVER_URL_WITH_HTTPS";
Maybe we can make an endpoint that serves this all prefilled from integrations/shopify?

2020-09-17 10:07 UTC, Kukks commented on BTCPayServer/wwwroot/shopify/btcpay-browser-client.js
>                  var interval = setInterval(function () {
You should use setTimeout instead of setInterval as it's been known to cause memory leaks

2020-09-18 10:52 UTC, NicolasDorier commented
tests seems to fail

2020-09-18 10:58 UTC, Kukks commented
I am doing changes, please do not merge

2020-09-23 05:31 UTC, NicolasDorier commented on BTCPayServer/Controllers/StoresController.Integrations.cs
> +                TextSearch = invoiceOrderId
Since we know the StoreId, you should add storeId here.

2020-09-23 05:32 UTC, NicolasDorier commented on BTCPayServer/Controllers/StoresController.Integrations.cs
> +            [FromServices] IHttpClientFactory httpClientFactory,
most of those services are probably already in the scope as field of StoresController.

2020-09-23 05:52 UTC, rockstardev reviewed
@Kukks changes look great, we've already talked on final touches from my POV on Mattermost.

2020-09-25 19:09 UTC, rockstardev commented on BTCPayServer/Controllers/StoresController.Integrations.cs
> +                TextSearch = invoiceOrderId
a7d7b5abc33092949be205f1da3746ccef4f37af

2020-09-25 19:14 UTC, rockstardev commented on BTCPayServer/Controllers/StoresController.Integrations.cs
> +            [FromServices] IHttpClientFactory httpClientFactory,
Just `StoreRepository` ;(... removed it: eb6b1b431cca221b01a481def5c29b6a5fd1c753

2020-09-25 19:15 UTC, rockstardev commented
OK, if there are no additional complaints in next hour, I'm merging this in order to get it in for next release.

2020-09-25 19:26 UTC, rockstardev commented on BTCPayServer/Services/Shopify/ApiModels/TransactionsCreateReq.cs
> +            public string currency { get; set; }
Lowercase properties surviving for now... can be part of additional PR.

2020-09-26 18:06 UTC, pavlenex commented on BTCPayServer/Views/Stores/Integrations/Shopify.cshtml
> +            In Shopify please add a payment method at <a target="_blank" href="https://satoshis-bakery.myshopify.com/admin/settings/payments" class="font-weight-bold"> Settings &gt; Payments &gt; Man
@rockstardev are you sure this part is correct? `ref="https://satoshis-bakery.myshopify.com/admin/settings/payments`

2020-09-26 18:29 UTC, rockstardev commented on BTCPayServer/Views/Stores/Integrations/Shopify.cshtml
> +            In Shopify please add a payment method at <a target="_blank" href="https://satoshis-bakery.myshopify.com/admin/settings/payments" class="font-weight-bold"> Settings &gt; Payments &gt; Man
Great catch bf7c8d5a5c6d0c69014dd0d9b6f088645bdb23cd

2020-09-30 02:23 UTC, merged