App: Light PoS on top of the existing PoS
btcpayserver/btcpayserver pull request #1909
Opened 2020-09-14 08:10 UTC by mariodian

resolves #481 and closes #1896

Unlike in #1896, the Light PoS now uses the existing PoS code so mostly just the frontend code was added. 

The only thing that's changed on the frontend side is that I added BTCPay logo at the bottom so it's in line with the existing Cart PoS' design.

2020-09-14 08:16 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/MinimalLight.cshtml
> +@using Microsoft.CodeAnalysis.CSharp.Syntax
Btw I'm not sure what this is for. I took it from the crowdfund minimal template. I suppose it doesn't need to be there?

2020-09-14 08:44 UTC, Kukks requested changes
Awesome, thanks for switching over. Got a few points to take care of.

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +        <svg class="logo" viewBox="0 0 192 84" xmlns="http://www.w3.org/2000/svg"><g><path d="M5.206 83.433a4.86 4.86 0 01-4.859-4.861V5.431a4.86 4.86 0 119.719 0v73.141a4.861 4.861 0 01-4.86 4.861"
no inline svgs please

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/wwwroot/light-pos/app.js
> +                setTimeout(function(){
you can use `this.$nextTick` instead

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/MinimalLight.cshtml
> +@using Microsoft.CodeAnalysis.CSharp.Syntax
yeah looks like junk

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/bundleconfig.json
> +            "wwwroot/vendor/bootstrap-vue/bootstrap-vue.js",
I dont think we need bootstrap vue?

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/wwwroot/light-pos/app.js
> +                eventAggregator.$emit("clearClicked");
if you use `this.$emit`, you can use `@clearClicked="xxx()"`  on `<keypad>`

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +<script type="text/x-template" id="display-template">
instead of separate script templates, you can write the template directly where the component is used and add attribute `inline-template`. This probablt makes mor sense since these components are only meant to be used once

2020-09-14 08:44 UTC, Kukks commented on BTCPayServer/wwwroot/light-pos/app.js
> +var eventAggregator = new Vue();
Most likely dont need a global event aggregator, everything can be bubbled up the component tree or binded

2020-09-14 08:46 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +        <svg class="logo" viewBox="0 0 192 84" xmlns="http://www.w3.org/2000/svg"><g><path d="M5.206 83.433a4.86 4.86 0 01-4.859-4.861V5.431a4.86 4.86 0 119.719 0v73.141a4.861 4.861 0 01-4.86 4.861"
The inline svg is also used in the original PoS, though.

2020-09-14 08:48 UTC, mariodian commented on BTCPayServer/bundleconfig.json
> +            "wwwroot/vendor/bootstrap-vue/bootstrap-vue.js",
Yup, we don't.

2020-09-14 08:51 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +<script type="text/x-template" id="display-template">
Seems that `inline-template` is no longer supported in 3.x https://v3.vuejs.org/guide/migration/inline-template-attribute.html#overview

2020-09-14 09:00 UTC, mariodian commented on BTCPayServer/wwwroot/light-pos/app.js
> +                eventAggregator.$emit("clearClicked");
`clearClicked` is not part of the <keypad> component though. Not exactly sure what you want me to do here?

2020-09-14 09:05 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +        <svg class="logo" viewBox="0 0 192 84" xmlns="http://www.w3.org/2000/svg"><g><path d="M5.206 83.433a4.86 4.86 0 01-4.859-4.861V5.431a4.86 4.86 0 119.719 0v73.141a4.861 4.861 0 01-4.86 4.861"
Yeah, we should move that eventually too

2020-09-14 09:05 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +<script type="text/x-template" id="display-template">
ah damn, that's a shame

2020-09-14 09:07 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +        <keypad :keys="keys"></keypad>
You would add `@clearClicked="clearTotal"` here

2020-09-14 09:07 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +<script type="text/x-template" id="display-template">
However, if there's no need to support vue 3.x any time soon, I can do it through inline template. Up to you.

2020-09-14 09:25 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +        <keypad :keys="keys"></keypad>
I get the following error:
The name `'clearClicked'` does not exist in the current context.

Can you please tell me what the "@" thing is so I can look it up in the documentation? thanks!

2020-09-14 09:33 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +        <keypad :keys="keys"></keypad>
it's a shorthand for `v-on:clearClicked` 
the error you're getting is c# thinking the vue code is c# syntax
You can escape with `@@`

2020-09-14 09:34 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +<script type="text/x-template" id="display-template">
It's fine, best be ready to switch eventually

2020-09-15 05:06 UTC, mariodian commented
Thanks for adding your changes. If you don't mind I'll fix a bug where the display's font size doesn't reset on pressing the "clear" button.

I'm also thinking should we add a native decimal separator? Some currencies use comma instead of period. But then how far would we want to go in formatting the amount? Not sure if we should overcomplicating it, since this is a product for vendors not the end users.

2020-09-15 05:17 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/MinimalLight.cshtml
> +        <div class="text-center mt-5 mb-3 bg-dark text-white ">
I know you wanted to add a clear border to the app, but shouldn't there be at least a small padding (py-1 or py-2) so that the logo isn't touching the box?

<img width="504" alt="Screen Shot 2020-09-15 at 1 07 21 PM" src="https://user-images.githubusercontent.com/3636406/93168031-8a6e0100-f754-11ea-8c6b-b5b3a90a2320.png">

Also `text-white` isn't necessary on `bg-dark`. The text color will always be inverted, plus some themes rewrite the color of the background to a lighter one so `text-white` would make the text invisible.

2020-09-15 05:17 UTC, mariodian commented on BTCPayServer/bundleconfig.json
> -            "wwwroot/vendor/babel-polyfill/polyfill.min.js",
Don't we need polyfill for old browsers?

2020-09-15 05:17 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +    <div class="text-center mt-4 mb-3 bg-dark text-white" >
The same goes for the padding and `bg-dark/text-white` issue here.

2020-09-16 09:52 UTC, Kukks commented on BTCPayServer/bundleconfig.json
> -            "wwwroot/vendor/babel-polyfill/polyfill.min.js",
nah, the polyfill was only there for bootstrap vue as it did not transpile stuff down to es5

2020-09-16 09:52 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/MinimalLight.cshtml
> +        <div class="text-center mt-5 mb-3 bg-dark text-white ">
Can you change it? It's also the same in the pos cart view

2020-09-16 09:52 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/PointOfSale/VueLight.cshtml
> +    <div class="text-center mt-4 mb-3 bg-dark text-white" >
Can you change it? It's also the same in the pos cart view

2020-09-16 09:54 UTC, Kukks approved these changes
From my end, it should be good enough for a first release. There's only those 2 css classes that you wanted changed. Good job!

2020-09-16 10:08 UTC, mariodian commented on BTCPayServer/Views/AppsPublic/PointOfSale/MinimalLight.cshtml
> +        <div class="text-center mt-5 mb-3 bg-dark text-white ">
Ok I will

2020-09-16 10:09 UTC, mariodian commented
I'll make the changes, likely tmrw.

2020-09-18 08:31 UTC, mariodian commented on BTCPayServer/wwwroot/light-pos/app.js
> +    var displayFontSize = 80;
I'm thinking, this probably shouldn't be outside of the app?

2020-09-18 09:43 UTC, Kukks commented on BTCPayServer/wwwroot/light-pos/app.js
> +    var displayFontSize = 80;
yeah this should be reverted

2020-09-19 03:51 UTC, mariodian commented on BTCPayServer/wwwroot/light-pos/app.js
> +    var displayFontSize = 80;
However, I need to work with the default font size var in a few places within the app so should I just put it in `data`? Not sure how it's best done in Vue? Don't want to hardcode the value.

2020-09-19 06:54 UTC, mariodian commented on BTCPayServer/wwwroot/light-pos/app.js
> +    var displayFontSize = 80;
I put it inside `data()`

2020-09-21 06:06 UTC, merged