Changelog 1.0.5.6
btcpayserver/btcpayserver pull request #1927
Opened 2020-09-25 07:53 UTC by NicolasDorier

Still want to add #1908 and #1841 before release

2020-09-25 10:05 UTC, Kukks requested changes

2020-09-29 03:50 UTC, NicolasDorier commented
Should we include https://github.com/btcpayserver/btcpayserver/pull/1930 ?

2020-09-29 08:39 UTC, dennisreimann commented
@NicolasDorier It's not fully implemented yet (pull payments UI missing) and given the variety of different states we should test, I think we should not rush it.

2020-09-29 08:49 UTC, pavlenex commented
I think it's best we leave out the #1930, as the time-frame is short and as Dennis mentioned we need a bit more time to test it out, so best not to rush it (we have plenty of interesting stuff ready for the release on Thursday already).

2020-09-30 05:57 UTC, Kukks commented on Changelog.md
> +* Improve invoices list view #1815 @dennisreimann
```suggestion
* Improve invoices list view #1815 @dennisreimann
* Improve sync progress dialog #1929 @Kukks 
```

2020-10-01 11:06 UTC, merged