Payment redesign
btcpayserver/btcpayserver pull request #1930
Opened 2020-09-28 14:58 UTC by dennisreimann

This PR addresses #1719. Right now it's in draft state, as the pull payments redesign isn't done yet.

The payment request part is done and I'd invite feedback, especially since a lot of different states are involved and the design differs across the breakpoints (see layouts in Figma).

Things to test:
- States: Pending, Expired, Settled + Archived
- Payments: None, Partially Paid, cancelled payment, fully paid
- Different breakpoints
- JavaScript: On and Off

## Light

![light](https://user-images.githubusercontent.com/886/94448970-d46ed200-01ab-11eb-9b49-f3f09f7a3d52.png)

## Dark

![dark](https://user-images.githubusercontent.com/886/94448816-a6898d80-01ab-11eb-8cec-f3c68ccb8388.png)

2020-09-28 15:05 UTC, Kukks requested changes
just some initial comments, will test a bit deeper tom. This is awesome!

2020-09-28 15:05 UTC, Kukks commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +    <bundle name="wwwroot/bundles/payment-request-bundle.min.css" asp-append-version="true"></bundle>
please remove `asp-append-version="true"` Bundles have their own internal versioning system

2020-09-28 15:05 UTC, Kukks commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +    <noscript>
Should these really be wrapped in `noscript`?

2020-09-28 15:05 UTC, Kukks commented on BTCPayServer/Views/Shared/Header.cshtml
> +@* Non-JS *@
Should these really be wrapped in noscript?

2020-09-28 15:05 UTC, Kukks commented on BTCPayServer/bundleconfig.json
> +        "outputFileName": "wwwroot/bundles/payment-request-bundle.min.js",
The reason this was split in 2 was because momentjs had issues with the minification process.

2020-09-28 15:17 UTC, dennisreimann commented on BTCPayServer/bundleconfig.json
> +        "outputFileName": "wwwroot/bundles/payment-request-bundle.min.js",
Hmm, do you remember what this was about? I didn't see anything strange.

2020-09-28 15:18 UTC, dennisreimann commented on BTCPayServer/Views/Shared/Header.cshtml
> +@* Non-JS *@
Yes, that's on purpose. These styles are the `noscript`-inverse of what's defined e.g. [here](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/wwwroot/main/site.css#L16).

2020-09-28 15:18 UTC, dennisreimann commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +    <noscript>
See [this comment](https://github.com/btcpayserver/btcpayserver/pull/1930#discussion_r496030565).

2020-09-28 17:48 UTC, dstrukt commented
Beautiful!! @dennisreimann 

Only concerns I have are how it currently looks on mobile.

Otherwise the only thing coming to mind is the current border-radius, is it currently 4px? I would bump it up to 8px if so.

2020-09-28 18:13 UTC, dennisreimann commented
>  Only concerns I have are how it currently looks on mobile.

What especially? Will test on an actual device tomorrow, have just used the desktop browser preview until now …

> Otherwise the only thing coming to mind is the current border-radius, is it currently 4px? I would bump it up to 8px if so.

For now, let's use what the current Bootstrap has to offer. Everything else that targets more overarching changes should be postponed to after the [Bootstrap 5 migration](https://github.com/btcpayserver/btcpayserver/issues/1866) imho.

2020-09-28 18:20 UTC, dstrukt commented
Oh, just wanted to see a screenshot or two, not worried about anything in particular.

Sounds good - I figured you probably made that conscious decision, but wanted to confirm.

2020-09-28 20:30 UTC, dstrukt commented
Seeing it implemented, I'm wondering if we want to switch "Expiry" and "Price"? Might be easier to parse scanning the page from top to bottom with the price on the right as well...

Thoughts?

2020-09-29 09:16 UTC, pavlenex commented
Took a quick glance in dev env.

Two notes:
1. I don't get pay button anywhere for some reason (regardless of the theme.
![Screenshot 2020-09-29 at 11 12 29](https://user-images.githubusercontent.com/36959754/94538899-df297580-0244-11eb-86b6-ff3a88c9c7f1.png)
2. Would be good to give some sort of indicator once `Copy link` is clicked that it's copied to clipboard.
3. 
![Screenshot 2020-09-29 at 11 15 41](https://user-images.githubusercontent.com/36959754/94539187-30396980-0245-11eb-8c49-e04597f8da9a.png)
`Expires in 12 hours
Expires on 09/29/2020 22:00 ` seems redundant, maybe move `
Expires on 09/29/2020 22:00` to appear on hover when over `Expires in 12 hours`

2020-09-29 09:19 UTC, dennisreimann commented
> I don't get pay button anywhere for some reason (regardless of the theme.

Can you pull again? There was an erroneous if-condition in the JS-version which I fixed with 
8fca813

2020-09-29 17:25 UTC, dstrukt commented
Small suggestion (will try to include all empty states in future design considerations).

Change "no payments made yet" to our grey, and add like 16px of padding to the top.

Otherwise, god damn this is looking fantastic! I'm so excited for BS-5 integration.

2020-09-30 06:17 UTC, Kukks commented on BTCPayServer/bundleconfig.json
> +        "outputFileName": "wwwroot/bundles/payment-request-bundle.min.js",
momentjs wasnt happy being minified, caused the bundle to blow up when used (may need to test it with Release profile)

2020-09-30 10:11 UTC, dennisreimann commented
@dstrukt I updated the emptystate to not display the table at all. This is the direction we are going elsewhere too and I think that makes the most sense.

## Empty

![empty](https://user-images.githubusercontent.com/886/94672755-fe440800-0315-11eb-9da2-f79ce25c3e6a.png)

## Partially paid

![partial](https://user-images.githubusercontent.com/886/94672778-07cd7000-0316-11eb-8d5b-19f8737fde24.png)

2020-09-30 10:14 UTC, dennisreimann commented
@dstrukt @pavlenex In 30ce87c I've decreased the opacity of the checkout modal, because imho it lacked focus, especially in light mode. What do you think?

## Before

![before](https://user-images.githubusercontent.com/886/94672996-5c70eb00-0316-11eb-8a11-fd2a658b31e7.png)

## After - Light

![light](https://user-images.githubusercontent.com/886/94673005-5d098180-0316-11eb-8afa-a741b678d3ac.png)

## After - Dark

![dark](https://user-images.githubusercontent.com/886/94672992-5a0e9100-0316-11eb-906a-e56c53a5c469.png)

2020-09-30 10:23 UTC, pavlenex commented
Looks great, I like how it makes you more focused on the invoice/payment part.
I have yet to test on the latest commit, will try to do that no later than Friday, as soon as we're done with the release ^^

2020-09-30 10:31 UTC, dennisreimann commented
@pavlenex I'll hopefully finish the pull payments part until Friday, let's review this alltogether then. No need to rush – looking forward to the release :)

2020-09-30 17:23 UTC, dennisreimann commented
Now the pull payment view is also done.

The layouts contain a description, similar to the payment requests. We don't have this field for pull payments, neevertheless the box works here too as it contains the pull payment information like title, update and expiration.

The header is sticky like with the payment request. Once the pull payment has no remaining amount the header is omitted. 

## Dark – Empty state 

![dark-lg](https://user-images.githubusercontent.com/886/94718270-cf4b8780-0351-11eb-83c9-3392d91fbcb4.png)

![dark-md](https://user-images.githubusercontent.com/886/94718274-d07cb480-0351-11eb-93cb-8e3167013ab6.png)

![dark-mm](https://user-images.githubusercontent.com/886/94718279-d1ade180-0351-11eb-9861-5366a5f37733.png)


## Partially paid

![light-partially](https://user-images.githubusercontent.com/886/94718528-23566c00-0352-11eb-9f5a-582fca9807bc.png)

![dark-partially](https://user-images.githubusercontent.com/886/94718538-25b8c600-0352-11eb-88a1-7804a937f4a7.png)

## Error Message

![err](https://user-images.githubusercontent.com/886/94718670-5a2c8200-0352-11eb-81a7-105347039801.png)

## Done

![done-lg](https://user-images.githubusercontent.com/886/94718692-631d5380-0352-11eb-94c8-99e2b43ed1a7.png)

![done-sm](https://user-images.githubusercontent.com/886/94718688-61539000-0352-11eb-81c9-c90c93ad36de.png)

2020-09-30 21:04 UTC, dstrukt commented
1. Love removing the table, and completely agree, been removing it in designs - just wasn't sure how easy it was for you at this stage.

2. Also agree on the scrim overlay, the latest version looks much better!

3. The margin on the top of the dismissible alert is correct, and should also be reflected the same on the bottom, currently it looks like a little bit more on the bottom.

4. Would definitely like to push for an *optional description field for pull payments @Kukks 

5. Can we right text-align the "Claim Limit" and "Total Requested" text and amount on both pull and push?

6. On dark mode for the payment progress - "progress bar" can we use the background grey we're using for the expanded TX list for the unpaid bar (before it becomes green when paid)?

7. Not sure what the padding is on the BTC pill for TX address header, but can we add 4px to the right and left of the "BTC" text?

---- 

I've definitely got some more thoughts are state/status for these when moving into BS5, but it's incredibly exciting seeing this get implemented. Excellent work @dennisreimann!

2020-10-01 16:28 UTC, dennisreimann commented on BTCPayServer/bundleconfig.json
> +        "outputFileName": "wwwroot/bundles/payment-request-bundle.min.js",
Looks like problem is resolved by now – at last I can build and run the release profile without errors.

2020-10-01 16:29 UTC, dennisreimann commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +    <bundle name="wwwroot/bundles/payment-request-bundle.min.css" asp-append-version="true"></bundle>
We have this for all bundles and would need to change this for all bundles in this case … it's not just something I introduced with this PR. Shall I removed it?

![bundles](https://user-images.githubusercontent.com/886/94837082-1437f280-0414-11eb-9d70-0314f207af43.jpg)

2020-10-01 18:49 UTC, dennisreimann commented
> The margin on the top of the dismissible alert is correct, and should also be reflected the same on the bottom, currently it looks like a little bit more on the bottom.

Updated with 525f0aff6a73ec82ca255aad2d4fd82c79fbb65b

<img width="577" alt="margin" src="https://user-images.githubusercontent.com/886/94850426-37b86880-0427-11eb-8e39-c1842faef202.png">


> Would definitely like to push for an *optional description field for pull payments

Is it this relevant? For pull payments that'd be info that the merchant would have to provide?

2020-10-01 19:03 UTC, dennisreimann commented
> Can we right text-align the "Claim Limit" and "Total Requested" text and amount on both pull and push?

> On dark mode for the payment progress - "progress bar" can we use the background grey we're using for the expanded TX list for the unpaid bar (before it becomes green when paid)?

Done with c8e093d and 5776d97.

<img width="570" alt="totals" src="https://user-images.githubusercontent.com/886/94851881-561f6380-0429-11eb-861b-94b23f70e6e8.png">






> Not sure what the padding is on the BTC pill for TX address header, but can we add 4px to the right and left of the "BTC" text?

Yes, we can – and do! a2eaeeb

<img width="495" alt="padding" src="https://user-images.githubusercontent.com/886/94851953-751df580-0429-11eb-9f57-08a7408e9695.png">

2020-10-01 19:38 UTC, dennisreimann commented
Rebased and incorporated all of @dstrukt's feeedback. 

It's ready for final review now :)

2020-10-01 21:59 UTC, dstrukt commented
> > The margin on the top of the dismissible alert is correct, and should also be reflected the same on the bottom, currently it looks like a little bit more on the bottom.
> 
> Updated with [525f0af](https://github.com/btcpayserver/btcpayserver/commit/525f0aff6a73ec82ca255aad2d4fd82c79fbb65b)
> 
> <img alt="margin" width="577" src="https://user-images.githubusercontent.com/886/94850426-37b86880-0427-11eb-8e39-c1842faef202.png">
> 
> > Would definitely like to push for an *optional description field for pull payments
> 
> Is it this relevant? For pull payments that'd be info that the merchant would have to provide?

Looks great -- and yes, it would be an optional field for the merchant to provide further context on the pull payment, in the same way the payment request works (AFAIA).

Love all the latest changes to my suggestions - send it!

2020-10-02 02:56 UTC, dstrukt commented
> 2. Would be good to give some sort of indicator once `Copy link` is clicked that it's copied to clipboard.

Agreed, we have that same functionality for copying the Tor link on login/signup as well, would be good to add it in both places.

"*checkmark icon* Link copied!" then after X seconds it goes back to "Copy link"

2020-10-03 15:10 UTC, dennisreimann commented
Copy link confirmation added.

![copy](https://user-images.githubusercontent.com/886/94994960-458efa80-059b-11eb-9f74-6c2eec20f00d.gif)

![register](https://user-images.githubusercontent.com/886/94994956-432ca080-059b-11eb-8fd5-ea3331877c12.gif)

2020-10-03 22:13 UTC, dstrukt commented
Nice - looks great!

2020-10-07 10:27 UTC, pavlenex commented
**tACK.** 
Unsure why tests are failing, but this is a pure masterpiece. I know you won't believe this one, but I have no suggestions or complaints. 

Great work guys. 🚀 🎉 

![Screenshot 2020-10-07 at 12 14 12](https://user-images.githubusercontent.com/36959754/95319529-4de77e00-0898-11eb-8006-dd6cb065adfb.png)
![Screenshot 2020-10-07 at 12 15 14](https://user-images.githubusercontent.com/36959754/95319541-50e26e80-0898-11eb-942c-40097f93bbce.png)
![Screenshot 2020-10-07 at 12 16 30](https://user-images.githubusercontent.com/36959754/95319542-52139b80-0898-11eb-8c3c-7d8e9401f22a.png)
![Screenshot 2020-10-07 at 12 23 46](https://user-images.githubusercontent.com/36959754/95319543-52ac3200-0898-11eb-9029-bb3d0526cb1d.png)

2020-10-07 10:43 UTC, dennisreimann commented
> Great work guys. 🚀 🎉

Thanks @pavlenex – and first and foremost thanks @dstrukt for providing this beauty 👌

> I know you won't believe this one, but I have no suggestions or complaints.

Must be the reason why the test are failing 😂

Nope, it's just flaky and unrelated, seen this before:

```
  X CanUsePoSApp [2s 139ms]
  Error Message:
   The collection was expected to contain a single element, but it contained more than one element.
  Stack Trace:
     at BTCPayServer.Tests.AltcoinTests.CanUsePoSApp() in /source/BTCPayServer.Tests/AltcoinTests/AltcoinTests.cs:line 812
```

2020-10-07 22:56 UTC, dstrukt commented
🍻 

Looking forward to the regular cadence of awesome releases!

2020-10-07 23:01 UTC, Eskyee commented
🛰 Ooooh yeah .. team on fiyaaaa

2020-10-08 03:10 UTC, merged

2020-10-08 06:38 UTC, Kukks commented
@dennisreimann  can you create a new PR from this branch? I dont think we can recover this one after merge +revert. :(

2020-10-08 10:37 UTC, dennisreimann commented on BTCPayServer/Controllers/PullPaymentController.cs
> +                              Status = Regex.Replace(entity.Entity.State.ToString(), "(\\B[A-Z])", " $1"),
Thanks, used the implementation straight from your commit.

2020-10-08 20:36 UTC, dennisreimann commented on BTCPayServer/wwwroot/payment-request/app.js
> +            copyLink: function (e) {
Done with https://github.com/btcpayserver/btcpayserver/pull/1967/commits/a37a42b10c07bb1ff0458e5705482a1da989d0e0

2020-10-08 20:36 UTC, dennisreimann commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +        document.getElementById("copyLink").addEventListener("click", function (e) {
Yes. https://github.com/btcpayserver/btcpayserver/pull/1967/commits/a37a42b10c07bb1ff0458e5705482a1da989d0e0

2020-10-08 20:44 UTC, dennisreimann commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +                                                        switch (invoice.Status)
This case isn't about readable text – it switched the html classname that's used for the text. As this is purely markup related I thought it might fit here. What's the proper way to do this? Still an extension method?

2020-10-09 14:15 UTC, dennisreimann commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +                                                        switch (invoice.Status)
[Made it a helper function](https://github.com/btcpayserver/btcpayserver/pull/1967/commits/33f741896fe27c708fba94130f75e21cc8ef6e94), as this seems appropriate to me.