Add Zammad Support Ticket Bridge
btcpayserver/btcpayserver pull request #1935
Opened 2020-10-04 07:25 UTC by xpayserver

2020-10-04 07:44 UTC, britttttk commented
is this feature only useful for third party hosts?

2020-10-04 07:53 UTC, xpayserver commented
main use yes but you can use as store owner for customers support if need with small changes

2020-10-04 08:18 UTC, mariodian commented
Any 3rd party code implementation should definitely be an extension once #1925 gets merged.

2020-10-05 10:07 UTC, Kukks requested changes
I dont think this makes sense to merge since it's such a niche use-case. #1925 to the rescue though

2020-10-05 16:30 UTC, pavlenex commented on BTCPayServer/Views/Shared/LayoutPartials/ZammadNavExtension.cshtml
> +@if (User.IsInRole(Roles.ServerAdmin) || (MemoryCache.TryGetValue(nameof(ZammadOptions), out var options) && options is ZammadOptions zammadOptions && zammadOptions.Configured))
I think it's good, you'd want quick way to check support tickets daily.

2020-10-06 05:51 UTC, Kukks commented on BTCPayServer/Views/Shared/LayoutPartials/ZammadNavExtension.cshtml
> +@if (User.IsInRole(Roles.ServerAdmin) || (MemoryCache.TryGetValue(nameof(ZammadOptions), out var options) && options is ZammadOptions zammadOptions && zammadOptions.Configured))
Yeah but it actually shows it 100% of the time once it is merged if you are an admin (so that you can configure it and then it will show up for other users)

2020-10-24 15:23 UTC, NicolasDorier commented
might be good use case for a plugin.

2020-10-26 15:30 UTC, pavlenex commented
@xpayserver would you be interested in packing this as a plugin? Perhaps also #1910?

2020-11-17 08:00 UTC, Kukks commented
DM me on chat, let's try and turn this into a plugin. Closing here until then

2020-11-17 08:00 UTC, closed without merging