Update PayButtonEnable.cshtml
btcpayserver/btcpayserver pull request #1952
Opened 2020-10-06 17:16 UTC by sgracia13

Edit PayButton Title

2020-10-07 04:24 UTC, britttttk commented
closes #1940

2020-10-07 08:03 UTC, dennisreimann approved these changes
Works, thank you! 🍰 

![after](https://user-images.githubusercontent.com/886/95304000-3d2d0d00-0884-11eb-9ac8-72a953c327db.png)

2020-10-07 08:12 UTC, pavlenex commented
Hey @sgracia13 congrats on your first PR. 🎉 

Was just testing this and on my end it looks like this when outside invoices aren't allowed. 
![Screenshot 2020-10-07 at 10 09 10](https://user-images.githubusercontent.com/36959754/95304710-4ff41180-0885-11eb-8a74-8dae3a35cae3.png)
`Pay Button: PayButton` in H2.

However when that button is clicked as Dennis mentioned then it's good.
![Screenshot 2020-10-07 at 10 11 20](https://user-images.githubusercontent.com/36959754/95304909-95184380-0885-11eb-9914-704a2cd28d97.png)

Can you please change the H2 tile of the above screenshot to make it consistent?

2020-10-07 08:22 UTC, dennisreimann commented on BTCPayServer/Views/Stores/PayButtonEnable.cshtml
>      ViewBag.MainTitle = "Pay Button";
```suggestion
```

@sgracia13 You can delete this line, then we are good to go 👍 

![pay](https://user-images.githubusercontent.com/886/95305843-d65d2300-0886-11eb-9043-e5bb765dc2d4.png)

2020-10-08 12:53 UTC, mariodian commented on BTCPayServer/Views/Stores/PayButtonEnable.cshtml
> +    ViewData.SetActivePageAndTitle(StoreNavPages.PayButton);
I think this should be: `ViewData.SetActivePageAndTitle(StoreNavPages.PayButton, "Outside Access");` or something along the lines to make it clear what page you're on.

2020-10-10 12:46 UTC, Kukks requested changes

2020-10-10 12:46 UTC, Kukks commented on BTCPayServer/Views/Stores/PayButtonEnable.cshtml
> +    ViewData.SetActivePageAndTitle(StoreNavPages.PayButton);
the title setter below overrides it

2020-10-10 12:46 UTC, Kukks commented on BTCPayServer/Views/Stores/PayButtonEnable.cshtml
>      ViewBag.MainTitle = "Pay Button";
should be part of `SetActivePageAndTitle`

2020-10-10 12:47 UTC, Kukks approved these changes

2020-10-11 03:35 UTC, bolatovumar approved these changes

2020-10-11 15:45 UTC, Kukks requested changes

2020-10-11 15:45 UTC, Kukks commented on BTCPayServer/Views/Stores/PayButtonEnable.cshtml
> +    ViewBag.Title = "Pay Button";
```suggestion
```

2020-10-11 15:45 UTC, Kukks commented on BTCPayServer/Views/Stores/PayButtonEnable.cshtml
> +    ViewData.SetActivePageAndTitle(StoreNavPages.PayButton);
```suggestion
    ViewData.SetActivePageAndTitle(StoreNavPages.PayButton, "Pay Button");
```

2020-10-11 15:45 UTC, Kukks approved these changes

2020-10-11 15:46 UTC, merged