Checkout: Overlay improvement and markup fixes
btcpayserver/btcpayserver pull request #1968
Opened 2020-10-08 20:39 UTC by dennisreimann

More focus, as discussed in #1930 ([comment](https://github.com/btcpayserver/btcpayserver/pull/1930#issuecomment-701298441))

2020-10-11 08:25 UTC, Kukks requested changes
There's something wrong with the branch, the PR says there are no changes

2020-10-11 08:26 UTC, Kukks commented
Maybe you need to cherrypick the commits onto a fresh branch on master

2020-10-11 20:19 UTC, dennisreimann commented
Weird, something was messed up here – corrected.

2020-10-11 20:57 UTC, bolatovumar approved these changes

2020-10-12 15:52 UTC, Kukks approved these changes

2020-10-12 15:52 UTC, merged