Allow changing block explorer
btcpayserver/btcpayserver pull request #1981
Opened 2020-10-14 07:01 UTC by Kukks

closes #1953

2020-10-14 07:07 UTC, NicolasDorier commented on BTCPayServer/Hosting/BTCPayServerServices.cs
> +                app.ApplicationServices.GetService<BTCPayNetworkProvider>()).GetAwaiter().GetResult();
pas de  `.GetAwaiter().GetResult()`, ca fini toujours par des probleme a un moment ou a un autre

2020-10-14 07:08 UTC, NicolasDorier commented on BTCPayServer/Views/Server/_Nav.cshtml
> +    <a asp-controller="Server" id="Server-@ServerNavPages.ExplorerLinks" class="nav-link @ViewData.IsActivePage(ServerNavPages.ExplorerLinks)" asp-action="UpdateExplorerLinks">Blockchain Explorer Lin
instead of dedicated page, can you put in Policies?

2020-10-14 07:12 UTC, Kukks commented on BTCPayServer/Hosting/BTCPayServerServices.cs
> +                app.ApplicationServices.GetService<BTCPayNetworkProvider>()).GetAwaiter().GetResult();
err, wat

2020-10-14 07:12 UTC, Kukks commented on BTCPayServer/Views/Server/_Nav.cshtml
> +    <a asp-controller="Server" id="Server-@ServerNavPages.ExplorerLinks" class="nav-link @ViewData.IsActivePage(ServerNavPages.ExplorerLinks)" asp-action="UpdateExplorerLinks">Blockchain Explorer Lin
I did dedicated page so I can move into an extension later :P

2020-10-14 10:05 UTC, NicolasDorier commented on BTCPayServer/Hosting/BTCPayServerServices.cs
> +                app.ApplicationServices.GetService<BTCPayNetworkProvider>()).GetAwaiter().GetResult();
sorry lol, no `.GetAwaiter().GetResult()` here.

2020-10-14 10:46 UTC, dennisreimann commented on BTCPayServer/Views/Server/UpdateExplorerLinks.cshtml
> +           debugger;
That should be removed.

2020-10-14 10:52 UTC, Kukks commented on BTCPayServer/Views/Server/UpdateExplorerLinks.cshtml
> +           debugger;
```suggestion

```

2020-10-15 06:31 UTC, britttttk commented
I don't understand how it works. Is it a refresh or a recycle button? 

I don't think it should be its own page, it seems more like a policy than an extension anyways.

![image](https://user-images.githubusercontent.com/39231115/96085221-bb3d7500-0e7d-11eb-8f62-ba0befd88d1b.png)

2020-10-15 07:28 UTC, pavlenex commented
I also think there's no need for a separate page for this one. Would fit in neatly within the policies page.

2020-10-19 15:44 UTC, pavlenex commented
I've played around with this PR, which now moved to be an extension. I haven't tested how the extension itself works, but I've tried it out, installed, uninstalled, restarted, and it worked as expected in that regard.

Concept ACK, until somebody reviews the code and tests the actual extension.

2020-10-19 19:09 UTC, dennisreimann requested changes
Only minor fomatting stuff, the `debugger` statement should be removed though.

2020-10-19 19:09 UTC, dennisreimann commented on BTCPayServer.Extensions.BlockExplorerLinks/Views/BlockExplorerEditor/UpdateExplorerLinks.cshtml
> +           debugger;
```suggestion
```

2020-10-19 19:09 UTC, dennisreimann commented on BTCPayServer.Extensions.BlockExplorerLinks/Views/BlockExplorerEditor/UpdateExplorerLinks.cshtml
> +                       background-color: #CCCCCC;
```suggestion
                background-color: #CCCCCC;
```

2020-10-19 19:09 UTC, dennisreimann commented on BTCPayServer/Views/Server/ListExtensions.cshtml
> +                    <div class="card-footer  py-0">
```suggestion
                    <div class="card-footer py-0">
```

2020-10-19 19:09 UTC, dennisreimann commented on BTCPayServer/Views/Server/ListExtensions.cshtml
> +                                <button type="submit" class="btn btn-link  pt-0">Uninstall</button>
```suggestion
                                <button type="submit" class="btn btn-link pt-0">Uninstall</button>
```

2020-10-19 19:09 UTC, dennisreimann commented on BTCPayServer/Views/Server/ListExtensions.cshtml
> +                                    <button type="submit" class="btn btn-link  pt-0">Update</button>
```suggestion
                                    <button type="submit" class="btn btn-link pt-0">Update</button>
```

2020-10-19 19:09 UTC, dennisreimann commented on BTCPayServer/Views/Server/ListExtensions.cshtml
> +                            <button type="submit" class="btn btn-link  pt-0">Install</button>
```suggestion
                            <button type="submit" class="btn btn-link pt-0">Install</button>
```

2020-10-20 01:49 UTC, NicolasDorier commented
I don't get why it should be an extension.

2020-10-20 05:34 UTC, Kukks commented
It's an extensions because:
* it's a non essential feature
* I needed an easy feature to work more on the extensions system

On Tue, 20 Oct 2020, 03:49 Nicolas Dorier, <notifications@github.com> wrote:

> I don't get why it should be an extension.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/btcpayserver/btcpayserver/pull/1981#issuecomment-712536907>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN357RPJZGA2Z46UJPHBW3SLTUENANCNFSM4SQGMG7A>
> .
>

2020-10-20 09:52 UTC, closed without merging