Add warning to configure e-mail server
btcpayserver/btcpayserver pull request #2024
Opened 2020-10-28 04:35 UTC by bolatovumar

Adds a warning to configure the e-mail server before "Requires a confirmation mail for registering" checkbox can be checked if e-mail server is not configured.

![Screen Shot 2020-10-27 at 9 34 36 PM](https://user-images.githubusercontent.com/1934678/97391365-4bc37e80-189c-11eb-95b2-c701f7f81657.png)

close #1889

2020-10-28 05:18 UTC, Kukks requested changes

2020-10-28 05:18 UTC, Kukks commented on BTCPayServer/Hosting/BTCPayServerServices.cs
> +            services.TryAddTransient<EmailSettings>();
No, you should be using the Settings Repo to fetch the email settings.

2020-10-28 05:18 UTC, Kukks commented on BTCPayServer/Views/Server/Policies.cshtml
> +@inject BTCPayServer.Services.Mails.EmailSettings EmailSettings
You should inject SettingsRepository, and then use something like `await _SettingsRepository.GetSettingAsync<EmailSettings>()` to get the settings.

2020-11-01 00:45 UTC, bolatovumar commented on BTCPayServer/Views/Server/Policies.cshtml
> +@inject BTCPayServer.Services.Mails.EmailSettings EmailSettings
Thanks. Will take a look.

2020-11-01 01:14 UTC, bolatovumar commented on BTCPayServer/Hosting/BTCPayServerServices.cs
> +            services.TryAddTransient<EmailSettings>();
Removed.

2020-11-01 01:14 UTC, bolatovumar commented on BTCPayServer/Views/Server/Policies.cshtml
> +@inject BTCPayServer.Services.Mails.EmailSettings EmailSettings
Done.

2020-11-02 13:34 UTC, Kukks requested changes

2020-11-02 13:34 UTC, Kukks commented on BTCPayServer/Views/Server/Policies.cshtml
> +            <input asp-for="RequiresConfirmedEmail" type="checkbox" class="form-check-input" disabled="@isEmailNotConfigured" />
You should enable it if  `emailSettings.IsComplete() || Model.RequiresConfirmedEmail` so that if someone enabled it before this is released, they can disable

2020-11-03 02:30 UTC, bolatovumar commented on BTCPayServer/Views/Server/Policies.cshtml
> +            <input asp-for="RequiresConfirmedEmail" type="checkbox" class="form-check-input" disabled="@isEmailNotConfigured" />
Right. Updated.

2020-11-03 05:53 UTC, Kukks approved these changes

2020-11-03 05:53 UTC, merged