Remove only dependency on Dbriize (TextSearch in new invoice column)
btcpayserver/btcpayserver pull request #2029
Opened 2020-10-29 10:52 UTC by Kukks

2020-11-05 02:06 UTC, NicolasDorier commented
So I took time to read the doc of postgres.

Doing ` query = query.Where(i => i.TextSearch.Contains(queryObject.TextSearch));` is out of question.

It is a full table scan, will take a while for old store, longer and longer.
What we can do though, on postgres, is to have a `tsvector` column, and just putting there all the words to index.
Then put an index on this column, and query via a `tsquery`. This will be fast and do what is intended.

Downside is that it works only on postgres.
For other DB maybe we can just keep dbreeze?

2020-11-19 19:44 UTC, rockstardev reviewed
@Kukks was kind enough to help me review this PR over screenshare - and the alternative proposal we came up with was to create `InvoicesIndex` table in database that would have two columns:

1. InvoiceId
2. IndexValue

You would then create a row for each value currently saved in the text file:
 - InvoiceTime.ToString(CultureInfo.InvariantCulture));
 - invoice.Price.ToString(CultureInfo.InvariantCulture));
 - invoice.Metadata.OrderId
 - ToString(invoice.Metadata, null)
 - invoice.StoreId
 - textSearch.Add(invoice.Metadata.BuyerEmail);

This way searches for Invoice would be simple SQL and work across all databases; allowing us to fully dump Breeze. As @Kukks - I'm against having different implementations depending on DB - if we're dumping Breeze we should fully dump it.

Also this format would be easy to extend in future... and have easy dump/rebuild index functionality.

2020-11-20 01:29 UTC, NicolasDorier commented
I think that's good idea to do it like that. If there is an index on the column, should be fine.
so `InvoiceId` would be foreign key with cascade delete, index on `IndexValue`.
For the Primary key, would be nice to have to have auto increment int, but I am not sure it is possible. As the key would take more space than the actual indexed data.

Or maybe is it possible to use `(IndexValue, InvoiceId)` as primary key? if that is possible, then we don't even have to put an index on index value.

2020-12-08 04:22 UTC, NicolasDorier commented
If I remember @rockstardev told me you both talked about having a table `(IndexValue, InvoiceId)`.
This would work.

2020-12-08 14:48 UTC, Kukks commented
Changed to a table but unsure if it's done correctly

2020-12-20 05:49 UTC, rockstardev commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +        public string Id { get; set; }
This should be `int` or `long`?

2020-12-20 05:53 UTC, rockstardev commented on BTCPayServer.Data/Migrations/20201208150236_InvoiceSearchTable.cs
> +                    Value = table.Column<string>(nullable: true)
I assume `maxLength` should only go on `InvoiceDataId`?

2020-12-20 16:53 UTC, rockstardev commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +            builder.Entity<InvoiceSearchData>().HasIndex(data => data.Value);
@NicolasDorier: you need to make subjective decision here of whether we want `Id` on this object. Tradeoff:

Removing `Id` we could switch to having less data and composite key:
```
builder.Entity<InvoiceSearchData>().HasKey(data => new
{
    data.InvoiceDataId,
    data.Value
});
```

We already do `Distinct()` calls on adding new entries in this table:
 - https://github.com/btcpayserver/btcpayserver/pull/2029/files#diff-f761bdfbdb17f885259fd38c8d601bec65e40d59a8278dbb73cab94804668c56R278
 - https://github.com/btcpayserver/btcpayserver/pull/2029/files#diff-c545b4806714f17ef9b042626a9db7614f96ba9abac22993a00f7ebc7d6398f9R363
 
 The problem would be for updates... where you would need to check presence of unique pair in database.
 
 So if we are deciding to keep `Id` - I would just make it `int` (or `long`) - that way it'll use less space.

2020-12-20 16:54 UTC, rockstardev commented on BTCPayServer.Data/Migrations/20201208150236_InvoiceSearchTable.cs
> +                    Value = table.Column<string>(nullable: true)
https://github.com/btcpayserver/btcpayserver/pull/2029/files#r546401885

2020-12-20 16:54 UTC, rockstardev commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +        public string Id { get; set; }
https://github.com/btcpayserver/btcpayserver/pull/2029/files#r546401885

2020-12-20 16:55 UTC, rockstardev commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +            builder.Entity<InvoiceSearchData>().HasIndex(data => new {data.InvoiceDataId, data.Value});
@NicolasDorier: Decide if you want this additional index... or if usage will be mostly to search `WHERE Value LIKE '%lala%'` then we don't need this composite index.

2020-12-20 16:56 UTC, rockstardev reviewed
Requires subjective decisions on two open comments.

@NicolasDorier when ready: make decisions and merge it.

EDIT: Changing to `Request Changes` since DBriizeEngine output is garbage; we get ~650 entries per invoice that are useless. 

I've consulted with @Kukks during the day on potentially switching to re-indexing from `InvoiceData` table... and he's OK with that approach as well. So I guess that's third subjective decision - will influence the other two.

2020-12-20 17:57 UTC, rockstardev requested changes
Updated original comment

2020-12-21 03:36 UTC, NicolasDorier commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +            builder.Entity<InvoiceSearchData>().HasIndex(data => new {data.InvoiceDataId, data.Value});
we don't need this one.
Though I am unsure if `WHERE InoivceDataId = && Value =` would use the other index. I know there is weird rules in SQL where even the order of clauses in WHERE impact whether or not an index is use. So need to test it.

2020-12-21 03:39 UTC, NicolasDorier commented
Reindexing on the `InvoiceData` table is indeed interesting. That way we can just completely drop DBRiize.
Don't need to reindex the whole thing, just OrderId, addresses, InvoiceId and emails...

2020-12-25 07:23 UTC, rockstardev commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +            builder.Entity<InvoiceSearchData>().HasIndex(data => new {data.InvoiceDataId, data.Value});
I've tested this extensively... `WHERE InoivceDataId = && Value =` would work with Postgresql with just that `data.Value` index.

2020-12-25 07:24 UTC, rockstardev commented on BTCPayServer.Data/Data/InvoiceSearchData.cs
> +            builder.Entity<InvoiceSearchData>().HasIndex(data => data.Value);
Decided to go with this data structure: https://github.com/btcpayserver/btcpayserver/pull/2029/commits/2d96a1b0aaf05b939c0a8e4579737950fc3c0282#diff-45444102c608c30496ffadec8c0a632b65bc271671e6c58dab1f91ce3e49f03c

2020-12-25 07:24 UTC, rockstardev commented
Just moving of data migration to HostedService left.

2020-12-25 07:29 UTC, Kukks commented
> Just moving of data migration to HostedService left.

I think it should be in the migration startup task to ensure its done before btcpay starts? 
Unless you intend it to index in the background?

2020-12-25 07:33 UTC, rockstardev commented
@Kukks: I understood @NicolasDorier wants this done this indexing in the background so big instances don't hang on the startup.

I plan on doing batches of 1000 invoices and saving results... so if indexing stops in the middle it can recover. That foreign key gave us index on InvoiceDataId so it shouldn't be a big problem to select by "not exists" if needed.

2020-12-25 07:57 UTC, Kukks commented
> @Kukks: I understood @NicolasDorier wants this done this indexing in the background so big instances don't hang on the startup.
> 
> I plan on doing batches of 1000 invoices and saving results... so if indexing stops in the middle it can recover. That foreign key gave us index on InvoiceDataId so it shouldn't be a big problem to select by "not exists" if needed. Or I may just save "last invoiceid indexed" somewhere and go by that.

Sounds good. Will you use a Transaction to guarantee the batch successfully? And will you store the progress in the MigrationSetttings through the settings repo?

2020-12-27 02:25 UTC, rockstardev commented
@Kukks 

![image](https://user-images.githubusercontent.com/5191402/103162616-5aed7c80-47b8-11eb-9e8a-d5cbe65552f4.png)

See `DbMigrationsHostedService` and let me know if you think something is missing in data migration.

@NicolasDorier ready for final review.

2020-12-27 13:28 UTC, Kukks reviewed
@rockstardev  added some comments

2020-12-27 13:28 UTC, Kukks commented on BTCPayServer/HostedServices/DbMigrationsHostedService.cs
> +            using var ctx = _dbContextFactory.CreateContext();
You should use a transaction to ensure all the data is saved without issue
```suggestion
            using var ctx = _dbContextFactory.CreateContext();
            using var transaction = ctx.Database.BeginTransaction();
```

2020-12-27 13:28 UTC, Kukks commented on BTCPayServer/HostedServices/DbMigrationsHostedService.cs
> +                await ctx.SaveChangesAsync();
```suggestion
                await ctx.SaveChangesAsync();
                transaction.Commit();

```

2020-12-27 17:05 UTC, rockstardev commented on BTCPayServer.Data/Migrations/ApplicationDbContextModelSnapshot.cs
> +                        .ValueGeneratedOnAdd()
Nice catch Kukkie, I've dealt with it in: 0f7869c23a8d5c9b928d0ae4181e6eb070b3533b

Tested with generating new migration, we are good to go now:  

https://user-images.githubusercontent.com/5191402/103175916-692cae80-4833-11eb-90ed-cb9ada700878.mp4

2020-12-27 17:08 UTC, rockstardev commented on BTCPayServer/HostedServices/DbMigrationsHostedService.cs
> +                await ctx.SaveChangesAsync();
From what I understand `SaveChangesAsync` already creates transaction. 

And what I did with `UpdateSettingInContext` is to ensure settings update doesn't trigger it's own `SaveChangesAsync`, but rather it's all unified in this one call on line 103.

2020-12-27 17:09 UTC, rockstardev commented on BTCPayServer/HostedServices/DbMigrationsHostedService.cs
> +            using var ctx = _dbContextFactory.CreateContext();
https://github.com/btcpayserver/btcpayserver/pull/2029#discussion_r549137609

2020-12-27 17:25 UTC, Kukks commented
Good from my end
@NicolasDorier  MERGE MERGE MERGE

2020-12-28 10:07 UTC, NicolasDorier commented
checking now

2020-12-28 10:10 UTC, NicolasDorier commented on BTCPayServer/HostedServices/DbMigrationsHostedService.cs
> +                    var textSearch = new List<string>();
Can you verify the CancellationToken here so that people can restart the servers and it does not hang here until migration is done?

2020-12-28 10:10 UTC, merged

2020-12-28 10:13 UTC, NicolasDorier commented on BTCPayServer/HostedServices/DbMigrationsHostedService.cs
> +                    var textSearch = new List<string>();
Did it