Add warning for zero-conf accept option
btcpayserver/btcpayserver pull request #2038
Opened 2020-11-02 01:19 UTC by bolatovumar

close #2003

Screenshot:
![Screen Shot 2020-11-01 at 5 18 03 PM](https://user-images.githubusercontent.com/1934678/97821211-687a0080-1c66-11eb-8bdd-9e9b3bc47cb7.png)

2020-11-02 06:34 UTC, Kukks requested changes

2020-11-02 06:34 UTC, Kukks commented on BTCPayServer/Views/Stores/UpdateStore.cshtml
> +                            unconfirmedWarning.hidden = select.value !== '0';
Where is `unconfirmedWarning` defined?

2020-11-02 07:37 UTC, dennisreimann commented on BTCPayServer/Views/Stores/UpdateStore.cshtml
> +                            unconfirmedWarning.hidden = select.value !== '0';
```suggestion
                            document.getElementById('unconfirmedWarning').hidden = select.value !== '0';
```

2020-11-03 02:33 UTC, bolatovumar commented on BTCPayServer/Views/Stores/UpdateStore.cshtml
> +                            unconfirmedWarning.hidden = select.value !== '0';
All elements with and id attribute are automatically global variable lol (true story). I can update it to explicitly grab the element by its id if that's clearer.

2020-11-03 02:38 UTC, bolatovumar commented on BTCPayServer/Views/Stores/UpdateStore.cshtml
> +                            unconfirmedWarning.hidden = select.value !== '0';
Alright, updated here: e88b88a5a30e3348e79c48a3f9548cbd77f71a4b

2020-11-03 05:55 UTC, Kukks approved these changes

2020-11-03 05:55 UTC, merged