Add Webhooks in store's settings
btcpayserver/btcpayserver pull request #2058
Opened 2020-11-08 04:58 UTC by NicolasDorier

This cover the new webhooks as alternative to #2025
The greenfield API not done yet, this only cover the UI.

The differences with #2025 are:

* Using standard HMAC (github like) for secure callback
* Ability to chose which callback to subscribe to in a granular maner for a single webhook
* Ability to browse the delivery (as well as the request)
* Ability to redeliver manually
* In-order delivery, if a delivery fails and automatic redelivery is turned on, the other delivery won't happen until the previous succeed or failed all redeliveries.

The UX follow github's one and the UI is copying the look & feel of @dennisreimann latest changes to the store.

![image](https://user-images.githubusercontent.com/3020646/98457366-e17ada00-21c9-11eb-8d7f-f763b87e0699.png)

![image](https://user-images.githubusercontent.com/3020646/98457372-ed669c00-21c9-11eb-9d27-a4529fec2aca.png)

2020-11-08 06:58 UTC, NicolasDorier commented
Added the deliveries also at invoice level

![image](https://user-images.githubusercontent.com/3020646/98459142-3d019380-21db-11eb-87b1-a2b957d9e4f5.png)

Delivery is forbidden to Guests

2020-11-08 09:29 UTC, Kukks requested changes
* Needs integration in GreenField stores update endpoint
* Needs endpoints for invoices and stores in GreenField to view deliveries
* Needs docs on how to verify in GreenField
* Needs docs for all different webhook events
* Needs a way for invoices to be able to specify additional webhook subscriptions on creation

IMO this version over #2025  overcomplicates and adds waaaay more stuff.

2020-11-08 11:03 UTC, NicolasDorier commented on BTCPayServer/HostedServices/WebhookNotificationManager.cs
> +                case InvoiceEventCode.ReceivedPayment:
Yeah I did not wanted to include payment for now for this reason.

2020-11-08 11:12 UTC, NicolasDorier commented on BTCPayServer.Data/Data/ApplicationDbContext.cs
> +        public DbSet<StoreWebhookData> StoreWebhooks { get; set; }
We have a limited amount of scopes, so I think that's fine.
This is an important feature that I expect will be used a lot by integrators.

Also other scopes don't have to use table if they don't want to. For example, the webhooks ids of server or app could be saved into blobs instead.

Arguably, I could have done this for store... maybe I should.

2020-11-08 11:13 UTC, NicolasDorier commented on BTCPayServer.Data/Data/ApplicationDbContext.cs
> +        public DbSet<StoreWebhookData> StoreWebhooks { get; set; }
I will try to remove the invoice and store table. It may fit into blobs.

2020-11-08 11:15 UTC, NicolasDorier commented
For greenfield, I want to do it in a separate PR.

2020-11-08 15:29 UTC, NicolasDorier commented on BTCPayServer/HostedServices/WebhookNotificationManager.cs
> +                case InvoiceEventCode.Completed:
For completed, it should just be hidden. There is no reason to leak this information anywhere.

For other stuff like reason why the invoice is invalid, I will just add event specific fields I think.

2020-11-16 03:35 UTC, NicolasDorier commented
@Kukks added all your points except

> Needs a way for invoices to be able to specify additional webhook subscriptions on creation

Which I don't think is necessary. Bitpay API allowed that, but there is no reason to keep this, as everybody can instead just register their webhook at the store level.

2020-11-19 03:17 UTC, merged