Ensure campaign status is shown correctly in minimal crowdfund app
btcpayserver/btcpayserver pull request #2062
Opened 2020-11-11 23:52 UTC by bolatovumar

Before:
![Screen Shot 2020-11-11 at 3 47 44 PM](https://user-images.githubusercontent.com/1934678/98877654-d3c98c80-2435-11eb-9f6c-8c092052e7b4.png)

After:
![Screen Shot 2020-11-11 at 3 44 08 PM](https://user-images.githubusercontent.com/1934678/98877649-d1ffc900-2435-11eb-888c-4f6eae6da896.png)

With JS enabled:
![Screen Shot 2020-11-11 at 3 44 22 PM](https://user-images.githubusercontent.com/1934678/98877652-d330f600-2435-11eb-9f27-b035ca026fca.png)

2020-11-14 11:06 UTC, Kukks approved these changes

2020-11-17 07:59 UTC, Kukks requested changes

2020-11-17 07:59 UTC, Kukks commented on BTCPayServer/Views/AppsPublic/Crowdfund/MinimalCrowdfund.cshtml
> +                    @if (Model.Started && !Model.Ended && Model.EndDate.HasValue)
```suggestion
                    @if (Model.Started && Model.Ended is false)
```

2020-11-18 02:26 UTC, bolatovumar commented on BTCPayServer/Views/AppsPublic/Crowdfund/MinimalCrowdfund.cshtml
> +                    @if (Model.Started && !Model.Ended && Model.EndDate.HasValue)
@Kukks if I just check for `Model.Ended is false` and don't check for `Model.EndDate.HasValue` I will get an error because `Model.Ended` can be true even when `Model.EndDate` doesn't have a value. Did you mean that I should do `Model.Ended is false && Model.EndDate.HasValue` instead of `!Model.Ended && Model.EndDate.HasValue`?

2020-12-04 04:06 UTC, bolatovumar commented on BTCPayServer/Views/AppsPublic/Crowdfund/MinimalCrowdfund.cshtml
> +                    @if (Model.Started && !Model.Ended && Model.EndDate.HasValue)
ping @Kukks

2020-12-12 06:24 UTC, merged