Changelog 1.0.5.10
btcpayserver/btcpayserver pull request #2080
Opened 2020-11-23 11:50 UTC by NicolasDorier

@dennisreimann @Kukks @dstruck @pavlenex @rockstardev @bolatovumar @mariodian 

Please review, I would like to release a new version tomorrow night (japan time, in 24H)

2020-11-23 11:57 UTC, Kukks requested changes

2020-11-23 11:57 UTC, Kukks commented on Changelog.md
> +* Allow disabling notifications per user and disabling specific notifications per user (ref #1991) (@Kukks)
```suggestion
* Allow disabling live notifications globally and disabling specific notifications per user (ref #1991) (@Kukks)
```

2020-11-23 11:57 UTC, Kukks commented on Changelog.md
> +* Share the link of a pay button so one can embbed in a QR code (fix #635) (@Kukks)
```suggestion
* Share the link of a pay button so one can embed in a QR code (fix #635) (@Kukks)
```

2020-11-23 13:21 UTC, dennisreimann commented
We have some [breaking changes](https://github.com/btcpayserver/btcpayserver/pull/2080/files#diff-c275fec9c453c2a42515bc5ab47e30fa4130ff1426aef2f6e000a9a34e122cb8R27-R29) in there – shouldn't wee assign the `1.0.6.0` version tag?

2020-11-23 19:00 UTC, rockstardev approved these changes
LGTM

2020-11-24 07:10 UTC, pavlenex commented on Changelog.md
> +* UI: Make store setup more awesome (ref #2011) (@dennisreimann @dstrukt)
* UI: Make store setup more **intuitive** (ref #2011) (@dennisreimann @dstrukt)

2020-11-24 07:12 UTC, pavlenex commented on Changelog.md
> +* UI: Make payment requests more awesome (ref #2011) (@dennisreimann @dstrukt)
* UI: Improve payment request design (ref #2011) (@dennisreimann @dstrukt)

2020-11-24 07:12 UTC, pavlenex commented on Changelog.md
> +* UI: Make pull payments more awesome (ref #2011) (@dennisreimann @dstrukt)
* UI: Improve pull payments design (ref #2011) (@dennisreimann @dstrukt)

2020-11-24 07:31 UTC, NicolasDorier commented on Changelog.md
> +* UI: Make payment requests more awesome (ref #2011) (@dennisreimann @dstrukt)
okay will change mister-stick-in-the-ass

2020-11-24 07:36 UTC, pavlenex commented on Changelog.md
> +* UI: Improvement of the checkout overlay (see [this comment](https://github.com/btcpayserver/btcpayserver/pull/1930#issuecomment-701298441)) (@dennisreimann)
* UI: Improvement of the **modal** checkout overlay (see [this comment](https://github.com/btcpayserver/btcpayserver/pull/1930#issuecomment-701298441)) (@dennisreimann)

2020-11-24 09:01 UTC, dennisreimann commented
```diff
- awesome changelog
+ improved changelog
```

😂

2020-11-25 15:14 UTC, merged

2020-11-28 17:13 UTC, rockstardev commented
@NicolasDorier I missed formalists took over, next changelog we're bringing `awesome` back.