Add "Mark all as seen" button to notification dropdown
btcpayserver/btcpayserver pull request #2101
Opened 2020-12-04 04:10 UTC by bolatovumar

## Motivation

I often find myself wanting to just clear all notifications after I have seen them. In order to do this I need to go to the "Notifications" page, mass-select them and then perform a batch action. This takes four clicks to do. I would like to be able to do this quicker.

## Solution

Added a "Mark all as seen" button in the notification dropdown which allows me to accomplish the goal of marking all notifications as seen in two clicks instead of four.

![Screen Shot 2020-12-03 at 7 54 20 PM](https://user-images.githubusercontent.com/1934678/101120875-91621e00-35a3-11eb-91a1-f15ccfba77ef.png)

2020-12-04 07:15 UTC, Kukks requested changes
Useful, but I would wait until #2055 is merged as there is a cleanup on the notification backend code which put most of the notification code in a service instead. 

In terms of style, IMO there should be an individual list item (border in between the 2 options). Maybe @pavlenex and @dennisreimann have input on this.

2020-12-04 10:59 UTC, dennisreimann commented
I agree with @kukks, drawing a line between those actions to let the appear separate would be good. Maybe we can have one action/meta row and fit both "See all" and "Mark all read" besides each other.

I'd also propose to tinker a bit with having a different bg/text color for this row and maybe put it up at the top of the flyout. I feel like this is the more usual position for the actions and it would work better with longer notification lists.

2020-12-04 19:00 UTC, dstrukt commented
Will mock out an updated view, should have something tonight or tomorrow morning.

2020-12-06 05:24 UTC, dstrukt commented
In true fashion, I'm presenting a few options :)

My personal favorite is Option B, the right (with more padding), all based on the 4px base (4, 8, 16, 24, etc...).

I realize this would be a bit more work, but this notification overlay was an area I wanted to address, so I thought I'd go ahead and share something a bit more ambitious with this addition, it's all cosmetic, but if it's out of scope, I understand.

As for the "eye" icon, I'm ambivalent, I could take it or leave it, with the addition of (potential) future icons however, it's cleaner not to have it, but for the current state .. shrug.

As usual, open to any and all feedback!

<img width="3000" alt="Notifications" src="https://user-images.githubusercontent.com/6250771/101272343-4c272300-3740-11eb-9fdc-ed90cdfcb769.png">

2020-12-06 05:34 UTC, dstrukt commented
(reposting, the original export was incorrect)

In my true fashion, I'm presenting a few options :)

My personal favorite is Option B, the right (with more padding), all based on the 4px base (4, 8, 16, 24, etc...).

I realize this would be a bit more work, but this notification overlay was an area I wanted to address, so I thought I'd go ahead and share something a bit more ambitious with this addition, it's all cosmetic, but if it's out of scope, I understand.

As for the "eye" icon, I'm ambivalent, I could take it or leave it, with the addition of (potential) future icons however, it's cleaner not to have it, but for the current state .. shrug.

As usual, open to any and all feedback!

<img width="3000" alt="Notifications" src="https://user-images.githubusercontent.com/6250771/101272495-a83e7700-3741-11eb-843e-c4ce000020a2.png">

2020-12-06 12:21 UTC, dennisreimann commented
I like the ones with less padding a bit better, imho Option A with the two rows per item works well too.

2020-12-06 19:04 UTC, bolatovumar commented
> (reposting, the original export was incorrect)
> 
> In my true fashion, I'm presenting a few options :)
> 
> My personal favorite is Option B, the right (with more padding), all based on the 4px base (4, 8, 16, 24, etc...).
> 
> I realize this would be a bit more work, but this notification overlay was an area I wanted to address, so I thought I'd go ahead and share something a bit more ambitious with this addition, it's all cosmetic, but if it's out of scope, I understand.
> 
> Option A, extending the current version with a similar pattern.
> 
> Option C, a modified version with everything on the bottom, which I suppose I could make an option D using the current text + date with everything on the bottom, but I'm not particularly a fan of this direction, so I didn't
> 

I'm OK with all options. Option A is probably the simplest as it's closest to what we currently have.

> As for the "eye" icon, I'm ambivalent, I could take it or leave it, with the addition of (potential) future icons however, it's cleaner not to have it, but for the current state .. shrug.
> 

I only added the "eye" icon because the Notifications page itself had it for the "Mark all as seen" option.

> As usual, open to any and all feedback!
> 
> <img alt="Notifications" width="2000" src="https://user-images.githubusercontent.com/6250771/101272495-a83e7700-3741-11eb-843e-c4ce000020a2.png">

2020-12-06 22:37 UTC, dstrukt commented
Sounds like the consensus is the 16px padding over the 24px option to keep things a bit tighter vertically - sounds good! The more I look at these, I think you guys are right on this call.

Keeping the item / date the way it currently is also sounds good - easy enough change down the road if we want to adjust for any reason.

If we roll with Option A, I think #1 (left) is probably the way to go, consistent vertical padding with 16px, and 24px padding on left & right. Attached the reduced version with the multi-wrap text / icon treatment, and updated on the Figma.

Good to know on the "eye" icon. Included both (regardless of which icon) to comparison, happy to go with either, still ambivalent. 

https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=2561%3A2310

<img width="1440" alt="Notifications0 2" src="https://user-images.githubusercontent.com/6250771/101295092-4b3dd200-37d0-11eb-9c99-55e363f32f6f.png">

2020-12-07 07:36 UTC, dennisreimann commented
> Good to know on the "eye" icon. Included both (regardless of which icon) to comparison, happy to go with either, still ambivalent.

I'd omit it, as it looks cleaner and the icon doesn't add much meaning or convey this clearer here.

2020-12-08 02:14 UTC, bolatovumar commented
> > Good to know on the "eye" icon. Included both (regardless of which icon) to comparison, happy to go with either, still ambivalent.
> 
> I'd omit it, as it looks cleaner and the icon doesn't add much meaning or convey this clearer here.

Yeah, I agree.

2020-12-08 02:27 UTC, dstrukt commented
Sounds good, and agreed, it doesn't add much value, and I always opt for cleaner, but try not

2020-12-09 02:37 UTC, bolatovumar commented
Do we want to start implementing this new design or wait until #2055 is merged?

2020-12-09 08:31 UTC, pavlenex commented
@Kukks Do we want to wait for notification API or can @bolatovumar continue to work on this one?

2020-12-09 08:50 UTC, Kukks commented
Let's wait

> @Kukks Do we want to wait for notification API or can @bolatovumar continue to work on this one?



> Do we want to start implementing this new design or wait until #2055 is merged?

2020-12-10 03:19 UTC, NicolasDorier commented
I would be for merging this for next release. @Kukks your notification API seems great, but I don't think it is conflicting at all with this PR. If anything we would need to encapsulate this code in a service, but I don't see that as necessary for your PR.

2020-12-10 03:21 UTC, NicolasDorier commented on BTCPayServer/Controllers/NotificationsController.cs
> +            var items = _db.Notifications.Where(a => a.ApplicationUserId == userId && !a.Seen);
I am raging inside... in pure SQL this would be 1 simple query :/ fuck ORMs

2020-12-10 06:25 UTC, Kukks commented
> I would be for merging this for next release. @Kukks your notification API seems great, but I don't think it is conflicting at all with this PR. If anything we would need to encapsulate this code in a service, but I don't see that as necessary for your PR.

My PR already did the hard work and moving dB access code to a service. Merging this PR means I have to clean up stuff again after this is merged

2020-12-10 14:05 UTC, Kukks commented
@bolatovumar I force pushed to this branch and based it on my PR and changed the backend code to fit. Only need to update the UI now

2020-12-11 04:11 UTC, bolatovumar commented
> @bolatovumar I force pushed to this branch and based it on my PR and changed the backend code to fit. Only need to update the UI now

Thanks. I'm OK with waiting, it's not a rush.

2020-12-12 05:12 UTC, NicolasDorier commented
I will merge this for next release and open an issue for the redesign of notification popup.

2020-12-12 05:14 UTC, merged

2020-12-12 22:45 UTC, bolatovumar commented
Lol @NicolasDorier is trigger-happy as always.