Introduce Spam protection
btcpayserver/btcpayserver pull request #2106
Opened 2020-12-04 07:08 UTC by Kukks

fixes #1958

Adds 2 new options:
* Do not allow stores to use the email settings of the server. Instead, they would need to fill in the email settings in their own store
* Do not allow user creation through the API unless you are an admin.

Both are opt-in and turned off by default.

2020-12-04 08:27 UTC, pavlenex commented
@rockstardev can you please review this one when you get time? It's related to API spam that third-party hosts like @Eskyee were having.

2020-12-07 01:23 UTC, rockstardev commented on BTCPayServer/Services/Mails/EmailSenderFactory.cs
> +                !_cssThemeManager.Policies.DisableStoresToUseServerEmailSettings ? serverSender : null, _jobClient,
`StoreEmailSender` class depends on FallbackSender not being `null`... otherwise `FallbackSender.GetEmailSettings();` will throw null exception:

https://github.com/btcpayserver/btcpayserver/blob/64ab8e3fbea1dac000a2d3d9a0870fdbe80469b9/BTCPayServer/Services/Mails/StoreEmailSender.cs#L34

2020-12-07 01:24 UTC, rockstardev requested changes
Both options look solid to me... if we agree they should become long term part of Spam solution, I would encourage having tests as well.

2020-12-08 04:17 UTC, NicolasDorier commented
need tests

> Do not allow user creation through the API unless you are an admin

I really think this one is quite unecessary. If somebody wants to spam, they will even without the API.

2020-12-08 07:13 UTC, Kukks commented
> need tests
> 
> > Do not allow user creation through the API unless you are an admin
> 
> I really think this one is quite unecessary. If somebody wants to spam, they will even without the API.

This is mostly about reducing email spam. When combining both options together, it should make a difference

2020-12-08 07:13 UTC, Kukks commented
Added tests

2020-12-08 07:14 UTC, Kukks commented on BTCPayServer/Services/Mails/EmailSenderFactory.cs
> +                !_cssThemeManager.Policies.DisableStoresToUseServerEmailSettings ? serverSender : null, _jobClient,
got it, thanks!

2020-12-09 07:43 UTC, merged