Hide pagination & page size when not necessary
btcpayserver/btcpayserver pull request #2122
Opened 2020-12-10 09:53 UTC by dennisreimann

As proposed by @dstrukt in [this issue](https://github.com/btcpayserver/btcpayserver/issues/2121). Closes #2121.

I saw that the pager component wasn't used for the notifications list and wallet transactions. The former was straight forward to integrate – for the latter I had to introduce the `PaginationQuery` property in the `BasePagingViewModel`: This list has the custom `labelFilter` query param, which we need to pass through on the pagination links.

I've talked to @kukks about this and we decided that using a `Dictionary` here would be a good choice, because it allows for easy query customizability like in this case.

2020-12-10 10:51 UTC, Kukks requested changes
+34 −157  awesome

Just got one change request for when to hide the pager

2020-12-10 10:51 UTC, Kukks commented on BTCPayServer/Components/Pager/Default.cshtml
> +@if (Model.Total > Model.Count)
This should probably be a different criteria. If you set the page size to something big, you'll never be able to unset it.
It should be compared to the smallest page size option instead

2020-12-10 11:30 UTC, dennisreimann commented on BTCPayServer/Components/Pager/Default.cshtml
> +@if (Model.Total > Model.Count)
Yup, thanks! Addressed in 97a832e13e3c35649c2f14f5874abedd519950dc.

2020-12-10 11:46 UTC, dennisreimann commented
`CanUseWebhooks` fails, unrelated to the changes here.

2020-12-10 14:01 UTC, Kukks requested changes

2020-12-10 14:01 UTC, Kukks commented on BTCPayServer/Components/Pager/Default.cshtml
> +@if (Model.Total > Model.Count)
Where is that commit? It's not applied to this PR.
also use `pageSizeOptions.Min()` instead

2020-12-10 14:02 UTC, Kukks requested changes

2020-12-10 14:02 UTC, Kukks commented on BTCPayServer/Components/Pager/Default.cshtml
> +@if (Model.Total > pageSizeOptions[0])
```suggestion
@if (Model.Total > pageSizeOptions.Min())
```

2020-12-10 20:43 UTC, dstrukt commented
I love it.. absolutely knocking through these!

2020-12-11 04:02 UTC, bolatovumar approved these changes

2020-12-12 06:21 UTC, merged