Add checkoutLink and defaultLang to GreenField invoice
btcpayserver/btcpayserver pull request #2124
Opened 2020-12-10 14:35 UTC by NicolasDorier

2020-12-10 14:41 UTC, Kukks requested changes

2020-12-10 14:41 UTC, Kukks commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +            public string DefaultLang { get; set; }
can we name this better now?
`
```suggestion
            public string DefaultLanguage { get; set; }
```

2020-12-10 14:41 UTC, Kukks commented on BTCPayServer.Client/Models/InvoiceData.cs
> +        public string CheckoutLink { get; set; }
ugh I would really prefer we don't do this. It is very opinionated and depends a lot on the calling environment (multiple domains, onion, reverse proxy, ssh tunnelling, etc)

2020-12-11 02:46 UTC, NicolasDorier commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +            public string DefaultLang { get; set; }
Actually I started doing that, but "Lang" is commonly used. No strong pref though.

2020-12-11 02:47 UTC, NicolasDorier commented on BTCPayServer.Client/Models/InvoiceData.cs
> +        public string CheckoutLink { get; set; }
No, we fill that out from the HttpRequest which gives the link adapted. (ie. if you query on onion, you get onion link)

People should not have to build the URL by themselves.

2020-12-11 03:28 UTC, NicolasDorier commented
renamed

2020-12-11 03:28 UTC, merged