Re-structure issue template
btcpayserver/btcpayserver pull request #2133
Opened 2020-12-12 17:07 UTC by pavlenex

This PR is an effort to better structure our issues.
The idea is to separate questions, discussions, feature requests and chit-chat from actual `Issues` that we want tackled.
Issues should be a to-do actionable tasks that we want to tackle. Tasks that are generally accepted by contributors.
Discussions are place to ask questions, suggest a feature where community can discuss and vote on it. 

Now, what this PR does is structures the "Issues page" a bit better so it provides better context on what can be found where when a new user wants to report something.

I've also deleted feature requests template as I don't think any random idea should be in the issues. Instead now discussions mention that feature requests go there. There's still a lot of stuff that have to be done in terms of structuring discussions and moving issues towards discussions. 

## Before
![BTCPayIssuesNow](https://user-images.githubusercontent.com/36959754/101989873-885c0580-3ca3-11eb-9731-93dd43c4a3bb.PNG)

## After
![BTCPayIssuesNow2](https://user-images.githubusercontent.com/36959754/101989876-8d20b980-3ca3-11eb-81ae-4f0790a8ca1c.PNG)

Unfortunately Security.md template is hardcoded into issue template so couldn't add an emoji.

## Bug report template

I also made minor adjustments to the bug report template, mostly adding ``

## Bug report for the person reporting
![bugreport](https://user-images.githubusercontent.com/36959754/101990020-7fb7ff00-3ca4-11eb-9599-e1a91ebe62c4.PNG)

## Bug report when filed (cleaner without context)
![aaaa](https://user-images.githubusercontent.com/36959754/101990066-d3c2e380-3ca4-11eb-93a4-2491539189f0.PNG)
 
Live test is available on my fork here https://github.com/pavlenex/btcpayserver/issues/new/choose 

Please test, suggest improvements and let me know if you like the concept.

2020-12-12 18:16 UTC, Zaxounette commented
ACK x10000

Love those improvements ! 

This should hopefully redirect support 100% to the chat instead of having support issues popping up from time to time.

Also, the context text is a nice idea. Anyone able and willing to report a bug should not be confused by it.

2020-12-12 19:43 UTC, pavlenex commented
I am just unsure if I should communicate `Feature Request` in `Discussion` a bit more clearer. If anyone has a better idea of text / heading for `Discussions` feel free to suggest.

2020-12-13 12:17 UTC, Kukks requested changes
nicer for sure

2020-12-13 12:17 UTC, Kukks commented on .github/ISSUE_TEMPLATE/config.yml
>      url: https://chat.btcpayserver.org/
```suggestion
    url: https://github.com/btcpayserver/btcpayserver/discussions
```

2020-12-13 12:17 UTC, Kukks commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://github.com/btcpayserver/btcpayserver/discussions
```suggestion
    url: https://docs.btcpayserver.org
```

2020-12-13 12:17 UTC, Kukks commented on .github/ISSUE_TEMPLATE/bug-report.md
> +**To Reproduce a bug**
```suggestion
**To Reproduce the bug**
```

2020-12-13 12:20 UTC, pavlenex commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://github.com/btcpayserver/btcpayserver/discussions
omg , thanks for catching this one.

2020-12-13 12:42 UTC, Kukks approved these changes

2020-12-14 09:12 UTC, merged