UI: Improve invoice view
btcpayserver/btcpayserver pull request #2144
Opened 2020-12-15 12:45 UTC by dennisreimann

- General improvements for the spacings on the page
- Hides rows of data in case they aren't present
- Improved the PoS data view so that it renders complex objects nicely and adds links for URLs

TDB: For the last row "Links" there's now a special `_urls` property, which renders a list of urls with the key being the title and the value being the URL.

![pos](https://user-images.githubusercontent.com/886/102216449-6d73d600-3edb-11eb-903f-9a944ecf7f5f.png)

This stems from the [recent updates to the woocommerce plugin](https://github.com/btcpayserver/woocommerce-plugin/pull/53#issuecomment-744456557), where we are now adding structured data to the PoS data field.

2020-12-15 13:22 UTC, Kukks requested changes

2020-12-15 13:22 UTC, Kukks commented on BTCPayServer/Views/Invoice/Invoice.cshtml
> +                        <th>Internal Id</th>
```suggestion
                        <th>Invoice Id</th>
```

2020-12-15 13:22 UTC, Kukks commented on BTCPayServer/Views/Invoice/PosData.cshtml
> +                    @if (key == "_urls")
I would not do this and focus on a more generic solution. For example, if value is an `IEnumerable`, render as a list, and let the `http` detection you added handle rendering an anchor.

2020-12-15 17:45 UTC, dennisreimann commented on BTCPayServer/Views/Invoice/PosData.cshtml
> +                    @if (key == "_urls")
Done in 2ef8af9.

2020-12-16 01:54 UTC, bolatovumar approved these changes

2020-12-16 08:15 UTC, Kukks approved these changes

2020-12-16 08:15 UTC, merged