Add Label and accoutKeyPath to the on chain payment methods
btcpayserver/btcpayserver pull request #2166
Opened 2020-12-23 08:41 UTC by NicolasDorier

This add a way to specify some fields of the on-chain payment methods such as `Label` and `AccountKeyPath`.

I wanted to use non-primitive (`RootedKeyPath`) types to make the greenfield library easier to use.
However, this caused problem as the default `ObjectModelValidator` would try to visit all the members of the `RootKeyPath` to validate everything. But those were sending back exception.

So I create a new `SkippableObjectModelValidator` which is like the `DefaultObjectModelValidator` of MVC, except that it is possible to register types to skip validations.

I initially wanted to remove all validations, but we rely on it for the UI and there is no way to allow it only for UI and not for API.

2020-12-25 08:01 UTC, Kukks commented
Are you sure about the label? I think it should be a read only property due to the deriv scheme parser converts the xpub input and the original becomes the label

2020-12-25 08:43 UTC, NicolasDorier commented
@Kukks this is not readonly. What you refer is the default behavior, but you can set any label in the wallet settings.

2020-12-25 10:38 UTC, Kukks commented
> @Kukks this is not readonly. What you refer is the default behavior, but you can set any label in the wallet settings.

TIL

2020-12-25 10:43 UTC, Kukks requested changes
Maybe it will simplify the code a lot to simply do the key path parsing and validation inside the controller action instead of the NBitcoin Json converter? It is a lot of hoops to jump through in mvc with this approach

2020-12-25 10:43 UTC, Kukks commented on BTCPayServer/Hosting/SkippableObjectValidatorProvider.cs
> +    public class SkippableObjectValidatorProvider : ObjectModelValidator
This is some hardcore stuff

2020-12-25 13:57 UTC, NicolasDorier commented on BTCPayServer/Hosting/SkippableObjectValidatorProvider.cs
> +    public class SkippableObjectValidatorProvider : ObjectModelValidator
Well this is possible, but this make the library a pain in the ass to use.
To be honest, I am not really fan of hardcore code like that either. But having to do work for parsing in the controller while we can get NewtonsoftJson do the work for us, making our life easier AND easier to use the client library.

I think for the other actions we'll do (create a hot wallet or querying UTXOs), we'll want to reuse this.

2020-12-27 11:24 UTC, Kukks approved these changes
Ok makes sense then.

2020-12-27 11:27 UTC, Kukks requested changes
Maybe this last change on the label setting actually?

2020-12-27 11:27 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/StoreOnChainPaymentMethodsController.cs
> +                strategy.Label = paymentMethodData.Label;
```suggestion
                if(!string.IsNullOrEmpty(paymentMethodData.Label)
                {
                    strategy.Label = paymentMethodData.Label;
                }
```

2020-12-27 12:55 UTC, NicolasDorier commented on BTCPayServer/Controllers/GreenField/StoreOnChainPaymentMethodsController.cs
> +                strategy.Label = paymentMethodData.Label;
what I did before, but actually you want to set to empty or null if you want to unset the label.

2020-12-28 12:59 UTC, merged