Update notification dropdown styling
btcpayserver/btcpayserver pull request #2167
Opened 2020-12-25 03:31 UTC by bolatovumar

This styling update brings the notification dropdown styling closer to where it is in the mock-up (https://www.figma.com/file/C7Xyq0FlxgFW8vaBr8ht1z/BTCPAY?node-id=1290%3A379). It's not exactly the same though. Some things that are different:

1. The notification icon is not the same as in the mock-up. I kept the same icon we currently have. I'm not sure what the approach here should be towards custom icons. I guess I could just plug the SVG in the place of the current icon? Not sure if that's what we want to do.
2. I didn't make the notification icon green as it ends up looking weird in different themes. I kept the same color we currently have.
3. The border color is not exactly the same as in the mock-up as we don't have that particular color defined in any of our variables. It is very close to what's in the mock-up though.
4. The dropdown is not positioned exactly the same as in the mock-up. I left the positioning the same.

**Before:**

![Screen Shot 2020-12-24 at 6 45 19 PM](https://user-images.githubusercontent.com/1934678/103116218-820e4780-461a-11eb-9a83-bc1e3995d1c9.png)
![Screen Shot 2020-12-24 at 6 45 48 PM](https://user-images.githubusercontent.com/1934678/103116220-833f7480-461a-11eb-8bee-1b7efb04d52f.png)
![Screen Shot 2020-12-24 at 6 46 10 PM](https://user-images.githubusercontent.com/1934678/103116222-833f7480-461a-11eb-9ae7-15ceb9eb6f4b.png)
![Screen Shot 2020-12-24 at 6 46 27 PM](https://user-images.githubusercontent.com/1934678/103116225-83d80b00-461a-11eb-9144-37f76df3bf3f.png)

**After:**

![Screen Shot 2020-12-24 at 7 22 34 PM](https://user-images.githubusercontent.com/1934678/103117238-5c833d00-461e-11eb-933d-b4606523b13d.png)
![Screen Shot 2020-12-24 at 7 23 14 PM](https://user-images.githubusercontent.com/1934678/103117239-5db46a00-461e-11eb-8008-b8dba4903ed3.png)
![Screen Shot 2020-12-24 at 7 26 17 PM](https://user-images.githubusercontent.com/1934678/103117241-5db46a00-461e-11eb-95ab-1be359273d94.png)
![Screen Shot 2020-12-24 at 7 23 53 PM](https://user-images.githubusercontent.com/1934678/103117240-5db46a00-461e-11eb-89e2-94106d37d17b.png)

2020-12-25 03:34 UTC, bolatovumar commented on BTCPayServer/Services/Notifications/Blobs/InvoiceEventNotification.cs
> +                {InvoiceEvent.Confirmed, "has been paid"}
Update this to match the wording in the mock-up.

2020-12-25 03:34 UTC, bolatovumar commented on BTCPayServer/Services/Notifications/Blobs/InvoiceEventNotification.cs
> +                {InvoiceEvent.PaidAfterExpiration, "was paid after expiration"},
Removed the trailing period in these ones as the wording in the mock-up didn't have a trailing period.

2020-12-25 03:34 UTC, bolatovumar commented on BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
> +.font-weight-semibold {
Added this here because the mock-up specified semibold weights but we didn't have a utility class for it like we have for other font weights.

2020-12-26 15:56 UTC, dennisreimann commented on BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
> +.font-weight-semibold {
Noted as a thing to add/update with our Bootstrap 5 migration (#1866).

2020-12-26 16:09 UTC, dennisreimann reviewed
Just a few notes. I don't want to delay this as it looks good from a code perspective, but we should note this PR to be revisited with/after the Bootstrap 5 migration (#1866).

I feel we will encounter things like this in a few places from now on until the migration is done. Will schedule the migration for when we are done with the wallet setup refactoring.

2020-12-26 16:09 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +        <a class="nav-link js-scroll-trigger" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" id="Notifications" style="border-bottom: 0;">
```suggestion
        <a class="nav-link js-scroll-trigger border-bottom-0" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" id="Notifications">
```

2020-12-26 16:09 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                <div role="heading" aria-level="3" class="font-weight-semibold" style="font-size: 20px;">Notifications</div>
I think we should use a heading here – even if it doesn't closely match the mockup with size and weight. My point would be that we should be consistent with the tools we have available currently (Bootstrap 4.5) and do the cleanup/extension in one go. This isn't ideal either, but I fear we will miss things if we are using inline styles and one-off solutions like this one, without marking them for the upcoming UI refactoring.

2020-12-26 16:09 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                        </svg>
In the wallet setup UI refactoring I've introduced a SVG icon sprite for our custom icons. We can add this there once the other PR is merged.

2020-12-27 11:23 UTC, Kukks requested changes
Agree with @dennisreimann's points but my main concern is the text change for one of the notifications, which should be reverted.

2020-12-27 11:23 UTC, Kukks commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                        </svg>
We should still move this to a separate svg file in this PR to avoid rendering bigger HTML markup since this is a list

2020-12-27 11:23 UTC, Kukks commented on BTCPayServer/Services/Notifications/Blobs/InvoiceEventNotification.cs
> +                {InvoiceEvent.Confirmed, "has been paid"}
Please revert. This makes the notification unclear whether the invoice was paid and settled or just paid and unconfirmed.

2020-12-28 20:25 UTC, bolatovumar commented on BTCPayServer/Services/Notifications/Blobs/InvoiceEventNotification.cs
> +                {InvoiceEvent.Confirmed, "has been paid"}
Cool, will do.

2020-12-28 20:25 UTC, bolatovumar commented on BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
> +.font-weight-semibold {
Cool, thanks!

2020-12-28 20:33 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                <div role="heading" aria-level="3" class="font-weight-semibold" style="font-size: 20px;">Notifications</div>
Ok, I will use a heading.

2020-12-28 20:43 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                        </svg>
@dennisreimann ok, I will update this once the other PR is merged. Could you link it here?

2020-12-28 20:45 UTC, bolatovumar commented on BTCPayServer/Services/Notifications/Blobs/InvoiceEventNotification.cs
> +                {InvoiceEvent.Confirmed, "has been paid"}
@Kukks updated here: acbd8004aee15777a4787002d1d72e633729a4dc

2020-12-28 20:45 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +
@dennisreimann updated here: 2e5b1b43a4d37b133f45e0b42e52c7489457a380

2020-12-28 20:45 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +        <a class="nav-link js-scroll-trigger" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" id="Notifications" style="border-bottom: 0;">
@dennisreimann updated here: 53fa520a167fb4582fe29c94c79f6cfb6db66e24

2020-12-28 20:46 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                <div role="heading" aria-level="3" class="font-weight-semibold" style="font-size: 20px;">Notifications</div>
@dennisreimann updated here: 090c9fcceceb6a39c3a6744c7775ae0a61106fa4

2020-12-29 09:04 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                        </svg>
That's #2164, but it'll likely take some time to get merged. Let's not wait for this, because it would postpone this otherwise ready PR.

Instead, you can add [the icon sprite file](https://github.com/btcpayserver/btcpayserver/pull/2164/files#diff-d0d2f4f86f403e6111f1a616e2551ff942201f853750abb443fc8ab0c05e9978) with the desired icons here too. There's also the [`Icon` vie component](https://github.com/btcpayserver/btcpayserver/pull/2164/files#diff-ee4a33b35fdc7dbe17e0dbe7835abefd5952c39dd1b98aa5f197fe7f8bfade18) to use the icons in that sprite.
You can also give me access to your fork and I can add all of that to this PR :)

2020-12-31 01:57 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                        </svg>
@dennisreimann alright, added the sprite in e6a3f1ecc70b650f5b4d7dbfc22d67b34b965afc.

2020-12-31 02:01 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="d-flex mr-3" style="width: 16px; height: 16px; color: #8D8D8F;">
Had to add the inline styles for width and height to make sure the icon appears in the right size since the sprite itself has height and width of zero. I wonder if there should be a built-in way to allow specifying the width and height and fill color? Something like `<vc:icon symbol="note" width="16px" height="16px" color="#8D8D8F"  />`. Or is this not desirable?

2020-12-31 08:07 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="d-flex mr-3" style="width: 16px; height: 16px; color: #8D8D8F;">
There are some [icon default styles](https://github.com/btcpayserver/btcpayserver/pull/2164/files#diff-4bf852c4cb9cf97d5675b9faadfb05a776056ef7b43fa3874eed85dbb1a03edcR367). 

Can we get around using a fixed color here? Because it'll most likely interfere with the different themes. If that color isn't present in the current set of variables, let's use the closest one for now.

2021-01-02 00:53 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="d-flex mr-3" style="width: 16px; height: 16px; color: #8D8D8F;">
@dennisreimann ok, thanks for pointing out the default styles. I will add those in. I initially had the color fixed but changed it to not be fixed as other icons in your PR didn't have them.

2021-01-02 01:19 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="d-flex mr-3" style="width: 16px; height: 16px; color: #8D8D8F;">
@dennisreimann alright, added default styles [here](749efd2a48e51a39cdb557eca33703802c120a1c) which solves the issue nicely. I did notice something weird though. When I updated the color in the `icon-sprite.svg` my app was refusing to show the new color even after I restarted BTCPay. I had to run `dotnet clean` and then build from fresh for the change to be reflected. Looked like the SVG was cached and was not updating.

2021-01-02 08:56 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="d-flex mr-3" style="width: 16px; height: 16px; color: #8D8D8F;">
For the color we should stick to using currentColor in the SVG as this allows to set it via CSS. We will need this to work with the different themes. 

I also came across caching issues, which I [brought up in this comment](https://github.com/dotnet/aspnetcore/issues/18271#issuecomment-750305509). I'll try to find a workaround, because this will likely take some time to get fixed.

2021-01-03 01:33 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="d-flex mr-3" style="width: 16px; height: 16px; color: #8D8D8F;">
@dennisreimann alright, updated here: https://github.com/btcpayserver/btcpayserver/pull/2167/commits/ebdd42e71752ddfea56bf3a1a790b648f463ee0a. 

I noticed that the cache seems to be cleared if you modify the `Default.cshtml` under `Components/Icon`.

2021-01-03 14:17 UTC, dennisreimann commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="mr-3" style="color: #8D8D8F;">
We should not go with a fixed color here but use one of the variables to be compatible with the themes. Also I'd rather have this in the site.css that an inline style, because that way it won't get overlooked easily.

2021-01-03 21:19 UTC, bolatovumar commented on BTCPayServer/Components/NotificationsDropdown/Default.cshtml
> +                    <div class="mr-3" style="color: #8D8D8F;">
@dennisreimann alright, updated here: 4d143d33a14fd6fa5944c159299963af51f7777d

2021-01-04 23:47 UTC, dennisreimann commented
Nice! I got two minor things I'd propose, because imho …

- the headline looks too big (h4), let's make it an h5 
- the positioning of the dropdown can be improved, especially as it blends too much with the header in the dark theme

```css
@media@media (min-width: 992px) {
    .notification-dropdown {
        width: 420px;
        top: 64px;
        right: -32px;
    }
}
```

See proposed screenshots …


## Current 

![current-dark](https://user-images.githubusercontent.com/886/103590770-013f2d80-4eef-11eb-9476-c7012e606b88.png)

![current-light](https://user-images.githubusercontent.com/886/103590771-01d7c400-4eef-11eb-84d8-f5f079c34078.png)

## Proposed

![proposed-dark](https://user-images.githubusercontent.com/886/103590968-1ae07500-4eef-11eb-82ee-ae0f43f586a6.png)

![proposed-light](https://user-images.githubusercontent.com/886/103590969-1b790b80-4eef-11eb-8da0-5250751fddeb.png)

2021-01-04 23:54 UTC, dstrukt commented
- Agree with @dennisreimann on the heading element size, the mocks have 20px font-size / 28px line-height, so whatever's the closest equivalent (if that's the H5 in today's system), let's roll with that.
- Also agree on the placement of the dropdown.

Otherwise, looks fantastic, great work @bolatovumar @dennisreimann!

2021-01-06 01:36 UTC, bolatovumar commented
@dennisreimann adjusted the dropdown positioning here: 5b04ccc6e389f0d82cf37da34e491d20aff70c9f

Here is what H5 heading looks like vs the H4 one:

**H4**
![Screen Shot 2021-01-05 at 5 28 40 PM](https://user-images.githubusercontent.com/1934678/103718691-3b0a4580-4f7c-11eb-9768-92b71cee9c19.png)

**H5**
![Screen Shot 2021-01-05 at 5 29 27 PM](https://user-images.githubusercontent.com/1934678/103718695-3c3b7280-4f7c-11eb-93b7-5844337fa469.png)

H4 is closer in size to what the mock-up has (mock-up has 20px and H4 is 21px). H5 is 18px. I can update it to be H5 but I picked H4 initially because it was closer in size to what the mock had.

2021-01-06 01:55 UTC, NicolasDorier commented
sexy as fuck, let's add this for next release this week.

2021-01-06 02:20 UTC, dstrukt commented
@bolatovumar Seeing them both in context, let's roll with H5 (18px), it looks better. 

My 2 sats.

2021-01-07 00:01 UTC, bolatovumar commented
> @bolatovumar Seeing them both in context, let's roll with H5 (18px), it looks better.
> 
> My 2 sats.
> 
> Oh, and what do hover states on the notification row look like currently? Only thing I think that's remaining.

Updated H4 to H5 here: https://github.com/btcpayserver/btcpayserver/pull/2167/commits/bcce5e3ceed7b2b0d571eab61db654732ec8d000

Hover states look like this (see second item):

![Screen Shot 2021-01-06 at 3 58 25 PM](https://user-images.githubusercontent.com/1934678/103834492-68b4c480-5038-11eb-82e5-1c3fdcca7549.png)
![Screen Shot 2021-01-06 at 3 58 58 PM](https://user-images.githubusercontent.com/1934678/103834496-69e5f180-5038-11eb-8474-528b41d6538d.png)
![Screen Shot 2021-01-06 at 3 59 14 PM](https://user-images.githubusercontent.com/1934678/103834499-6a7e8800-5038-11eb-91d4-000825e92f06.png)
![Screen Shot 2021-01-06 at 3 59 29 PM](https://user-images.githubusercontent.com/1934678/103834501-6b171e80-5038-11eb-80e0-737282e2ed9b.png)

2021-01-07 08:21 UTC, dennisreimann approved these changes

2021-01-07 09:07 UTC, merged