Reenabling uppercase BECH32 in QR codes
btcpayserver/btcpayserver pull request #2181
Opened 2021-01-03 19:42 UTC by rockstardev

Fix: #2110

2021-01-04 07:13 UTC, Kukks approved these changes
LGTM

2021-01-05 04:33 UTC, rockstardev commented
Moving it to draft to signal it'll be re-enabled and merged once @NicolasDorier think we've raised enough awareness.

2021-01-05 05:01 UTC, NicolasDorier commented on BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentHandler.cs
> +        private static string[] bech32Prefixes = new[] { "bc1", "tb1", "bcrt1" };
Don't hardcode "bitcoin:" and the bech32 prefixes.

You have the scheme with this:
```
BTCPayNetworkProvider q;
((BTCPayNetwork)q.GetNetwork("BTC")).UriScheme
```
You have bech32 with... 

```
BTCPayNetworkProvider q;
                var hrp = Encoders.ASCII.EncodeData(((BTCPayNetwork)q.GetNetwork("BTC")).NBitcoinNetwork.GetBech32Encoder(NBitcoin.Bech32Type.WITNESS_PUBKEY_ADDRESS, false)
                    .HumanReadablePart);
```

Will make this code less ugly later on.

2021-01-05 05:02 UTC, NicolasDorier requested changes
Don't hardcode strings

2021-02-28 19:47 UTC, rockstardev commented on BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentHandler.cs
> +        private static string[] bech32Prefixes = new[] { "bc1", "tb1", "bcrt1" };
616ceee

2021-02-28 20:00 UTC, rockstardev commented
Tests are failing because of Bittrex not providing DASH_BTC rate any more. I see some other PRs are failing because of this as well. Let's address this as soon as possible @NicolasDorier @Kukks.

2021-03-06 04:52 UTC, merged

2021-03-06 10:48 UTC, Kixunil commented
Awesome! Perhaps open a tracking issue for `BITCOIN:`?

2021-03-06 11:40 UTC, pavlenex commented
Sure @Kixunil , however it's very unlikely we can push `BITCOIN:` any time soon, as there are lots of wallet that aren't yet compatible and as a payment software the last thing we want is customers not being able to pay an invoice.

2021-03-06 12:17 UTC, Kixunil commented
Sure, I understand. (Although it's a bit worrying how many projects ignore standards).

2021-03-06 12:19 UTC, Kixunil commented
Should the tracking issue be opened here or in discussions?

2021-03-06 15:57 UTC, gruve-p commented
This broke our GRS implementation

2021-03-06 15:58 UTC, gruve-p commented on BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentHandler.cs
> +            var currentNetwork = (BTCPayNetwork)networkProvider.GetNetwork("BTC");
if we change `BTC` to `GRS` then our btcpayserver fork starts to work again

2021-03-07 09:05 UTC, pavlenex commented
@Kixunil Let's open it as a discussion to keep a track of wallets we have to ping, once ready, we can move it as an issue (to-do) that can be implemented.

2021-03-15 00:29 UTC, rockstardev commented on BTCPayServer/Payments/Bitcoin/BitcoinLikePaymentHandler.cs
> +            var currentNetwork = (BTCPayNetwork)networkProvider.GetNetwork("BTC");
30c7cbba96f55f08118fbba30888632bc56d8d1a thanks @Kukks