GreenField API: Configure Store Lightning Payment Method
btcpayserver/btcpayserver pull request #2194
Opened 2021-01-12 08:28 UTC by Kukks

2021-01-13 14:02 UTC, dennisreimann reviewed
Nice, I can use this for my LNbank setup automation script. Will test the PR in this context  later :)

2021-01-13 14:17 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/StoreLightningNetworkPaymentMethodsController.cs
> +            return (_btcPayServerEnvironment.IsDeveloping || User.IsInRole(Roles.ServerAdmin) || _cssThemeManager.AllowLightningInternalNodeForAll);
technical debt, CssThemeManager is really just a cache for the PolicySettings at this point. It is ripe for refactoring

2021-01-14 08:16 UTC, dennisreimann requested changes
Two things I came across while testing.

2021-01-14 08:16 UTC, dennisreimann commented on BTCPayServer/Controllers/GreenField/StoreLightningNetworkPaymentMethodsController.cs
> +                        strategy.AccountDerivation.ToString(), !excludedPaymentMethods.Match(strategy.PaymentId)))
```suggestion
                .OfType<LightningSupportedPaymentMethod>()
                .Select(paymentMethod =>
                    new LightningNetworkPaymentMethodData(paymentMethod.PaymentId.CryptoCode,
                        paymentMethod.GetLightningUrl().ToString(), !excludedPaymentMethods.Match(paymentMethod.PaymentId)))
```

2021-01-14 09:04 UTC, dennisreimann approved these changes
Ok, tested the other endpoints as well and this looks good to me. 👍

2021-01-14 09:07 UTC, merged

2021-01-17 12:43 UTC, NicolasDorier commented
Reverted, need more review and also need for next feature release rather than bug fix release.