Update README.md
btcpayserver/btcpayserver pull request #2210
Opened 2021-01-19 03:18 UTC by radWorx

Using Polar to test Lightning payments.

2021-01-19 03:44 UTC, britttttk requested changes
Fixed typo and bullet point list. 

An alternative place for this info could be in [this document](https://github.com/btcpayserver/btcpayserver-doc/blob/master/docs/Contribute/ContributeDev/ContributeDevTest.md#testing-btcpay-server).

2021-01-19 03:44 UTC, britttttk commented on BTCPayServer.Tests/README.md
> +-Install and run [Polar](https://lightningpolar.com/). Setup a small network of nodes.
```suggestion
- Install and run [Polar](https://lightningpolar.com/). Setup a small network of nodes.
```

2021-01-19 03:44 UTC, britttttk commented on BTCPayServer.Tests/README.md
> +-Goto your Store's General Settings and enable Lightning
```suggestion
- Goto your Store's General Settings and enable Lightning
```

2021-01-19 03:44 UTC, britttttk commented on BTCPayServer.Tests/README.md
> +-Build you connection string using the Connect infomation in the Polar app
```suggestion
- Build you connection string using the Connect information in the Polar app
```

2021-01-19 03:58 UTC, bolatovumar commented on BTCPayServer.Tests/README.md
> +PLEASE NOTE:
I'm not sure what this `PLEASE NOTE:` is for here.

2021-01-19 03:58 UTC, bolatovumar commented on BTCPayServer.Tests/README.md
> +- Goto your Store's General Settings and enable Lightning
`Goto` should be `Go to`

2021-01-19 03:58 UTC, bolatovumar commented on BTCPayServer.Tests/README.md
> +- Goto your Store's General Settings and enable Lightning
Does `Store` need to be capitalized here?

2021-01-19 03:58 UTC, bolatovumar commented on BTCPayServer.Tests/README.md
> +Now you can create a lightning invoice on BTCPayserver regtest and make payment through polar
`polar` should be capitalized. Also missing a period at the end of the sentence.
Also, `and make payment` should be `and make a payment`.

2021-01-19 03:58 UTC, bolatovumar commented on BTCPayServer.Tests/README.md
> +- Build you connection string using the Connect information in the Polar app
`Build you` should probably be `Build your` here?

2021-01-19 04:04 UTC, radWorx commented on BTCPayServer.Tests/README.md
> +PLEASE NOTE:
Was going to add a note about a break on exception. Will add and fix the recommendations.

2021-01-19 18:29 UTC, pavlenex commented on BTCPayServer.Tests/README.md
> +Now you can create a lightning invoice on BTCPayserver regtest and make a payment through polar.
```suggestion
Now you can create a lightning invoice on BTCPay Server regtest and make a payment through Polar.
```

2021-01-21 09:25 UTC, dennisreimann approved these changes
Tested, works as promised :)

You could also mention that ones needs to bring the Polar Bitcoin node to the same blockheight as the BTCPay node – otherwise the LN node shows up as not synched. On the other side this may not be necessary, as the LN connection message shows how many blocks difference there are and this is for advanced users anyways …

2021-02-03 04:50 UTC, bolatovumar commented on BTCPayServer.Tests/README.md
> +Or, uncheck the box that says, "Break when this exceptiontype is thrown".
`exceptiontype` looks like there is a space missing?

2021-02-10 13:45 UTC, NicolasDorier commented
Please move it after `Using the test lightning-cli` and mention that this is an alternative.

2021-02-15 20:08 UTC, radWorx commented on BTCPayServer.Tests/README.md
> +Or, uncheck the box that says, "Break when this exceptiontype is thrown".
Yes. Will fix.

2021-02-21 21:48 UTC, bolatovumar approved these changes

2021-02-22 09:22 UTC, merged