Improve password reset email copy
btcpayserver/btcpayserver pull request #2211
Opened 2021-01-20 08:32 UTC by saliehendricks

Fix for #1978 

Simple fix to update the password reset email copy:
![image](https://user-images.githubusercontent.com/1830594/105148180-bdf9d700-5b0a-11eb-8168-0fe6a9173e1d.png)

2021-01-21 03:10 UTC, britttttk commented
ack 

@saliehendricks looks good. I'm not sure about the copy and paste link though. It looks kind of long and intimidating to non-tech people. Is that typical? @brainharrington @Eskyee any feedback? :)

2021-01-21 03:28 UTC, Eskyee commented
@saliehendricks looks good.  but I agree with @britttttk 
the copy & paste does looks intimidating to newbies & messy yes.



BTCPay Logo

Please confirm your password.  by clicking the button or link below. 

Button





I think this is the standard Forgot My Password reply. it might be nice just to have a single button 
"if we have a button?? I would remove the link word" and BTCPay Logo in header  included in forgotten email..  
would look more professional and clean.  I think!!

2021-01-21 03:39 UTC, PresidentNick commented
The previous string was setting the email copy on whether the user was creating a new password or resetting their existing password.

@saliehendricks Can you add a conditional string for when the user is setting their password for the first time, please? 

Although, I haven't seen what calls the email function with the new password boolean set to True. So maybe it doesn't make sense to have an extra string for when the user is setting a new password? When is this function called with True for newPassword argument?

2021-01-21 19:39 UTC, saliehendricks commented
@britttttk I have seen fallback urls in authentication emails, but i dont disagree its pretty techy and ugly tbh. Happy to remove that part.

@Eskyee Agree, a button would be nice. Will try to put something together. I wasn't even sure the email was html formatted, but it appears to be. BTCPayServer logo would be pretty cool. Might as well give it a try :)

@PresidentNick The initial issue that was set out did say it should just be 1 email regardless of it being for a new user. Lets see what I can do to smooth out the copy a little - maybe we can get it done with just 1 simple sentence and no conditionals.

2021-01-21 20:48 UTC, saliehendricks commented
I think we making progress. So far this is what I have:
![image](https://user-images.githubusercontent.com/1830594/105410008-fd731100-5c39-11eb-8950-32f20dd0d9e1.png)

Still need to confirm location/file/css regarding the styling & logo with some other devs before committing.

2021-01-21 20:51 UTC, Eskyee commented
That's sexi 💯 
Have a look around here for any design tips https://design.btcpayserver.org
Good job 👏

2021-01-21 20:53 UTC, Eskyee commented
@dennisreimann could fast track that 🙌

2021-01-21 21:36 UTC, dennisreimann commented
Thanks for the pointer @Eskyee, I'll review this tomorrow :)

2021-01-21 21:56 UTC, saliehendricks commented
Thanks @dennisreimann. 

My thinking is to create /email.css (currently I just have static strings which is not great). This requires plumbing in the schema:host:port in order to link to the css+images. Let me know if that sounds ok.

2021-01-22 11:37 UTC, dennisreimann commented
I would not get too fancy here, especially since styling email content is a pain. Most clients don't load external content and if we want to go with HTML emails we should

- inline css and images, so I think having a general email layout file the content gets wrapped with would be best
- keep it as streamlined as possible
- provide a plain text version too

2021-01-24 05:29 UTC, britttttk commented
I like the button @saliehendricks 💯, good idea @Eskyee

2021-01-24 09:50 UTC, Kukks requested changes
I suggest we stick to just the copy text improvement for the scope of this PR. We can do more advanced layout email changes separately to keep things moving

2021-01-24 09:50 UTC, Kukks commented on BTCPayServer/Extensions/EmailSenderExtensions.cs
> +                $"Update Password",
I don't think this should be a static "Update" password. If the user was created by an admin and no pass is set, it's more a "set" password as it's a creation action
```suggestion
                $"{(newPassword ? "Set" : "Update")}  Password",
```

2021-01-24 21:41 UTC, saliehendricks commented on BTCPayServer/Extensions/EmailSenderExtensions.cs
> +                $"Update Password",
@Kukks @dennisreimann Cool cool, will keep it to just a copy update. Will adjust the subject as above.

A new feature request can be opened for html emails.

2021-01-26 10:27 UTC, saliehendricks commented on BTCPayServer/Extensions/EmailSenderExtensions.cs
> +                $"Update Password",
@Kukks @dennisreimann I thought before I strip out the html parts we could review and discuss what we have so far. Kept it as simple as possible (no logo) just inline styles for a button and html font.

![image](https://user-images.githubusercontent.com/1830594/105833362-bd14e980-5fd1-11eb-94e0-f1ee14ce72c0.png)

2021-01-26 10:36 UTC, dennisreimann commented on BTCPayServer/Extensions/EmailSenderExtensions.cs
> +                $"Update Password",
As this is explicitely setting the font color – have you checked this works in dark mode too? (E.g. for user's that are using dark mode via system preferences)

2021-01-26 10:44 UTC, saliehendricks commented on BTCPayServer/Extensions/EmailSenderExtensions.cs
> +                $"Update Password",
@dennisreimann I don't think dark mode affects emails?

2021-01-26 12:24 UTC, NicolasDorier approved these changes

2021-01-27 05:27 UTC, NicolasDorier commented
fine for me, ping @Kukks , if that's ok for you, you can merge.

2021-01-27 07:41 UTC, Kukks approved these changes
Looks good to me now. We can iterate with nicer HTML stuff later.

Good job @saliehendricks 👍

2021-01-27 07:42 UTC, merged