Safe browsing quick fixes
btcpayserver/btcpayserver pull request #2234
Opened 2021-01-28 09:49 UTC by dennisreimann

As discussed in #2139 these changes might address the issue.

2021-01-28 10:00 UTC, Kukks requested changes
Please prepend `~` to the route as it ensures that the controller doesnt do any funny business and try to itself  as part of the route.

Also, the forgot password route change will break existing links

Meh, hate these blind changes but will hopefully give us some insight.. (I messaged netcraft but still no response btw)

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/login")]
```suggestion
        [Route("~/login")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/login")]
```suggestion
        [Route("~/login")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/register")]
```suggestion
        [Route("~/register")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/register")]
```suggestion
        [Route("~/register")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/logout")]
```suggestion
        [Route("~/logout")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/forgot-password")]
```suggestion
        [Route("~/forgot-password")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/forgot-password")]
```suggestion
        [Route("~/forgot-password")]
```

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/wwwroot/modal/btcpay.js
> +    // iframe.setAttribute('allowtransparency', 'true');
What are the implications for this? Is there potential for it to render badly?

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/forgot-password")]
We need to leave the old route too. If there are active password resets, their links will be broken once they update.

2021-01-28 10:00 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +        [Route("/forgot-password")]
We need to leave the old route too. If there are active password resets, their links will be broken once they update.

2021-01-28 10:59 UTC, dennisreimann commented on BTCPayServer/wwwroot/modal/btcpay.js
> +    // iframe.setAttribute('allowtransparency', 'true');
I haven't noticed any difference in Firefox.

2021-01-28 12:05 UTC, NicolasDorier commented on BTCPayServer/wwwroot/modal/btcpay.js
> +    // iframe.setAttribute('allowtransparency', 'true');
I think @rockstardev wrote this, he might have an idea.

2021-01-28 12:05 UTC, NicolasDorier commented
Another commit I would like to see: Remove the Tor link from the login/register page. This is not needed anymore.

2021-01-28 14:42 UTC, dennisreimann commented
@NicolasDorier see 4984674b1d23b6978ddedacc21371313d983ba6f

2021-01-29 09:11 UTC, Kukks approved these changes
ack

2021-01-29 09:24 UTC, NicolasDorier commented
I will make a release with only those fixes.

2021-01-29 09:24 UTC, merged