Readme overhaul
btcpayserver/btcpayserver pull request #2239
Opened 2021-01-29 11:25 UTC by pavlenex

I've noticed that our readme has a bit of outdated information and doesn't really link to all relevant places. Since our readme is our GitHub landing page, this PR attempts to organize things and clean things up.

**Preview here** https://github.com/pavlenex/btcpayserver/tree/readme-improve#btcpay-server

Here's what's added:
- Navigation header with links to demo, bug reports, and important places (docs, site, yt API)
- Software screenshot (important to preview how  software looks)
- Adds Developing section, nests (build, run, debug) and adds API section that clarifies our two API's (hopefully)
- Adds new badges (PR welcome, Twitter, Chat, etc) and aligns them properly 
- Simplifies features section
- Adds emoji in headings for more fun :tada: 
 
Here's what's removed:
- YouTube video (we can add a new one once it's done)
- Removes introduction section as it was too wordy, instead adds simple sentence and links to docs
- Removes Azure deploy badge since it'll be added in the azure readme (azure no longer recommended deployment method)

2021-01-29 11:31 UTC, Kukks requested changes
small nits

2021-01-29 11:31 UTC, Kukks commented on README.md
> +<p align="center"> BTCPay Server is a free and open-source Bitcoin payment processor which allows you to accept bitcoin without fees or intermediary.
Should mention self-hosted imo

2021-01-29 11:31 UTC, Kukks commented on README.md
> +* Enhanced privacy & privacy
```suggestion
* Enhanced privacy & security
```

2021-01-29 11:31 UTC, Kukks commented on README.md
> +* Share your instance with friends
```suggestion
* Share your instance with friends (multi-tenant)
```

2021-01-29 11:31 UTC, Kukks commented on README.md
> +The main community chat is located on [Mattermost](https://chat.btcpayserver.org/).
main or official?

2021-01-29 11:31 UTC, Kukks commented on README.md
> +BTCPay Server has two API:
```suggestion
BTCPay Server has two APIs:
```

2021-01-29 11:35 UTC, pavlenex commented on README.md
> +<p align="center"> BTCPay Server is a free and open-source Bitcoin payment processor which allows you to accept bitcoin without fees or intermediary.
It's mentioned in the features. And in a way doesn't have to be self-hosted. But the main reason I didn't put it is the "self hosted" wallet drama. If you think it's important I can add it.

2021-01-29 11:36 UTC, pavlenex commented on README.md
> +The main community chat is located on [Mattermost](https://chat.btcpayserver.org/).
Master community chat!

2021-01-29 11:39 UTC, pavlenex commented on README.md
> +The main community chat is located on [Mattermost](https://chat.btcpayserver.org/).
Actually, since we now have community section I removed this sentence as it was unrelated to documentation section. d887546e5834451bbc6d4993d1553e97516e296a

2021-01-29 13:00 UTC, dennisreimann approved these changes

2021-01-29 16:41 UTC, Zaxounette commented
I'm taking this PR as an occasion to have a thorough read and review. Please stand by.

2021-01-29 16:59 UTC, Zaxounette requested changes
Just grammar police nitpicks (I'm @bolatovumar 's son on that one) and a few old paragraph reviews that can be changed while this file is being worked on.

2021-01-29 16:59 UTC, Zaxounette commented on README.md
>  Firstly, decide if you want to host an instance yourself or use a [third-party host](https://docs.btcpayserver.org/ThirdPartyHosting/). If you've chosen to self-host, we documented plenty [ways to de
```suggestion
Firstly, decide if you want to host an instance yourself or use a [third-party host](https://docs.btcpayserver.org/ThirdPartyHosting/). If you've chosen to self-host, we documented plenty of [ways to deploy BTCPay Server](https://docs.btcpayserver.org/Deployment/).
```

Old un-noticed typo

2021-01-29 16:59 UTC, Zaxounette commented on README.md
>  Please check out our [official website](https://btcpayserver.org/), our [complete documentation](https://docs.btcpayserver.org/) and [FAQ](https://docs.btcpayserver.org/FAQ/) for more details.
```suggestion
Please check out our [official website](https://btcpayserver.org/), [complete documentation](https://docs.btcpayserver.org/) and [FAQ](https://docs.btcpayserver.org/FAQ/) for more details.
```

Repetition.

2021-01-29 16:59 UTC, Zaxounette commented on README.md
> +If you have trouble using BTCPay, consider joining [communities listed on the official website](https://btcpayserver.org/#communityCTA) to get help from the BTCPay community members. Only file [Githu
```suggestion
If you have trouble using BTCPay Server, consider joining [communities listed on the official website](https://btcpayserver.org/#communityCTA) to get help from the members. Only file [Github issue](https://github.com/btcpayserver/btcpayserver/issues/new/choose) for technical issues you can't resolve through other channels or feature requests you've validated with other members of the community.
```

* BTCPay Server for consistency
* Update the `github new issue` link,
* Delete word repetition (`community`)

2021-01-29 16:59 UTC, Zaxounette commented on README.md
> +To begin developing locally, visit [local development guide](https://docs.btcpayserver.org/LocalDevelopment/). There are also several video-tutorials:
```suggestion
To begin developing locally, visit our [local development guide](https://docs.btcpayserver.org/LocalDevelopment/). There are also several video-tutorials:
```
Grammar police.

2021-01-29 16:59 UTC, Zaxounette commented on README.md
> +First, install .NET Core SDK v3.1 as specified by [Microsoft website](https://dotnet.microsoft.com/download/dotnet-core/3.1).
```suggestion
First, install .NET Core SDK v3.1 as specified by the [Microsoft website](https://dotnet.microsoft.com/download/dotnet-core/3.1).
```
Grammar police.

2021-01-29 16:59 UTC, Zaxounette commented on README.md
> +BTCPay Server has two APIs:
```suggestion
BTCPay Server has two API's:
```
Grammar'ish police.

2021-01-29 16:59 UTC, Zaxounette commented on README.md
> +The **legacy API**, is fully compatible with [BitPay's API](https://bitpay.com/api/). It has limited features, but allows instant migration from BitPay.
```suggestion
The **Legacy API**, is fully compatible with [BitPay's API](https://bitpay.com/api/). It has limited features, but allows instant migration from BitPay.
```
Capital L.

2021-01-29 16:59 UTC, Zaxounette commented on README.md
> +Our community is ❤️ of the project. To chat with other community members in real-time, join our [Mattermost chat](https://chat.btcpayserver.org). We're also on [GitHub discussions](https://github.com
```suggestion
Our community is the ❤️ of the project. To chat with other community members in real-time, join our [Mattermost chat](https://chat.btcpayserver.org). We're also on [GitHub discussions](https://github.com/btcpayserver/btcpayserver/discussions).
```
Grammar police.

2021-01-30 02:16 UTC, NicolasDorier approved these changes

2021-01-30 04:18 UTC, britttttk requested changes
looks great @pavlenex! definitely needed a refresh

2021-01-30 04:18 UTC, britttttk commented on README.md
> +If you have trouble using BTCPay Server, consider joining [communities listed on the official website](https://btcpayserver.org/#communityCTA) to get help from the members. Only file [Github issue](h
```suggestion
If you have trouble using BTCPay Server, consider joining [communities listed on the official website](https://btcpayserver.org/#communityCTA) to get help from other contributors. Only create a [GitHub issue](https://github.com/btcpayserver/btcpayserver/issues/new/choose) for technical issues you can't resolve through other channels or feature requests you've validated with other members of the community.
```

2021-01-30 04:18 UTC, britttttk commented on README.md
> +The **Greenfield API** is our brand-new API which is still in development. Once complete, it will allow you to run BTCPay Server heedlessly.
```suggestion
The **Greenfield API** is our brand-new API which is still in development. Once complete, it will allow you to run BTCPay Server headlessly.
```

2021-02-05 10:29 UTC, merged