Improve policies structure and wordings
btcpayserver/btcpayserver pull request #2308
Opened 2021-02-23 09:40 UTC by dennisreimann

Closes #2307.

![policies](https://user-images.githubusercontent.com/886/108825563-7a8c0000-75c3-11eb-8eb2-ccf12b68cfae.png)

2021-02-23 09:41 UTC, dennisreimann commented
@pavlenex Somehow I cannot add @britttttk and @Zaxounette as reviewers … can we add them to the list of potential reviewers?

2021-02-23 10:57 UTC, Kukks approved these changes
CODE ACK
Concept ACK

2021-02-23 14:16 UTC, Zaxounette requested changes
* The "check for new version and notify" string is missing in your screenshot. Did you place it elsewhere ?

* Also, the `Display app on website root` dropdown clickable arrow has changed. 
I personally prefer the current arrow representation.

Current:
![DaQ3sWAwQr](https://user-images.githubusercontent.com/51208677/108860619-a8d30500-75ee-11eb-81b7-206375725ece.png)

Proposed in this PR:
![MXZVgDUDph](https://user-images.githubusercontent.com/51208677/108860797-d750e000-75ee-11eb-8092-099deec245be.png)

2021-02-23 15:18 UTC, dennisreimann commented
@Zaxounette I took the screenshot locally and [this check](https://github.com/btcpayserver/btcpayserver/pull/2308/files#diff-fb98632cfde120a1e821fce642b2a8ea5f615f6d284b84011aa2fbed07501be7L76) seems to prevent the option from showing in this case (maybe related to the dev mode).

Here's what it looks like without the check:

![policies](https://user-images.githubusercontent.com/886/108864337-63b0d200-75f2-11eb-946a-bdf680d555ae.png)

As for the select dropdown: I've added the `w-auto` CSS class, which ensures it's not wider than necessary, but as far as I can see it doesn't affect the arrow display. I also checked my current live version, and it looks the same there too:

![select](https://user-images.githubusercontent.com/886/108864660-b38f9900-75f2-11eb-8857-92212e3142ab.png)

2021-02-23 15:55 UTC, Zaxounette commented
Thanks Dennis ! 

FYI, just checked on different browsers for the dropdown arrow:
* Firefox renders it as your screenshot.
* Chrome renders it as mine.

In any case, sorry for that.

2021-02-23 15:57 UTC, Zaxounette approved these changes
Thanks Dennis !

FYI, just checked on different browsers for the dropdown arrow:

* Firefox renders it as your screenshot.
* Chrome renders it as mine.

In any case, sorry for that.

2021-02-23 16:03 UTC, dennisreimann commented
No worries, thanks for pointing that out, @Zaxounette – might as well have been related to that change, so that feedback is welcome :)

2021-02-23 21:04 UTC, britttttk commented
Concept ACK, much more clear! @dennisreimann

2021-02-24 10:58 UTC, pavlenex commented
> @pavlenex Somehow I cannot add @britttttk and @Zaxounette as reviewers … can we add them to the list of potential reviewers?

I've invited both Brit and Zax to the organization, once they accept the invitation, we should be able to assign issues to them.

2021-02-26 02:47 UTC, NicolasDorier commented on BTCPayServer/Views/Server/Policies.cshtml
> +                    var network = networks.ElementAt(i);
I'll let it pass this time, but please don't put logic in cshtml, you should put this logic in the controller and changing the viewmodel

2021-02-26 02:49 UTC, merged

2021-02-26 05:36 UTC, dennisreimann commented on BTCPayServer/Views/Server/Policies.cshtml
> +                    var network = networks.ElementAt(i);
This PR didn't change that part, but I'm happy to refactor it with the next pass. Thanks for the hint!