Refactor how we handle and validate LN ConnectionStrings
btcpayserver/btcpayserver pull request #2314
Opened 2021-02-26 08:26 UTC by NicolasDorier

This PR is refactoring how we handle and validate connection strings for LN payment methods.

Because connection string can read the file system, we must be sure that a malicious party can't leverage lightning connection string to read and steal arbitrary file on the host.

While the original code was doing this successfully, it was hard to read and hard to understand.

I simplified the code in the following way: Now a Lightning Payment Method can be either an external connection string (as before), but some fields forbidden (such as macaroonfilepath).
If the user wants to use the internal node, then the connection string should be the string "Internal Node".

The nice thing about it is that if the user change his internal lightning implementation, he won't need to re-set the connection string to the new internal node.

Before, we were allowing administrator to set fields such as `macaroonfilepath` in the connection string, but I dropped this as it was difficult to read for something that is security sensitive.

I am also migrating all stores which used the internal node before to the new connection string "Internal Node".

2021-02-26 13:45 UTC, Kixunil commented
This sounds reasonable, good point about reading arbitrary files!

I'd still love to see the ability to have multiple internal nodes. It doesn't need to be implemented right away. Maybe to make it easier connection string could be `InternalNode=LABEL`? The initial implementation can use fixed `InternalNode=main` value.

2021-02-26 15:10 UTC, NicolasDorier commented
That's good idea, after this refactoring it can be easily implemented later.

2021-02-27 10:39 UTC, Kukks requested changes
simplifies and cleans up all the hardcore logic around internal node checks

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Views/Stores/AddLightningNode.cshtml
> +                                <code>Internal Node</code>
Is it supposed to be with a space here too?

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Payments/Lightning/LightningListener.cs
> +        private LightningConnectionString GetLightningUrl()
Duplicated code (add as static helper somewhere?)

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Payments/Lightning/LightningListener.cs
> +        private LightningConnectionString GetLightningUrl(LightningSupportedPaymentMethod supportedMethod)
Are you sure this is correct? 
It seems to try and see if payment method has a value and if not sets it to internal node.
What if a user finds a way to empty the conn string without deleting the method (non admin would gain access to internal node)?

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs
> +        private ILightningClient CreateLightningClient(LightningSupportedPaymentMethod supportedPaymentMethod, BTCPayNetwork network)
duplicated method

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Controllers/StoresController.LightningLike.cs
> +            return User.IsInRole(Roles.ServerAdmin) || _CssThemeManager.AllowLightningInternalNodeForAll;
This might break tests?

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Controllers/StoresController.LightningLike.cs
> +                    ModelState.AddModelError(nameof(vm.ConnectionString), $"You are not admin, so the connection string should not contains 'cookiefilepath', 'macaroondirectorypath', 'macaroonfilepat
```suggestion
                    ModelState.AddModelError(nameof(vm.ConnectionString), $"You are not a server admin, so the connection string should not contain 'cookiefilepath', 'macaroondirectorypath', 'macaroonfilepath', and should not point to a local ip or to a dns name ending with '.internal', '.local', '.lan' or '.'.");
```

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +                "type=clightning;server=tcp://127.0.0.1",
what about 0.0.0.0, and even the ip of the server?

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +                "type=clightning;server=tcp://127.0.0.1",
or even ipv6 local ones?

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Hosting/MigrationStartupTask.cs
> +                foreach (var prop in strats.Properties().Where(p => p.Name.EndsWith("LightningLike", StringComparison.OrdinalIgnoreCase)))
Should try and parse with PaymentMethodId to be safe

2021-02-27 10:39 UTC, Kukks commented on BTCPayServer/Hosting/MigrationStartupTask.cs
> +                    if (lightningCharge != null)
why is charge so special?

2021-02-27 15:20 UTC, NicolasDorier commented on BTCPayServer/Controllers/StoresController.LightningLike.cs
> +            return User.IsInRole(Roles.ServerAdmin) || _CssThemeManager.AllowLightningInternalNodeForAll;
I changed tests so the user is admin.

2021-02-27 15:20 UTC, NicolasDorier commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +                "type=clightning;server=tcp://127.0.0.1",
@Kukks yeah, both should be forbidden, I can add test for that.

2021-02-27 15:21 UTC, NicolasDorier commented on BTCPayServer/Hosting/MigrationStartupTask.cs
> +                foreach (var prop in strats.Properties().Where(p => p.Name.EndsWith("LightningLike", StringComparison.OrdinalIgnoreCase)))
I was thinking about it, but then we have a problem if somebody disabled shitcoins. (As payment id will not be parseable)

2021-02-27 15:22 UTC, NicolasDorier commented on BTCPayServer/Hosting/MigrationStartupTask.cs
> +                    if (lightningCharge != null)
Charge was the first lightning implementation supported by BTCPay, so before there was 3 fields Username/Password/ChargeUrl rather than a single ConnectionString.

We probably changed that 1 or 2 years ago, but those fields were still there.

2021-02-27 15:33 UTC, NicolasDorier commented on BTCPayServer/Payments/Lightning/LightningListener.cs
> +        private LightningConnectionString GetLightningUrl(LightningSupportedPaymentMethod supportedMethod)
not possible, setting the connection string is only done through `void SetLightningUrl(LightningConnectionString connectionString)` which verify that: `connectionString` is not null.
`LightningConnectionString` make it sure it is not empty.

2021-02-27 15:36 UTC, NicolasDorier commented on BTCPayServer/Views/Stores/AddLightningNode.cshtml
> +                                <code>Internal Node</code>
yes

2021-02-27 15:36 UTC, Kixunil commented
Since this changes connection string validation, I wonder how this affects #1603 
If it doesn't, would it make sense to bundle such change here?

2021-02-27 15:42 UTC, NicolasDorier commented
It probably does, will test if I can repro. I don't check http/https anymore in this PR. I just check that the external configuration string does not contains local stuff, so the checks are now simpler.

2021-03-01 01:49 UTC, NicolasDorier commented on BTCPayServer/Payments/Lightning/LightningListener.cs
> +        private LightningConnectionString GetLightningUrl(LightningSupportedPaymentMethod supportedMethod)
I will put a separated string instead. Make it harder to shoot in the foot.

2021-03-01 08:42 UTC, Kixunil commented on BTCPayServer/Views/Stores/AddLightningNode.cshtml
> +                                <code>Internal Node</code>
I'm afraid this will lead to confusion if other ways are without space. Do you have some particular reason for it?

2021-03-01 14:16 UTC, Kukks approved these changes
ACCK

2021-03-02 02:11 UTC, merged