1725 pull payments display date
btcpayserver/btcpayserver pull request #2339
Opened 2021-03-07 23:30 UTC by AlexGidge

Closes #1725 by:

- Adding "Start Date" to View Pull Payments screen
- "Last Updated" relabelled to "Last Refreshed"
- "Last Refreshed" to display in local timezone

Note: Date times are formatted based on the server's date time culture info 

----
Before:
![image](https://user-images.githubusercontent.com/8363987/110258910-cdd75880-7f9c-11eb-8247-837444d78046.png)

----
After:
![image](https://user-images.githubusercontent.com/8363987/110258832-75a05680-7f9c-11eb-832c-b922d19ab54b.png)

2021-03-08 03:08 UTC, britttttk commented
tACK

2021-03-08 06:47 UTC, Zaxounette requested changes
As a standalone string, `Last updated` indeed was confusing.
But with the addition of the string `Start date`, both together are clear.

In addition, `Last refreshed` can be confusing on the viewers standpoint, because it could refer to having refreshed the browser page, which has nothing to do with this.

2021-03-08 06:47 UTC, Zaxounette commented on BTCPayServer/Views/PullPayment/ViewPullPayment.cshtml
> +                                <span class="text-muted text-nowrap">Last Refreshed</span>
```suggestion
                                <span class="text-muted text-nowrap">Last Updated</span>
```

2021-03-08 08:26 UTC, pavlenex commented
Is there a reason why we want to display `Last Refreshed` why does it matter to the user?

2021-03-08 09:02 UTC, AlexGidge commented
@Zaxounette I've reverted the field label back to `Last Updated` 

@pavlenex Does the date help the user if they look at the page and the pull payment is still showing an outdated amount/status?

2021-03-30 05:29 UTC, merged

2021-04-01 02:35 UTC, NicolasDorier commented
@AlexGidge the changes on ToBrowserDate seems to have broken something (`g` instead of `o`) seems to have broken date (does not appear as browser date anymore)

What was the rational for this change?

2021-04-01 12:25 UTC, AlexGidge commented
@NicolasDorier Sorry, that's my mistake - I didn't look into the formatting enough. I copied `g` from the existing HTML assuming that only impacted formatting not date localisation

I've reproduced the issue in my fork and confirmed the correct date is now displaying after your fix in 94acf60