FIDO2/WebAuthN Support
btcpayserver/btcpayserver pull request #2356
Opened 2021-03-13 15:05 UTC by Kukks

This adds initial support for WebAuthN/FIDO2 as another MFA mode. U2F is still intact and runs alongside it for now. Once this is merged, I will start work on migrating U2F support to happen over the FIDO2 protocol instead.

closes #1564

2021-03-15 08:09 UTC, Kukks commented
Demo:
![](https://i.imgur.com/DU6v8Hv.gif)

2021-03-15 08:16 UTC, pavlenex commented
This one would be perfect for user-testing. @britttttk can we deploy an instance with this PR so that people may test different OS, devices, etc?

@Kukks would it be useful if we first register U2F with the old method and should it then @britttttk bump just so we test the migration or is that not necessary at this stage?

2021-03-15 08:21 UTC, Kukks commented
> This one would be perfect for user-testing. @britttttk can we deploy an instance with this PR so that people may test different OS, devices, etc?
> 
> @Kukks would it be useful if we first register U2F with the old method and should it then @britttttk bump just so we test the migration or is that not necessary at this stage?

This will be tricky, If I do the U2F migration first, the U2F options will disappear (WebAuthN handles U2F natively). Maybe I will need to do 3 PRs then:
* Adding WebAuthN (this one)
* Making MFA Login of U2F through WebAuthN  (leave U2F management intact)
* Remove U2F management

2021-03-15 08:22 UTC, Kukks commented
> This one would be perfect for user-testing. @britttttk can we deploy an instance with this PR so that people may test different OS, devices, etc?
> 
> @Kukks would it be useful if we first register U2F with the old method and should it then @britttttk bump just so we test the migration or is that not necessary at this stage?

I think it is fine to test this separately. They are different features for each one.

2021-03-15 08:33 UTC, britttttk commented
>  deploy an instance with this PR

Sure it's deployed at commit [9634f96](https://github.com/btcpayserver/btcpayserver/pull/2356/commits/9634f96646a569851b2de88c6754ad9e2bb27a5b) in the mattermost Testers channel if anyone wants to try it.

2021-03-15 15:08 UTC, dennisreimann requested changes
Tested it and it works for me with a YubiKey. 

One thing though: The device/credential name does not get saved.

2021-03-15 15:08 UTC, dennisreimann commented on BTCPayServer/Views/Fido2/Create.cshtml
> +</section>
Here the section creates a superfluous spacing, removed it:

```suggestion
<div class="row">
    <div class="col-lg-12 section-heading">
        <div>
            <span id="spinner" class="fa fa-spinner fa-spin float-right ml-3 mr-5 mt-1" style="font-size:2.5em"></span>
            <p>Insert your security key into your computer's USB port. If it has a button, tap on it.</p>
        </div>
        <p id="error-message" class="d-none alert alert-danger"></p>
        <a id="btn-retry"  class="btn btn-secondary d-none" href="javascript:window.location.reload()">Retry</a>
    </div>
</div>
```

2021-03-15 15:08 UTC, dennisreimann commented on BTCPayServer/Views/Fido2/List.cshtml
> +@using ExchangeSharp
```suggestion
```

2021-03-15 15:08 UTC, dennisreimann commented on BTCPayServer/Views/Fido2/Create.cshtml
> +@model Fido2NetLib.CredentialCreateOptions
```suggestion
@model Fido2NetLib.CredentialCreateOptions
@{
    ViewData.SetActivePageAndTitle(ManageNavPages.Fido2, "Register FIDO2 Credentials");
}
```

2021-03-15 15:36 UTC, Kukks commented
> Tested it and it works for me with a YubiKey.
> 
> One thing though: The device/credential name does not get saved.

fixed  it

2021-03-15 18:06 UTC, dennisreimann commented on BTCPayServer.Tests/BTCPayServer.Tests.csproj
> +    <Folder Include="Pages" />
Did this slip in or is it necessary?

2021-03-16 11:08 UTC, dennisreimann approved these changes
Just some minor things.

Other than that I can confirm this also works with a Trezor and that the device/credential name gets saved now.

2021-03-16 11:08 UTC, dennisreimann commented on BTCPayServer/Fido2/Fido2Service.cs
> +
```suggestion
               if (user == null || !CreationStore.TryGetValue(userId, out var options))
               {
                    return false;
               }

```

2021-03-16 11:08 UTC, dennisreimann commented on BTCPayServer/Views/Account/SecondaryLogin.cshtml
> +                    <h2 class="bg-danger">Both 2FA and U2F/FIDO2 Authentication Methods are not available. Please go to the https endpoint</h2>
```suggestion
                    <h2 class="bg-danger">Both 2FA and U2F/FIDO2 Authentication Methods are not available. Please go to the https endpoint.</h2>
```

2021-03-16 11:08 UTC, dennisreimann commented on BTCPayServer/Views/Fido2/Create.cshtml
> +
```suggestion

<script>
    // send to server for registering
```

2021-03-27 07:29 UTC, britttttk commented
| MFA Device | Browser | OS  | Works |
|--|--|--|--|
| Windows pin | MS Edge | Windows |✔️|
| Windows pin | Firefox | Windows |✔️|
| Windows pin | Chrome | Windows |✔️|
| Windows pin | Opera | Windows |✔️|
| Yubikey | | |
| Yubikey | | |

etc.
@Kukks for testing, is this the info we are looking for in user testing for this PR?

2021-03-29 00:28 UTC, bolatovumar approved these changes
Tested with a Yubikey Nano on MacOS and works as expected. The only weird thing I noticed is that the "waiting" animation doesn't go away if you cancel the login:

![Screen Shot 2021-03-28 at 5 24 05 PM](https://user-images.githubusercontent.com/1934678/112773462-06da7a00-8feb-11eb-92b4-1295c6cd0bb4.png)

2021-03-29 08:30 UTC, pavlenex commented
@bolatovumar which Yubikey, which versions/browsers, it's important we have this information, as this may work very differently depending on the environment. @britttttk started the table below, we should try to leave comments formatted like that so we can easier add tested env/devices.

2021-03-29 11:55 UTC, dennisreimann commented
MFA Device | Browser | OS | Works
-- | -- | -- | --
YubiKey 5Ci | Chrome | iOS |  (unsupported)
YubiKey 5Ci | Firefox | iOS | (unsupported)
YubiKey 5Ci | Firefox Focus | iOS | (unsupported)
YubiKey 5Ci | Opera | iOS | (unsupported)
YubiKey 5Ci | Mobile Safari | iOS | ✔️
YubiKey 5Ci | Brave | iOS | ✔️
YubiKey 5Ci | Firefox | macOS | ✔️
YubiKey 5Ci | Chrome | macOS | ✔️
YubiKey 5Ci | Safari | macOS | ✔️
Trezor One | Firefox | macOS | ✔️
Trezor One | Chrome | macOS | ✔️
Trezor One | Safari | macOS | ✔️

2021-03-29 18:40 UTC, bolatovumar commented
> Tested with a Yubikey Nano on MacOS and works as expected. The only weird thing I noticed is that the "waiting" animation doesn't go away if you cancel the login:
> 
> ![Screen Shot 2021-03-28 at 5 24 05 PM](https://user-images.githubusercontent.com/1934678/112773462-06da7a00-8feb-11eb-92b4-1295c6cd0bb4.png)

@pavlenex as I mentioned in my comment it's Yubikey Nano (the USB A version) on MacOS on Opera and Chrome. Can test other browsers as well if needed.

2021-04-05 11:54 UTC, NicolasDorier commented on BTCPayServer/Controllers/AccountController.cs
> +                if (!await _userManager.IsLockedOutAsync(user) && (await _u2FService.HasDevices(user.Id) || await _fido2Service.HasCredentials(user.Id)))
can you store this in a boolean and reuse it in LoginWithU2F/Fido viewmodel rather than calling those two times?

2021-04-05 11:55 UTC, NicolasDorier commented on BTCPayServer/Fido2/Fido2Controller.cs
> +        [Authorize]
Can you put Authorize at the controller level?

2021-04-05 12:00 UTC, NicolasDorier commented on BTCPayServer/Hosting/Startup.cs
> +                    options.ServerName = "BTCPay Server";
What is the effect of this? If somebody has multiple BTCPay Server, will the FIDO providers confuse the logins?

2021-04-05 12:00 UTC, NicolasDorier commented on BTCPayServer/Hosting/Startup.cs
> +            services.AddTransient<Fido2Configuration>(provider =>
Must be AddScoped, because `IHttpContextAccessor` is only available in the context of a request

2021-04-05 12:02 UTC, NicolasDorier commented on BTCPayServer/Views/Account/LoginWithFido2.cshtml
> +    window.makeAssertionOptions = @Json.Serialize(Model.Data);
XSS, use `@Safe.Json(Model)`

2021-04-05 12:42 UTC, Kukks commented on BTCPayServer/Hosting/Startup.cs
> +                    options.ServerName = "BTCPay Server";
No, it is simply shown on the device if supported

2021-04-05 12:46 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +                if (!await _userManager.IsLockedOutAsync(user) && (await _u2FService.HasDevices(user.Id) || await _fido2Service.HasCredentials(user.Id)))
done

2021-04-05 12:46 UTC, Kukks commented on BTCPayServer/Fido2/Fido2Controller.cs
> +        [Authorize]
done

2021-04-05 12:46 UTC, Kukks commented on BTCPayServer/Hosting/Startup.cs
> +            services.AddTransient<Fido2Configuration>(provider =>
done

2021-04-05 12:46 UTC, Kukks commented on BTCPayServer/Views/Account/LoginWithFido2.cshtml
> +    window.makeAssertionOptions = @Json.Serialize(Model.Data);
done

2021-04-05 12:47 UTC, Kukks commented on BTCPayServer/Hosting/Startup.cs
> +                    options.ServerName = "BTCPay Server";
> > Tested with a Yubikey Nano on MacOS and works as expected. The only weird thing I noticed is that the "waiting" animation doesn't go away if you cancel the login:
> > ![Screen Shot 2021-03-28 at 5 24 05 PM](https://user-images.githubusercontent.com/1934678/112773462-06da7a00-8feb-11eb-92b4-1295c6cd0bb4.png)
> 
> @pavlenex as I mentioned in my comment it's Yubikey Nano (the USB A version) on MacOS on Opera and Chrome. Can test other browsers as well if needed.
> 
> MFA Device	Browser	OS	Works
> Yubikey Nano USB A	Chrome	MacOS	✔️
> Yubikey Nano USB A	Opera	MacOS	✔️

fixed this laoder issue

2021-04-06 03:43 UTC, bolatovumar commented
Tested in a couple more browsers:

MFA Device | Browser | OS | Works
-- | -- | -- | --
Yubikey Nano USB A | Safari 14.0 | MacOS | ✔️
Yubikey Nano USB A | Firefox 86.0 | MacOS | ✔️

2021-04-06 09:58 UTC, pavlenex commented
MFA Device | Browser | OS | Works
-- | -- | -- | --
Yubikey 4 USB | Safari 14.3 | MacOS | ❌
Yubikey 4 USB | Firefox 87.0  | MacOS | ✔️


@bolatovumar can you try your Yuibkey 4 on the latest Safari 14.3, it doesn't work for me.

2021-04-07 14:11 UTC, 9mido commented
https://caniuse.com/webauthn

2021-04-08 02:42 UTC, bolatovumar commented
> MFA Device	Browser	OS	Works
> Yubikey 4 USB	Safari 14.3	MacOS	❌
> Yubikey 4 USB	Firefox 87.0	MacOS	✔️
> @bolatovumar can you try your Yuibkey 4 on the latest Safari 14.3, it doesn't work for me.

@pavlenex I don't have Safari 14.3 since I haven't update my OS to latest yet but it should work given that it works for me on Safari 14.

2021-04-13 03:16 UTC, NicolasDorier commented on BTCPayServer/Hosting/Startup.cs
> +                    options.ServerName = "BTCPay Server";
Would have been nice if it was the server domain instead, but meh.

2021-04-13 04:32 UTC, Kukks commented
The server domain is part of the specification too and is shown too

On Tue, 13 Apr 2021, 05:16 Nicolas Dorier, ***@***.***> wrote:

> *@NicolasDorier* commented on this pull request.
> ------------------------------
>
> In BTCPayServer/Hosting/Startup.cs
> <https://github.com/btcpayserver/btcpayserver/pull/2356#discussion_r612097980>
> :
>
> > @@ -78,6 +82,29 @@ public void ConfigureServices(IServiceCollection services)
>              services.AddProviderStorage();
>              services.AddSession();
>              services.AddSignalR();
> +            services.AddFido2(options =>
> +                {
> +                    options.ServerName = "BTCPay Server";
>
> Would have been nice if it was the server domain instead, but meh.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/btcpayserver/btcpayserver/pull/2356#discussion_r612097980>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAN357QGJRSGTSTNHFNV5G3TIOZQXANCNFSM4ZD4ZZPA>
> .
>

2021-04-16 12:22 UTC, Kukks commented
@NicolasDorier  https://www.youtube.com/watch?v=52vsExtoeC0

2021-04-18 03:03 UTC, NicolasDorier commented on BTCPayServer/Controllers/AccountController.cs
> +                if (!await _userManager.IsLockedOutAsync(user) &&  u2fDevices ||  fido2Devices)
Below, there is some code that execute if `user.TwoFactorEnabled`.
I am surprised we don't need the same pattern for u2f and fido. Is it normal?

2021-04-19 11:06 UTC, Kukks commented on BTCPayServer/Controllers/AccountController.cs
> +                if (!await _userManager.IsLockedOutAsync(user) &&  u2fDevices ||  fido2Devices)
Yes, it's normal. 2FA is baked into microsoft.identity while the others are our own stuff

2021-04-20 02:49 UTC, NicolasDorier commented
If you have both u2f and fido, u2f is not usable.

2021-04-20 05:04 UTC, Kukks commented
> If you have both u2f and fido, u2f is not usable. It fails immediately. (the two api must conflict)
> 
> I think you should have two different page.
> In secondary login, if there is several way of having your two factor, then we should ask to the user which he wants to use.

I am going to try migrate u2f to fido2 in next pr so this is not necessary

2021-04-20 05:06 UTC, NicolasDorier commented
ok cool.

2021-04-20 05:06 UTC, merged