Fix POS item newline break
btcpayserver/btcpayserver pull request #2366
Opened 2021-03-15 10:29 UTC by Kukks

fixes #2365

2021-03-15 12:18 UTC, dennisreimann requested changes

2021-03-15 12:18 UTC, dennisreimann commented on BTCPayServer/Views/Apps/TemplateEditor.cshtml
> +                        <p v-text="item.description" style="white-space: pre;"></p>
The `white-space: pre;` leads to strange side effect :)

![pre](https://user-images.githubusercontent.com/886/111151943-6f0f7180-8590-11eb-8485-7c6072370926.png)

2021-03-15 14:05 UTC, Kukks commented on BTCPayServer/Views/Apps/TemplateEditor.cshtml
> +                        <p v-text="item.description" style="white-space: pre;"></p>
Removed it altogether, this was just scope creep :)

2021-03-15 14:31 UTC, dennisreimann commented
I think without proper YAML parsing we are setting us up for problems with edge cases here. For instance if the string contains `"`, it'll also break – a description like this will result in an invalid template:

```
This is "THE BEST TEA EVAR" someone said.

I tend to agree. 
```

With a YAML parser we could use [multiline YAML](https://yaml-multiline.info/) and get rid of the other hacks as well. Otherwise we need to at least patch this by escaping the quotes `\"` … not optimal.

2021-03-15 14:47 UTC, Kukks commented
> I think without proper YAML parsing we are setting us up for problems with edge cases here. For instance if the string contains `"`, it'll also break – a description like this will result in an invalid template:
> 
> ```
> This is "THE BEST TEA EVAR" someone said.
> 
> I tend to agree. 
> ```
> 
> With a YAML parser we could use [multiline YAML](https://yaml-multiline.info/) and get rid of the other hacks as well. Otherwise we need to at least patch this by escaping the quotes `\"` … not optimal.

If anything, we should get rid of the YAML parser and switch over to JSON. YAML is a superset of JSON anyway so it shouldn't be that hard. We're also already hiding the raw editor now so any benefits of yml readability has gone a long time ago.

2021-03-15 14:48 UTC, Kukks commented
> I think without proper YAML parsing we are setting us up for problems with edge cases here. For instance if the string contains `"`, it'll also break – a description like this will result in an invalid template:
> 
> ```
> This is "THE BEST TEA EVAR" someone said.
> 
> I tend to agree. 
> ```
> 
> With a YAML parser we could use [multiline YAML](https://yaml-multiline.info/) and get rid of the other hacks as well. Otherwise we need to at least patch this by escaping the quotes `\"` … not optimal.

I had actually initially added multiline yaml support but it ended up being messy and it affected many parts.

2021-03-15 14:50 UTC, dennisreimann commented
+ 1 for switching to JSON.

2021-03-15 15:18 UTC, Kukks commented
> I think without proper YAML parsing we are setting us up for problems with edge cases here. For instance if the string contains `"`, it'll also break – a description like this will result in an invalid template:
> 
> ```
> This is "THE BEST TEA EVAR" someone said.
> 
> I tend to agree. 
> ```
> 
> With a YAML parser we could use [multiline YAML](https://yaml-multiline.info/) and get rid of the other hacks as well. Otherwise we need to at least patch this by escaping the quotes `\"` … not optimal.

addressed this issue

2021-03-15 18:11 UTC, dennisreimann approved these changes

2021-03-19 08:46 UTC, NicolasDorier commented
do not use `@Safe.Raw` for things that are not raw html.

2021-03-19 08:47 UTC, NicolasDorier commented on BTCPayServer/Views/AppsPublic/PointOfSale/Cart.cshtml
> +                                <p class="card-text">@Safe.Raw(System.Net.WebUtility.HtmlDecode(description))</p>
Remove HtmlDecode, if the goal is to put HTML, just `Safe.Raw`

2021-03-19 08:48 UTC, NicolasDorier commented on BTCPayServer/Views/AppsPublic/PointOfSale/Static.cshtml
> -                            <p class="card-text">@System.Net.WebUtility.HtmlDecode(item.Description)</p>
Remove HtmlDecode, if the goal is to put HTML, just Safe.Raw

2021-03-19 08:49 UTC, NicolasDorier commented
Do not use `Safe.Raw` for things that are not meant to be html

2021-03-19 12:04 UTC, NicolasDorier commented
I think it breaks a test `CanCreateAppPoS `

2021-03-19 12:54 UTC, Kukks commented
> I think it breaks a test `CanCreateAppPoS `

Fixed, it was actually an unrelated bug I uncovered...

2021-03-19 14:25 UTC, merged