Give better error for greenfield API
btcpayserver/btcpayserver pull request #2446
Opened 2021-04-08 06:58 UTC by NicolasDorier

This attempt to remove generic errors with error carrying better information about what is going on.
There are probably still other places which need to be fixed.

2021-04-08 06:59 UTC, Kukks approved these changes
LGTM

2021-04-08 07:35 UTC, Zaxounette requested changes
Nitpicks on the wording or the errors.

2021-04-08 07:35 UTC, Zaxounette commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +            return this.CreateAPIError(404, "invoice-not-found", "The invoice has not been found");
```suggestion
            return this.CreateAPIError(404, "invoice-not-found", "The invoice was not found");
```

2021-04-08 07:35 UTC, Zaxounette commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +            return this.CreateAPIError(404, "store-not-found", "The store has not been found");
```suggestion
            return this.CreateAPIError(404, "store-not-found", "The store was not found");
```

2021-04-08 09:20 UTC, dennisreimann approved these changes

2021-04-15 03:23 UTC, bolatovumar approved these changes

2021-04-20 09:25 UTC, merged