Improving File Storage page
btcpayserver/btcpayserver pull request #2455
Opened 2021-04-11 19:07 UTC by rockstardev

Resolves: #2272

Improving navigation between files and storage services and rewording info text. Go at it @Zaxounette if you want to try and change my l33t text ;)

2021-04-11 19:41 UTC, Zaxounette requested changes
Remove `external` from description since one of the options is an internal storage provider.
Replaces with `file` to better indicate that it's files that are stored.

2021-04-11 19:41 UTC, Zaxounette commented on BTCPayServer/Views/Server/Files.cshtml
> +            choose your external storage service provider
```suggestion
            choose your file storage service provider
```

2021-04-12 09:27 UTC, pavlenex approved these changes
tACK.

Agreed with @Zaxounette's suggestion above.

2021-04-13 07:28 UTC, Kukks approved these changes
LGTM, any reason why PR is a draft @rockstardev?

2021-04-17 09:53 UTC, pavlenex commented
@Kukks I asked @rockstardev about it and it seems he wants to do a few more improvements that should be done early next week.

2021-04-18 01:14 UTC, bolatovumar approved these changes

2021-04-18 19:07 UTC, rockstardev commented
OK, I'm done with my changes, needed to ensure that you can only select valid providers in dropdown and clean up those error sandwiches. See https://youtu.be/ortCV8U4kfQ from ~40:00 in if you want to understand changes more deeply... and see YouTube trollbox ofc.

2021-04-18 20:57 UTC, Zaxounette requested changes
A second instance of `external` appeared.
Changes to `file`, same as previous review.

2021-04-18 20:57 UTC, Zaxounette commented on BTCPayServer/Views/Server/Files.cshtml
> +        Change your <a asp-action="storage" asp-route-forceChoice="true" asp-route-returnurl="@ViewData["ReturnUrl"]">external storage service</a> provider.
```suggestion
        Change your <a asp-action="storage" asp-route-forceChoice="true" asp-route-returnurl="@ViewData["ReturnUrl"]">file storage service</a> provider.
```

2021-04-20 02:06 UTC, merged