customized api/v1/invoices query parameters to filter results
btcpayserver/btcpayserver pull request #2461
Opened 2021-04-13 23:18 UTC by SakerOmera

2021-04-14 06:18 UTC, Kukks requested changes
Will also need to be documented in the swagger once we agree on the mentioned changes

2021-04-14 06:18 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +            bool includeAddresses = true, bool includeArchived = false)
Please remove the `include Addresses` option as it doesn't fit this API entity

2021-04-14 06:18 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +        public async Task<IActionResult> GetInvoicesV2(string storeId, string orderId, string status,
make orderId a string array

2021-04-14 06:18 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +        public async Task<IActionResult> GetInvoicesV2(string storeId, string orderId, string status,
do not rename method

2021-04-14 06:18 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +            DateTimeOffset? startDate = null,
We have not yet decided how to handle dates in query strings. My gut tells me we need to handle them in the same format as we do in the json body, which is a unix timestamp in seconds. We may need to create some special attribute to tell the method parameter to be accepted in this way

2021-04-16 06:24 UTC, NicolasDorier commented
the test `CheckSwaggerIsConformToSchema` is failing.

2021-04-16 06:33 UTC, Kukks requested changes

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +                queryPayload.Add(nameof(startDate), startDate);
```suggestion
                queryPayload.Add(nameof(startDate), Utils.DateTimeToUnixTime(startDate));
```

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +                queryPayload.Add(nameof(endDate), endDate);
```suggestion
                queryPayload.Add(nameof(endDate), Utils.DateTimeToUnixTime(endDate));

```

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +        public virtual async Task<IEnumerable<InvoiceData>> GetInvoices(string storeId, string orderId = null, string status = null,
`status` should be an array of `InvoiceStatus`

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +                queryPayload.Add(nameof(status), status);
Once `status` is an array of an enum as a parameter to the method, the provided value here should be converter to string[]

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +                queryPayload.Add(nameof(status), status);
```suggestion
                queryPayload.Add(nameof(status), status.Select(s=> s.ToString()).ToArray());
```

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +            queryPayload.Add(nameof(includeAddresses), includeAddresses);
remove

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.Invoices.cs
> +            bool includeAddresses = true, bool includeArchived = false,
remove `includeAddresses`

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/InvoiceController.cs
> +            [FromQuery] DateTimeOffset? startDate = null,
startDate and endDate should be a `long?` and then converted in the method body (unless you introduce some Model Binder attribute to convert it behind the scenes)

2021-04-16 06:33 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.invoices.json
> +                                "type": "string",
use the defined schema for the status instead:
`"$ref": "#/components/schemas/InvoiceStatus"`

2021-04-25 18:50 UTC, rockstardev commented
Thanks for contribution @SakerOmera

2021-04-26 02:31 UTC, NicolasDorier commented
test failing is unrelated

2021-04-26 02:32 UTC, merged

2021-04-26 03:38 UTC, NicolasDorier commented
Pushed dcc4214dcb72aa6b8e2a5c51e36da8850181f69e to make things more easy to use