Lightning setup redesign
btcpayserver/btcpayserver pull request #2477
Opened 2021-04-19 15:33 UTC by dennisreimann

Based on #2469, this introduces the Lightning setup redisgn by @dstrukt.

##  Internal Node

This one looks and feels empty without the extra text assuring the user that there's nothing to configure. Open to suggestions on how to handle this. 

<img width="610" alt="light-internal" src="https://user-images.githubusercontent.com/886/115262309-b612f880-a134-11eb-909d-5386f7926b41.png">

<img width="613" alt="dark-internal" src="https://user-images.githubusercontent.com/886/115262354-c1662400-a134-11eb-896f-7e3766877361.png">

## Custom Node

<img width="612" alt="light-custom" src="https://user-images.githubusercontent.com/886/115262540-ef4b6880-a134-11eb-8931-52e1e3d58e26.png">

<img width="613" alt="dark-custom" src="https://user-images.githubusercontent.com/886/115262554-f2465900-a134-11eb-9dea-5954d735da08.png">

## Internal Node not available for non-admins

The current state sets the custom node option in case the internal one isn't allowed. So this screen doesn't occur … nevertheless I wanted to bring it up to discuss how we want to handle it. Leaving out the switch options would also be a variant, though I think defaulting to custom and displaying "Internal node" as disabled makes most sense.

<img width="614" alt="light-internal-disabled" src="https://user-images.githubusercontent.com/886/115262628-fffbde80-a134-11eb-9bd7-7d7517ec0f86.png">

2021-04-19 15:49 UTC, dstrukt commented
This looks fantastic! @dennisreimann 

I think the only bit that confuses me a little bit is the button. Every time I read it, I would do a double take back to the top to make sure I was on the correct setting, almost expecting it to toggle to the other node option .. but maybe that's just me.

I think I still prefer "Save" or something along those lines, but that's my 2 sats.

Otherwise, I think this is pretty damn close to ready - curious to see other feedback.

2021-04-20 10:35 UTC, dennisreimann commented
The test failure in `CanOnlyUseCorrectAddressFormatsForPayjoin` seems unrelated. 

@Zaxounette This is now all yours, feel free to go ahead and propose wording changes. 👍

2021-04-20 11:05 UTC, Zaxounette requested changes
Wording pass.

2021-04-20 11:05 UTC, Zaxounette commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +            <p class="my-4">Only administrators can use the internal Lightning node.</p>
Also, regarding this, I feel it should be centered.

2021-04-20 11:05 UTC, Zaxounette commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +        <label asp-for="ConnectionString" class="mt-4">The connection string configuration for your custom Lightning node:</label>
```suggestion
        <label asp-for="ConnectionString" class="mt-4">Connect your custom Lightning Node with this BTCPay Server instance using the following string:</label>
```

Suggestion. Makes it more clear that the string is used to connect to a custom node.

2021-04-20 11:21 UTC, dennisreimann commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +    ViewData.SetActivePageAndTitle(StoreNavPages.Index, "Configure your Lightning node", Context.GetStoreData().StoreName);
imho this is confusing … there is no Lightning wallet, we are configuring the connection to a specific node here.

2021-04-20 11:23 UTC, dennisreimann commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +            <p class="my-4">Only administrators can use the internal Lightning node.</p>
I tried centering it, it also looked a bit weird imho.

2021-04-20 11:23 UTC, Zaxounette commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +    ViewData.SetActivePageAndTitle(StoreNavPages.Index, "Configure your Lightning node", Context.GetStoreData().StoreName);
Another suggestion then: `Connect to a Lightning Node`.

It does indeed fit better than my first suggestion.

2021-04-20 11:25 UTC, Zaxounette commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +            <p class="my-4">Only administrators can use the internal Lightning node.</p>
Sadge :'(

If centered looks weird then leave as is.

2021-04-20 11:27 UTC, dennisreimann commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +        <label asp-for="ConnectionString" class="mt-4">The connection string configuration for your custom Lightning node:</label>
What about "Connection configuration for your custom Lightning node: (see examples below)" like this …

<img width="697" alt="cs" src="https://user-images.githubusercontent.com/886/115388418-24f75c80-a1dc-11eb-8842-7506d287c162.png">

2021-04-20 11:35 UTC, Zaxounette commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +        <label asp-for="ConnectionString" class="mt-4">The connection string configuration for your custom Lightning node:</label>
I like the hiding mechanism, but i'm not sure about the `see examples below` and `click to show examples`.

How about just leaving out the first one `see examples below` and just staying with the second one ? Would delete the kind of repetition I'm feeling.

They are in proximity of each other on the page and a user will see both at the same time without scrolling. This might probably be true also on mobile.

2021-04-20 12:54 UTC, dennisreimann commented
Alrigght, thanks for all the suggestions @Zaxounette, I applied them and this is the current state of the custom node section now … expanded c-lightning to give an impression of what it looks like.

![custom-node](https://user-images.githubusercontent.com/886/115399175-36defc80-a1e8-11eb-9b66-05058fe52662.png)

2021-04-20 12:59 UTC, Zaxounette commented
Nice ! 
The `that's it, no need to config anything else` sentence might still need brainstorming.
But I'd like other's opinions on that, it might just be me.

2021-04-20 13:07 UTC, dennisreimann commented
Sure, let's nail it down, I think this is very close and I want to get it included in the upcoming release.

@NicolasDorier @dstrukt @pavlenex 

For reference …

![internal](https://user-images.githubusercontent.com/886/115400828-026c4000-a1ea-11eb-878f-a81b5b14ceb2.png)

2021-04-20 18:23 UTC, dstrukt commented
l like the addition of the choice to collapse / expand them.

However, I know we have the text to indicate, "click to show", that could be a little more clear, e.g. with an accordion carrot .. 

I'm not the biggest fan of the default bootstrap accordion, and I think we need to do a little bit of custom modification to make it look a bit nicer, but it's a more clear indication of usage - mocked this up real quick.

2021-04-20 18:25 UTC, Zaxounette commented
> mocked this up real quick.

I like this addition.

2021-04-21 12:40 UTC, dennisreimann commented
Done, thanks for the superb suggestion @dstrukt!

<img width="609" alt="light" src="https://user-images.githubusercontent.com/886/115555114-745a8d00-a2af-11eb-87fe-9308b20afa3f.png">

<img width="612" alt="dark" src="https://user-images.githubusercontent.com/886/115555143-7ae90480-a2af-11eb-9057-34b4ad8b5076.png">

2021-04-21 12:48 UTC, Zaxounette requested changes
Simple proposal for the `nothing more to do` sentence.

2021-04-21 12:48 UTC, Zaxounette commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +            <p class="my-4">That's it, no need to configure anything else.</p>
```suggestion
            <p class="my-4">Using the BTCPay Server internal node for this store requires no further configuration. Click the save button below to start accepting Bitcoin through the Lightning Network.</p>
```

Simple proposal.
A really high level sentence, aimed at the less technical of our users, to inform what needs to be done (nothing) and what they'll have once they save.

2021-04-21 12:53 UTC, dennisreimann commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +            <p class="my-4">That's it, no need to configure anything else.</p>
Awesome, thank you! 👍

2021-04-21 16:56 UTC, dstrukt commented on BTCPayServer/Views/Stores/SetupLightningNode.cshtml
> +            <p class="my-4">That's it, no need to configure anything else.</p>
ACK

2021-04-22 03:02 UTC, NicolasDorier commented
Code ACK, anything to add?

2021-04-22 05:14 UTC, dennisreimann commented
@NicolasDorier We are ready for liftoff. 🚀

2021-04-22 08:39 UTC, merged