Changelog 1.0.7.3
btcpayserver/btcpayserver pull request #2480
Opened 2021-04-20 05:45 UTC by NicolasDorier

2021-04-20 05:56 UTC, NicolasDorier commented
Still some PRs and stuff to do before release, but starting to write this as it is long.

Maybe we need more details about the lazy payment activation stuff in blog post @pavlenex

2021-04-20 06:21 UTC, Kukks requested changes

2021-04-20 06:21 UTC, Kukks commented on Changelog.md
> +* Add `BTCPAY_TOR_SERVICES` configuration to expose tor services via the server settings. Useful for integration with self-hosted node such as Umbrel (see #2388) @Kukks @junderw
```suggestion
* Add `BTCPAY_TOR_SERVICES` configuration to expose tor services via the server settings. Useful for integration with self-hosted node such as Umbrel (see #2388) @Kukks @junderw 
* Start separation of Coinswitch feature and Shopify integration as plugins (#2384 #2390) @Kukks 
```

2021-04-20 06:39 UTC, Kukks commented on Changelog.md
> +* If a store was created via the greenfield API, warning signs of unconfigured stores would not appear. (Fix #2434) @bolatovumar
```suggestion
* If a store was created via the greenfield API, warning signs of unconfigured stores would not appear. (Fix #2434) @bolatovumar
* Do not crash if plugin folder mismatches plugin identifier @Kukks 
```

2021-04-20 06:40 UTC, dennisreimann commented on Changelog.md
> +* UI: Header and navigation improvements #2412 #2378 @dennisreimann @dstruck
```suggestion
* UI: Header and navigation improvements #2412 #2378 @dennisreimann @dstrukt
```

2021-04-20 06:40 UTC, dennisreimann commented on Changelog.md
> +* Improve Lightning setup page (#2348) @dennisreimann @dstruck
```suggestion
* Improve Lightning setup page #2348 @dennisreimann @dstrukt
```

2021-04-20 08:23 UTC, pavlenex commented on Changelog.md
> +## 1.0.7.3
Considering the size, do we consider this a major release? 1.0.8.0?

2021-04-20 08:40 UTC, Zaxounette commented on Changelog.md
> +## 1.0.7.3
I agree.
I'll draft a proposal for consistency in changelogs in the discussions on that matter.

2021-04-20 09:11 UTC, Zaxounette requested changes
Wording, typo and such.

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* Improving navigation between files and storage services and rewording info text (Fix #2272) @rockstardev
```suggestion
* Improving navigation between files and storage services and rewording info text (#2272) @rockstardev
```

Remove `fix` since it's the PR.

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* Improve Lightning setup page (#2348) @dennisreimann @dstrukt
```suggestion
* UI: Improve Lightning setup page (#2348) @dennisreimann @dstrukt
```

UI overhaul.

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* Fix typo in PoS cart view (#2428) @MaxHillebrand
```suggestion
* Fix: Block explorer links for signet @kristapsk
* Fix: Typo in PoS cart view (#2428) @MaxHillebrand
```

Consistency in typo.

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* Fix json type in doc API @g33kme
```suggestion
* Fix: Json type in doc API @g33kme
```

Consistency in typo.

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* Separate Coinswitch integration and Shopify integration as plugins @Kukks
```suggestion
```

Duplicate from line 14.

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* If a store was created via the greenfield API, warning signs of unconfigured stores would not appear. (Fix #2434) @bolatovumar
```suggestion
* If a store was created via the Greenfield API, warning signs of unconfigured stores would not appear. (Fix #2434) @bolatovumar
```

2021-04-20 09:11 UTC, Zaxounette commented on Changelog.md
> +* New setting for checkout: Ability to activate specific payment methods after the creation of the invoice (need doc) @xpayserver @Kukks @rockstardev
```suggestion
* New setting for checkout: Ability to activate specific payment methods after the creation of the invoice @xpayserver @Kukks @rockstardev 
```

Remove `need doc`, not changelog related.

2021-04-20 10:51 UTC, dennisreimann commented on Changelog.md
> +* Improve Lightning setup page (#2348) @dennisreimann @dstrukt
If possible we should also merge and include #2477 here.

2021-04-21 15:44 UTC, Kukks requested changes

2021-04-21 15:44 UTC, Kukks commented on Changelog.md
> +* Do not crash if plugin folder mismatches plugin identifier @Kukks
```suggestion
* Do not crash if plugin folder mismatches plugin identifier @Kukks 
* Fix notification count on mobile (#2483) @dennisreimann 
```

2021-04-22 12:30 UTC, dennisreimann commented on Changelog.md
> +* Improve Lightning setup page (#2348) @dennisreimann @dstrukt
Zax, can you include #2477 in your suggestion?

2021-04-22 12:32 UTC, Zaxounette commented on Changelog.md
> +* Improve Lightning setup page (#2348) @dennisreimann @dstrukt
> Zax, can you include #2477 in your suggestion?

Done !

2021-04-23 18:30 UTC, Marcin198 approved these changes

2021-04-26 07:23 UTC, dennisreimann commented on Changelog.md
> +* Default PoS store would now show placeholder as images @dennisreimann
#2449 isn't merged yet and I think there isn't even decided how to handle the whole case.

2021-04-28 03:52 UTC, NicolasDorier commented on Changelog.md
> +* Default PoS store would now show placeholder as images @dennisreimann
let's put it in next release then

2021-04-28 06:50 UTC, NicolasDorier commented
Next release will be 1.1.0, not 1.0.7.3 or 1.0.8.0 we will follow semver.

2021-04-28 06:56 UTC, dennisreimann reviewed
Removed a duplicate, consistency updates otherwise.

2021-04-28 06:56 UTC, dennisreimann commented on Changelog.md
> +* Fix: Fix the notification badge count on mobile view #2483 @dennisreimann
```suggestion
```

Duplicate, see line 38

2021-04-28 06:56 UTC, dennisreimann commented on Changelog.md
> +* Payment methods can be toggled directly from the update store page, rather than inside the page of each payment method (See #2469) @dennisreimann
```suggestion
* Payment methods can be toggled directly from the update store page, rather than inside the page of each payment method (#2469) @dennisreimann
```

2021-04-28 06:56 UTC, dennisreimann commented on Changelog.md
> +* Add `BTCPAY_TOR_SERVICES` configuration to expose tor services via the server settings. Useful for integration with self-hosted node such as Umbrel (see #2388) @Kukks @junderw
```suggestion
* Add `BTCPAY_TOR_SERVICES` configuration to expose tor services via the server settings. Useful for integration with self-hosted node such as Umbrel (#2388) @Kukks @junderw
```

2021-04-28 06:56 UTC, dennisreimann commented on Changelog.md
> +* UI: Improve Lightning setup page (#2348) (#2477) @dennisreimann @dstrukt
```suggestion
* UI: Improve Lightning setup page (#2348 #2477) @dennisreimann @dstrukt
```

2021-04-28 06:56 UTC, dennisreimann commented on Changelog.md
> +* UI: Header and navigation improvements #2412 #2378 @dennisreimann @dstrukt
```suggestion
* UI: Header and navigation improvements (#2412 #2378) @dennisreimann @dstrukt
```

2021-04-29 03:51 UTC, merged