Update HWI library, warn users to run newer version
btcpayserver/btcpayserver pull request #2544
Opened 2021-05-27 08:01 UTC by NicolasDorier

hwi made some breaking change in version 2.0.1.
The next release of BTCPayServer assume hwi on version 2.0.1, if not the following message will appear.

Note that the 2.0.1 version of the vault is in pre-release at this stage. I plan to release it when we release next btcpayserver version.

New version of the vault should work on old version of btcpayserver. (except one edge case for the address verification steps when adding a wallet)

![image](https://user-images.githubusercontent.com/3020646/119788364-0851f100-bf0d-11eb-9ecc-207d15553908.png)

2021-05-27 08:56 UTC, Zaxounette requested changes
Wording nitpicks.

2021-05-27 08:56 UTC, Zaxounette commented on BTCPayServer/wwwroot/js/vaultbridge.ui.js
> +        vaultNeedUpdate: new VaultFeedback("failed", "BTCPayServer Vault is running, but you need to update. Download the latest version on <a target=\"_blank\" href=\"https://github.com/btcpayserver
```suggestion
        vaultNeedUpdate: new VaultFeedback("failed", "Your BTCPay Server Vault version is obsolete. Please <a target=\"_blank\" href=\"https://github.com/btcpayserver/BTCPayServer.Vault/releases/latest\">download</a> the latest version.", "vault-feedback2", "vault-outdated"),
```

Wording suggestion.
Instead of `obsolete`, can also be `outdated`.

2021-05-27 08:58 UTC, pavlenex commented on BTCPayServer/wwwroot/js/vaultbridge.ui.js
> +        vaultNeedUpdate: new VaultFeedback("failed", "BTCPayServer Vault is running, but you need to update. Download the latest version on <a target=\"_blank\" href=\"https://github.com/btcpayserver
Obsolete is not the right word I prefer `outdated`.

2021-05-27 08:59 UTC, pavlenex commented on BTCPayServer/wwwroot/js/vaultbridge.ui.js
> +        vaultNeedUpdate: new VaultFeedback("failed", "Your BTCPay Server Vault version is obsolete. Please <a target=\"_blank\" href=\"https://github.com/btcpayserver/BTCPayServer.Vault/releases/late
```suggestion
        vaultNeedUpdate: new VaultFeedback("failed", "Your BTCPay Server Vault version is outdated. Please <a target=\"_blank\" href=\"https://github.com/btcpayserver/BTCPayServer.Vault/releases/latest\">download</a> the latest version.", "vault-feedback2", "vault-outdated"),
```

2021-05-27 15:06 UTC, pavlenex approved these changes

2021-05-29 02:20 UTC, britttttk approved these changes

2021-05-29 11:21 UTC, Zaxounette approved these changes

2021-05-30 09:02 UTC, Kukks approved these changes
lgtm

2021-06-06 12:02 UTC, merged