Add "stores/{storeId}/payment-methods" endpoint
btcpayserver/btcpayserver pull request #2555
Opened 2021-06-02 03:50 UTC by bolatovumar

address #2545

2021-06-02 03:57 UTC, bolatovumar reviewed
@Kukks not sure if this was what you meant in your comment in #2545 but I took a stab at it. Even if this was not what you meant it's probably useful to have this endpoint. If this looks good I will go ahead and add docs/tests.

2021-06-02 03:57 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/StoreLightningNetworkPaymentMethodsController.cs
> +        public static IEnumerable<LightningNetworkPaymentMethodData> GetLightningPaymentMethods(StoreData store, BTCPayNetworkProvider networkProvider, bool enabledOnly = false)
The change here is that I moved the code into a static method so it can be called from another class that's responsible for the endpoint which returns data both for on-chain and LN payments methods.

2021-06-02 03:57 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/StoreLightningNetworkPaymentMethodsController.cs
> +                        paymentMethod.GetExternalLightningUrl()?.ToString() ?? paymentMethod.GetDisplayableConnectionString(),
This code was copied almost one to one from the non-static method but this line is different. Previously because `paymentMethod.GetExternalLightningUrl()` can return `null` this would consistently result in a 500 error for me (both in local development and on my actual BTCPay instance deployed in the wild). I updated this line not to result in a null reference exception.

2021-06-02 03:57 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/StoreOnChainPaymentMethodsController.cs
> +        public static IEnumerable<OnChainPaymentMethodData> GetOnChainPaymentMethods(StoreData store, BTCPayNetworkProvider networkProvider, bool enabledOnly = false)
Same change as above, I just made this into a static method so I can call it from another class.

2021-06-02 03:57 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/StorePaymentMethodsController.cs
> +            return Ok(new {
This just combines the on-chain and LN calls and returns them as one object. Not sure if that's what you had in mind or something else.

2021-06-02 03:57 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/StorePaymentMethodsController.cs
> +        [HttpGet("~/api/v1/stores/{storeId}/payment-methods")]
This is the new endpoint which gives you configured payment methods for both on-chain and LN.

2021-06-02 03:57 UTC, bolatovumar commented on BTCPayServer/Payments/Lightning/LightningSupportedPaymentMethod.cs
> +#nullable enable
Added this as previously a bunch of the fields here could actually be `null` but it wasn't made obvious which resulted in a 500 error when `.ToString()` was called on the result of `GetExternalLightningUrl` which can return `null`.

2021-06-03 08:30 UTC, Kukks requested changes
I think the actual result needs to be more generic. There are also other payment types available (such as xmr and eth), which while we wont handle, should be hookable into this in the future through plugins from anyone that cares

Will also:
* swagger docs
*  Greenfield client support
* need tests

2021-06-03 08:30 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/StorePaymentMethodsController.cs
> +            return Ok(new {
I think this needs to change, perhaps to return a `Dictionary<string, object> ` where the key is the payment method and the object is either 
* the actual object. 
* a generic object with common data from each payment method (enabled, general description?)

2021-06-18 01:54 UTC, bolatovumar commented
> I think the actual result needs to be more generic. There are also other payment types available (such as xmr and eth), which while we wont handle, should be hookable into this in the future through plugins from anyone that cares

Are there example of plugins hooking into BTCPay functionality out there? I'm really familiar with how plugins work currently.

> Will also:
> 
> * swagger docs
> * Greenfield client support
> * need tests

Yeah, will add it once the functionality is good.

2021-06-26 10:42 UTC, pavlenex commented
@bolatovumar Can you please resolve the conflict?

2021-07-09 20:40 UTC, bolatovumar commented
> @bolatovumar Can you please resolve the conflict?

@pavlenex I don't think resolving the conflict will help here as the main thing preventing me from continuing is that I don't know how I can make it available for plugins to hook into for other chains like XMR or whatever as @Kukks said above:

> There are also other payment types available (such as xmr and eth), which while we wont handle, should be hookable into this in the future through plugins from anyone that cares

2021-07-23 08:44 UTC, Kukks commented
Hey @bolatovumar, rebased, fixed conflicts, reafactored, added docs, added tests.

Can you try it out and see if it's good for you?

2021-07-25 23:35 UTC, bolatovumar reviewed
@Kukks tested and working as expected.

One thing I noticed: if I try to hit the API endpoint for a store which doesn't exist I get a 403 status. Should it be a 404? I placed a breakpoint and it looks like the corresponding method doesn't even get hit if you provide a non-existent store id so it must be getting checked somewhere even before it gets to the API method. It's probably unrelated to this PR though.

2021-07-26 08:54 UTC, Kukks commented
> @Kukks tested and working as expected.
> 
> One thing I noticed: if I try to hit the API endpoint for a store which doesn't exist I get a 403 status. Should it be a 404? I placed a breakpoint and it looks like the corresponding method doesn't even get hit if you provide a non-existent store id so it must be getting checked somewhere even before it gets to the API method. It's probably unrelated to this PR though.

Yeah, since the expected permission for these endpoints is to modify a store, we try to check if the current API key has access to that specific store id that is present in the route. Since this check happens during permissions, the error is automatically a 403

2021-07-26 10:03 UTC, merged