Fix visual bug with invoices search help text overlapping invoice action buttons
btcpayserver/btcpayserver pull request #2583
Opened 2021-06-20 04:18 UTC by bolatovumar

close #2582

**Before:**
![Screen Shot 2021-06-19 at 9 03 00 PM](https://user-images.githubusercontent.com/1934678/122661890-be42e080-d143-11eb-8f75-c9cadb440ef2.png)

**After**
![Screen Shot 2021-06-19 at 9 18 00 PM](https://user-images.githubusercontent.com/1934678/122661902-dadf1880-d143-11eb-9d7f-92bb3d407523.png)

2021-06-20 04:19 UTC, bolatovumar commented on BTCPayServer/Views/Invoice/ListInvoices.cshtml
> +        <div class="@(Model.Total > 0 ? "mb-lg-5" : "") row collapse" id="help">
To compensate for the negative margin we apply on the action buttons to align them with the search box.

2021-06-21 06:15 UTC, Kukks approved these changes

2021-06-21 08:52 UTC, dennisreimann requested changes

2021-06-21 08:52 UTC, dennisreimann commented on BTCPayServer/Views/Invoice/ListInvoices.cshtml
>              <div class="col">
```suggestion
        <div class="row collapse" id="help">
            <div class="col @(Model.Total > 0 ? "pt-3 pb-lg-5" : "")">
```

By moving it into the inner container and using padding instead of margin we can prevent a bump in the animation.

2021-06-24 14:52 UTC, NicolasDorier commented
@bolatovumar  the suggestion of @dennisreimann  seems good?

2021-06-26 10:42 UTC, pavlenex commented
LGTM, just waiting for @bolatovumar to check Dennis' change.

2021-06-30 04:23 UTC, bolatovumar commented
@NicolasDorier yeah, looks good, I applied it!

2021-06-30 08:05 UTC, merged