Delete confirmation modals
btcpayserver/btcpayserver pull request #2614
Opened 2021-06-23 13:28 UTC by dennisreimann

This is a proof of concept for what's been proposed in #2589 by @dstrukt.

A progressive enhancement for the delete confirmations: If JavaScript is enabled, a modal in the current page context is used instead of a separate confirmation page. Both views use the shared modal code, the modal version gets the relevant data injected via JavaScript.
Depending on the context, the relevant buttons are shown (e.g. the modal has a close button in the top right corner, which isn't shown on the separate confirmation page).

The current state is to gather feedback. If we decide to progress with this, the rest of the `ConfirmModel` cases can also be added in a similar fashion.

2021-06-24 10:20 UTC, pavlenex commented
A fantastic improvement to the UX IMO.

This is what we have now
![Screenshot 2021-06-24 at 12 19 30](https://user-images.githubusercontent.com/36959754/123246858-8bec0700-d4e6-11eb-92c7-42604d4aad8f.png)

This is what this PR is trying to achieve
![Screenshot 2021-06-24 at 12 19 18](https://user-images.githubusercontent.com/36959754/123246873-91495180-d4e6-11eb-9e5a-1c8fb7fa3820.png)

Concept ACK on my end to proceed with implementation.

Much smoother UX.

2021-06-24 10:56 UTC, NicolasDorier commented
@dennisreimann I think that we should remove the old one. No need of fallback for people who does not have JS.

2021-06-24 11:30 UTC, dennisreimann commented
@NicolasDorier Ok, just to clarify, because we are doing progressive enhancement in several places: For the backend we can build JS-only versions of features?

2021-06-24 12:27 UTC, NicolasDorier commented
@dennisreimann I think it make sense to have no js callback for things like checkout to increase the reach. We don't want the merchant to drop customer because there is no JS.

But for the backend? I don't think we should care. Even the checkout page, I am unsure it is working correctly without JS.

2021-06-24 12:32 UTC, dennisreimann commented
@NicolasDorier Ok, full ACK and that makes our lives on the UI side a little easier!

2021-07-02 08:30 UTC, Kukks commented
> @dennisreimann I think that we should remove the old one. No need of fallback for people who does not have JS.
> This is the back end, not really something customer facing.

I disagree with this point. I always try to make things at least degrade but still work for non JS users. But if this PR moves forward I guess I'll open a PR to fix this after.

2021-08-09 02:05 UTC, bolatovumar commented
We do have some users who sometimes report bugs they observe when using admin pages with JS disabled so I assume there are people who do this? (use admin pages without JS)

2021-08-09 08:22 UTC, dennisreimann commented
Kukks and I decided to leave the non-JS code as a fallback and we'll do classic progressive enhancement here.

In the design meeting we also discussed to do client-side confirmation for delete actions: Like on GitHub the user has to confirm the action by typing/copying the items name into a textfield. This will be done in the model, only client-side and no addition of that in the backend code.

2021-09-01 10:19 UTC, Kukks requested changes

2021-09-01 10:19 UTC, Kukks commented on BTCPayServer/Views/UserStores/ListStores.cshtml
> +<div class="modal fade" id="ConfirmModal" tabindex="-1" aria-labelledby="ConfirmTitle" aria-hidden="true">
This code seems duplicated on every page with the confirm dialog. Can we have a partial that contains it  all?

2021-09-01 10:26 UTC, pavlenex commented
tACK.

Only thing I'd like to see improved is the text we use for the modals.
![Screenshot 2021-09-01 at 12 22 45](https://user-images.githubusercontent.com/36959754/131655603-2995584e-c056-4daf-9927-4a849e5bde37.png)

`This app will be removed from this store` isn't helpful. _AppName_ app will be removed from the _StoreName_ store may be a tiny bit more contextual. (with storename and appname being visually different, bold or italic so we don't end up with `store store`.

2021-09-01 14:40 UTC, dennisreimann commented
@Kukks @pavlenex I think your feedback can be addressed in unison: What about if we simplify the headline a la "Confirm deletion/change/removal" (whatever matches the use case) and in the text refer to the actual item? 

Right now I just replicated what the separate page version of the confirmation stated, but I think the proposed way will work well with the upcoming "To confirm type ITEM_NAME" input we planned.

If we streamline it, it will also be easier to extract the snippet into a partial. Will proceed in that direction.

2021-09-02 20:36 UTC, dennisreimann commented
Refactored the code to use one single partial, this makes it way easier to maintain and integrate new confirmable actions.

I've also done some preparations for the confirmation input, which I'd now like to add in this PR as well.

@pavlenex I think we should also take the time to change the wordings here and there while we are added. You already noted that some of the texts aren't helpful. I also think we aren't consistent: Sometime we speak of deletion, othertimes of removal. 

@Zaxounette Could you maybe help with the wording?

2021-09-02 22:21 UTC, Zaxounette requested changes
> Could you maybe help with the wording?

Aye captain!

> I also think we aren't consistent: Sometime we speak of deletion, other times of removal.

Removal and deletion have two different purposes:
* `Removal/Remove`: We can use this when another action can produce the opposite result without any loss. **Example:** Removing a user from a store <> Adding a user to a store.
* `Deletion/Deleting`: When an action is permanent and other actions can't get whatever you deleted back to it's previous state
  * We can also use `delete permanently` to emphasis that the action is permanent and it has to be thought of, not rushed.

I also added a bunch of "are you sure?" parts to the strings, to emphasis again to the user that he's taking an action that should be thought of, and not done in a hurry.

2021-09-02 22:21 UTC, Zaxounette commented on BTCPayServer/Views/Manage/TwoFactorAuthentication.cshtml
> +        <a asp-action="Disable2fa" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action py-3" data-bs-toggle="modal" data-bs-target="#ConfirmModal" data-tit
```suggestion
        <a asp-action="Disable2fa" class="list-group-item d-flex justify-content-between align-items-center list-group-item-action py-3" data-bs-toggle="modal" data-bs-target="#ConfirmModal" data-title="Disable two-factor authentication (2FA)" data-description="Disabling 2FA does not change the keys used in the authenticator apps. If you wish to change the key used in an authenticator app you should reset your authenticator keys." data-confirm="Disable 2FA">
```

2021-09-02 22:21 UTC, Zaxounette commented on BTCPayServer/Views/Server/DynamicDnsServices.cshtml
> +                Note that you need to properly configure your NAT and BTCPay Server install to get HTTPS certificate.
```suggestion
                Note that you need to properly configure your NAT and BTCPay Server installation to get the HTTPS certificate. 
```

2021-09-02 22:21 UTC, Zaxounette commented on BTCPayServer/Views/Server/LndSeedBackup.cshtml
> +    <partial name="_Confirm" model="@(new ConfirmModel("Delete LND Seed", "Please make sure you made a backup of the seed and password before deleting the LND backup seed from the server!", "Delete")
```suggestion
    <partial name="_Confirm" model="@(new ConfirmModel("Delete LND Seed", "This action will permanently delete your LND seed and password. You will not be able to recover them if you don't have a backup. Are you sure?", "Delete"))"/>
```

2021-09-02 22:21 UTC, Zaxounette commented on BTCPayServer/Views/UserStores/ListStores.cshtml
> +<partial name="_Confirm" model="@(new ConfirmModel("Delete store", "This action is irreversible and will remove all information related to this store. (Invoices, Apps etc...)", "Delete"))" />
```suggestion
<partial name="_Confirm" model="@(new ConfirmModel("Delete store", "This action will permanently delete this store and its associated settings, apps, invoices, etc... Are you sure?", "Delete"))" />
```

2021-09-03 12:21 UTC, dennisreimann commented
Thanks @Zaxounette, I've incorporated your wording changes. Also included @dstrukt's modal style changes and added the confirmation input, as you can see below:

![delete-confim](https://user-images.githubusercontent.com/886/132004080-6d186bfa-4a9e-401b-b860-f69d0792ca04.gif)

More lightweight actions like archiving a pull request do not require the confirmation input, so that it does not interrupt the user's flow too much. Only destructive actions require it (in case the user has JavaScript enabled -- this is a purely client side feature).

@Kukks can you re-review? I like how this turned out, thanks to you and @pavlenex for the feedback!

2021-09-03 13:02 UTC, dennisreimann commented
The tests work locally, I think they might be flaky.

2021-09-03 13:21 UTC, pavlenex commented
@dennisreimann Can we just use `DELETE`
`LND seed` may confuse some people to type in their actual lnd seed.
Plus, we should pay attention to capitalization and use all caps like they do on github.

2021-09-03 13:55 UTC, dennisreimann commented
@pavlenex Good point, done!

2021-09-03 15:02 UTC, pavlenex commented
@dennisreimann Do we plan to expand this to the delete a user view, doesn't appear that the modal is implemented there?
When deleting a user
![Screenshot 2021-09-03 at 17 00 10](https://user-images.githubusercontent.com/36959754/132026546-86852a20-4992-4e7f-9878-56a6bac4acf3.png)

2021-09-03 15:06 UTC, dennisreimann commented
@pavlenex The delete user case is a bit more [complicated](https://github.com/btcpayserver/btcpayserver/pull/2614/files#L205), because it involves server side checks on the user being an admin and if so, whether or not it's the last admin. I kept it this way, because it would be tricky to move this to the client-side.

2021-09-03 15:08 UTC, pavlenex approved these changes
Alright, makes sense. I've played around a bit with this PR and it LGTM.

2021-09-04 13:50 UTC, NicolasDorier commented
@dennisreimann it seems to me there can be only a single confirm modal per page? What if on the same page there is two different thing that can be deleted?

2021-09-04 13:57 UTC, dennisreimann commented
The modal gets configured via the data attributes of the opening link/button. See for instance the 2FA page, where three different actions are on one page – or the list views.

2021-09-05 11:17 UTC, pavlenex commented
@dennisreimann How about for wallet removal? I assume it's the same case as with the user removal?
Would be good to have confirmation there and modal if possible.

![Screenshot 2021-09-05 at 13 17 13](https://user-images.githubusercontent.com/36959754/132124819-4fb7c13d-f49d-41ec-a45d-934bdc568d16.png)

Tested once again with and LGTM.

2021-09-05 11:44 UTC, dennisreimann commented
Thanks for spotting the inconsistency, will fix that. 

The wallet removal is similar to the user case, it has different conditions depending on whether or not it's a hot wallet. That might be just different texts though, will double check that

2021-09-06 09:26 UTC, Kukks approved these changes
Code looks good now :)

2021-09-06 09:41 UTC, pavlenex approved these changes
tACK.

Great work, let's get this baby merged. 🚀

2021-09-07 02:55 UTC, merged