Greenfield: add text search terms to an invoice
btcpayserver/btcpayserver pull request #2648
Opened 2021-07-01 05:05 UTC by NicolasDorier

* Now it is possible to use `additionalSearchTerms` to the invoice creation via the greenfield API.
* It is possible to text search in the invoice list via greenfield API.

2021-07-01 06:48 UTC, pavlenex commented
#2631

2021-07-01 07:41 UTC, NicolasDorier commented
I gave up calling it "tags" because tags would implies other kind of UX concept. (like a way to group by tags all the invoices)
Here we just add the words to the search index.

2021-07-02 08:11 UTC, Kukks requested changes
Just one comment.

2021-07-02 08:11 UTC, Kukks commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +        public string[] AdditionalSearchTerms { get; set; }
I think we should make this property available also when invoices are fetched. Otherwise, integrations are blind in terms of what they have set it to.

2021-07-05 03:18 UTC, NicolasDorier commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +        public string[] AdditionalSearchTerms { get; set; }
That's actually the big reason why I called it `addtionalSearchTerms` rather than `tags`.

If we expose this, then it begs the question of why we don't show other terms as well?

2021-07-08 07:28 UTC, Kukks commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +        public string[] AdditionalSearchTerms { get; set; }
> If we expose this, then it begs the question of why we don't show other terms as well?
Because they are predefined by existing data. We could just document what the default terms are.

2021-07-08 07:29 UTC, Kukks commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +        public string[] AdditionalSearchTerms { get; set; }
I think it makes sense to have both features, but both should be exposed

2021-07-09 01:57 UTC, NicolasDorier commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +        public string[] AdditionalSearchTerms { get; set; }
So you mean for each invoice we should expose all the indexed terms? That seem to me quite useless. It's not like any search engine is doing that.

2021-07-09 06:54 UTC, Kukks commented on BTCPayServer.Client/Models/CreateInvoiceRequest.cs
> +        public string[] AdditionalSearchTerms { get; set; }
> So you mean for each invoice we should expose all the indexed terms? That seem to me quite useless. It's not like any search engine is doing that.
> 
> But if we do it, this is not be limited to AddtionalSearchTerms, but should be to all terms.

No I mean AddtionalSearchTerms is what should be exposed because everything else added to the search index is pre-determined and they know it just by looking at existing data (we can document it). All the indexed data is already available via API
```
foreach (var paymentMethod in invoice.GetPaymentMethods())
                    {
                        if (paymentMethod.Network != null)
                        {
                            var paymentDestination = paymentMethod.GetPaymentMethodDetails().GetPaymentDestination();
                            textSearch.Add(paymentDestination);
                            textSearch.Add(paymentMethod.Calculate().TotalDue.ToString());
                        }
                    }
                    // 
                    textSearch.Add(invoice.Id);
                    textSearch.Add(invoice.InvoiceTime.ToString(CultureInfo.InvariantCulture));
                    textSearch.Add(invoice.Price.ToString(CultureInfo.InvariantCulture));
                    textSearch.Add(invoice.Metadata.OrderId);
                    textSearch.Add(invoice.StoreId);
                    textSearch.Add(invoice.Metadata.BuyerEmail);
                    //
                    textSearch.Add(invoice.RefundMail);
```

2021-07-14 14:32 UTC, NicolasDorier commented
As discussed, merging this. If anybody ask requesting it, we can add.
Or maybe just add a real tag system later.

2021-07-14 14:32 UTC, merged