Add misc/permissions to document the hierarchical structure
btcpayserver/btcpayserver pull request #2654
Opened 2021-07-02 06:57 UTC by NicolasDorier

This document which permission include which other in the form (I renamed `subPermissions` to `included`)

@Kukks I am thinking, maybe in a later PR, also adding the description. Then getting rid of the human description of each permission in the doc, and rather referencing this operation directly.

![image](https://user-images.githubusercontent.com/3020646/124233684-0dc6da80-db4e-11eb-9c1e-ebdfbd6992d2.png)

2021-07-02 07:22 UTC, Kukks requested changes
Just one comment around a possible bug

2021-07-02 07:22 UTC, Kukks commented on BTCPayServer.Client/Models/PermissionMetadata.cs
> +            foreach (var n in nodes)
I think we need a recursive method here instead in case there are sub permissions more than 1 level deep

2021-07-05 01:33 UTC, NicolasDorier commented on BTCPayServer.Client/Models/PermissionMetadata.cs
> +            foreach (var n in nodes)
I don't think we need, because we are looping on all permissions. The API is not hierarchical, it is just a list of the permission included in each permission.

The `Permission.Contains` would properly returns true whatever how deep the hierarchy is.

2021-07-06 22:09 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.misc.json
> +                                                "type": "string",
Wouldn't this be type `"array"`?

2021-07-06 22:09 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.misc.json
> +                    "Miscalleneous"
Typos here, should be `miscellaneous`

2021-07-06 22:09 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.json
> +                "description": "BTCPay Server supports authenticating and authorizing users through an API Key that is generated by them. Send the API Key as a header value to Authorization with the
`#operation/langCodes` pointing to the wrong ID?

2021-07-08 04:10 UTC, NicolasDorier commented
Fixed all

2021-07-08 05:34 UTC, merged