Re-enable "Create" button for invoices on correct form input
btcpayserver/btcpayserver pull request #2694
Opened 2021-07-11 23:11 UTC by bolatovumar

fix #2693

2021-07-12 10:09 UTC, dennisreimann approved these changes

2021-07-12 13:11 UTC, satwo commented
tACK.

2021-07-13 06:19 UTC, Kukks requested changes
small change requested. Would prefer if we could hook on to some validation events instead but the plugin used is ancient and doesn't seem to offer such features.

2021-07-14 04:02 UTC, bolatovumar commented on BTCPayServer/Views/Invoice/CreateInvoice.cshtml
> +            $("input").on("input", function () {
@Kukks done here: $("#create-invoice-form input")

2021-07-14 14:49 UTC, merged