Add support for uploading multiple files to server
btcpayserver/btcpayserver pull request #2705
Opened 2021-07-20 15:02 UTC by cypherbeerus

#899 
Changed file upload object to a list, which allows multiple files to be uploaded at once.

2021-07-21 05:56 UTC, Kukks commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +                        this.TempData.SetStatusMessageModel(new StatusMessageModel()
You should probably do a counter of invalid file names  and set the status message based on the counter result (if counter ==0 show "Files added", else if counter >0 & counter< files.length show "only x files added due to invalid files" else show "files could not be added"

2021-07-21 06:00 UTC, Kukks commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +                        fileId = fileIds[0]
Perhaps due to this change, we should enhance the `Files` action to accept an array of `fileIds` instead. We can do this in a separate PR.

2021-07-21 06:01 UTC, Kukks requested changes
Left a comment around the setting of the status message, and tests need to be fixed.

2021-07-21 07:38 UTC, cypherbeerus commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +                        fileId = fileIds[0]
Yes, this makes sense. I'll create a separate issue later for this.

2021-07-22 06:48 UTC, Kukks requested changes
Looks great now, good job on your first contribution!

2021-07-22 06:48 UTC, Kukks approved these changes
Oops, my evil twin wanted to reject this.  I'll approve :)

2021-07-22 06:49 UTC, merged