Implement topup invoices
btcpayserver/btcpayserver pull request #2730
Opened 2021-08-01 03:13 UTC by NicolasDorier

2021-08-01 03:48 UTC, NicolasDorier commented
ping @Kukks @dennisreimann

2021-08-02 03:43 UTC, NicolasDorier commented
I am really on the fence on the nullable things.

1. This might be a breaking change. If you use a client which expect to always have an amount on an invoice (if calling GetInvoices for example)
2. Now we need to check if the amount is null all the time.

That said, I don't see other good alternative.

2021-08-02 08:06 UTC, Kukks commented
> I am really on the fence on the nullable things.
> 
> 1. This might be a breaking change. If you use a client which expect to always have an amount on an invoice (if calling GetInvoices for example)
> 2. Now we need to check if the amount is null all the time.
> 
> That said, I don't see other good alternative.

The alternative is to have 0 amount + isTopup

2021-08-02 08:38 UTC, NicolasDorier commented
@Kukks there are advantage to this actually. Since the amount change for the topup, right now we can't know if an invoice was topup when it has been paid.

2021-08-02 12:20 UTC, NicolasDorier commented
will implement this
```
	
kukks
7:45 PM



I say we add type to invoice  where value can be Standard and Topup. 
If: 

creating using Bitpay: Type is ALWAYS standard no matter what
creating using Greenfield: You specify type but if amount is set >0. the validation error. if amount is null the type is implicitly toptip
fetching topup invoice using Bitpay: I am inclined to say it should return not found. But we can also just send it back with 0 amount
fetching topup invoice using Greenfield: send it back with 0 amount. The type property will help identify it and the status not being complete will protect the flow for existing integrations
```

2021-08-03 03:47 UTC, NicolasDorier commented
@Kukks  ended up following your advice, except I allow the creation of topup via bitpay API.
It turns out it is actually simpler code wise. However, I do not expose the type of invoice in their API.

2021-08-03 06:25 UTC, Kukks requested changes

2021-08-03 06:25 UTC, Kukks commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +                if (invoiceData == null)
We should check if invoice type is topup

2021-08-03 08:03 UTC, merged