Enhance files actions to accept arrays of fileids
btcpayserver/btcpayserver pull request #2735
Opened 2021-08-01 13:06 UTC by cypherbeerus

#2707

2021-08-01 13:45 UTC, cypherbeerus commented
@kukks @rockstardev 
Build failing on test "EnsureNewLightningInvoiceOnPartialPayment". 
Unable to figure out the reason.

2021-08-01 17:20 UTC, rockstardev commented
@Kukks `EnsureNewLightningInvoiceOnPartialPayment` test has failed twice in a row before finally passing:

https://app.circleci.com/pipelines/github/btcpayserver/btcpayserver?branch=pull%2F2735

![image](https://user-images.githubusercontent.com/5191402/127779875-8f911814-80c0-4138-88a7-fb9f2264b417.png)

2021-08-02 02:24 UTC, NicolasDorier commented
Should we merge this for this release @rockstardev ?

2021-08-02 08:05 UTC, Kukks requested changes
Suggested some changes for simplification of the logic

2021-08-02 08:05 UTC, Kukks commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +                var model = new ViewFilesViewModel()
We cna probably get away with having this one instantiation of the view model for the entre method with some fine-tuning of the above logic (better to avoid 3 different ways of creating the same VM that you want to return)

2021-08-02 08:05 UTC, Kukks commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +                    fileId = JsonConvert.SerializeObject(fileIds),
As mentioned above, make fileId a string array and just pass the fileIds to it instead of jsonifying it into a string and needing a multiple flag.

2021-08-02 08:05 UTC, Kukks commented on BTCPayServer/Models/ServerViewModels/ViewFilesViewModel.cs
> +        public List<string> DirectFileUrls { get; set; }
Personally I would prefer a dedicated property that holds both of these items. Perhaps a `Dictionary<string,string> directFileUrlForSelectedFiles`  where the key is the selected file id and the value is the direct file url

2021-08-02 08:30 UTC, cypherbeerus commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +        public async Task<IActionResult> Files(string fileId = null, bool multiple = false)
fileId is an optional route parameter. How can that be a list?

2021-08-03 12:54 UTC, dennisreimann commented
Not directly related to this PR, but we should clean up the UI once this is merged. Also the UX can be improved as having the file details separately below the files table is rather unintuitive.

2021-08-03 16:43 UTC, cypherbeerus commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +        public async Task<IActionResult> Files(string fileId = null, bool multiple = false)
Hi! I tried sorting this out. 
fileId is a route parameter. I'm not sure if there's a way other than serializing the list, or converting fileId to a query parameter.

2021-08-03 16:45 UTC, cypherbeerus commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +        public async Task<IActionResult> Files(string fileId = null, bool multiple = false)
Are we fine with converting fileId to a query parameter?
The API calls will now look like
GET /server/files?fileId=f1&fileId=f2

2021-08-03 16:45 UTC, cypherbeerus commented on BTCPayServer/Models/ServerViewModels/ViewFilesViewModel.cs
> +        public List<string> DirectFileUrls { get; set; }
Will update this. Agreed that the mapping would be better.

2021-08-04 15:06 UTC, cypherbeerus commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +                {
Done

2021-08-04 15:06 UTC, cypherbeerus commented on BTCPayServer/Controllers/ServerController.Storage.cs
> +        public async Task<IActionResult> Files(string fileId = null, bool multiple = false)
Added a new commit.

2021-08-05 03:44 UTC, dstrukt commented
Second @dennisreimann's call, but great work, excited to see this functionality get worked into btcpay!

2021-08-06 07:37 UTC, Kukks requested changes

2021-08-06 07:37 UTC, Kukks commented on BTCPayServer/Models/ServerViewModels/ViewFilesViewModel.cs
> +        public string[] SelectedFileIds { get; set; }
This is not needed as `DirectUrlByFiles.Keys` should yield the same list

2021-08-06 22:11 UTC, cypherbeerus commented on BTCPayServer/Models/ServerViewModels/ViewFilesViewModel.cs
> +        public string[] SelectedFileIds { get; set; }
done

2021-08-09 12:14 UTC, pavlenex commented
tACK.

2021-08-09 14:40 UTC, merged