Fix bug with top-up invoices when used with "Only enable the payment method after user explicitly chooses it" enabled
btcpayserver/btcpayserver pull request #2780
Opened 2021-08-17 04:35 UTC by bolatovumar

close #2772

2021-08-17 04:36 UTC, bolatovumar commented on BTCPayServer/Controllers/InvoiceController.cs
> +                if (storeBlob.LazyPaymentMethods && entity.Type != InvoiceType.TopUp)
This is the actual fix, the rest is just me specifying that certain values can be `null`.

2021-08-17 04:36 UTC, bolatovumar commented on BTCPayServer/Controllers/InvoiceController.cs
> -using System.ComponentModel.DataAnnotations;
Unused directives.

2021-08-17 09:09 UTC, Kukks requested changes
I don't think this is correct. It completely removes compatibility of Topup invoices + Lazy Payments. The fix needs to happen in the LightningLikePaymentHandler somehow.

2021-08-22 20:46 UTC, bolatovumar commented
@Kukks alright, I updated it in https://github.com/btcpayserver/btcpayserver/pull/2780/commits/5fa520708c0828970d059395d64a58199f406705 to check in `LightningLikePaymentHandler`. Not sure if it's entirely the right approach.

2021-08-22 20:48 UTC, bolatovumar commented on BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs
> +            LightningSupportedPaymentMethod supportedPaymentMethod, PaymentMethod paymentMethod, Data.StoreData store,
Had to update this to `Data.StoreData` because now `StoreData` is an ambiguous reference as there is also a `StoreData` in `BTCPayServer.Client.Models`.

2021-08-22 20:48 UTC, bolatovumar commented on BTCPayServer/Payments/Lightning/LightningLikePaymentHandler.cs
> +using BTCPayServer.Client.Models;
Replaced unused `BTCPayServer.Rating` with `BTCPayServer.Client.Models` which has the `InvoiceType` enum.

2021-08-23 06:06 UTC, Kukks approved these changes
ACK

2021-08-23 06:13 UTC, merged