Refactor themes
btcpayserver/btcpayserver pull request #2794
Opened 2021-08-20 15:53 UTC by dennisreimann

In [design call #11](https://github.com/btcpayserver/organization/issues/40#issuecomment-863577103) we decided to deprecate the Classic and Casa theme, as well as to make the theme switch a per user setting.

Putting this out here as WIP to discuss the technical implications.

97371e0 is a cleanup in which the customizability of the Bootstrap and Creative Start CSS files gets removed. I think we can assume that no one is using this feature -- otherwise we would have heard of this, because `creative.css` is based on Bootstrap 4 and the recent migration would have broken stuff for users in that case.
Making these files a part of our bundle simplifies the maintenance and the customizability options are fairly limited anyways, as one would have to generate a custom Bootstrap version. We should discourage that and rather guide people towards the customizability via theme variable files, which will make maintenance easier for us and the users.

c04eb5b removes the Casa and Classic theme files. They are [still available via the design system](https://design.btcpayserver.org/resources/css/#old-themes) and should be added as custom theme CSS file, like any other customized version.

The next step after discussing this would be to make the theme switch a user facing setting, like we do on the website, docs and blog. This way users can choose if they prefer light or dark. If the admin sets a custom theme, the light/dark theme switch could be hidden.

A bunch of ideas, open for discussion :) /cc @dstrukt

2021-08-23 09:59 UTC, pavlenex commented
Concept ACK, I think removing those two was long-overdue and also ACK on user-preference theme selection.

How would this affect users using the casa theme and updating? I assume they'd be switched to a default one?

2021-08-23 13:54 UTC, dennisreimann commented
> How would this affect users using the casa theme and updating? I assume they'd be switched to a default one?

Right now, as it is implemented in this PR, they'd fall back to the default light theme.

Here's a demo of the current state -- the basic implementation is finished now and we can discuss the technical implications (mainly the refactoring of `ThemesSettings.cs` and everything that follows from that) now.

2021-08-23 14:41 UTC, Kukks approved these changes
looks good code wise

2021-08-23 16:32 UTC, pavlenex commented
Really good flow there @dennisreimann! Great work.

2021-08-23 19:13 UTC, Zaxounette approved these changes

2021-08-23 21:14 UTC, dennisreimann commented
@pavlenex This'd be a good one for user testing. I'll post it to the testers channel.

2021-08-23 22:23 UTC, dstrukt commented
Great work!

I think the next modifications to our menu are going to tie in nicely to this!

I updated the copy, as there are no pre-selectable themes (anymore), just adding a custom CSS file. I took a stab at it. 

"Please provide a CSS theme file."

Feel free to modify or improve as needed.

2021-08-24 00:20 UTC, Zaxounette requested changes
@dstrukt 
Iterated upon your proposed COPY.

2021-08-24 00:20 UTC, Zaxounette commented on BTCPayServer/Views/Server/Theme.cshtml
> +            <p>Please provide a CSS theme file.</p>
```suggestion
            <p>Use the default Light or Dark Themes, or provide a CSS theme file below.</p>
```

2021-08-24 00:42 UTC, dstrukt commented on BTCPayServer/Views/Server/Theme.cshtml
> +            <p>Please provide a CSS theme file.</p>
There we go.

2021-08-24 07:09 UTC, dennisreimann commented on BTCPayServer/Views/Server/Theme.cshtml
> +            <p>Please provide a CSS theme file.</p>
Thanks to both of you! 🙏

2021-09-02 14:01 UTC, dennisreimann commented
Rebased and ready to rock!

2021-09-03 07:16 UTC, merged