Add ability to set default payment method on invoice basis
btcpayserver/btcpayserver pull request #2815
Opened 2021-08-30 01:22 UTC by bolatovumar

2021-08-30 06:15 UTC, Kukks requested changes
Code looks good but you need a test

2021-09-01 07:46 UTC, Kukks approved these changes

2021-09-01 07:47 UTC, Kukks requested changes
Selenium test you added fails. Maybe you need to wait a bit before trying to grab the currency dropdown

2021-09-02 02:01 UTC, bolatovumar commented
@Kukks I fixed the test (it was using the wrong selector) and confirmed that it passes locally but now a bunch of tests are failing in CI because of timeouts. I don't think it's related to my change as I only change a selector in one test. Is there a way to re-run the tests? I can't click on that button in CI.

2021-09-03 17:09 UTC, bolatovumar commented
@Kukks alright, build is green now.

2021-09-03 19:18 UTC, Kukks approved these changes

2021-09-04 13:12 UTC, NicolasDorier commented on BTCPayServer/Services/Invoices/InvoiceExtensions.cs
> +            this InvoiceRepository invoiceRepository,
1. `invoiceRepository` is not used
2. Do we really need this? I think this extension method is used only once.

2021-09-04 17:11 UTC, bolatovumar commented on BTCPayServer/Services/Invoices/InvoiceExtensions.cs
> +            this InvoiceRepository invoiceRepository,
@NicolasDorier I added this here because the similar method for getting the default payment id for a store was in a store extensions class os I just did the same here. I can move it out of here though, it doesn't really matter.

2021-09-04 22:38 UTC, bolatovumar commented on BTCPayServer/Services/Invoices/InvoiceExtensions.cs
> +            this InvoiceRepository invoiceRepository,
@NicolasDorier updated in this commit: 97f5fac2024fc58c7d3b3f37f826b3d5884ef8ae (there is a failing test in CI but it's unrelated)

2021-09-07 13:43 UTC, ndeet commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.invoices.json
> +                        "description": "Default payment type for the invoice (e.g., BTC, BTC_LightningLike). Default payment method set for the store is used if this parameter is not specified."
nitpick: on line 1026 above the examples use `-` to concatenate the payment method strings `BTC-LightningNetwork`, not sure if underscore also works too but for consistency we should stick to one of them. As the Greenfield API returns `BTC-LightningNetwork` I would stick with that

2021-09-10 04:37 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.invoices.json
> +                        "description": "Default payment type for the invoice (e.g., BTC, BTC_LightningLike). Default payment method set for the store is used if this parameter is not specified."
@ndeet Actually, both of them work. For some reason internally we use the one with the underscore but the one with a dash also works. I updated the example in this commit: be3b1f3ec79f353f74ba0efe333e1053c1a544ff

Just to provide an example, this works:

```json
{
    "currency": "USD",
    "amount": 100,
    "checkout": {
        "defaultPaymentMethod": "BTC-LightningNetwork"
    }
}
```

and this works:

```json
{
    "currency": "USD",
    "amount": 100,
    "checkout": {
        "defaultPaymentMethod": "BTC_LightningLike"
    }
}
```

2021-09-16 05:29 UTC, merged