Disallow cancelling payment request when "Allow payee to create invoices in their own denomination" is not enabled
btcpayserver/btcpayserver pull request #2843
Opened 2021-09-06 01:02 UTC by bolatovumar

close #2802

2021-09-06 08:52 UTC, Kukks requested changes
You need to add the same logic to the backend.

2021-09-06 18:59 UTC, bolatovumar commented
> You need to add the same logic to the backend.

@Kukks done here: fda2b00c84cdb4422c822d2f6db09f1981b33989

Also updated the non-JS view to follow the same logic here: https://github.com/btcpayserver/btcpayserver/pull/2843/commits/9a8216fd2f62e8903ed94d452ac1c9d6ea8f27ab

2021-09-09 07:46 UTC, Kukks approved these changes
Awesome lgtm

2021-09-09 07:47 UTC, Kukks requested changes
Actually, you now need to adjust the test `CanCancelPaymentWhenPossible` as the logic is different.

2021-09-13 03:09 UTC, bolatovumar commented on BTCPayServer.Tests/PaymentRequestTests.cs
> +                Assert.IsType<BadRequestObjectResult>(await
I will first try to cancel the payment request without `AllowCustomPaymentAmounts` set to `true` and assert that it fails and then set `AllowCustomPaymentAmounts` to `true`  and expect the rest of the test to pass as is was previously.

2021-09-13 03:40 UTC, bolatovumar commented
> Actually, you now need to adjust the test `CanCancelPaymentWhenPossible` as the logic is different.

@Kukks updated tests in this commit: 37222aacff37ef7eb8cdcaa13edd6eecc607fcbb

2021-09-17 01:24 UTC, NicolasDorier commented on BTCPayServer/Controllers/PaymentRequestController.cs
> +                return BadRequest("Not allowed to cancel this invoice");
@rockstardev do we have a vin diesel error page for this one? :p

2021-09-17 01:24 UTC, merged

2021-09-17 01:25 UTC, NicolasDorier commented
Ping @pavlenex you should take a look as well