Show total balances for each currency on List Wallets Page
btcpayserver/btcpayserver pull request #2882
Opened 2021-09-15 14:54 UTC by maxdignan

2021-09-15 20:26 UTC, dstrukt commented
Mind posting screenshots of the change in the future?

Thanks!

2021-09-15 23:03 UTC, maxdignan commented
Shared here: https://github.com/btcpayserver/btcpayserver/discussions/2306

2021-09-16 05:19 UTC, dstrukt commented
Forgot this was already a PR, apologies, it's been a long day. Link to mocks in the discussion below:

https://github.com/btcpayserver/btcpayserver/discussions/2306#discussioncomment-1336629

Will continue to post updates here.

2021-09-27 15:38 UTC, dennisreimann requested changes

2021-09-27 15:38 UTC, dennisreimann commented on BTCPayServer/Views/Wallets/ListWallets.cshtml
> +                    }
Can you change the whole upper row into this, so that it fits the design @dstrukt came up with?

```cshtml
        <div class="d-sm-flex justify-content-between mb-2">
            <h2 class="mb-0">
                @ViewData["Title"]
                <small>
                    <a href="https://docs.btcpayserver.org/Wallet/" target="_blank" rel="noreferrer noopener">
                        <span class="fa fa-question-circle-o text-secondary" title="More information..."></span>
                    </a>
                </small>
            </h2>
            @if (Model.Wallets.Any())
            {
                <div class="mt-2 mt-sm-1">
                    @foreach (var balanceForACrypto in @Model.BalanceForCryptoCode)
                    {
                        <div class="fs-5 fw-semibold">@(balanceForACrypto.Value.ShowMoney(balanceForACrypto.Key) + " " + balanceForACrypto.Key.CryptoCode)</div>
                    }
                    <div class="text-muted text-sm-end fs-6">Total Balance</div>
                </div>
            }
        </div>
```

2021-09-27 19:04 UTC, maxdignan commented on BTCPayServer/Views/Wallets/ListWallets.cshtml
> +                    }
Just updated in adherence to the designs 👍

2021-09-28 06:07 UTC, dennisreimann commented on BTCPayServer/Views/Wallets/ListWallets.cshtml
> +                    }
You can replace the whole `div.row`, now there are nested rows and the indenting is kinda messed up. If you grant me access to your fork I can also clean it up.

2021-09-28 18:54 UTC, dstrukt commented
Looking forward to seeing this! Can we get some screenshots?

2021-09-28 18:59 UTC, maxdignan commented on BTCPayServer/Views/Wallets/ListWallets.cshtml
> +                    }
Invited you @dennisreimann . Thanks for the help!

2021-09-29 09:55 UTC, dennisreimann commented
Worth discussing too: We could get rid of the trailing zeros and the crypto code column of the table. @NicolasDorier 

## Mobile

![mobile](https://user-images.githubusercontent.com/886/135246324-3c25f65c-c6ba-4aac-94f5-5cf3b25ff2ef.png)

## Desktop
![desktop](https://user-images.githubusercontent.com/886/135246332-f74a4488-07c5-412f-bf33-681004645bb9.png)

2021-09-29 09:56 UTC, dennisreimann approved these changes

2021-09-29 11:40 UTC, dennisreimann commented
Rebased to fix Selenium tests.

2021-10-01 09:39 UTC, pavlenex commented
@dennisreimann I wonder what happens when you have shitcoins enabled? How do we display those, I assume every `cryptocode` has its own balance? Not sure how it looks visually.

2021-10-01 10:48 UTC, dennisreimann commented
Yes, it'd display them underneath each other. We once discussed this in a design meeting and concluded it might be best to only add this feature for the bitcoin-only build, so that we do not have to care about the rest and displaying tons of shitcoins. 

Let's discuss this in the context of this issue, now that it comes up in practice :)

2021-10-04 15:07 UTC, Kukks approved these changes

2021-10-04 15:10 UTC, merged

2021-10-04 19:28 UTC, dstrukt commented
yeah, this was primarily created for bitcoin only, we might be able to come up with another creative solution for the shitcoins, but it was a lower priority to get this shipped