Fixed wrong API permission for GreenField/StorePaymentMethodsController.cs
btcpayserver/btcpayserver pull request #2905
Opened 2021-09-22 12:31 UTC by woutersamaey

Viewing store payment methods needs CanViewStoreSettings instead of CanModifyStoreSettings as per the docs

2021-09-22 12:33 UTC, woutersamaey commented
@Kukks and @ndeet this may interest you. The permissions are wrong in code, but correct in the docs.

2021-09-22 14:37 UTC, Kukks approved these changes
i think it is an actual bug but maybe @NicolasDorier has some more insight?

2021-09-23 05:28 UTC, Kukks requested changes
So, potentially this is on purpose because for `GetLightningNetworkPaymentMethod`, it is also `CanModifyStoreSettings`.

Most likely, the reasoning is that the payment method contains sensitive information that would compromise the security of your payment method, even if it is only with viewing rights. For example, the lightning connection string could contain the access token/macaroon to control and spend from your lightning node.

2021-09-23 07:14 UTC, woutersamaey commented
@Kukks this cuts both ways, doesn't it?

Either you compromise on security by weakening your LN config security
Or, you weaken your installation by creating and storing API keys in an eCommerce system that can be hacked and more control can be gained than was needed.

The best solution would be to censor the potentially dangerous fields if the lesser permissions is used, and include the sensitive info when an API key with more permissions is used.

That way you get security for both cases, but I guess some refactoring would be involved? Or can you simply filter out the values as a filter before data is output from the controller? (i.e. set the dangerous values to NULL or something like `*HIDDEN*` or `***`

2021-09-23 07:40 UTC, Kukks commented
> @Kukks this cuts both ways, doesn't it?
> 
> Either you compromise on security by weakening your LN config security
> Or, you weaken your installation by creating and storing API keys in an eCommerce system that can be hacked and more control can be gained than was needed because the API key was created with otherwise less permissions.
> 
> The best solution would be to censor the potentially dangerous fields if the lesser permissions is used, and include the sensitive info when an API key with more permissions is used.
> 
> That way you get security for both cases, but I guess some refactoring would be involved? Or can you simply filter the values before data is output from the controller? (i.e. set the dangerous values to something like `*HIDDEN*` or `***`
> 
> Just trying to find an easy solution here...

Yeah, this is probably the best way.

2021-10-04 05:54 UTC, Kukks commented
Fixed up the PR with the discussed changes.

2021-10-04 06:48 UTC, woutersamaey commented
Probably nitpicking here, but I believe `*HIDDEN*` would've been less confusing to newbies over that `###` you used.
I fear this will lead to more support questions.

Maybe better yet would be something like `*NEED CanModifyStoreSettings PERMISSION TO VIEW*`

2021-10-04 08:43 UTC, Kukks requested changes

2021-10-04 08:43 UTC, Kukks commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +            Assert.NotEqual("###", lightningNetworkPaymentMethodBaseData.ConnectionString);
```suggestion
            Assert.NotEqual("*NEED CanModifyStoreSettings PERMISSION TO VIEW*", lightningNetworkPaymentMethodBaseData.ConnectionString);
```

2021-10-04 08:43 UTC, Kukks commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +            Assert.Equal("###", lightningNetworkPaymentMethodBaseData.ConnectionString);
```suggestion
            Assert.Equal("*NEED CanModifyStoreSettings PERMISSION TO VIEW*", lightningNetworkPaymentMethodBaseData.ConnectionString);
```

2021-10-04 08:43 UTC, Kukks commented on BTCPayServer/Payments/PaymentTypes.Lightning.cs
> +                            "###"
```suggestion
                            "*NEED CanModifyStoreSettings PERMISSION TO VIEW*"
```

2021-10-04 09:34 UTC, woutersamaey commented
Awesome!

2021-10-04 15:06 UTC, merged