Add admin badge to user list
btcpayserver/btcpayserver pull request #3033
Opened 2021-10-29 22:57 UTC by satwo

Currently, a user must click "Edit" on each individual user to see whether that user has admin privs.

This PR provides list-view visibility of admin privs by adding an `ADMIN` badge beside an admin user's email.

![image](https://user-images.githubusercontent.com/4956763/139509672-30607e71-d668-4d9d-ab33-2a0532e183ae.png)

2021-10-29 23:13 UTC, satwo commented on BTCPayServer/Controllers/ServerController.Users.cs
> +            }
@NicolasDorier @rockstardev @Kukks  Instead of this foreach loop, any ideas on a more elegant way to assign the `IsAdmin` directly in the LINQ Select() query above? 

I tried for a bit but couldn't make anything work with all the async stuff going on.

2021-10-30 01:50 UTC, NicolasDorier commented on BTCPayServer/Controllers/ServerController.Users.cs
> +            }
In the Select clause, you should be able to reach the Roles of the user `u.`.

2021-10-30 02:52 UTC, satwo commented on BTCPayServer/Controllers/ServerController.Users.cs
> +            }
Tried for a while and coming up short...

2021-10-30 03:38 UTC, Zaxounette requested changes
I'll just ping @dennisreimann and @dstrukt to see if they can make it a bit prettier UI wise.

Other than that, tACK the idea.

2021-10-30 06:20 UTC, dennisreimann commented on BTCPayServer/Views/Server/ListUsers.cshtml
> +                    <span class="badge">ADMIN</span>
```suggestion
                    <span class="badge bg-info">Admin</span>
```

2021-10-30 20:35 UTC, dstrukt commented on BTCPayServer/Views/Server/ListUsers.cshtml
> +                    <span class="badge">ADMIN</span>
ACK.

Great addition @satwo!

2021-10-30 21:05 UTC, satwo commented on BTCPayServer/Views/Server/ListUsers.cshtml
> +                    <span class="badge">ADMIN</span>
Thanks @dstrukt !

2021-11-08 10:22 UTC, pavlenex approved these changes
tACK https://github.com/btcpayserver/btcpayserver/pull/3033/commits/4af6299ec443b9468ce45490b6e4289241f30721

2021-11-08 10:23 UTC, dennisreimann approved these changes

2021-11-10 09:49 UTC, Kukks approved these changes

2021-11-10 09:49 UTC, merged

2021-11-15 08:47 UTC, NicolasDorier commented
this shouldn't have been merged. We shouldn't have one query per line.

2021-11-15 08:52 UTC, dennisreimann commented
> We shouldn't have one query per line.

Agreed, can you fix this and show @satwo and me how it should be done? We couldn't make it work.

2021-11-16 14:03 UTC, satwo commented
This is an issue I've already come across twice actually. @dennisreimann I will hit the books to try to understand `async` better and try to find a better solution for this situation.