New API endpoint: Send email using store SMTP
btcpayserver/btcpayserver pull request #3181
Opened 2021-12-06 19:54 UTC by woutersamaey

- Send a plain text email using the Store's SMTP
- No HTML mail support yet as we may want to develop our own email letterhead etc at a later time
- No attachment support yet, this could be an incremental improvement later on
- I'm using the `CanModifyStoreSettings` permission, but think we can make a new permission `CanSendStoreEmail` or similar as we are adding a new feature. Changing this later would mean breaking changes at that time, so would be best to consider this now.

**Usage**
```
POST /api/v1/stores/xxxxx/email
{"toName": "Wouter Samaey", "toEmail": "wouter.samaey@storefront.be", "subject": "Hey hey!", "body": "Testing testing"}
```

**Responses**
200 OK
404 if store not found
400 SMTP not configured yet
400 some other email problem

2021-12-06 19:54 UTC, woutersamaey commented
Swagger coming later

2021-12-11 15:39 UTC, woutersamaey commented
I should probably change the response code for "some other email problem" to something in the 500 range. Will investigate a bit more and update.

2021-12-15 03:37 UTC, NicolasDorier commented
@woutersamaey can you review/test then rebase on https://github.com/btcpayserver/btcpayserver/pull/3202 once merged?

2021-12-21 11:13 UTC, Kukks requested changes

2021-12-21 11:13 UTC, Kukks commented on BTCPayServer.Client/BTCPayServer.Client.csproj
> +      <PackageReference Include="MimeKit" Version="3.0.0" />
we should not add this dependency to the client

2021-12-21 11:13 UTC, Kukks commented on BTCPayServer.Client/Models/SendEmailRequest.cs
> +        public MailboxAddress toMailAddress()
Can just be an extension method inside BTCPay  project

2021-12-21 11:13 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/StoreSendEmail.cs
> +            var client = await emailSettings.CreateSmtpClient();
We should ideally use the `EmailSenderFactory` service here

2021-12-21 11:14 UTC, Kukks commented on BTCPayServer.Client/Models/SendEmailRequest.cs
> +        public MailboxAddress toMailAddress()
Also: pascal case

2021-12-21 11:30 UTC, woutersamaey commented on BTCPayServer.Client/Models/SendEmailRequest.cs
> +        public MailboxAddress toMailAddress()
You mean putting this in a plugin? If so I don't want to do this. The reason I'm making this is so that sending emails in the name of the store becomes easier for Zapier users.

2021-12-22 15:20 UTC, Kukks commented on BTCPayServer.Client/Models/SendEmailRequest.cs
> +        public MailboxAddress toMailAddress()
No, c# has a concept called extension methods for example:

```cs
public static class EmailExtensions{
  public static  MailboxAddress ToMailAddress(this SendEmailRequest request){
	return new MailboxAddress(request.ToEmail, request.ToName);
  }
}
```


This could live inside Btcpayserver proj, while the Btcpayserver.client can remove the mimekit dependency

2022-03-11 07:37 UTC, woutersamaey commented
@Kukks do we have a markdown to HTML tool in BTCPay? It may be handy to allow markdown for the email body. This would allow you some basic email formatting without going full HTML which can later conflict with email templates.

I'd add a field `body_type` and set that to `plain` or `markdown`.

The markdown body can be put inside a full email template without breaking the HTML around it.

I'm thinking about this as with eCommerce emails, you'll likely want to have some rich content such as an order table or a few links, bullets, etc. Allowing only plain text is very very restrictive.

2022-03-11 07:54 UTC, Kukks commented
> @Kukks do we have a markdown to HTML tool in BTCPay? It may be handy to allow markdown for the email body. This would allow you some basic email formatting without going full HTML which can later conflict with email templates.
> 
> I'd add a field `body_type` and set that to `plain` or `markdown`.
> 
> The markdown body can be put inside a full email template without breaking the HTML around it.
> 
> I'm thinking about this as with eCommerce emails, you'll likely want to have some rich content such as an order table or a few links, bullets, etc. Allowing only plain text is very very restrictive.

This is out of scope for this PR. Let's keep it lean.

PS. I adapted this PR to sue the internal services we use for sending emails. Email bodies are html by default. The endpoint is now also /v1/stores/storeid/email/send so that we have /v1/stores/storeid/emaill for configuring the email settings

2022-03-11 09:17 UTC, merged