Store centric finetuning
btcpayserver/btcpayserver pull request #3205
Opened 2021-12-16 10:28 UTC by dennisreimann

WIP to address #3180 and #3183.

2021-12-20 11:01 UTC, Kukks requested changes
small change on the way logic is handled around context data

2021-12-20 14:19 UTC, dennisreimann commented on BTCPayServer/Controllers/AppsController.Crowdfund.cs
> +            if (CurrentApp == null)
Thanks, addressed in b9d6df5.

2021-12-21 08:23 UTC, Kukks approved these changes

2021-12-21 08:24 UTC, merged

2021-12-22 09:50 UTC, NicolasDorier commented
This code is changing authorizations.
Code that was previously checking if the user was an owner of the payment request, now is only checking if the user has access to the app.