PaymentReq "Created" is not really a unix timestamp in JSON. Also renamed to "CreatedTime" like with invoices
btcpayserver/btcpayserver pull request #3221
Opened 2021-12-21 09:22 UTC by woutersamaey

Payment Requests have a field `Created` which should be a unix timestamp in seconds, but it is not. Current result is a string like `2021-12-21T09:21:06.8924122+00:00`, which is wrong.

This change makes it a unix timetsamp + renames `Created` to `CreatedTime` like it is with invoices.

This is a breaking change, but it does make things consistent.

2021-12-21 09:24 UTC, Kukks requested changes
nack on the renaming of the field, ack on the correct time format

2021-12-21 09:31 UTC, woutersamaey commented
I left the name as it was.

In either case it is still a breaking change as the output is now a different format.

2021-12-21 09:32 UTC, Kukks commented
@NicolasDorier Thoughts?

2021-12-23 04:30 UTC, merged

2021-12-23 04:31 UTC, NicolasDorier commented
even if breaking change, it should be unix timestamp. This is not widely used API so that's ok

2021-12-23 10:01 UTC, woutersamaey commented
@NicolasDorier I would've still liked the field to be named `CreatedTime` instead of `Created` to be consistent. Since we are breaking BC, is this OK?

2021-12-23 10:08 UTC, NicolasDorier commented
Seems ok to me @Kukks  what do you think?