Store centric UI: Part 3
btcpayserver/btcpayserver pull request #3224
Opened 2021-12-21 16:41 UTC by dennisreimann

* Store context is kept for Account and Server Settings (TODO: Authorize other actions like Homepage etc.)
* Store switch links to wallet transactions if wallet is set up - otherwise it links to the payment methods, where the wallet can be set up.
* Integrations now appear in the nav under Plugins
* Pay Button got moved to the sidebar nav under Apps
* Correct nav item highlighting

2021-12-21 16:48 UTC, dennisreimann commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    if (endpoint?.RoutePattern?.RawText.IndexOf("Manage/", StringComparison.InvariantCultureIgnoreCase) == 0 || isAdmin)
This check is weird and potentially unnecessary, but I wanted to ensure we are dealing with the account settings and not the settings of another user.

2021-12-23 03:42 UTC, NicolasDorier commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    if (endpoint?.RoutePattern?.RawText.IndexOf("Manage/", StringComparison.InvariantCultureIgnoreCase) == 0 || isAdmin)
I don't understand why you need to add this policy?
Why would admin have access to view of all profiles?

2021-12-23 05:39 UTC, dennisreimann commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    if (endpoint?.RoutePattern?.RawText.IndexOf("Manage/", StringComparison.InvariantCultureIgnoreCase) == 0 || isAdmin)
Ok, I'll simply remove it then.

2021-12-27 10:03 UTC, Kukks requested changes

2021-12-28 18:06 UTC, dennisreimann commented on BTCPayServer/Views/Wallets/_Nav.cshtml
> +    <a class="nav-link @ViewData.IsActivePage(WalletsNavPages.Transactions)" asp-controller="Wallets" asp-action="WalletTransactions" asp-route-walletId="@wallet" id="SectionNav-Transactions">Transac
Done in c9f0b81.

2021-12-28 21:12 UTC, dennisreimann commented
Now all user-facing actions should have policies and hence the store context. 

This PR is ready for review now. Will send a separate last one once this is merged.

2021-12-30 11:58 UTC, NicolasDorier commented on BTCPayServer/Controllers/VaultController.cs
> +    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
why? not needed afaik

2021-12-30 11:58 UTC, NicolasDorier commented on BTCPayServer/Controllers/UserStoresController.cs
> -    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
why did you remove it from the class level down to action level?

2021-12-30 12:01 UTC, NicolasDorier commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    success = true;
I don't understand this, it means that everybody has CanViewInvoices permissions over every store.

2021-12-30 12:01 UTC, NicolasDorier commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    if (usedCookieFallback)
I don't understand this.

2021-12-30 13:36 UTC, dennisreimann commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    if (usedCookieFallback)
Simplified it in 2e7d830.

2021-12-30 13:36 UTC, dennisreimann commented on BTCPayServer/Controllers/UserStoresController.cs
> -    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie)]
Fixed in 97e8b83.

2021-12-30 13:36 UTC, dennisreimann commented on BTCPayServer/Controllers/VaultController.cs
> +    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
Fixed in 97e8b83.

2021-12-30 13:44 UTC, dennisreimann commented
@kukks Please also take a look at 2e7d830: I could simplify it by distinguishing the global and store case on the  [controller level](https://github.com/btcpayserver/btcpayserver/pull/3224/files#diff-06fcf681839e3a4010482db3e64aba26d0e6cab7d207514f7150d8976b8355e4R750). 

So it is either:
- `/invoices/` (unfiltered list)
- `/invoices?SearchTerm=storeId%3AID` (filters that store on the global list without settting the store id cookie value; there can also be multiple `storeId` filters)
- `/stores/ID/invoices` just invoices for that particular store, sets the store id cookie value

I think it is best to approach it like this, because it gives us easy options to handle the different cases of which we can potentially eliminate the global invoices one in the future.

2021-12-31 07:36 UTC, merged