Add loading indicator for "Pay" button in POS terminal app
btcpayserver/btcpayserver pull request #3342
Opened 2022-01-21 05:16 UTC by bolatovumar

Show loading indicator and disable the "Pay" button in POS terminal app when "Pay" button is clicked.

close #3336

2022-01-21 08:52 UTC, dennisreimann requested changes
As this is a [Vue app](/btcpayserver/btcpayserver/blob/master/BTCPayServer/wwwroot/light-pos/app.js), the handling of the loading state should also be done inside the Vue app. Otherwise rerendering could interfere with state that has been changed natively in the DOM, as Vue wouldn't know about these changes.

2022-01-21 19:59 UTC, Kukks requested changes
the feature needs to be handled in Vue

2022-01-24 04:14 UTC, bolatovumar commented
@dennisreimann @Kukks moved over to Vue here: 833e4d1a8fab96ce3576216132e17c77cb31570e

2022-01-24 04:15 UTC, bolatovumar commented on BTCPayServer/wwwroot/light-pos/app.js
> +                this.$refs.form.submit();
Binding an event to the pay button in Vue prevents the default form submit for whatever reason so I have to trigger it manually.

2022-01-24 12:48 UTC, dennisreimann commented on BTCPayServer/wwwroot/light-pos/app.js
> +        },
I don't think that these are necessary, because the whole app resets when navigating back.

2022-01-24 12:48 UTC, dennisreimann commented on BTCPayServer/wwwroot/light-pos/app.js
> +                this.$refs.form.submit();
For me it works fine without the ref and the programmatic form submit.

2022-01-24 12:50 UTC, dennisreimann commented on BTCPayServer/Views/UIAppsPublic/PointOfSale/VueLight.cshtml
> +            <button class="btn btn-primary btn-lg mb-0" id="pay-button" type="submit" v-on:click="payButtonClicked" v-bind:disabled="payButtonLoading">
The `v-on:click="payButtonClicked"` here should rather be a `v-on:click="handleFormSubmit"` on the form.

2022-01-26 04:34 UTC, bolatovumar commented on BTCPayServer/wwwroot/light-pos/app.js
> +                this.$refs.form.submit();
Yeah, it works without it if I attach a submit event listener on the form instead of the click listener on the button.

2022-01-26 04:36 UTC, bolatovumar commented on BTCPayServer/wwwroot/light-pos/app.js
> +        },
@dennisreimann They are necessary if your browser cached the page completely in memory (which seems to happen for me pretty much always when I click the "Pay" button and then click the browser back button).

https://web.dev/bfcache/

2022-01-26 04:38 UTC, bolatovumar commented on BTCPayServer/Views/UIAppsPublic/PointOfSale/VueLight.cshtml
> +            <button class="btn btn-primary btn-lg mb-0" id="pay-button" type="submit" v-on:click="payButtonClicked" v-bind:disabled="payButtonLoading">
@dennisreimann I assume you meant `v-on:submit`. Updated in this commit: https://github.com/btcpayserver/btcpayserver/pull/3342/commits/813138842f8083a996aa86f9c7a9746d3b671970

2022-01-26 13:43 UTC, dennisreimann approved these changes

2022-01-26 13:43 UTC, dennisreimann commented on BTCPayServer/wwwroot/light-pos/app.js
> +        },
You are correct, I can reproduce it. Well, that's unfortunate, but let's handle it like this then.

2022-01-27 01:58 UTC, merged