Remove payment methods not currently configured when creating invoice
btcpayserver/btcpayserver pull request #3394
Opened 2022-01-31 06:13 UTC by bolatovumar

#3380

2022-02-02 05:30 UTC, bolatovumar commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                if (!store.GetSupportedPaymentMethods(_NetworkProvider).Any())
Added an error message at the top of the page asking user to create a wallet first before trying to create an invoice.

2022-02-02 05:30 UTC, bolatovumar commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                        Html = $"To create an invoice, you need to <a href='{Url.Action(nameof(UIStoresController.SetupWallet), "UIStores", new { cryptoCode = "BTC", storeId = store.Id })}' class='al
Link to create a wallet has `BTC` hardcoded. Not sure if this is OK but I figured you would probably want to have a BTC wallet first. We also do this for LN wallets:

![Capture](https://user-images.githubusercontent.com/1934678/152097812-5cb31e39-9bfe-4b22-997f-ec5884c38e02.PNG)


Alternatively we would have to iterate over all derivation schemes and generate a link for each one which is kind of weird to potentially have multiple links in the error message.

Or alternative we could have a whole new wallet page (which we had previously) that lists all wallets which you can create.

2022-02-02 05:30 UTC, bolatovumar commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                    Html = $"To create an invoice, you need to <a href='{Url.Action(nameof(UIStoresController.SetupWallet), "UIStores", new { cryptoCode = "BTC", storeId = store.Id })}' class='alert-
Updated this link to be the same as the above as it's the same kind of error.

2022-02-02 05:30 UTC, bolatovumar commented on BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
> +@if (!TempData.HasErrorMessage())
I figured we probably don't want to show the form to the user if they don't have a wallet created first. Otherwise they could end up trying to create an invoice without any payment methods available.

Instead they will see an error message at the top with a link to the page which allows them to create a new wallet.

2022-02-02 09:14 UTC, Kukks requested changes

2022-02-02 09:14 UTC, Kukks commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                if (!store.GetSupportedPaymentMethods(_NetworkProvider).Any())
You might also need to check if the available payment methods have been disabled (there are helper methods in the store blob)

2022-02-02 09:15 UTC, franciscode12 commented on BTCPayServer/Extensions.cs
> +                tempData.Peek("StatusMessageModel") != null &&
Mándame monedas

2022-02-02 09:15 UTC, franciscode12 commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                if (!store.GetSupportedPaymentMethods(_NetworkProvider).Any())
Envíame monedas

2022-02-04 05:12 UTC, bolatovumar commented on BTCPayServer/Extensions.cs
> +                tempData.Peek("StatusMessageModel") != null &&
Done here: 39309d02cf2c2d2bce80c7a385b40a9bf381d2ed

2022-02-04 05:12 UTC, bolatovumar commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                if (!store.GetSupportedPaymentMethods(_NetworkProvider).Any())
@Kukks like this? 85574797d277c2cb4f15301d0ef5aa0007f7be1a

2022-02-07 09:13 UTC, Kukks requested changes

2022-02-07 09:13 UTC, Kukks commented on BTCPayServer/Views/UIInvoice/CreateInvoice.cshtml
> +@if (!TempData.HasErrorMessage())
This is too generic. What if we were displaying an unrelated error to your description? I would remove it

2022-02-10 03:43 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                    Html = $"To create an invoice, you need to <a href='{Url.Action(nameof(UIStoresController.SetupWallet), "UIStores", new { cryptoCode = "BTC", storeId = store.Id })}' class='alert-
Can you add the DefaultNetwork I added on https://github.com/btcpayserver/btcpayserver/commit/0afc2cd2cb42d13bd6c00ab0b4d5790a244dc6de ? rather than hardcode BTC?

2022-02-17 03:25 UTC, bolatovumar commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                    Html = $"To create an invoice, you need to <a href='{Url.Action(nameof(UIStoresController.SetupWallet), "UIStores", new { cryptoCode = "BTC", storeId = store.Id })}' class='alert-
@NicolasDorier looks like @Kukks did this already,

2022-02-17 09:22 UTC, merged