Pull payment fixes
btcpayserver/btcpayserver pull request #3497
Opened 2022-02-24 11:52 UTC by dennisreimann

Fixes #3490 plus a redirect and missing store context for Lightning payouts.

Note: Is there a reason for `UILightningLikePayoutController` to sit in `BTCPayServer/Data/Payouts/LightningLike` instead of the controllers directory?

2022-02-24 12:08 UTC, Kukks requested changes

2022-02-24 12:08 UTC, Kukks commented on BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs
> +    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
This is incorrect, as the ln payouts page shows payouts from multiple stores

2022-02-24 12:59 UTC, dennisreimann commented on BTCPayServer/Data/Payouts/LightningLike/UILightningLikePayoutController.cs
> +    [Authorize(AuthenticationSchemes = AuthenticationSchemes.Cookie, Policy = Policies.CanModifyStoreSettings)]
Thanks, updated in [42ddd21](https://github.com/btcpayserver/btcpayserver/pull/3497/commits/42ddd2153d04ef441d58fb03087eb04cc5f92a41).

2022-03-01 08:18 UTC, Kukks approved these changes

2022-03-01 08:18 UTC, merged