Remove fee bump button from invoice actions
btcpayserver/btcpayserver pull request #3509
Opened 2022-02-26 12:26 UTC by dennisreimann

Fixes #3506.

2022-02-27 03:25 UTC, bolatovumar approved these changes

2022-02-27 10:41 UTC, Kukks requested changes
We need to see if there is actual functionality in invoices with this button and move it over toi the wallet transactions

2022-03-01 13:55 UTC, dennisreimann commented
Actually [there is](https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/UIInvoiceController.UI.cs#L451) CPFP functionality on the invoices list. @NicolasDorier can you elaborate on the use case? I'm struggling to see why the receiving end could initiate CPFP for invoices.

2022-03-11 02:40 UTC, NicolasDorier commented
https://github.com/btcpayserver/btcpayserver/issues/3506#issuecomment-1064713258

2022-03-11 04:44 UTC, closed without merging