Bugfix: Could not find an order by OrderId after it's OrderId was changed through the API
btcpayserver/btcpayserver pull request #3521
Opened 2022-03-03 14:15 UTC by woutersamaey

As discussed with @NicolasDorier

2022-03-11 05:37 UTC, bolatovumar approved these changes

2022-03-25 10:49 UTC, Kukks requested changes
W

2022-03-25 10:49 UTC, Kukks commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +                if (oldOrderId != null && !newOrderId.Equals(oldOrderId, StringComparison.InvariantCulture))
```suggestion
                if (oldOrderId != null && (newOrderId is null || !newOrderId.Equals(oldOrderId, StringComparison.InvariantCulture)))
```

2022-03-25 10:49 UTC, Kukks commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +                AddToTextSearch(context, invoiceData, new[] { newOrderId });
```suggestion
                if (newOrderId != null) {
                	AddToTextSearch(context, invoiceData, new[] { newOrderId });
                }
```

2022-03-25 13:01 UTC, woutersamaey commented
Thanks for the improvements @Kukks

2022-03-25 13:21 UTC, merged