FileService: AddFile from URL
btcpayserver/btcpayserver pull request #3566
Opened 2022-03-21 19:27 UTC by dennisreimann

I've implemented this for PodServer and wanted to propose the addition. If this goes beyond the core functionality of the FileService we can close this and I'll add it in my code.

2022-03-22 11:27 UTC, Kukks commented
We can probably add this, but afterwards, we should start working on a greenfield API for  files management + configuration

2022-03-25 12:28 UTC, Kukks commented on BTCPayServer/Storage/Services/FileService.cs
> +            var filePath = Path.Join(_dataDirectories.Value.TempStorageDir, fileName);
Please use a different location. This folder is meant to hold descriptor json files for "temporary links"

2022-03-25 12:29 UTC, Kukks requested changes

2022-03-25 12:29 UTC, Kukks commented on BTCPayServer/Storage/Services/FileService.cs
> +            var settings = await _settingsRepository.GetSettingAsync<StorageSettings>();
🤤

2022-03-26 17:26 UTC, dennisreimann commented on BTCPayServer/Storage/Services/FileService.cs
> +            var filePath = Path.Join(_dataDirectories.Value.TempStorageDir, fileName);
Which one shall it be?

2022-03-26 17:26 UTC, dennisreimann commented on BTCPayServer/Storage/Services/FileService.cs
> +            var settings = await _settingsRepository.GetSettingAsync<StorageSettings>();
What's wrong here?

2022-03-26 21:46 UTC, Kukks commented on BTCPayServer/Storage/Services/FileService.cs
> +            var filePath = Path.Join(_dataDirectories.Value.TempStorageDir, fileName);
Something new (but ensure the dir is created as otherwise it t will fail)

2022-03-29 15:17 UTC, dennisreimann commented on BTCPayServer/Storage/Services/FileService.cs
> +            var filePath = Path.Join(_dataDirectories.Value.TempStorageDir, fileName);
Cleanup added in [2971a9a](https://github.com/btcpayserver/btcpayserver/pull/3566/commits/2971a9a4e07732a74ab2905ec8b5e703709ad9da).

2022-03-29 15:18 UTC, dennisreimann commented on BTCPayServer/Storage/Services/FileService.cs
> +            var filePath = Path.Join(_dataDirectories.Value.TempStorageDir, fileName);
Done in [e07ff20](https://github.com/btcpayserver/btcpayserver/pull/3566/commits/e07ff203a67d053c178ab676937033aefe617644). Thanks!

2022-03-29 15:42 UTC, Kukks reviewed
Does this feature work with the other file options such as azure?

2022-03-29 19:16 UTC, dennisreimann commented
I had no way to test the cloud storage providers, but it's supposed to work, because I just download the file and delegate to the original `AddFile` method. The storage provider code didn't need to be touched to implement this feature.

2022-03-31 09:54 UTC, Kukks approved these changes

2022-03-31 09:54 UTC, merged