Change payment method name from "Wallet" to "Bitcoin"
btcpayserver/btcpayserver pull request #3574
Opened 2022-03-25 05:45 UTC by phershbe

As discussed here: https://github.com/btcpayserver/btcpayserver/issues/3571

2022-03-25 08:04 UTC, pavlenex approved these changes
Looks good to me! 🎉 

By the way you can test your own PR's by [building them locally](https://docs.btcpayserver.org/Development/LocalDevelopment/).
![Screenshot 2022-03-25 at 09 03 19](https://user-images.githubusercontent.com/36959754/160079643-e058d997-3dce-484f-949b-a28f712089a0.png)

2022-03-25 08:43 UTC, dennisreimann requested changes
We need to adapt it like this, because for the altcoin build we want to show e.g. "LTC Wallet".

2022-03-25 08:43 UTC, dennisreimann commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                                <span>@(Model.AltcoinsBuild ? $"{scheme.Crypto} " : "")Bitcoin</span>
```suggestion
                                                <span>@(Model.AltcoinsBuild ? $"{scheme.Crypto} Wallet" : "Bitcoin")</span>
```

2022-03-25 08:43 UTC, dennisreimann commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                                <span>@(Model.AltcoinsBuild ? $"{scheme.Crypto} " : "")Bitcoin</span>
```suggestion
                                                <span>@(Model.AltcoinsBuild ? $"{scheme.Crypto} Wallet" : "Bitcoin")</span>
```

2022-03-25 10:45 UTC, Kukks approved these changes

2022-03-25 10:45 UTC, merged

2022-03-25 10:48 UTC, pavlenex commented
Congrats on your first contribution @phershbe here's to many more 🍻 🎉 🚀

2022-03-28 17:06 UTC, phershbe commented
@pavlenex Thank you for the information about building them locally, I know Django and Node and how to build them locally but not .NET. I'll go through the link that you provided!

2022-03-28 17:19 UTC, phershbe commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                                <span>@(Model.AltcoinsBuild ? $"{scheme.Crypto} " : "")Bitcoin</span>
@dennisreimann Okay sorry about that. I understand now that it checks for altcoins and then renders either the name of the altcoin or "Bitcoin" depending on the result.