fix unwanted alert list marker for single error, issue #3583
btcpayserver/btcpayserver pull request #3704
Opened 2022-05-02 20:17 UTC by MrPaz

should fix #3583 

noob who hasn't coded in a while getting back into coding.  please let me know if there is any better way to do this, or if I made any mistakes in the github / pull request process.  thank you!

<img width="1426" alt="Screen Shot 2022-05-02 at 2 42 18 PM" src="https://user-images.githubusercontent.com/35268901/166318982-c4aa5477-003c-4e5b-b96f-8d41e7470e4b.png">

2022-05-02 22:29 UTC, dstrukt commented
Visually, and logically (if only 1, hide <li> dot) looks good to me.

2022-05-02 22:30 UTC, dstrukt approved these changes

2022-05-03 14:56 UTC, dennisreimann commented
Haven't tested it yet, but this looks like quite a large changeset for such a small thing.

2022-05-03 19:17 UTC, MrPaz commented
yeah idk why the diff shows so many changes.  this is the only relevant change to the cshtml file:

<img width="900" alt="Screen Shot 2022-05-03 at 2 15 28 PM" src="https://user-images.githubusercontent.com/35268901/166529123-8c4d297b-7954-44d0-8ff0-5b268dff89eb.png">

2022-05-18 08:54 UTC, dennisreimann requested changes
@MrPaz Can you bring in the changes I made on [my fork](https://github.com/dennisreimann/btcpayserver/tree/PullPaymentAlertBug) or give me access to your fork, so that I can push them to this PR branch?

I've fixed the indentation, simplified the condition and inlined the no-marker styles.

2022-05-18 09:31 UTC, NicolasDorier commented
I did it, will merge when test pass

2022-05-18 12:08 UTC, dennisreimann commented on BTCPayServer/Views/UIPullPayment/ViewPullPayment.cshtml
> +    </noscript>
@NicolasDorier This part can be removed now that the PR is rebased. It is part of the `LayoutHead` partial included bove.

2022-05-18 12:38 UTC, merged

2022-05-18 14:38 UTC, dennisreimann commented
@MrPaz Yes, I think it males sense to inline the styles in this case.