Allow resending verification email for users
btcpayserver/btcpayserver pull request #3726
Opened 2022-05-08 04:37 UTC by bolatovumar

This PR adds ability to resend a verification email to those users who may have lost the original email or it has timed out as described in #3645.

2022-05-10 11:31 UTC, pavlenex reviewed
Thanks for addresing this one. I've see that re-send should be triggered on the user's page, but I think I may be testing this incorrectly (bear in mind I've set up both store and server smtp locally), but I still don't see a way to re-send a confirmation to the user, I assume re-send is allowed only if they initially authenticated through the link?

Meaning, if I as an admin, had this disabled, then enabled it after a while, only user registring afterwards and getting email link will be able to have their verification email re-sent?

2022-05-10 11:34 UTC, pavlenex commented
Okay, this works as expected and actually it will probably solve the problem that I've seen many first-time users face. They set up SMTP incorrectly and then require email verification.

This PR, fixes this, by allowing admins to re-send emails for users that registered when email verification was required.

![Screenshot 2022-05-10 at 13 32 24](https://user-images.githubusercontent.com/36959754/167619413-a83bdb77-8601-4bd0-b913-934736a88190.png)


concept ACK, and tACK needs someone to make sure there aren't edge cases in the code.

2022-05-12 03:39 UTC, bolatovumar commented
> to make sure there aren't edge cases in the code.

It's using exactly the same code as we use to send the verification email when user first signs up so I think it's pretty safe. Also, this link will only be available for users who signed up when the server policy required email verification.

2022-05-12 05:50 UTC, Kukks requested changes

2022-05-12 05:50 UTC, Kukks commented on BTCPayServer/Views/UIServer/ListUsers.cshtml
> +                    @if (user.RequiresEmailConfirmation && !user.Disabled) {
You should use `user.Verified` not `RequiresEmailConfirmation ` as the `RequiresEmailConfirmation ` is only a flag to show that this requirement is present for the user and not that he is waiting for verification.

(IE. You require verification for users. A user registers and `RequiresEmailConfirmation` is set to true for User. You turn off verification for users. The user still needs to verify email as he was created before you changed the setting)

2022-05-18 04:08 UTC, bolatovumar commented on BTCPayServer/Views/UIServer/ListUsers.cshtml
> +                    @if (user.RequiresEmailConfirmation && !user.Disabled) {
@Kukks sure, I can do that. I didn't use this flag initially because I wanted to allow the server admin to resend the email anyway, even if the user is verified already as long as the user was created when the policy required email confirmation.

2022-05-18 04:13 UTC, bolatovumar commented on BTCPayServer/Views/UIServer/ListUsers.cshtml
> +                    @if (user.RequiresEmailConfirmation && !user.Disabled) {
@Kukks done here: afed3577794023d59d60425425fc4f5518b83088

2022-05-27 04:36 UTC, merged