Removes `Plugins` tab from navigation on Server Settings
btcpayserver/btcpayserver pull request #3805
Opened 2022-06-01 00:30 UTC by dstrukt

Maybe this was kept for the sake of redundancy, or some other reason I'm not privy to? If so, apologies for this PR.

Otherwise, it's redundant, and the manage plug-in link is easy to find in the left sidebar, so thought we could go ahead and remove from the tab menu!

2022-06-01 04:48 UTC, dennisreimann approved these changes

2022-06-01 05:42 UTC, Kukks requested changes
Managing plugins still happens in the Server section of the site. If you remove this, there would be no active navigation in the top menu when on the Plugins page

2022-06-02 07:37 UTC, dennisreimann commented
I agree with @dstrukt here, it simply removes the Server Settings subav link in favor of the one in the sidebar.

![Bild eingefügt am 2022-6-1 09-41](https://user-images.githubusercontent.com/886/171578320-607be859-d444-447c-9e3b-244b96e284f6.png)

That link takes you to the Plugins page which doesn‘t have the Server Settings top nav and hence there is no real connection to the Server Settings anyways. 

Broader context: The Plugins page will become more of a separate thing on its own in the future – kinda like a Plugin Store. SO also in that sense I think we shpould move it out of the Server Settings.

2022-06-13 10:08 UTC, dennisreimann commented
@pavlenex What do you think? I agree with @dstrukt here and it should be removed.

2022-06-15 02:19 UTC, merged