Minor tweak to Payout UI
btcpayserver/btcpayserver pull request #3823
Opened 2022-06-05 11:49 UTC by dstrukt

Had to keep tweaking it :) 

Currently, I've removed the `.border` class, but still want to change the `.bg-tile` to the equivalent of `var(--btcpay-neutral-800);` but wasn't sure which bootstrap class would be best to use cc @dennisreimann?

Will make that change and submit for approval.

Will ultimately look like this:

<img width="746" alt="Screen Shot 2022-06-05 at 4 43 06 AM" src="https://user-images.githubusercontent.com/6250771/172048971-2d4a0087-b831-4ea0-9907-6d8e164f5195.png">

2022-06-05 12:45 UTC, dennisreimann approved these changes
Done :)

2022-06-05 21:48 UTC, dstrukt commented
Nice, LGTM.

Thanks @dennisreimann!

2022-06-06 07:01 UTC, Kukks requested changes

2022-06-06 07:01 UTC, Kukks commented on BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
> +/* custom bg and border classes */
Are you sure about adding things to this file? Isn't this file going to be overwritten once we update bootstrap?

2022-06-06 07:04 UTC, dennisreimann commented on BTCPayServer/wwwroot/main/bootstrap/bootstrap.css
> +/* custom bg and border classes */
These are additions to the Bootstrap file we append as part of the design system build process. So all is good here.

2022-06-06 08:32 UTC, merged