Remove option of picking LNURL method from custom amount perk in crowdfund app
btcpayserver/btcpayserver pull request #3892
Opened 2022-06-22 04:33 UTC by bolatovumar

Having two ways to get to the LNURL payment method doesn't really make sense, better to leave it to be handled at the invoice level.

close #3746

2022-06-22 07:40 UTC, pavlenex commented
tACK. 

While testing I noticed something weird. 

Something weird is going on.
1. Create a perk with a fixed price `0`
2. Click contribute
3. Try to click on a perk, nothing happens.
Not sure if this was introduced in your PR or generally a bug we can perhaps address in this PR.

https://user-images.githubusercontent.com/36959754/174971766-ba0283d4-1d64-4bdd-927a-ca4d8964f9a2.mov

In theory, when invoice is 0 it will automatically mark invoice as `settled`. I am not sure what's going on and if we even need to allow 0 in invoices. @Kukks what is this wizardry?

2022-06-22 08:23 UTC, Kukks commented
Still nack from my end on just nuking features. Please wait till I am back.

2022-06-22 08:25 UTC, Kukks requested changes
Nack on just nuking the whole thing.

2022-06-24 04:47 UTC, bolatovumar commented
> Can you explain what feature does this bring, LNURL is already available on the invoice? This just removes an extra step.

Yeah, I figured since it's already available through the invoice having it on the perk itself doesn't provide much extra benefits. I can look into fixing the one on the perk itself if we want to keep it though.

2022-06-24 04:55 UTC, bolatovumar commented
> tACK. Custom price is now working as expected.
> 
> While testing I noticed something weird with `fixed price`which I don't think is related with this PR, but perhaps we can tackle it or open a follow up issue from this comment.
> 
> To replicate
> 
> 1. Create a perk with a fixed price `0`
> 2. Click contribute
> 3. Try to click on a perk, nothing happens.
>    Not sure if this was introduced in your PR or generally a bug we can perhaps address in this PR.
> 
>  Screen.Recording.2022-06-22.at.09.35.27.mov 
> In theory, when invoice is 0 it will automatically mark invoice as `settled`. I am not sure what's going on and if we even need to allow 0 in invoices.
> 
> @Kukks what is this wizardry?

@pavlenex seems like this is an existing issue, not introduced by this PR. Tested both on latest `master` and on my instance of BTCPay and can repro it in both. I don't even know what the expected behavior here would be.

2022-06-27 06:09 UTC, NicolasDorier commented
Ping @Kukks

2022-06-27 07:03 UTC, Kukks commented
Still abroad

2022-06-28 05:22 UTC, NicolasDorier commented on BTCPayServer/wwwroot/crowdfund/app.js
> +                    console.log('lol');
need to remove this in any case

2022-06-28 05:27 UTC, NicolasDorier commented
I need to understand more about this. We should talk about it in a meeting with @Kukks .

2022-06-30 04:57 UTC, closed without merging