Add support for updating POS app through Greenfield API
btcpayserver/btcpayserver pull request #3979
Opened 2022-07-18 05:26 UTC by bolatovumar

With this PR you will be able to update a POS app through Greenfield API.

Part of #3458

2022-07-18 05:46 UTC, bolatovumar commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        public bool? ShowCustomAmount { get; set; } = null;
Fallback in the code instead of here and mark these as optional as they are.

2022-07-18 05:46 UTC, bolatovumar commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> -            //Get current api key
The whitespaces were auto-trimmed. Ignore all of these.

2022-07-18 05:46 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +            var store = await _storeRepository.FindStore(storeId);
Moved the store validation to the top since it doesn't make sense to first validate the request and only then validate that the store we are trying to create an app for exists, should be the other way around.

2022-07-18 05:46 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                Template = request.Template != null ? _appService.SerializeTemplate(_appService.Parse(request.Template, request.Currency)) : null,
Previously the template was saved raw which is wrong cuz you can end up saving an invalid template. I added validation for this as well now.

2022-07-18 05:46 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                Title = request.Title ?? settings.Title,
Use the request properties or fallback to what exists on the app already if not provided.

2022-07-18 05:46 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +            if (request.Currency != null && _currencies.GetCurrencyData(request.Currency, false) == null)
Added previously missing validation for currency and template validity.

2022-07-19 06:13 UTC, Kukks requested changes
Please do a full UPDATE (Http PUT not PATCH) instead of selective property updating, as we have not defined this update mechanism for any other entity or endpoint.

2022-07-22 13:04 UTC, NicolasDorier commented
I think that it is fine. While it is strange to have our first PATCH, it doesn't mean that is bad.

2022-07-22 13:09 UTC, NicolasDorier commented
@bolatovumar I think this PATCH doesn't work as expected. Because you call `ValidateCreateAppRequest` which doesn't expect to stumble across null values.

2022-07-22 13:15 UTC, NicolasDorier commented
@bolatovumar I thought with it with @Kukks , I think that it should be PUT.

Not only because the PATCH has already some bug here, but because I believe PATCH for all routes with a GET and PUT can be created automatically the following way:

1. Do the json from the GET
2. Patch the json with the JObject of the PATCH
3. Do the PUT.

It can be generalized for every routes having both PUT and GET, without corner case to handle manually.

2022-08-06 04:39 UTC, bolatovumar commented
@Kukks @NicolasDorier alright, updated to be a `PUT` instead. Failing test is unrelated.

![Capture](https://user-images.githubusercontent.com/1934678/183234099-6a0715d6-a789-4772-9a8f-272b23ea8ce0.PNG)

2022-08-10 04:17 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs
> +        public override async Task<PointOfSaleAppData> PutPointOfSaleApp(
Updated in https://github.com/btcpayserver/btcpayserver/pull/3979/commits/0dfbc3725f47cae92ed9d1032ed30b0b60c6c1f3

2022-08-10 04:17 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +            "patch": {
Updated in https://github.com/btcpayserver/btcpayserver/pull/3979/commits/a8d6f78955569f1e2f2352f0f24c06c60e0ece6a

2022-08-10 13:07 UTC, Kukks approved these changes

2022-08-11 03:52 UTC, bolatovumar commented
Failing test is still unrelated.

2022-08-19 05:20 UTC, bolatovumar commented
@NicolasDorier ping. I rebased the branch and now tests are green.

2022-08-21 06:40 UTC, Kukks approved these changes

2022-08-21 06:41 UTC, merged