Custodian Account Deposit UI
btcpayserver/btcpayserver pull request #4024
Opened 2022-08-05 19:10 UTC by woutersamaey

UI to make deposits to a custodian account.
- Deposits are made using a modal
- Select the asset, then the payment method
- A QR code appears just like in "Wallet Receive"
- QR code generation was a bit refactored (moved <img> tag generation to a separate service so it can be used in a controller without view.
- Only OnChain is supported for now, but that's normal as the Custodian API is also OnChain only for now.

2022-08-05 19:22 UTC, woutersamaey commented
@dennisreimann and @NicolasDorier please review so I can continue with withdrawal support.

@NicolasDorier just FYI I noticed 1 strange thing after refactoring the QR Code generation logic. The "Send" page from my Store Wallet did not show a QR code at first. Only after I clicked "Generate next address" the QR code appeared. After that, it did work and I could not reproduce. I did check the code extensively and looked at other files in `Components` but didn't see anything that could be wrong.

During a debugging session I did see that the constructor was not called the first time and only after clicking the button "Generate next address" was it called and running the Component, which is very odd.

It may be nothing, but I thought I'd mention it so the "Send" page doesn't break unexpectedly. If you do run into this issue, please advise. I did only very simple, basic refactoring, so if I made a mistake, you'll probably know better than me what to do.

2022-08-05 19:25 UTC, woutersamaey commented
Tests failed because of dead link (not my fault)

2022-08-08 11:54 UTC, dennisreimann reviewed
One more thing I noticed: When the API key is expired, the loading indicator keeps spinning and the error isn't reported. In my case I'm running into an `account.depositablePaymentMethods is null` in the dev console. The same also happens for the fake custodian.
But I think you should check whether or not the API key is still working in general.

For me the wallet receive page is still behaving normally, so I didn't notice anything breaking there.

2022-08-08 11:54 UTC, dennisreimann commented on BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
> +                    <select class="form-control" v-model="deposit.asset" name="DepositAsset">
```suggestion
                    <select class="form-select" v-model="deposit.asset" name="DepositAsset">
```

2022-08-08 11:54 UTC, dennisreimann commented on BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
> +                    <select class="form-control" v-model="deposit.paymentMethod" name="DepositPaymentNetwork">
```suggestion
                    <select class="form-select" v-model="deposit.paymentMethod" name="DepositPaymentNetwork">
```

2022-08-08 12:09 UTC, woutersamaey commented
> One more thing I noticed: When the API key is expired, the loading indicator keeps spinning and the error isn't reported. In my case I'm running into an `account.depositablePaymentMethods is null` in the dev console. The same also happens for the fake custodian. But I think you should check whether or not the API key is still working in general.

This issue has been fixed. Just needed to check for `NULL`.
Your expired API key may be unrelated to this issue, because the list of what assets are depositable is public and not the result of a private API call.

2022-08-08 12:36 UTC, Kukks requested changes
Please revert the QR code changes, and use the Vue QR component instead.

2022-08-08 12:36 UTC, Kukks commented on BTCPayServer/Services/QRCodeImgTagGenerator.cs
> +    public string generateImgTag(string data)
```suggestion
    public string GenerateImgTag(string data)
```
Pascal case

2022-08-08 12:36 UTC, Kukks commented on BTCPayServer/Models/CustodianAccountViewModels/DepositPrepareViewModel.cs
> +    public string LinkQRHtml { get; set; }
Let's not start passing HTML through API calls, this is a horrible practice from back in the jquery mayhem days.

2022-08-08 12:36 UTC, Kukks commented on BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
> +                                <div v-html="deposit.linkQRHtml"></div>
we have a dedicated Vue component that can render a qr code from the link

2022-08-08 12:36 UTC, Kukks commented on BTCPayServer/Controllers/UICustodianAccountsController.cs
> +        public async Task<IActionResult> GetDepositPrepareAjax(string storeId, string accountId,
Don't name things with "Ajax"

2022-08-08 12:36 UTC, Kukks commented on BTCPayServer/Controllers/UICustodianAccountsController.cs
> +                        if (paymentMethod.Equals("BTC-OnChain"))
Please use the `PaymentMethodId` class instead of hardcoded strings to determine things like this.

2022-08-08 19:54 UTC, woutersamaey commented on BTCPayServer/Controllers/UICustodianAccountsController.cs
> +        public async Task<IActionResult> GetDepositPrepareAjax(string storeId, string accountId,
Done

2022-08-08 19:54 UTC, woutersamaey commented on BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
> +                                <div v-html="deposit.linkQRHtml"></div>
Good point. Done.

2022-08-08 19:54 UTC, woutersamaey commented on BTCPayServer/Models/CustodianAccountViewModels/DepositPrepareViewModel.cs
> +    public string LinkQRHtml { get; set; }
Done.

2022-08-08 19:55 UTC, woutersamaey commented on BTCPayServer/Services/QRCodeImgTagGenerator.cs
> +    public string generateImgTag(string data)
This file no longer exists since we're using the VueJS QR component

2022-08-08 20:11 UTC, woutersamaey commented on BTCPayServer/Controllers/UICustodianAccountsController.cs
> +                        if (paymentMethod.Equals("BTC-OnChain"))
Good point. Done

2022-08-08 20:12 UTC, woutersamaey commented
@Kukks I have addressed all your feedback + Also added a loading spinner while the deposit address is being loaded.
Can I get your blessing now please?

2022-08-08 20:49 UTC, dennisreimann commented on BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
> +                                    <select name="FromAsset" v-model="trade.assetToTrade" class="form-control">
```suggestion
                                    <select name="FromAsset" v-model="trade.assetToTrade" class="form-select">
```

2022-08-08 20:49 UTC, dennisreimann commented on BTCPayServer/Views/UICustodianAccounts/ViewCustodianAccount.cshtml
> +                                    <select name="ToAsset" v-model="trade.assetToTradeInto" class="form-control">
```suggestion
                                    <select name="ToAsset" v-model="trade.assetToTradeInto" class="form-select">
```

2022-08-09 03:28 UTC, NicolasDorier commented on BTCPayServer/wwwroot/js/custodian-account.js
> +                return '/wallets/S-' + this.account.storeId + '-' + this.deposit.asset + '/send?defaultDestination=' + encodeURI(this.deposit.address)+"&returnUrl="+encodeURI(window.location.href);
Never build URLs like this. Instead, generate it server side using the `LinkGenerator`, and pass them to the front.

Search `GetUriByAction` to see how to use it.

2022-08-09 05:38 UTC, woutersamaey commented on BTCPayServer/wwwroot/js/custodian-account.js
> +                return '/wallets/S-' + this.account.storeId + '-' + this.deposit.asset + '/send?defaultDestination=' + encodeURI(this.deposit.address)+"&returnUrl="+encodeURI(window.location.href);
You’re right. Silly mistake. Will fix asap.

2022-08-09 17:36 UTC, woutersamaey commented on BTCPayServer/wwwroot/js/custodian-account.js
> +                return '/wallets/S-' + this.account.storeId + '-' + this.deposit.asset + '/send?defaultDestination=' + encodeURI(this.deposit.address)+"&returnUrl="+encodeURI(window.location.href);
Fixed it.

2022-08-09 17:42 UTC, woutersamaey commented
@dennisreimann I switched all selects to `form-select` + fixed the width since this class is wider than before. I made it so that tickers with 4 characters can fit.

2022-08-09 17:43 UTC, woutersamaey commented
@dennisreimann @Kukks @NicolasDorier all feedback has been addresses and fixed. Can I get your final blessing pls?

2022-08-09 18:03 UTC, Kukks approved these changes

2022-08-09 18:03 UTC, merged