add eCash
btcpayserver/btcpayserver pull request #4026
Opened 2022-08-08 14:36 UTC by mishfit

Relies on https://github.com/dgarage/NBXplorer/pull/369

2022-08-09 12:58 UTC, Kukks requested changes
Your logo is probably not in the corrected dimensions as it usually fits centered in a qr code.

2022-08-09 12:58 UTC, Kukks commented on BTCPayServer.Common/Altcoins/BTCPayNetworkProvider.ECash.cs
> +>>>>>>> 8532ad69 (add ecash)
conflict pointers

2022-11-16 06:44 UTC, Kukks requested changes
The way this PR stands and how the PR dependency looks, I don't think it will be mergeable unless you go back and add the coin to NBitcoin the normal way without all the changes. As nicolas mentioned before, we won't include dedicated nuget packages for altcoins as that presents attack vectors.

I will close this PR for now, reopen, when you have finished NBitcoin + NBXplorer support

2022-11-16 06:44 UTC, closed without merging

2022-11-16 07:16 UTC, Inyourdreams182 commented
> Relies on [dgarage/NBXplorer#369](https://github.com/dgarage/NBXplorer/pull/369)

U want to forces to me