Add crowdfund app create endpoint
btcpayserver/btcpayserver pull request #4068
Opened 2022-08-23 05:19 UTC by bolatovumar

2022-09-13 08:22 UTC, Kukks requested changes

2022-09-13 08:22 UTC, Kukks commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +    class DateTimeJsonConverter : JsonConverter
use `NBitcoin.JsonConverters.DateTimeToUnixTimeConverter` instead

2022-09-13 08:22 UTC, Kukks commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        public DateTime? StartDate { get; set; } = null;
Ideally, we stick to `DateTimeOffset` in Greenfield to stay consistent.

2022-09-13 09:01 UTC, Tastry commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +    class DateTimeJsonConverter : JsonConverter
?

2022-09-14 04:34 UTC, bolatovumar commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +    class DateTimeJsonConverter : JsonConverter
Done here: https://github.com/btcpayserver/btcpayserver/pull/4068/commits/affa2eaf8dfe8fef48f2e6d7c69076e355d838ca

2022-09-14 04:34 UTC, bolatovumar commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        public DateTime? StartDate { get; set; } = null;
Done here: https://github.com/btcpayserver/btcpayserver/pull/4068/commits/fd4f64605ec148e7cf6f400c38394cb471f3f973

2022-09-28 09:17 UTC, NicolasDorier commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +            var parsedColors = ParseBySplitByComma(request.AnimationColors);
why using csv rather than just an array?

2022-10-05 03:55 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +            var parsedColors = ParseBySplitByComma(request.AnimationColors);
@NicolasDorier updated here: https://github.com/btcpayserver/btcpayserver/pull/4068/commits/5d328ab392c2651060305c6a15d06e569bf3d84d

2022-10-05 04:21 UTC, bolatovumar commented
Failing test unrelated

![Capture](https://user-images.githubusercontent.com/1934678/193980604-55030498-8adc-4614-b934-724f1fb03403.PNG)

2022-10-17 09:47 UTC, Kukks requested changes

2022-10-17 09:47 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "endDate": {
follow this example:
```
 "createdAt": {
                        "description": "The unix timestamp when the payment got created",
                        "nullable": true,
                        "allOf": [ {"$ref": "#/components/schemas/UnixTimestamp"}]
                    },
```

2022-10-25 04:23 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "endDate": {
@Kukks updated in https://github.com/btcpayserver/btcpayserver/pull/4068/commits/b8fa4cfd5905ac75b1e063eb21521a43314287e0

2022-11-18 04:34 UTC, NicolasDorier commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "sounds": {
it's not comma separated, this is an array

2022-11-18 04:34 UTC, NicolasDorier commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "animationColors": {
it's not comma separated, this is an array

2022-11-18 04:47 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "animationColors": {
Updated in https://github.com/btcpayserver/btcpayserver/pull/4068/commits/26a1bfb6172bf1a77228a8677fd4e277ee322284

2022-11-18 05:20 UTC, merged