Update WalletTransactions pagination default settings
btcpayserver/btcpayserver pull request #4074
Opened 2022-08-24 06:39 UTC by HamroRamro

As of now 3/5 task of https://github.com/btcpayserver/btcpayserver/issues/3954 is resolved here. Will work on the remaining later this week/month.

- [X] Load 1 month's worth of transactions by default

- [X] Add a "Load/View More" button at the bottom of the scroll view, which triggers the loading of the next month of transactions

- [X] Display Show All after loading 90 days of data which triggers infinite scroll with no additional button click necessary

Please let me know if you have any feedback @dstrukt @NicolasDorier. 
cc: @pavlenex @Kukks

2022-08-24 08:12 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +    }
```suggestion
    <div class="text-center mb-5">
        @if (displayLoadMoreButton)
        {
            <a role="button" class="btn btn-primary" asp-action="WalletTransactions" asp-route-walletId="@walletId" asp-route-interval="@nextInterval">@loadMoreButtonText</a>
        }
        else
        {
            <button type="button" class="btn btn-primary" onclick="window.scrollTo({ top: 0, behavior: 'smooth' })">Go to top</button>
        }
    </div>
```

2022-08-24 08:12 UTC, dennisreimann commented on BTCPayServer/Controllers/UIWalletsController.cs
> +            TimeSpan? interval = null
We can simplify it quite a bit in the other parts also when we use an `int` here and also rename it, to reveal the intention better: 
  
```suggestion
            int days = 30
```

2022-08-24 17:41 UTC, dstrukt commented
Awesome, will take a look this evening!

2022-08-24 22:03 UTC, HamroRamro commented on BTCPayServer/Extensions/StringExtensions.cs
> +
Thank you for the feedback @dennisreimann. I have reverted the changes and have modified relevant code accordingly.

2022-08-24 22:03 UTC, HamroRamro commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +    }
Awesome tip! Made the change!

2022-08-24 22:04 UTC, HamroRamro commented on BTCPayServer/Controllers/UIWalletsController.cs
> +            TimeSpan? interval = null
Changed it to days. LOT CLEANER!! Thank you for the suggestion!

2022-08-25 08:20 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +    nextInterval = nextInterval > 90 ? 365000 : nextInterval;
It can be simplified to this, when we apply the other checks that are used just once in-place (see other suggestions):

```suggestion
    var nextInterval = Model.Days > 60 ? 365000 : Model.Days + 30;
    var displayLoadMoreButton = nextInterval < 365000;
```

2022-08-25 08:20 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +            <a role="button" class="btn btn-primary" asp-action="WalletTransactions" asp-route-walletId="@walletId" asp-route-days="@nextInterval">@loadMoreButtonText</a>
```suggestion
            <a role="button" class="btn btn-primary" asp-action="WalletTransactions" asp-route-walletId="@walletId" asp-route-days="@nextInterval">@(nextInterval > 90 ? "Show All" : "Load More")</a>
```

2022-08-25 08:20 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +@if (scrollToBottom)
```suggestion
@if (nextInterval > 60)
```

2022-08-25 08:20 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +}
Let's also move this part into the `@section PageFootContent` above, because otherwise it might get overlooked when scripts are spread across multiple places.

2022-08-25 10:03 UTC, dstrukt requested changes
First of all, excellent work!

Few nits:
- [ ] We should switch to our `btn-secondary` style

- [ ] Something worth considering too is making this a full-width button, e.g (@dennisreimann thoughts?):
<img width="1225" alt="Screen Shot 2022-08-25 at 2 48 56 AM" src="https://user-images.githubusercontent.com/6250771/186636146-36457bd3-a3d1-4dd4-b701-8b7302e16a2f.png">
<img width="1224" alt="Screen Shot 2022-08-25 at 2 58 44 AM" src="https://user-images.githubusercontent.com/6250771/186636279-cf2925aa-ccbd-4f07-9daf-f0a5779f5a0c.png">

- [ ] Functionally, should we start infinite scroll loading when the user hits the bottom of the view after 1 or 2 "Load More" clicks, as opposed to continuing to click until "View All"? @dennisreimann Thoughts?

Otherwise, looks & works great!

2022-08-25 11:19 UTC, dennisreimann commented
I'd rather left-align the button than having it full width.

Infinite scrolling: Ideally we'd do it all via AJAX, so that even initially there's no page reload. We could switch to that once the "Load more" button was pressed, which seems like an intuitive thing. RIght now it feeld kinda random to switch to infinite mode after two clicks.

2022-08-25 18:02 UTC, dstrukt commented
- hmm, i prefer center, even if it's not `full-wdith` (even though I do like this), I also realize it could be too much .. maybe there's a middle ground of the 2? Regardless, would be more than happy to proceed with the standard button size.

- w.r.t to the infinite scroll, agreed with the switch after the first press, that would be even better!

2022-08-26 02:05 UTC, HamroRamro commented
Hi @dstrukt and @dennisreimann ,

Thanks for all the feedback. I have made the code a little cleaner. 

I have made the button btn-secondary. I do prefer the button to be center rather than full width. Full width is a little too heavy for me. 
I have also made it so that it gives you option to Show All after 1 Load More. So 
1st page load = 30 days of data. 
2nd page load  = 60 days of data and button changes to "Show All"

Once Show All is hit, it loads everything and takes you to the bottom.

And technically..... you CAN SCROLL UP "INFINITELY" haha :)

I will work on the tx search and date filter next but please feel free to suggest more UI/UX enhancements!!

2022-08-26 05:43 UTC, dennisreimann commented
I think having a "Load All" button that simply fetches the rest will bring trouble for wallets with many transactions. We have users with lots of transactions and I don't think this would be a good way to handle it. 

Can we rather make it load in 30 day interval steps with AJAX and the infitite scroll? It doesn't have to be part of this PR, but I think that'd be a more user-friendly and scalable way.

2022-08-26 06:50 UTC, HamroRamro commented
I agree with you. Load All can be heavy with wallets with a lot of transactions.

I'll take a stab at your suggestions over the weekend. Thanks for the feedback ser

2022-08-27 22:16 UTC, dstrukt commented
ACK to @dennisreimann's suggestion, and looking forward to the next iteration @HamroRamro 💪

2022-08-28 21:32 UTC, HamroRamro commented
Hello gentlemen @dstrukt @dennisreimann ,

I have implemented infinite scroll. It will load 30 days worth of data every time you scroll to the bottom. 
Also got rid of the "Load More" completely because it will always add on 30 days more worth of data on scrolling down. 

It shows "Loading..." in the center while fetching data. 

Let me know your thoughts. Thank you!

2022-08-29 14:42 UTC, dennisreimann requested changes
The changeset became pretty big with the latest change and in some parts the indentation got messed up.

I think the AJAX part can be solved in a better way. Can you make the annotated changes and grant me access to you fork, so that I can do some more modifications afterwards?

2022-08-29 14:42 UTC, dennisreimann commented on BTCPayServer/BTCPayServer.csproj
> +	  <None Include="Views\UIWallets\_WalletTransactions.cshtml" />
Can you remove the changes in this file? They are superfluous.

2022-08-29 14:42 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/_WalletTransactions.cshtml
> +@section PageHeadContent {
Please don't split it up like this, the sections do not belong into partial views, because they won't render anymore.

The `ViewData.SetActivePage` also belongs to the outer page.

2022-08-29 14:42 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +        $(window).scroll(function() {
Let's not use jQuery for new code, can you convert it into the native equivalents like [fetch](https://javascript.info/fetch)?

2022-08-29 21:31 UTC, HamroRamro commented
Hi @dennisreimann , I have added you as a contributor to my fork. I am out of town today so I will try to implement your suggestions tomorrow.

2022-08-29 23:45 UTC, dstrukt commented
@HamroRamro Great work!

I do like the infinite load UX much more .. debating if I like it being triggered by hitting the bottom of the page by default, or if we should have a singular "Load More" then the second, and onward content is loaded with the infinite scroll .. are there potential issues of someone abusing this (API calls, etc..)? Regardless, I think we could easily go with the current iteration, and we'll get some feedback, and adjust as needed.

2022-08-31 17:14 UTC, dennisreimann commented
I've pushed the cleanups taht resolve my previous comments. This is still in WIP state, as I found that tehre is something weird going on when using the `skip` and `count` parameters. I've simplified the general approach quite a bit by removing the previous changes based on days as an interval and reusing what we have with the pager already.

However, I couldn't find out why it behaves so weirdly and e.g. the second page is just empty when using `?skip=50&count=50` for instance. I've re-added the pager to verify this isn't just an issue with the AJAX calls.

@NicolasDorier Debugging it I found that the [`else` branch here](https://github.com/btcpayserver/btcpayserver/blob/8873c51f2be85f12ff73b4674e3c4346c89abc53/BTCPayServer/Services/Wallets/BTCPayWallet.cs#L230) doesn't yield the expected results - we'll need to take a closer look what's going on.

@HamroRamro Sorry for rewriting larger chunks, if you want to, we can go through the changes in detail if you have questions.

2022-09-10 07:39 UTC, dennisreimann commented
Ok, problems found and solved:

- [f7fc866](https://github.com/btcpayserver/btcpayserver/pull/4074/commits/f7fc866febab0caf8e272c559fb8ec41666262f2) fixes a bug on the Controller level, which lead to the weird behaviour I describe in my previous comment.
- There's still a bug in NBXplorer's `get_wallets_recent`, which @NicolasDorier is taking care of. [c760a05](https://github.com/btcpayserver/btcpayserver/pull/4074/commits/c760a0565cae4fc77797503c81a1027dc13f002c) circumvents it and should be removed once the NBXplorer fix is integrated.

I added the workaround, so that @HamroRamro and @dstrukt can take a look already. I think the current behaviour matches what we agreed upon and I think it's a good solution like that.

2022-09-16 03:17 UTC, HamroRamro commented
Hi @dennisreimann , this looks great! 👍  Thank you so much for doing this! And sorry for late response, I was out of town with family! 

The user first sees Load More and Go To Top and once they hit Load More once, it triggers the infinite scroll. I like it! 

Lets see what @dstrukt has to say :)

2022-09-18 07:04 UTC, dstrukt commented
Apologies for my delay in review, will take a look in the morning!

Appreciate all of the work that has gone into this.

2022-09-18 14:48 UTC, NicolasDorier commented
I think, in the request, the `skip` should always be true, then after the request we should manually skip the rows.

It's less efficient of course, but this will ensure the bug is fixed even if somebody didn't update NBXplorer.
I may consider later to detect the NBXPlorer version and just remove this workaround for what is higher, but can do that in another PR.

2022-09-18 21:14 UTC, dstrukt commented
I think the section being loading in is bugged...?

<img width="1508" alt="Screen Shot 2022-09-18 at 2 14 20 PM" src="https://user-images.githubusercontent.com/6250771/190928366-f4066abe-6244-4c02-9ab5-1e914b97dc08.png">

2022-09-19 17:09 UTC, dennisreimann approved these changes
Good to go now :)

2022-09-20 05:54 UTC, dstrukt commented
Strange. I pulled the latest, but still getting similar results, but slightly more broken ...

<img width="1507" alt="Screen Shot 2022-09-19 at 10 53 20 PM" src="https://user-images.githubusercontent.com/6250771/191178006-637a3cee-160b-4686-a11b-b9f1d18ff8a7.png">

2022-09-20 07:48 UTC, dennisreimann commented
@dstrukt can you run `dotnet clean && dotnet restore` and also stop and restart the docker-compose?

@NicolasDorier I've upgraded NBXplorer in both docker-compose files, so that the bugfix is now included. Both cases work properly now.

2022-09-20 18:37 UTC, dstrukt approved these changes
Functionally and aesthetically, LGTM!

Only thing I'm not really a fan of is the "Back to top" button, think it should be removed, imo, but I could be persuaded.

2022-09-22 01:42 UTC, NicolasDorier commented
Need rebase, the two .cs files are just style issue, the site.css, I don't know how to merge properly.

2022-09-26 07:10 UTC, pavlenex commented
@NicolasDorier do you want this one in the v1.6.11?

2022-09-26 07:24 UTC, dennisreimann commented
@pavlenex We added #4150 with the fix as a subset of this one. So we'll ship the feature part of this with one of the next releases after 1.6.11

2022-09-27 09:17 UTC, dennisreimann commented
Now that the tests are green again and the release is done, this is ready to be reviewed and merged. @NicolasDorier

2022-09-27 12:24 UTC, merged

2022-09-27 12:24 UTC, NicolasDorier commented
This is awesome