Custodian withdrawal support + Some refactoring and cleanup
btcpayserver/btcpayserver pull request #4085
Opened 2022-08-28 19:32 UTC by woutersamaey

- Withdrawal support UI
- Refactoring of previous UI so things are more consistent across the board
- New Greenfield API endpoint to "simulate" the withdrawal before actually executing => gives you info on fees, min and max to withdraw
- Nothing fancy or new  this time. More of the same.

Only 1 todo (might be for later?): better currency formatting to reduce the number of decimals or avoid scientific notation. Not that big a problem tbh.

Screenshots of the withdrawals
![Screenshot from 2022-08-28 21-20-06](https://user-images.githubusercontent.com/71019/187091115-1160b836-a448-455f-b531-6b8716e6de50.png)
![Screenshot from 2022-08-28 21-20-29](https://user-images.githubusercontent.com/71019/187091117-ca9b86cf-02b6-4065-b796-eeef5ec110ff.png)

2022-08-29 06:29 UTC, woutersamaey commented
Not sure what this failed test “CanExportInvoicesJson” is exactly as I’m not touching that at all. Will look into it.

2022-08-29 14:44 UTC, dennisreimann commented
> Not sure what this failed test “CanExportInvoicesJson” is exactly as I’m not touching that at all. Will look into it.

@kukks is trying to fix it in #4082

2022-08-29 16:03 UTC, dennisreimann reviewed
LGTM.

btw I think those OpenAPI `x-` properties can be removed, at least I haven't found them in the [ReDoc specification](https://redocly.com/docs/api-reference-docs/spec-extensions/) and they don't seem to have an impact on the UI.

2022-08-29 16:03 UTC, dennisreimann commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.custodians.json
> +                    "x-position": 1
```suggestion
                    "required": true
```

2022-08-29 16:03 UTC, dennisreimann commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.custodians.json
> +                    "x-name": "request",
```suggestion
```

2022-08-29 19:54 UTC, woutersamaey commented
The tests should now be fixed.

Only minor issue remaining is the decimal formatting, which is not critical.

2022-08-30 01:21 UTC, dstrukt commented
Loving how the UI is shaping up!

Great work all around .. will do a bit of reviewing this evening / tomorrow morning as well.

2022-08-30 05:51 UTC, woutersamaey commented
@dstrukt let’s brainstorm in Riga about potential improvements. Ok?

2022-08-30 09:47 UTC, dstrukt commented
Absolutely!

Looking forward to it.

2022-09-19 13:25 UTC, woutersamaey commented
@Kukks can you merge my PR please? @dennisreimann has already given his blessing before Riga.

2022-09-19 13:45 UTC, Kukks commented
> @Kukks can you merge my PR please? @dennisreimann has already given his blessing before Riga.

I haven't reviewed it myself yet. I don't merge anything this big until I've gone through it myself.

If @dennisreimann has gone through it and feels comfortable with it, he can merge it in though(PS, please squash in if you do as there are way too many commits)

2022-09-19 14:08 UTC, dennisreimann commented
I'd also need to take another look, but won't find the time today.

2022-09-19 14:15 UTC, woutersamaey commented
> I'd also need to take another look, but won't find the time today. 

That's okay. Thanks man. Only issue I know about is number rounding (too many decimals), but I'll be doing UX refinements in a PR after this one, hopefully along with unit tests etc...

2022-09-27 10:27 UTC, dennisreimann reviewed
Tested and it looks good to me. Most likely this will need coordination with #4137 for the form builder changes.

2022-09-27 10:27 UTC, dennisreimann commented on BTCPayServer.Tests/MockCustodian/MockCustodian.cs
> +            if ((""+amount).Equals(""+WithdrawalAmount, StringComparison.InvariantCulture) || WithdrawalAmountPercentage.Equals(amount))
Why not use `ToString(CultureInfo.InvariantCulture)` for an explicit conversion here?

2022-09-30 07:21 UTC, woutersamaey commented on BTCPayServer.Tests/MockCustodian/MockCustodian.cs
> +            if ((""+amount).Equals(""+WithdrawalAmount, StringComparison.InvariantCulture) || WithdrawalAmountPercentage.Equals(amount))
You mean to say that the `""+ ` part should be replaced making the new line like this?
```
 if ((amount.ToString(CultureInfo.InvariantCulture)).Equals(WithdrawalAmountToString(CultureInfo.InvariantCulture)) || WithdrawalAmountPercentage.Equals(amount))
```
Guess the `StringComparison.InvariantCulture` can be dropped then?
I had no specific reason for this. Sometimes my PHP creeps into my C#

2022-10-16 18:25 UTC, woutersamaey commented on BTCPayServer.Tests/MockCustodian/MockCustodian.cs
> +            if ((""+amount).Equals(""+WithdrawalAmount, StringComparison.InvariantCulture) || WithdrawalAmountPercentage.Equals(amount))
@dennisreimann I made the change you requested.

2022-10-16 18:28 UTC, woutersamaey commented
Rebased to master

2022-10-16 18:57 UTC, woutersamaey commented
@NicolasDorier Please review

2022-10-17 03:14 UTC, NicolasDorier commented on BTCPayServer/Controllers/UICustodianAccountsController.cs
> +            // TODO Maybe cast to KrakenConfig (or whatever type the custodian plugin uses) and back into JObject so superfluous data is removed from the JSON?
I think you should do this, because right now some joker can put any shit they want in the JSON, which may have ability to do some other nasty things.

2022-10-30 09:18 UTC, Kukks requested changes
Please fix all the methods in the btcpayserver.client to have `Custodian` in the name as they are very confusing when using the client.

For example
`SimulateWithdrawal` => `SimulateCustodianWithdrawal`


Please also implement all the custodian methods into `LocalBTCPayServerClient` as currently the custodian functionality will not work for any plugins attempting to call them.

2022-12-19 11:10 UTC, woutersamaey commented
I'll take care of this this week or the next.

2022-12-26 18:29 UTC, woutersamaey commented on BTCPayServer/Controllers/UICustodianAccountsController.cs
> +            // TODO Maybe cast to KrakenConfig (or whatever type the custodian plugin uses) and back into JObject so superfluous data is removed from the JSON?
@NicolasDorier I am struggling with this as the config object is different for each custodian. In my case it is a KrakenConfig type. I think I may need generics here, but I'm not sure. Tried using "Type" to return the class type, but I cannot convert the JObject to the "Type" as it is variable.

Any ideas? Or do I need generics in your opinion?

The code I tried is a new getter:
```
    public Type GetConfigType()
    {
        return typeof(KrakenConfig);
    }
```

and then trying to use this "Type" to convert the JObject to... but I cannot use the type inside the "< >" characters.
This does not work:
![image](https://user-images.githubusercontent.com/71019/209575287-ef5ee5b2-9a20-4199-a651-404b3ae89e6b.png)

2023-03-10 14:47 UTC, woutersamaey commented
The easiest way to test everything is by using my "dev" branch on my personal fork. This is this PR + the kraken plugin pre-installed. Get it here: https://github.com/woutersamaey/btcpayserver/tree/dev

2023-03-16 15:47 UTC, dennisreimann approved these changes
I could not fully test it, because I don't have any BTC on Kraken, but I adjusted the UI a bit ;)

2023-03-16 15:48 UTC, woutersamaey commented
> 

You did test using your "other tokens" a while back, didn't you?

2023-03-16 15:53 UTC, Bryansadventure commented
Am I going to be able to collect from my Bitcoin bonus

2023-03-20 01:45 UTC, merged