Greenfield get app details
btcpayserver/btcpayserver pull request #4102
Opened 2022-09-07 03:44 UTC by bolatovumar

2022-09-17 08:09 UTC, petzsch commented
Quick Question: Does this PR also enable access to the articles of a POS cart app? I've just read the Swagger docs changes and couldn't see anything related to it.

The reason I'm asking: In the BTCPay Telegram group was quite some discussion about having POS phone apps to integrate with what we allready have and also include support for POS printers (bluetooth). For something like this to be created, the POS cart app functionality would need to be accessable via API. (get article list, maybe create new articles, create order with list of articles maybe?)

If this is out of scope for this PR, I'll create a new issue for it.

2022-09-18 04:24 UTC, bolatovumar commented
> Quick Question: Does this PR also enable access to the articles of a POS cart app? I've just read the Swagger docs changes and couldn't see anything related to it.
> 
> The reason I'm asking: In the BTCPay Telegram group was quite some discussion about having POS phone apps to integrate with what we allready have and also include support for POS printers (bluetooth). For something like this to be created, the POS cart app functionality would need to be accessable via API. (get article list, maybe create new articles, create order with list of articles maybe?)
> 
> If this is out of scope for this PR, I'll create a new issue for it.

@petzsch it returns the template used by the store so you should be able to parse it

2022-09-18 07:54 UTC, petzsch commented
I guess that would be sufficient for an app to display articles for i.e. a waiter/waitress to quickly take an order and generate an invoice from it. (and do the receipt printing magic)

Inventory management would have to happen through the btcpay UI, or would we have a POST method for app details as well where we can upload a article template?

2022-09-22 03:07 UTC, bolatovumar commented
> Inventory management would have to happen through the btcpay UI, or would we have a POST method for app details as well where we can upload a article template?

You can already POST app details

2022-10-17 09:44 UTC, Kukks requested changes

2022-10-17 09:44 UTC, Kukks commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +    class DateTimeJsonConverter : JsonConverter
We can use `NBitcoin.JsonConverters.DateTimeToUnixTimeConverter` so please remove this converter

2022-10-17 09:44 UTC, Kukks commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        [JsonConverter(typeof(DateTimeJsonConverter))]
```suggestion
        [JsonConverter(typeof(NBitcoin.JsonConverters.DateTimeToUnixTimeConverter))]
```

2022-10-17 09:44 UTC, Kukks commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        [JsonConverter(typeof(DateTimeJsonConverter))]
```suggestion
        [JsonConverter(typeof(NBitcoin.JsonConverters.DateTimeToUnixTimeConverter))]
```

2022-10-17 09:44 UTC, Kukks commented on BTCPayServer.Client/Models/PointOfSaleAppData.cs
> +        public DateTime? EndDate { get; set; }
Date time offset is preferred.
```suggestion

        [JsonConverter(typeof(NBitcoin.JsonConverters.DateTimeToUnixTimeConverter))]
        public DateTimeOffset? EndDate { get; set; }
```

2022-10-17 09:44 UTC, Kukks commented on BTCPayServer.Client/Models/PointOfSaleAppData.cs
> +        public DateTime? StartDate { get; set; }
```suggestion

      [JsonConverter(typeof(NBitcoin.JsonConverters.DateTimeToUnixTimeConverter))]
        public DateTimeOffset? StartDate { get; set; }
```

2022-10-17 09:44 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "startDate": {
should be something like
```json
 "createdAt": {
                        "description": "The unix timestamp when the payment got created",
                        "nullable": true,
                        "allOf": [ {"$ref": "#/components/schemas/UnixTimestamp"}]
                    },
```

2022-11-23 06:01 UTC, bolatovumar commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        [JsonConverter(typeof(DateTimeJsonConverter))]
Done

2022-11-23 06:01 UTC, bolatovumar commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +    class DateTimeJsonConverter : JsonConverter
Done

2022-11-23 06:01 UTC, bolatovumar commented on BTCPayServer.Client/Models/CreateAppRequest.cs
> +        [JsonConverter(typeof(DateTimeJsonConverter))]
Done

2022-11-23 06:01 UTC, bolatovumar commented on BTCPayServer.Client/Models/PointOfSaleAppData.cs
> +        public DateTime? StartDate { get; set; }
Done

2022-11-23 06:03 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                    "startDate": {
Done

2022-11-23 06:12 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                RequiresRefundEmail = settings.RequiresRefundEmail == RequiresRefundEmail.InheritFromStore ? store.GetStoreBlob().RequiresRefundEmail : settings.RequiresRefundEmail == RequiresRefundE
Converting this to a boolean cuz it's weird to return an enum for this.

2022-11-23 06:12 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                "operationId": "Apps_GetApp",
Updated this since it's not specific to PoS app.

2022-11-23 06:12 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                "operationId": "Apps_DeleteApp",
Updated this since it's not specific to PoS app.

2022-11-23 06:12 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                        "description": "Whether refund email is required when paying the invoice. Defaults to what is set in the store settings",
Corrected this.

2022-11-23 06:12 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                        "description": "Displays values of perks if set to true",
Corrected this also.

2022-11-25 04:28 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                Items = JsonConvert.DeserializeObject(
I'm returning both the original Yaml template and the deserialized JSON object of the template. Idk if we need both? I'm doing the same for the crowdfund app.

2022-11-25 05:06 UTC, bolatovumar commented
Failing test unrelated

![Capture](https://user-images.githubusercontent.com/1934678/203905163-8e8e957c-a4f8-428f-a5f0-01fad86166dc.PNG)

2023-01-11 17:25 UTC, dennisreimann requested changes
The `GetPosApp` and `GetCrowdfundApp` methods should be added to the `LocalBTCPayServerClient` as well.

2023-01-11 17:25 UTC, dennisreimann commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                                "example": [
This example seems too elaborate.

2023-01-11 17:25 UTC, dennisreimann commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                                "description": "App view type (e.g., static, cart, etc...)",
As this is backed by the `PosViewType` enum: Can we document that enum as well? It's present in the `CreatePointOfSaleAppRequest` definition already, this should be extracted and referenced in both places.

2023-01-20 04:38 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                                "example": [
Updated in 665f8a67de6b5fd3e7a87f74135c0ac5aa85890d

2023-01-20 04:38 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                                "description": "App view type (e.g., static, cart, etc...)",
Done in ae61b4a06997467c7af3f81d18caba976bdbfade

2023-01-20 04:38 UTC, bolatovumar commented
> The `GetPosApp` and `GetCrowdfundApp` methods should be added to the `LocalBTCPayServerClient` as well.

Done in d2e966815ef1b4f2e8efb48275f6d50f968086c2

2023-01-21 17:42 UTC, dennisreimann approved these changes

2023-01-21 17:43 UTC, dennisreimann commented
@Kukks are you OK with merging this now?

2023-01-25 08:33 UTC, Kukks requested changes

2023-01-25 08:33 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                Perks = JsonConvert.DeserializeObject(
I am unsure about this. You're providing both a serialized and an object. 

Please pick one.


keep in mind we currently store the perks in yml format, and this is in json, so you re introducing a new format to consider. I would prefer we migrate the template to json and then we introduce it in the api.

2023-01-25 08:33 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                RequiresRefundEmail = settings.RequiresRefundEmail == RequiresRefundEmail.InheritFromStore ? store.GetStoreBlob().RequiresRefundEmail : settings.RequiresRefundEmail == RequiresRefundE
I would make this a nullable bool, where if `InheritFromStore`, then null

2023-01-25 08:33 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                Items = JsonConvert.DeserializeObject(
see other comment

2023-01-27 02:45 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs
> +                Perks = JsonConvert.DeserializeObject(
@Kukks I kept just the JSON since it's actually useful and easy to consume. I originally only had the template  but then figured it's not that useful as clients would have to parse it to make any use of it. 

I know we wanted to support JSON for store/crowdfund app items for a while now and I will follow up with a PR which actually adds the support for it.

2023-01-27 03:00 UTC, bolatovumar commented
Failing test unrelated.

2023-02-07 08:01 UTC, merged

2023-02-14 18:21 UTC, Atitlanio commented
Thank you for this feature! I am planning to use it to do a custom front-end for an app.

Are there plans to be able to update the item details? Particularly the inventory?

E.g., if I have a custom front-end store and someone buys an item, how might I be able to update the app so that the item's inventory is current? 

Much appreciated @bolatovumar and all!

2023-02-15 02:59 UTC, bolatovumar commented
> Thank you for this feature! I am planning to use it to do a custom front-end for an app.
> 
> Are there plans to be able to update the item details? Particularly the inventory?
> 
> E.g., if I have a custom front-end store and someone buys an item, how might I be able to update the app so that the item's inventory is current?
> 
> Much appreciated @bolatovumar and all!
> 
> This seems to be an extension of @petzsch 's question above. As far as I can see right now, I can GET items, however I can neither POST nor PUT items [Greenfield API ref](https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Apps_CreatePointOfSaleApp)

@Atitlanio you can `PUT` the `template` property of the app which contains items: https://docs.btcpayserver.org/API/Greenfield/v1/#operation/Apps_PutPointOfSaleApp

It's not very easy to use and we should probably have a separate endpoint to update items. Feel free to file a feature request for this.