Fix settigs sidebar activation
btcpayserver/btcpayserver pull request #4138
Opened 2022-09-19 19:03 UTC by daviogg

https://github.com/btcpayserver/btcpayserver/issues/4134

2022-09-19 19:52 UTC, dennisreimann requested changes

2022-09-19 19:52 UTC, dennisreimann commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                <a asp-area="" asp-controller="UIStores" asp-action="GeneralSettings" asp-route-storeId="@Model.Store.Id" class="nav-link js-scroll-trigger @ViewData.IsActivePage(Stor
We cannot use Payouts here, because that will also highlight the settings when the Payouts section is active.

2022-09-19 19:55 UTC, dennisreimann commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                <a asp-area="" asp-controller="UIStores" asp-action="GeneralSettings" asp-route-storeId="@Model.Store.Id" class="nav-link js-scroll-trigger @ViewData.IsActivePage(Stor
See #4139.

2022-09-20 04:55 UTC, daviogg commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                <a asp-area="" asp-controller="UIStores" asp-action="GeneralSettings" asp-route-storeId="@Model.Store.Id" class="nav-link js-scroll-trigger @ViewData.IsActivePage(Stor
Ok sorry, so we can close this without merge right?

2022-09-20 05:00 UTC, dennisreimann commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                <a asp-area="" asp-controller="UIStores" asp-action="GeneralSettings" asp-route-storeId="@Model.Store.Id" class="nav-link js-scroll-trigger @ViewData.IsActivePage(Stor
Yes, but we can also merge an adapted version of yours – you were first ;) – and afterwards merge a rebased version of mine.

2022-09-20 05:10 UTC, daviogg commented on BTCPayServer/Components/MainNav/Default.cshtml
> +                                <a asp-area="" asp-controller="UIStores" asp-action="GeneralSettings" asp-route-storeId="@Model.Store.Id" class="nav-link js-scroll-trigger @ViewData.IsActivePage(Stor
Ok, done, let me know if some other changes are needed :)

2022-09-20 07:35 UTC, dennisreimann approved these changes
Added my commit from #4139 here.

2022-09-20 07:38 UTC, Kukks approved these changes

2022-09-20 08:05 UTC, dennisreimann commented
Test failure unrelated.

2022-09-20 08:05 UTC, merged