[Greenfield] Can create an invoice for a payment request via Greenfield
btcpayserver/btcpayserver pull request #4243
Opened 2022-10-27 09:21 UTC by NicolasDorier

This add the ability to create a new invoice for a payment request via Greenfield.  A user seemed to need this in the mattermost.
I tried to refactor a bit so we could reuse code between the UI and the API.

2022-10-30 09:12 UTC, Kukks requested changes
I believe the /pay endpoint used to check if an active invoice was available and load that. If a different amount was requested, it would generate a new invoice (we should maybe cancel the old one too).

Need to also override the LocalBtcpayClient

2022-10-30 09:12 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.payment-requests.json
> +                "summary": "Create a new invoice for the payment request",
This may also just fetch a currently active invoice though.

2022-10-31 02:45 UTC, NicolasDorier commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.payment-requests.json
> +                "summary": "Create a new invoice for the payment request",
good point, I missed that.

2022-11-01 12:30 UTC, Kukks approved these changes

2022-11-02 09:28 UTC, NicolasDorier commented on BTCPayServer.Client/Models/PayPaymentRequestRequest.cs
> +        public bool? AllowPendingInvoiceReuse { get; set; }
I was considering it, so we keep same behavior as the UI. However, I'm not sure it is a good idea, without looking the UI, the name of this endpoint suggest a new invoice is created.

2022-11-02 09:31 UTC, NicolasDorier commented on BTCPayServer/Controllers/GreenField/GreenfieldPaymentRequestsController.cs
> +            if (amount.HasValue && !pr.AllowCustomPaymentAmounts)
good point, just did it.

2022-11-02 09:41 UTC, merged