Add Greenfield API endpoint for pull payment LNURL items
btcpayserver/btcpayserver pull request #4472
Opened 2022-12-23 07:18 UTC by bolatovumar

Added new Greenfield API `GET` endpoint under `/api/v1/pull-payments/{pullPaymentId}/lnurl` which returns LNURL details for the pull payment in Bech32 and URI representations.

![Capture](https://user-images.githubusercontent.com/1934678/209290404-b689f6b4-2cbe-4323-a78a-1868e7dfc951.PNG)

close #4365

2022-12-23 07:20 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldPullPaymentController.cs
> +                    cryptoCode = "BTC",
I'm hardcoding `BTC` here since I figured we won't have this functionality for other coins.

2023-01-13 11:56 UTC, Kukks requested changes

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer.Client/BTCPayServerClient.PullPayments.cs
> +        public virtual async Task<PullPaymentLNURL> GetLNURLs(string pullPaymentId,
```suggestion
        public virtual async Task<PullPaymentLNURL> GetPullPaymentLNURL(string pullPaymentId,
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +            await this.AssertAPIError("ln-url-not-supported", async () => await unauthenticated.GetLNURLs(pp.Id));
```suggestion
            await this.AssertAPIError("lnurl-not-supported", async () => await unauthenticated.GetLNURLs(pp.Id));
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldPullPaymentController.cs
> +        public async Task<IActionResult> GetLNURLs(string pullPaymentId)
```suggestion
        public async Task<IActionResult> GetPullPaymentLNURL(string pullPaymentId)
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldPullPaymentController.cs
> +            return this.CreateAPIError("ln-url-not-supported", "LNURL not supported for this pull payment");
```suggestion
            return this.CreateAPIError("lnurl-not-supported", "LNURL not supported for this pull payment");
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldPullPaymentController.cs
> +                    cryptoCode = "BTC",
I wouldn't since you're checking for the default crypto code elsewhere.

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/GreenfieldPullPaymentController.cs
> +                    cryptoCode = "BTC",
```suggestion
                    cryptoCode = _networkProvider.DefaultNetwork.CryptoCode,
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/Controllers/GreenField/LocalBTCPayServerClient.cs
> +        public override async Task<PullPaymentLNURL> GetLNURLs(string pullPaymentId, CancellationToken cancellationToken = default)
```suggestion
        public override async Task<PullPaymentLNURL> GetPullPaymentLNURL(string pullPaymentId, CancellationToken cancellationToken = default)
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.pull-payments.json
> +              "operationId": "PullPayments_LNURL",
```suggestion
              "operationId": "PullPayments_GetPullPaymentLNURL",
```

2023-01-13 11:56 UTC, Kukks commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.pull-payments.json
> +                      "description": "Pull payment not found but does not support LNURL"
```suggestion
                      "description": "Pull payment found but does not support LNURL"
```

2023-01-20 04:20 UTC, bolatovumar commented on BTCPayServer.Client/BTCPayServerClient.PullPayments.cs
> +        public virtual async Task<PullPaymentLNURL> GetLNURLs(string pullPaymentId,
Updated in 4f83bc0c344ea4e40ab706d5b6eef7213a6d431e

2023-01-20 04:20 UTC, bolatovumar commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +            await this.AssertAPIError("ln-url-not-supported", async () => await unauthenticated.GetLNURLs(pp.Id));
Updated in e834df8ef6927a269936a748a350f80c2ee6e38f

2023-01-20 04:21 UTC, bolatovumar commented on BTCPayServer/Controllers/GreenField/GreenfieldPullPaymentController.cs
> +                    cryptoCode = "BTC",
Updated in fbc0f48e90ee1aab3b522b7b9cb5cf32112c7fbf

2023-01-20 04:21 UTC, bolatovumar commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.pull-payments.json
> +                      "description": "Pull payment not found but does not support LNURL"
Updated in ea239caa5663c84459dc01ebd87cee065dc8f6d8

2023-01-26 05:43 UTC, merged