Point of Sale: Improve merchant view
btcpayserver/btcpayserver pull request #4560
Opened 2023-01-24 11:11 UTC by dennisreimann

Closes #3843. There are two more TODOs in that issue, but they aren't specified in more detail.

I opted for a more reduced POS style selector: I experimented a bit with it and played through some variants, because I found that it takes up quite some space when done like in Figma.

![image](https://user-images.githubusercontent.com/886/214275374-59ff2dff-75d7-4ddd-bf6b-fac3d1c0d39f.png)

2023-01-24 16:30 UTC, dstrukt commented
Thoughts:

- I like the minified POS option selections, and I think it makes sense to have them exposed (as opposed to say a dropdown or other equivalent) if we keep them all in one "app/plugin" like this as well. 
- Do we need an additional descriptor for the `Type`?
- Debating if putting the `App Name` and `Display Title` together above the selection options makes more sense...?
- Agree with your decision to split the `Display Title` and `Currency`

Otherwise, looks great!

2023-01-24 16:31 UTC, dstrukt requested changes
Thoughts:

- I like the minified POS option selections, and I think it makes sense to have them exposed (as opposed to say a dropdown or other equivalent) if we keep them all in one "app/plugin" like this as well.
- Do we need an additional descriptor for the Type?
- Debating if putting the App Name and Display Title together above the selection options makes more sense...?
- Agree with your decision to split the Display Title and Currency

Otherwise, looks great!

2023-01-24 16:35 UTC, dennisreimann commented
> Do we need an additional descriptor for the Type?

Imho merging the short title with the additional description makes it more concise and the labels as they are seem clear to me.

> Realize it was in the mock, but debating if putting the App Name and Display Title together above the selection options makes more sense...?

I could see that make sense :)

2023-01-24 16:43 UTC, dstrukt commented
> Imho merging the short title with the additional description makes it more concise and the labels as they are seem clear to me.
Sounds good, happy to roll with this great quicker improvement and address more in the future.

> I could see that make sense :)
Hahah the common A or B .. both work, could make sense to select the type, then the display you want on that type, but just re-evaluating the step-by-step again with fresh eyes.

<img width="884" alt="Screen Shot 2023-01-24 at 8 40 48 AM" src="https://user-images.githubusercontent.com/6250771/214353830-729198ee-dc92-4c54-a400-0fea01e3ddca.png">

Also, should we rename this section to `Checkout` now perhaps? As `Appearance` no longer makes as much sense without the type selector.

2023-01-24 17:58 UTC, Daedaesde commented on BTCPayServer.Tests/SeleniumTests.cs
>              s.Driver.FindElement(By.CssSelector(".template-item:nth-of-type(1) .btn-primary")).Click();
R

2023-01-24 18:33 UTC, dennisreimann commented
I think we could trim the whole bottom section to something like this:

![grafik](https://user-images.githubusercontent.com/886/214378545-5201a34d-2e5f-48e4-9bdf-20acf4efbd68.png)

## Before

![appearance-before](https://user-images.githubusercontent.com/886/214378580-55967698-8477-4708-afb7-670a167dc4c5.png)

2023-01-24 21:01 UTC, dstrukt commented
I like the idea of consolidating the options, and even though it sometimes add more height, I like the section headers, makes the content a bit more parsable imo, e.g.  seeing `Custom Payments`,`Tips` & `Discounts` within the `Checkout` header might be more easy to understand.

Hmm, will think on here...

2023-01-24 21:48 UTC, dennisreimann commented
The rationale behind removing the subheaders was that it's only a single toggle per header, so I thought the toggle + label might be enough.

2023-01-24 22:24 UTC, dstrukt commented
Ahh yeah, that makes sense .. hmm it's still a bit parse to parse, but..

If we go that route, I'd rearrange:
- Request customer data on checkout (most important item)
- Text to display on the button
- Tips (second most important item)
- Discounts
- Custom Amount

2023-01-24 22:37 UTC, pavlenex commented
Concept ACK, just want to say that graphically presenting the types of pos is fantastic design choice.

2023-01-25 09:50 UTC, dennisreimann commented
@dstrukt Ok, I'm giving in ;)

![grafik](https://user-images.githubusercontent.com/886/214531873-628d64c0-862e-4499-8772-207e0ec046ae.png)

2023-01-25 10:45 UTC, dennisreimann commented
Now also hides the options that aren;t relevant for the Keypad-only view: Description and products are hidden in that case.

![grafik](https://user-images.githubusercontent.com/886/214543244-34915d40-2207-4a3a-ac28-7b34793db0ae.png)

2023-01-25 10:47 UTC, dennisreimann commented
@dstrukt @pavlenex  This is now ready from my point of view.

2023-01-25 19:13 UTC, dstrukt commented
Looks great, will take a look asap.

Great work!

2023-01-25 20:45 UTC, dstrukt commented
Wow. This is so much better for such a quick iteration!

Only other thoughts and nits I have looking at this, which aren't necessary to wrap this one up:

- [ ] Should we kill the constraint on the `Products`? Or possibly increase it .. feels like we could get 3-4 on the row, feels a bit more constrained now, but not sure the best way to go about this.
- [ ] Eventually we'll probably want to expose the `customer information` in a similar way that we did for the POS type, it's very easy to parse and a pretty important decision to overall experience. 
- [ ] It still makes sense to keep `Products` above the `Checkout` yeah? Don't know why I'm questioning this, but wanted to raise it as a discussion point

2023-01-25 20:46 UTC, dstrukt approved these changes

2023-01-26 00:27 UTC, merged