Checkout: Allow NFC/LNURL-W whenever LNURL is available
btcpayserver/btcpayserver pull request #4671
Opened 2023-02-20 17:01 UTC by dennisreimann

With what we have in master right now, we display NFC only for top-up invoices. With these changes, we display NFC in all cases, where LNURL is available. Note that this hides LNURL from the list of selectable payment methods, it's only available to use the NFC — and explicitely selectable only for the edge case of top-up invoice + non-unified QR (as before).

Rationale: Now that we got NFC tightly integrated, it doesn't make sense to support the NFC experience only for top-up invoices. With this we bring back LNURL for regular invoices as well, but don't make it selectable and use it only for the NFC functionality.

There are many different cases. Basically it's a test matrix permutating:

- Unified/non-unified
- Regular vs. top-up invoice
- LNURL available as payment method

## Unified

### Without LNURL

![unified-without-lnurl](https://user-images.githubusercontent.com/886/220165413-7f31a9db-940c-4367-9bd1-9fd040539f1f.png)

### With LNURL

![unified-with-lnurl](https://user-images.githubusercontent.com/886/220165418-916361d0-8950-4a9f-b64a-be82d2f9632f.png)

### Top-up

![unified-topup](https://user-images.githubusercontent.com/886/220165407-e371d984-ddeb-4ec2-bd86-384de24eb3b6.png)

## Non-unified

### Without LNURL

![non-unified-without-lnurl](https://user-images.githubusercontent.com/886/220165119-fcda3a0d-bf41-4246-81c6-27b2245485db.png)

### With LNURL

![non-unified-with-lnurl](https://user-images.githubusercontent.com/886/220165122-cf31047a-5435-4802-9a43-47198a3eb747.png)

### Top-up

![non-unified-topup](https://user-images.githubusercontent.com/886/220165233-abe3b043-e380-4bd8-be13-c23c7832bdca.png)

## Just Lightning + LNURL

![ln-with-lnurl](https://user-images.githubusercontent.com/886/220165547-113c0f6c-81c7-46aa-a8eb-3c1c181f759d.png)

2023-02-20 17:13 UTC, dennisreimann commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> -                    paymentMethodTemp = invoice.GetPaymentMethods().FirstOrDefault();
This and the part above prevents LNURL from showing up as initial payment method. We don't want this, as LNURL also isn't explicitely selectable.

2023-02-20 17:13 UTC, dennisreimann commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                OnChainWithLnInvoiceFallback = storeBlob.OnChainWithLnInvoiceFallback,
We now need this to discern on the UI-level, whether or not to have LNURL available as payment method — which is the case only for top-up + non-unified.

2023-02-20 17:13 UTC, dennisreimann commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> -                                              i.GetId() != lnurlId || invoice.IsUnsetTopUp())
Instead of completely removing LNURL for non-topup invoices, this leaves LNURL in, but hides it from the payment method switches.

2023-02-20 17:13 UTC, dennisreimann commented on BTCPayServer/Views/Shared/NFC/CheckoutEnd.cshtml
> +              return !!this.model.availableCryptos.find(pm => pm.paymentMethodId === 'BTC_LNURLPAY');
Allows NFC whenever LNURL is available.

2023-02-20 17:18 UTC, dennisreimann commented
> I am for completely removing it where it makes no sense, graying it out, may just add confusion. Oh, could be that you're actually already doing that removing lnurl button when estimated that it's not functional or just per payment method?

@pavlenex Yes, it already isn't available in Checkout v2 anymore — we completely removed it for non-top-up invoices. And this PR reintroduced it kinda in "hidden" mode, so that it is available for NFC beyond just top-up invoices.

In that sense we kinda went to far by removing it completely, because without the changes here, LNURL (and hence NFC) wouldn't be available for regular invoices. I think the above screenshots explain it better — LNURL isn;t shown as a payment method other than for the top-up + non-BIP21 case.

2023-02-20 17:20 UTC, pavlenex commented
Got it, I have to test this and sync up, just to make sure I understood correctly, if the invoice is 10$, and lightning is available as a payment method, all other criterias (browser, etc) are met, the user would be able to checkout by tapping let's say boltcard? I just want to be completely sure I understand 

> we completely removed it for non-top-up invoices

2023-02-21 01:40 UTC, NicolasDorier commented
Code ACK for me, however, I am a bit overwhelmed by all of this, so I'll let  @pavlenex  judge :D

2023-02-21 04:45 UTC, dennisreimann commented
@NicolasDorier yeah, we'll need proper testing. I just turned this into a draft again, because I noticed that it still isn't fully correct and breaks again what I fixed in #4660. 

Will also add checks for the button in the Selenium tests.

2023-02-21 06:54 UTC, dennisreimann commented
> we'll need proper testing. I just turned this into a draft again, because I noticed that it still isn't fully correct and breaks again what I fixed in https://github.com/btcpayserver/btcpayserver/pull/4660.

Fixed that, added test cases and updated the screenshots above.

2023-02-21 06:57 UTC, dennisreimann commented
> just to make sure I understood correctly, if the invoice is 10$, and lightning is available as a payment method, all other criterias (browser, etc) are met, the user would be able to checkout by tapping let's say boltcard?

@pavlenex With the changes in this PR - yes, and that's the purpose of this pull request. Before it wouldn't show. 

Screenshots for your test case:

## This PR

![pav-pr](https://user-images.githubusercontent.com/886/220270173-998bbacf-7e60-4e41-946d-91de3f0c2320.png)

## On current master

![pav-master](https://user-images.githubusercontent.com/886/220270166-5491b355-5b3c-40f4-922c-5ceabdfc58a5.png)

2023-02-21 08:11 UTC, ndeet commented
Nice work! 

When I tested NFC with checkout v1 it was a bit annoying to always scroll down to have the NFC button show up. Maybe a bit OT and for a follow up:
I think it would be useful to have an option to show the NFC button more at the top. If someone runs a pos terminal and mostly has face2face customers, they either scan the QR or pay with NFC. The "pay in wallet" and "LN invoice" button/text is not really useful to them. So maybe a "pos mode" for checkout?

2023-02-21 12:02 UTC, NicolasDorier commented
@ndeet I think we should eventually have a Checkout "Retail mode" automatically stripping stuff. Like the `Pay in wallet`.

Maybe not for this PR, but I think checkout pages could get more optimized for retails.

2023-02-21 12:12 UTC, dennisreimann commented
@NicolasDorier Yes, I still have it on my list for v1.8.x — didn't get to it in time for this release.

2023-02-21 14:51 UTC, Kukks requested changes
the NFC option is available regardless of LNURL. If there is a bolt11 or an lnurl on the screen, it should be shown.

2023-02-21 15:41 UTC, dennisreimann commented
@Kukks thanks for the pointer, I've fixed this in [3474fd5](https://github.com/btcpayserver/btcpayserver/pull/4671/commits/3474fd5cd80b8f63097a90d099af38ad9ac12f02) and also added a test for that case.

2023-02-21 22:24 UTC, Kukks approved these changes

2023-02-21 22:24 UTC, Kukks commented on BTCPayServer/Views/UIInvoice/CheckoutV2.cshtml
> +    var displayedPaymentMethods = Model.IsUnsetTopUp && !Model.OnChainWithLnInvoiceFallback
We should really make this glue more flexible so thta we dint hardcode  these things in a view

2023-02-22 06:53 UTC, merged