Wallet transactions: Add label manager
btcpayserver/btcpayserver pull request #4796
Opened 2023-03-21 13:06 UTC by dennisreimann

Uses the label manager component in the wallet transactions list. Closes #4706.

![labels-inline](https://user-images.githubusercontent.com/886/226614047-5edc3c71-ce9d-408c-8f79-9a196efbb420.png)

Also improved the label manager UI to work better with the list: Introduced an inline display mode, which removes the form input appearance. Also adjusted the dropdown and options to fit what we have elsewhere.

2023-03-21 13:14 UTC, dennisreimann commented on BTCPayServer/Components/LabelManager/LabelManager.cs
> +        public IViewComponentResult Invoke(WalletObjectId walletObjectId, string[] selectedLabels, bool excludeTypes = true, bool displayInline = false)
Options that got added for the trasactions list, on which one was able to manage type labels as well. Inline mode is also for the list.

2023-03-21 13:14 UTC, dennisreimann commented on BTCPayServer/Controllers/UIWalletsController.cs
> +                : await WalletRepository.GetWalletLabels(walletObjectId);
It turned out I didn't need this, but this makes it more flexible so that one can request either labels for the whole wallet or individual wallet objects.

2023-03-21 13:14 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/_WalletTransactionsList.cshtml
> +                <noscript>
Moved the previous approach into `noscript` parts — shall we keep it or remove that?

2023-03-22 08:08 UTC, Kukks commented on BTCPayServer/Views/UIWallets/_WalletTransactionsList.cshtml
> +                <noscript>
this is fine

2023-03-22 10:51 UTC, Kukks requested changes
just tested and it feels good but we now lost a key feature: the descriptions of the labels are gone (for example payout ids, invoice link, etc)

2023-03-22 10:55 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +            initLabelManagers();
It doesn't, see the `:not(.tomselected)` in the selector. It only inits the ones that aren't initialized already.

2023-03-22 14:37 UTC, dennisreimann commented
> we now lost a key feature: the descriptions of the labels are gone (for example payout ids, invoice link, etc)

Good point, added in [e5c5cdc](https://github.com/btcpayserver/btcpayserver/pull/4796/commits/e5c5cdc55eca81ac39abce949a8892907803931f).

![grafik](https://user-images.githubusercontent.com/886/226938498-a8dada09-377b-414f-9c41-6deab11c5827.png)

2023-03-23 06:35 UTC, NicolasDorier commented on BTCPayServer/Views/UIWallets/_WalletTransactionsList.cshtml
> +                <noscript>
imho the `noscript` should go. Burning trees for nothing.

2023-03-23 06:38 UTC, NicolasDorier commented
I think you should get ride of `<noscript>` stuff, which only work if no JS is present.
While I think it's cool to have it on public pages, backend pages can just require javascript.

2023-03-23 10:40 UTC, Kukks requested changes
![](https://i.imgur.com/ZUVMJhF.png)
weird red pixels?

also there is no link on the badges that used to have links

2023-03-26 11:42 UTC, merged