Wallet Transactions Export: Add BIP-329 support
btcpayserver/btcpayserver pull request #4799
Opened 2023-03-21 15:34 UTC by dennisreimann

Adds support for the [BIP 329](https://github.com/bitcoin/bips/blob/master/bip-0329.mediawiki) export format.

Sample transactions export:

```jsonl
{"type":"tx","ref":"9eb4b1f69dc0aad88f2530fdd124c77021c1633500e14369d0896bf75a025596","label":"microtransaction"}
{"type":"tx","ref":"98ee2e20e45967eeda330b191d881584d1e02ea05e633e4cb7c48aea8980fc63","label":"test"}
{"type":"tx","ref":"84ce8b198d85e715588da114b7b441833cfc4892ba9aa1f7f3cfbfdcf2ca1235","label":"Mining Income, microtransaction, test"}
```

Currently only the transaction data is exported, but I think we can also leverage the new labeling system to export other types, like `addr` as well. @NicolasDorier 

Closes #4536.

2023-03-22 08:04 UTC, NicolasDorier commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    Label = tx.Labels is { Count: > 0 } ? string.Join(", ", tx.Labels): string.Empty
I believe you need 1 line per label. If a tx has several label, there should be several lines.

2023-03-22 08:04 UTC, NicolasDorier commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +                <a asp-action="Export" asp-route-walletId="@walletId" asp-route-format="bip329" asp-route-labelFilter="@labelFilter" class="dropdown-item export-link" target="_blank" id="ExportBIP329
`Wallet Labels Export (BIP-329)`

2023-03-22 08:52 UTC, dennisreimann commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    Label = tx.Labels is { Count: > 0 } ? string.Join(", ", tx.Labels): string.Empty
Is it like that, @craigraw? I couldn't find that case in the BIP.

2023-03-22 09:16 UTC, craigraw commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    Label = tx.Labels is { Count: > 0 } ? string.Join(", ", tx.Labels): string.Empty
There is no specific instruction on how to handle duplicate references, but since most wallets only show one label per reference I believe comma-separated is the way to go.

2023-03-22 09:18 UTC, dennisreimann commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    Label = tx.Labels is { Count: > 0 } ? string.Join(", ", tx.Labels): string.Empty
Done in [5a904f2](https://github.com/btcpayserver/btcpayserver/pull/4799/commits/5a904f2872fe0605b5a802673a13c9b5f5649167).

2023-03-22 09:18 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletTransactions.cshtml
> +                <a asp-action="Export" asp-route-walletId="@walletId" asp-route-format="bip329" asp-route-labelFilter="@labelFilter" class="dropdown-item export-link" target="_blank" id="ExportBIP329
Done in [351f492](https://github.com/btcpayserver/btcpayserver/pull/4799/commits/351f49234439f6e94a51454c98b4ecada907b3be)

2023-03-22 09:20 UTC, dennisreimann commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    Label = tx.Labels is { Count: > 0 } ? string.Join(", ", tx.Labels): string.Empty
@craigraw Does Sparrow already support this, so that we can test it?

2023-03-22 09:38 UTC, Kukks requested changes

2023-03-22 09:38 UTC, Kukks commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                            new { Type = "label", Ref = tx.TransactionId, Label = label }, Formatting.None,
This doesn't look right according to the bip. There is no type `label`, just a property `label`.
I think the spec says you need to create a record of type `tx`, for each label applied to it.

2023-03-22 09:44 UTC, Kukks requested changes

2023-03-22 09:44 UTC, Kukks commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    var label = string.Join(", ", tx.Labels);
No, I think you need to create a new row for each label.

2023-03-22 09:45 UTC, dennisreimann commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +                    var label = string.Join(", ", tx.Labels);
I reverted the change from making it one per line because see Craig's comment above.

2023-03-23 00:36 UTC, NicolasDorier commented on BTCPayServer/Services/Wallets/Export/TransactionsExport.cs
> +            var lines = txs.Aggregate(new List<object>(), (res, tx) =>
use of Aggregate instead of foreach is really weird.

2023-03-23 05:53 UTC, NicolasDorier commented
I give up implementing address export as well.
I need to refactor the export stuff so we don't need another hack overload.

2023-03-23 06:03 UTC, NicolasDorier approved these changes

2023-03-27 04:59 UTC, merged