Checkout v2: Improve expired paid partial state
btcpayserver/btcpayserver pull request #4827
Opened 2023-03-28 13:06 UTC by dennisreimann

Adds an email property to the store blob and displays that email as a "Contact us" button on the expired view if the invoice was paid partially. Closes #4303.

![grafik](https://user-images.githubusercontent.com/886/228244000-3b24fe05-9f6e-41ee-90cb-5ecba72ec016.png)

### Sample email

The subject is prefilled with `Invoice {InvoiceID}` and the email body looks like this:

```
Hi {StoreName},

the invoice {InvoiceID} (Order ID: {OrderId}) was paid partial.
Please let me know how to proceed.

Best regards!
```

2023-03-29 08:23 UTC, Kukks commented
Are emails the right approach for this? I don't have any suggestions yet, but every time I'm personally greeted with a mailto link, I cry a little

2023-03-29 08:29 UTC, dennisreimann commented
@Kukks It's the easiest approach by far (the alternative was having an email form and requiring the store to have SMTP set up) and this is mostly for getting customer and merchant into contact.

2023-03-29 12:01 UTC, Kukks requested changes

2023-03-29 12:01 UTC, Kukks commented on BTCPayServer/Views/UIInvoice/CheckoutV2.cshtml
> +                        <a v-if="isPaidPartial && contactLink" class="btn btn-primary rounded-pill w-100" :href="contactLink" v-t="'contact_us'" id="ContactLink"></a>
Why only paid partial?  Probably makes sense for any situation that does not result in a processing/settled state but a payment has been made. (partial, over, late)

2023-03-30 11:12 UTC, dennisreimann commented on BTCPayServer/Views/UIInvoice/CheckoutV2.cshtml
> +                        <a v-if="isPaidPartial && contactLink" class="btn btn-primary rounded-pill w-100" :href="contactLink" v-t="'contact_us'" id="ContactLink"></a>
That's basically the condition, as we also don't have that concrete state:

```
isPaidPartial () {
    return this.btcPaid > 0 && this.btcDue > 0;
},
```

2023-03-30 17:52 UTC, dstrukt commented
> @Kukks It's the easiest approach by far (the alternative was having an email form and requiring the store to have SMTP set up) and this is mostly for getting customer and merchant into contact.

The only alternative would be including a .. 
`Please email 
{email}` (with a copy icon
at the end of the copy.

I too hate the mailto: but realize we're pretty limited here on the UX.

2023-03-31 00:50 UTC, Kukks commented
OK let's do this for now, maybe we can do a plugin that adds a mini embedded chat ojnth checkout to spice things up without bloating core

2023-04-04 01:38 UTC, NicolasDorier commented
@dennisreimann I don't think email is a good idea.
I suggest you instead allow input any URL, so merchants who wants to be contacted by mail can just enter `mail:blah@blag.org`, while those who wants to redirect to some custom page can put the URL. If it is an URL, we can later add a query string so the page knows why this "Contact Us" is reached.

2023-04-04 07:25 UTC, dennisreimann commented
@NicolasDorier Ok, but what about the prefilled email body? Would we also remove that or append it in case it's a `mailto` link? I don't see a general link as that useful, because the context would get lost and we might need to explain how this is different from the Store Website URL, which is also present.

@pavlenex I think this just wasn't specified enough to be worked on. Maybe we should postpone it until the next release before rushing it.

2023-04-04 10:33 UTC, pavlenex commented
I am fine with postponing this one for until we iron out the details, may as well then postpone #4850 just to pack it all up together and ship in 1.9.10 @NicolasDorier @Kukks what do you guys think?

2023-04-10 01:02 UTC, Moxita33 commented on BTCPayServer/wwwroot/checkout-v2/checkout.js
> +                const body = `Hi ${this.srvModel.storeName},\n\nthe invoice ${details} was paid partial.\nPlease let me know how to proceed.\n\nBest regards!`;
****

2023-04-19 13:41 UTC, NicolasDorier commented
Idea from @Kukks : for a url, we can use the placeholder like `{OrderId}` so the merchant can know automatically which OrderId is impacted by the problem.

2023-04-20 09:49 UTC, dennisreimann commented
Updated to make it an URL instead of email address.

![grafik](https://user-images.githubusercontent.com/886/233329368-21611b78-5ace-4130-85f5-493f4c4f1ba7.png)

2023-04-25 13:09 UTC, Kukks approved these changes

2023-04-26 07:20 UTC, Kukks approved these changes

2023-04-26 19:22 UTC, dstrukt approved these changes
Like the latest proposed solution, LGTM!

2023-05-11 08:38 UTC, Kukks approved these changes

2023-05-11 08:38 UTC, merged