Remove LNURLStandardInvoiceEnabled
btcpayserver/btcpayserver pull request #4911
Opened 2023-04-24 13:14 UTC by NicolasDorier

Remove the lightning setting `LNURL enabled for standard invoices`.
This is currently `false` by default.

The motivation of this settings was to not bother the user on the checkout page for both BOLT11 payment and LNURL.

LNUrl is the only option for TopUp invoices, since BOLT11 have a mandatory amount. (technically not true, but no wallet support no amount correctly)

If BOLT11 is possible, LNURL as a payment option in the checkout was useless as it's just a different QR code offering nothing more than what BOLT11 was offering.

Checkout v2 was properly only showing BOLT11 even if LNURL was also possible.
Checkout v1 is still showing both options.

The main issue now is that LNURL is used outside of the checkout via NFC/Print view for PoS, and if this obscure checkbox wasn't checked, NFC and print view wouldn't be working, since LNURL was disabled for standard invoices.

This PR removes completely the option, and update Checkout v1 to not show LNURL payment in the displayed payment methods if BOLT11 is available.

2023-04-24 13:38 UTC, dennisreimann commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +            if (storeBlob is { CheckoutType: CheckoutType.V2, OnChainWithLnInvoiceFallback: true } &&
I think we should then also remove the `CheckoutType: CheckoutType.V2` part here, so that we unify V1 and V2.

2023-04-25 00:21 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +            if (storeBlob is { CheckoutType: CheckoutType.V2, OnChainWithLnInvoiceFallback: true } &&
btw, there is a bug with this: If the store is checkout v2, doesn't mean the invoice is. The invoice can opt in checkout v1 overriding the store settings.

So we should definitely unify this later.

2023-04-25 07:22 UTC, Kukks requested changes
You will need to remove `DisableBOLT11PaymentOption` option in `LightningSupportedPaymentMethod`; else, there will be installs with LN fully disabled for standard invoices.

2023-04-25 09:38 UTC, dennisreimann commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +            if (storeBlob is { CheckoutType: CheckoutType.V2, OnChainWithLnInvoiceFallback: true } &&
Unified it in [8de55ce](https://github.com/btcpayserver/btcpayserver/pull/4911/commits/8de55cef313ef5cd58f67fb32d73cb5aa57065e7).

2023-04-25 10:22 UTC, dennisreimann commented
> You will need to remove DisableBOLT11PaymentOption option in LightningSupportedPaymentMethod; else, there will be installs with LN fully disabled for standard invoices.

Done in [c95f75b](https://github.com/btcpayserver/btcpayserver/pull/4911/commits/c95f75bc6c157da43ec88fd1dc86af780703d03d).

2023-04-25 11:53 UTC, Kukks approved these changes
i think it's ok, but we should def test before a public release

2023-04-25 11:53 UTC, Kukks commented on BTCPayServer/Models/StoreViewModels/LightningSettingsViewModel.cs
>          public bool LUD12Enabled { get; set; }
Maybe we can remove this too then and have it always enabled?

2023-04-25 11:53 UTC, Kukks commented on BTCPayServer/Views/UIInvoice/CheckoutNoScript.cshtml
> +					@foreach (var crypto in displayedPaymentMethods)
nit: weird ident (tabs)

2023-04-25 12:08 UTC, dennisreimann commented on BTCPayServer/Models/StoreViewModels/LightningSettingsViewModel.cs
>          public bool LUD12Enabled { get; set; }
Concept ACK. I think with the approach we took for Checkout v2 (and now also unified in v1 as of this PR) it makes sense to not bother the user with this.

2023-04-25 12:34 UTC, dennisreimann approved these changes

2023-04-26 01:18 UTC, NicolasDorier commented
@Kukks 

> You will need to remove DisableBOLT11PaymentOption option in LightningSupportedPaymentMethod; else, there will be installs with LN fully disabled for standard invoices.

This isn't the case. This PR activates LNURL for all invoices even standard.
If BOLT11 isn't available, then the LNURL QR Code is shown.

2023-04-26 06:15 UTC, merged