Improve invoice filtering UI
btcpayserver/btcpayserver pull request #4914
Opened 2023-04-24 16:19 UTC by dennisreimann

Closes #3664.

2023-05-01 10:20 UTC, pavlenex approved these changes
tACK This is a good cleanup, concept ACK, will leave it up to @dstrukt to comment on UI, but imo this is great solution, good job!

2023-05-05 04:00 UTC, dstrukt requested changes
Overall, love it, very clean change!

However, few suggestions:

- [ ] Push the `Export` button (it's disappeared?) next to the Create button
- [ ] Let the elements go full width (sans Export / Actions)
- [x] Rename `Date` to `Time`? Thoughts?
- [x] min-width the `Status` and `Time` buttons to 120px?
- [x] Reduced the left padding (looked better) to 16px vs. 24px?

i.e:
<img width="1425" alt="Screen Shot 2023-05-04 at 5 12 43 PM" src="https://user-images.githubusercontent.com/6250771/236372311-872d1f53-e941-4dff-a635-3bf0028c56ea.png">

- [ ] Thoughts on pushing the mass actions to the next line? i.e:
<img width="779" alt="Screen Shot 2023-05-04 at 8 55 51 PM" src="https://user-images.githubusercontent.com/6250771/236374822-b9aa3889-2e88-4938-8413-7fa18560bd96.png">

Do you think we could remove the `Search` button, and instead add `Search...` instead?

Otherwise, this looks great - awesome work! We could easily translate this to other views too.

2023-05-05 06:28 UTC, dennisreimann commented
Did the updates: 

![grafik](https://user-images.githubusercontent.com/886/236389610-12fbba34-9e99-4df6-8483-19ab179513e8.png)


@dstrukt The export/actions buttons are only present when there are results, so I think the first point of that list doesn't apply?

2023-05-05 18:01 UTC, dstrukt commented
Ahh yes, it was intented for if >1 invoice, just knew I could show what the search/time/status would look like sans Export/Actions.

I've been wanting to improve the `Actions` button/CTA for a little while, so thought this might be a good time, but if you think it falls outside of the scoe of this PR, feel free to ignore for now.

2023-05-11 12:48 UTC, dennisreimann commented
@dstrukt I added the app filter and also indicators to see which filter is active:

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/38bde649-6431-401b-a6bf-78d6c71ce32b)

2023-05-11 12:55 UTC, dennisreimann commented
@dstrukt Regarding "Export button next to Create Invoice": We are a bit constraint here, because there are actually two HTML forms on this page: One for search/filtering and another one for export/archive. The latter has to include the checkboxes in the list and we cannot move the Export button out of the form.

Something like this would work though, if we move the Export button next to Archive again. This would also make it more logical imho, because we made it so that only the checked invoices get exported — so having a direct connection to the list would make sense for the user as well.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/d830a76d-51b8-4520-a0cd-9e417b2a7d52)

2023-05-14 01:04 UTC, dstrukt commented
Updated two snippets of text (Plugin instead of App) as we're moving to plug-ins, and `Search...` instead of `Search ...`.

Overall it looks fantastic, this is all much easier to parse!

- I still think we should try to address mass actions in a sep. PR. 
- I see where you're coming from with <form> concerns for Export, so perhaps maybe we can add the export as part of the mass action

The current implementation work, but thought/suggestion for "selected" filters:
For the Status and Plugin filters, we could surface the active count to the parent text, e.g.
- 2 Plugin(s) or 1 Plugin
- 3 Status or 1 Status 
But for Time it could just change to the selected range, e.g simply:
- 24 Hours, 3 Days, 7 Days or Custom
Just a thought.

Otherwise, think we're ready to go!

2023-05-15 08:55 UTC, dennisreimann commented
> I suppose if you have 5K invoices, and could only select 500, that might be a problem though... 

If there are none selected, everything will be exported.

> suggestion for even more clarity wrt "selected" filters

Implemented it …

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/09151658-07cf-4636-a61e-8a1062c50025)

2023-05-15 17:31 UTC, dstrukt commented
> If there are none selected, everything will be exported.

Ahh, good to know, and something to consider with the mass action mock proposal, in its current form, in order to see the options at least 1 result needs to be selected.

> Implemented it …

Looks great in the screenshot! will review this evening .. what do you think of it?

2023-05-15 17:59 UTC, dennisreimann commented
> what do you think of it?

I think it gives even more overview, so good suggestion and full ACK 👌

2023-05-15 22:17 UTC, dstrukt approved these changes
LGTM!

Only change we could consider the new filtering update @dennisreimann is `All Status` `All Plugins` `All Time` as the default states, but I realize this adds more horizontal space .. so could be something we could address when we tackle Export / Actions stuff, but very minor.

2023-05-16 05:22 UTC, dennisreimann commented on BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
> +                    <span>Plugin</span>
```suggestion
                    <span>All Plugins</span>
```

2023-05-16 05:22 UTC, dennisreimann commented on BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
> +                <span>Status</span>
```suggestion
                <span>All Status</span>
```

2023-05-16 05:22 UTC, dennisreimann commented on BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
> +                <span>Time</span>
```suggestion
                <span>All Time</span>
```

2023-05-16 05:25 UTC, dennisreimann commented
> All Status All Plugins All Time as the default states

Applied it :)

2023-05-17 00:34 UTC, dstrukt commented
LGTM!

2023-05-19 01:42 UTC, merged