Forms: Add multiline input
btcpayserver/btcpayserver pull request #4942
Opened 2023-05-02 09:29 UTC by dennisreimann

Up to now we don't have a way to accept multiline input values via the forms. The input type text strips the newlines and replaces them with whitespace, so there wasn't even a way to solve #4941 correctly.

This add the textarea form provider and modifies the PosData partial, so that it properly displays multiline values.

Closes #4941.

2023-05-02 09:29 UTC, dennisreimann commented on BTCPayServer/Views/Shared/PosData.cshtml
> +                        @Safe.Raw(Regex.Replace(str.Trim(), @"(\r\n)|\n|\r", "<br/>"))
@NicolasDorier OK like this?

2023-05-02 10:01 UTC, learntheropes commented on BTCPayServer/Views/Shared/PosData.cshtml
> +                        @Safe.Raw(Regex.Replace(str.Trim(), @"(\r\n)|\n|\r", "<br/>"))
Guys, sorry for asking, but I don't understand anything of this programming language.

I just want to make sure that the replacement happens only in the rendered field and does not manipulate the data actually stored in the metadata property, which are correct at the moment.

If we recall the invoice, we should find the same text we have added when we created it.

2023-05-02 10:24 UTC, Kukks requested changes

2023-05-02 10:24 UTC, Kukks commented on BTCPayServer/Views/Shared/PosData.cshtml
> +                        @Safe.Raw(Regex.Replace(str.Trim(), @"(\r\n)|\n|\r", "<br/>"))
This seems excessively complicated, I think we should do as suggested with `white-space: pre-wrap;` styling

2023-05-02 10:32 UTC, dennisreimann commented on BTCPayServer/Views/Shared/PosData.cshtml
> +                        @Safe.Raw(Regex.Replace(str.Trim(), @"(\r\n)|\n|\r", "<br/>"))
Done in [5501b91](https://github.com/btcpayserver/btcpayserver/pull/4942/commits/5501b916897bfd63489260979d01cae558ba003e).

2023-05-04 20:18 UTC, dstrukt approved these changes
LGTM!

At least visually / functionally.

2023-05-10 09:11 UTC, dennisreimann commented on BTCPayServer/Views/Shared/Forms/TextareaElement.cshtml
> +    <textarea id="@Model.Name" type="@Model.Type" class="form-control @(errors is null ? "" : "is-invalid")"
```suggestion
    <textarea id="@Model.Name" class="form-control @(errors is null ? "" : "is-invalid")"
```

2023-05-10 09:13 UTC, dennisreimann commented
@Kukks Your feedback has been addressed. Can we merge it so that I can use the textarea in #4695?

2023-05-10 09:14 UTC, Kukks approved these changes

2023-05-10 09:14 UTC, merged