Add What's New in v1.10.0
btcpayserver/btcpayserver pull request #4992
Opened 2023-05-22 17:06 UTC by dennisreimann

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/60448b0c-9a19-4ee1-88ce-fa0fa26dcc5c)

2023-05-24 14:12 UTC, Bas02 requested changes
Couldn't figure out what you tried to say with what i took out.

2023-05-24 14:12 UTC, Bas02 commented on BTCPayServer/Views/UIStores/Dashboard.cshtml
> +                <p class="mb-2">We've added some more options for refunds and an editor for creating custom forms. A propos custom: You can now also define your own roles with customized access to st
```suggestion
                <p class="mb-2">We've added some more options for refunds and an editor for creating custom forms. You can now also define your own roles with customized access to store features.</p>
```

2023-05-25 21:00 UTC, dstrukt commented
`A propos custom` is less common in the states, usually see `with regard to`, or `speaking of...`

Might consider dropping, or editing, but just my 2sats, otherwise, looks great!

2023-05-25 22:27 UTC, dennisreimann commented
Yup, @Bas02 already took that out, good to have two second pairs of eyes on it 😁

2023-05-26 12:24 UTC, pavlenex approved these changes

2023-05-29 07:08 UTC, merged