Quality of life improvements to payout processors
btcpayserver/btcpayserver pull request #5135
Opened 2023-06-30 09:12 UTC by Kukks

* Allows more fleixble intervals for payout processing from 10-60 mins to 1min-24hours(requested by users)
* Cancel ln payotus that expired (bolt11)
* Allow cancelling of ln payotus that have failed to be paid after x attempts
* Allow conifguring a threshold for when to process on-chain payouts (reduces fees)

2023-07-11 04:41 UTC, NicolasDorier approved these changes

2023-07-11 04:42 UTC, NicolasDorier requested changes
Need to protect `failedPayoutCounter` with lock.

2023-07-11 04:43 UTC, NicolasDorier commented
I made a small commit which I think simplify the code. Feel free to revert.
Also I believe you need to lock the dictionary or use a ConcurrentDictionarry.

2023-07-12 00:19 UTC, NicolasDorier commented
You need to add a test for `ProcessNewPayoutsInstantly`.

2023-07-20 08:15 UTC, Kukks commented on BTCPayServer.Tests/GreenfieldAPITests.cs
> +            //create a payout that should not be processed straight away
```suggestion
            //create a payout that should not be processed straight away due to threshold
```

2023-07-20 09:49 UTC, NicolasDorier commented on BTCPayServer/PayoutProcessors/BaseAutomatedPayoutProcessor.cs
> +            await Task.Delay(blob.Interval, CancellationTokenSource.CreateLinkedTokenSource(CancellationToken, _timerCTs.Token).Token);
I believe you need to dispose `CreateLinkedTokenSource`.

2023-07-20 09:50 UTC, NicolasDorier commented on BTCPayServer/PayoutProcessors/BaseAutomatedPayoutProcessor.cs
> +        _timerCTs?.Cancel();
There is probably a concurrency issue here if two SkipInterval get called as same time

2023-07-20 09:53 UTC, Kukks commented on BTCPayServer/PayoutProcessors/BaseAutomatedPayoutProcessor.cs
> +        _timerCTs?.Cancel();
added a lock

2023-07-20 09:54 UTC, Kukks commented on BTCPayServer/PayoutProcessors/BaseAutomatedPayoutProcessor.cs
> +            await Task.Delay(blob.Interval, CancellationTokenSource.CreateLinkedTokenSource(CancellationToken, _timerCTs.Token).Token);
```suggestion
            var cts= CancellationTokenSource.CreateLinkedTokenSource(CancellationToken, _timerCTs.Token);
            await Task.Delay(blob.Interval, cts.Token);
            cts.Dispose();
```

2023-07-20 13:05 UTC, merged