Custom Forms: Allow HTML in labels and help text
btcpayserver/btcpayserver pull request #5136
Opened 2023-06-30 10:30 UTC by dennisreimann

We partially allowed it already for the help texts — up for discussion if we want to support this. Fixes #5003.

2023-06-30 10:36 UTC, Kukks commented
Maybe it's ok if we sanitize it?

2023-06-30 16:13 UTC, dennisreimann commented
> Maybe it's ok if we sanitize it?

THe `Safe.Raw` method sanitizes the output — or do you mean we should restrict it further and only allow some formatting and links?

2023-07-03 06:53 UTC, Kukks approved these changes

2023-07-10 00:16 UTC, NicolasDorier commented
the use of `v-html`  in VueJS for user input is a XSS vector. You can try it by adding `<script>alert("lol")</script>` in your label.

If you really want to do this, you need to run the sanitizer before affecting the property `model.Label = Safe.Raw(app.Label);` .

2023-07-10 00:17 UTC, NicolasDorier requested changes
Need sanitize the `v-html` bound properties

2023-07-10 00:32 UTC, NicolasDorier commented on BTCPayServer/Views/Shared/Forms/FieldSetElement.cshtml
> +        <legend class="h3 mt-4 mb-3">@Safe.Raw(Model.Label)</legend>
is this rendered in a form with VueJS? if so, you need to add `v-pre` to avoid injection.

2023-07-10 06:29 UTC, dennisreimann commented on BTCPayServer/Views/Shared/Forms/FieldSetElement.cshtml
> +        <legend class="h3 mt-4 mb-3">@Safe.Raw(Model.Label)</legend>
The form page that includes this doesn't use Vue.

2023-07-10 14:21 UTC, dennisreimann commented
> Need sanitize the v-html bound properties

Added [vue-sanitize-directive](https://github.com/leopiccionia/vue-sanitize-directive/) in [28cb01f](https://github.com/btcpayserver/btcpayserver/pull/5136/commits/28cb01f788c320190c3b04d06e0432507432028e). Guess we can reuse that elsewhere too.

2023-07-11 04:02 UTC, merged

2023-07-11 04:34 UTC, NicolasDorier commented
@dennisreimann will need doc update on https://docs.btcpayserver.org/AdvancedForms/ indicating helptext can be html.

2023-07-11 08:37 UTC, dennisreimann commented
@NicolasDorier Added a PR for the doc update.