Add reporting feature
btcpayserver/btcpayserver pull request #5155
Opened 2023-07-05 11:40 UTC by NicolasDorier

2023-07-05 12:25 UTC, Kukks commented on BTCPayServer.Client/BTCPayServer.Client.csproj
> +      <PackageReference Include="NodaTime" Version="3.1.9" />
Do we really need a whole new library on the client library level?

2023-07-05 12:25 UTC, Kukks commented on BTCPayServer/wwwroot/js/store-reports.js
> +$(function () {
reduce jquery usage:
```suggestion
document.addEventListener("DOMContentLoaded", () => {
```

2023-07-05 12:25 UTC, Kukks commented on BTCPayServer/wwwroot/js/store-reports.js
> +    $(".flatdtpicker").on("input", function () {
```suggestion
    document.querySelectorAll('.flatdtpicker').forEach(el => el.addEventListener("input", ()=>{
```

2023-07-05 12:25 UTC, Kukks commented on BTCPayServer/wwwroot/js/store-reports.js
> +        var to = $("#toDate").val();
```suggestion
        const to = document.querySelector("#toDate").value
```

2023-07-05 13:38 UTC, NicolasDorier commented
What is the problem with jquery?

2023-07-10 07:30 UTC, NicolasDorier commented
@dstrukt @dennisreimann I just added a commit to generate fake data in the reporting.

* When chosing a new view, I believe it is better to not show the raw data upfront unlike I am doing now. Reasons are:
  *  For 10000 rows, the UI seems to be slow to render for some reason. (Probably something that can be fixed)
  * Few people would want to see the raw data, in general I expect they are more interested in the aggregates.
  * The raw data having many column, it can't look nice

2023-07-11 15:35 UTC, dennisreimann commented
> UX: This add a new page at store level: Reporting

I think we could either put it up between Dashboard and Settings or at the end of the Payments section. Regardless of where we position it, we need a new icon for this feature :) @dstrukt

2023-07-11 16:41 UTC, dennisreimann commented
Introduced a fixed header and made the tables auto-width, so that thgey read a bit better. Will experiment with sticky table header rows next.

![Peek 2023-07-11 18-36](https://github.com/btcpayserver/btcpayserver/assets/886/39a6d06f-6bd0-48da-8ebf-479d93647f90)

2023-07-12 01:40 UTC, NicolasDorier commented
The make me more happy

2023-07-12 08:50 UTC, dennisreimann commented on BTCPayServer/Views/UIReports/StoreReports.cshtml
> +	Csp.AllowUnsafeHashes("javascript:void(0)");
What is this for?

2023-07-12 08:51 UTC, dennisreimann commented on BTCPayServer/wwwroot/js/datatable.js
> +        eval('function filter() {return ' + filterStrings.join(' && ') + ';}');
Yikes 😬

2023-07-12 09:02 UTC, NicolasDorier commented on BTCPayServer/wwwroot/js/datatable.js
> +        eval('function filter() {return ' + filterStrings.join(' && ') + ';}');
The basic idea is that the report provider can decide to filter rows before building the table.
I use it for the summary of lightning addresses payments. Without this, the datatable would show a row with empty ligthning address if none are present. Instead, I want this line to be gone.

2023-07-12 09:03 UTC, NicolasDorier commented on BTCPayServer/wwwroot/js/datatable.js
> +        eval('function filter() {return ' + filterStrings.join(' && ') + ';}');
Note that the conversion from tabular data to a representation bindable to VueJS for summary tables is done JS side.
I am unsure this is good idea, I believe we could just do that C# side.

2023-07-12 09:05 UTC, NicolasDorier commented on BTCPayServer/Views/UIReports/StoreReports.cshtml
> +	Csp.AllowUnsafeHashes("javascript:void(0)");
Note that this trick doesn't work in safari...

2023-07-12 09:25 UTC, dennisreimann commented on BTCPayServer/Views/UIReports/StoreReports.cshtml
> +	Csp.AllowUnsafeHashes("javascript:void(0)");
Removed and fixed in [f07b85a](https://github.com/btcpayserver/btcpayserver/pull/5155/commits/f07b85a9defcbe19f07673e7227b0b1638822ab0).

2023-07-17 21:01 UTC, dstrukt requested changes
# Still Reviewing & Updating Mocks

Few initial thoughts after reviewing, some might be out of scope, others are minor nits and suggestions:

Happy to make some of these changes post-merge as well, if it makes more sense.

## Search

- [ ] Do we want the ability to search? e.g. something like this:
- Calendar icons to the left of the inputs for the date selection could be nice too
<img width="601" alt="Screen Shot 2023-07-17 at 3 02 49 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/87f23d2c-5a23-4635-97a7-ddb5299e5b19">


## Balance Tables

- [ ] Any reason we don't want to conserve a bit of space by doing two columns like so. Am I missing something? Might be nice to consolidate in the future, but for the time being.
<img width="1439" alt="Screen Shot 2023-07-17 at 1 49 54 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/77821c28-6522-47ee-84f0-1f52ba8ed2fe">

### Payments
- [ ] Could be improved with updated labels:
<img width="930" alt="Screen Shot 2023-07-17 at 2 29 22 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/13cb1d98-b9d0-4c0c-be5f-3c1ec1b443f7">

- [ ] Lightning Address label updates
- Makes me think some of the other Amount labels could be Balance instead...hmm
<img width="587" alt="Screen Shot 2023-07-17 at 3 51 15 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/200e0d52-add2-41e2-bf05-35de0aa3086d">


### On-Chain
- [ ] Could be improved with updating the label and pushing the header into the table key value for the on-chain view:
- Context: I found the Balance Change aspect of the On-Chain table a little confusing... as the test data amounts were mostly negative values?
<img width="504" alt="Screen Shot 2023-07-17 at 3 00 53 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/13684986-b565-4408-aaf9-55c7063311ae">

- Still exploring ways of consolidating the tables for more space and ease of parsing the data, just sharing, might be a later follow up if any of the explorations make sense:
<img width="699" alt="Screen Shot 2023-07-17 at 4 18 18 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/3d92ea7b-4922-4ff1-a106-2a2528915142">

e.g: On-Chain/Lightning, doesn't hold up as well, but interesting nonetheless:
<img width="883" alt="Screen Shot 2023-07-17 at 5 56 21 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/0b0de8de-ecdd-4ef0-a894-79cc0be989db">

works in a simple context as well:
<img width="672" alt="Screen Shot 2023-07-17 at 6 27 36 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/0d79f849-703b-4b43-8041-d33f098a330d">


## Raw Data
### Payments
- [ ] Is the date formatting messed up? `2023-07-05T01:42:41-06:00` 
<img width="196" alt="Screen Shot 2023-07-17 at 3 34 10 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/5678b8a2-5971-4db8-8d35-4e01e1b32cba">

### On-Chain
- [ ] Suggestions for improvements
- Unconfirmed would be a red `X` icon instead of the green checkmark
- Balance Change decrease would be `-1.06150021` and be colored red
<img width="904" alt="Screen Shot 2023-07-17 at 3 41 50 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/24fc349d-1909-413a-add4-15ae4939c554">



## Filter Dropdown

- [ ] Copy suggestion: `Items sold` -> `Products` or `Products Sold`? To keep it consistent with the POS label
- [ ] Copy suggestion: `On-Chain Wallets` -> `On-Chain` or `Wallets`? On second thought, might be fine with the original..
<img width="177" alt="Screen Shot 2023-07-17 at 1 37 15 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/d1c79821-f8d3-4988-a5d8-7a16f8af8648">

## General

- [ ] I noticed there's an additional scrollbar at the bottom of the page, can we remove this? I think the table specific scrollbar makes sense, given the width of it's contents.
<img width="1792" alt="Screen Shot 2023-07-17 at 1 34 33 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/73ae2c68-7de8-4adc-b2a1-885dbdbedf25">


- [ ] The main CTA could arguably just be `Export` cleaner, as the CSV bit isn't necessary imo
<img width="320" alt="Screen Shot 2023-07-17 at 2 14 43 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/cb4ed892-d76c-4b6e-922a-7e63ba5b5bb5">

## Really great work!

2023-07-18 04:10 UTC, NicolasDorier commented
About wallet balance confirmed/unconfirmed: I don't believe a bar make sense. In most case, unconfirmed will be ridiculously low compared to confirmed, so this doesn't add lot's of information.

For on-chain versus lightning, it might make more sense.

Also, I was thinking: Some tables are grouping on Invoice currency. I believe this is overkill, as most of the time, the invoice currency is the same.

Rather than grouping per currency, I will just make additional chart per currency?

2023-07-18 04:19 UTC, NicolasDorier commented
@dstrukt I want to add, the aggregated tables I am showing could potentially be replaced by any chart that make sense.

2023-07-18 10:17 UTC, Kukks commented on BTCPayServer/Controllers/UIReportsController.CheatMode.cs
> +            return rand.NextSingle() > 0.2 ? "USD" : TakeOne("JPY", "EUR", "CHF");
These hardcoded currencies are a very small subset

2023-07-18 10:18 UTC, Kukks commented on BTCPayServer/Services/Reporting/PaymentsReportProvider.cs
> +                if (paymentType.PaymentType == PaymentTypes.LightningLike || paymentType.PaymentType == PaymentTypes.LNURLPay)
use the payment type tostring  instead of hardcoding

2023-07-18 10:20 UTC, Kukks requested changes
Missing api docs and tests! 😂

2023-07-18 12:32 UTC, NicolasDorier commented on BTCPayServer/Services/Reporting/PaymentsReportProvider.cs
> +                if (paymentType.PaymentType == PaymentTypes.LightningLike || paymentType.PaymentType == PaymentTypes.LNURLPay)
I did this because because the difference between lightning versus LNURL doesn't matter at all for merchants.

They want the consolidated view of how much they received on lightning, they don't care whether it come from LNURL or not.

2023-07-18 15:43 UTC, dstrukt commented
> About wallet balance confirmed/unconfirmed: I don't believe a bar make sense. In most case, unconfirmed will be ridiculously low compared to confirmed, so this doesn't add lot's of information.

Tend to agree, it's a bit much for what would only be a pending state at best, and rarely visible for instances with low volume.

> For on-chain versus lightning, it might make more sense.

Also agree, but wasn't intended to be included in this PR, just a quick visual exploration to see if it made sense / worth the time to implement!

> Also, I was thinking: Some tables are grouping on Invoice currency. I believe this is overkill, as most of the time, the invoice currency is the same.

> Rather than grouping per currency, I will just make additional chart per currency?

That could work, I do appreciate the flexibility/clarity of the current implementation, but I think I'd have to see it.

2023-07-19 10:28 UTC, pavlenex commented
@NicolasDorier Any chance fake data can generate items for POS? I think this is one of the highest-requested reports, so would be good to test it out.

2023-07-19 21:19 UTC, dstrukt commented
ACK to fake data, if possible! Was my biggest challenge in providing more feedback as well.

2023-07-20 00:33 UTC, NicolasDorier commented
@dstrukt @pavlenex done

2023-07-21 19:56 UTC, pavlenex commented
@NicolasDorier I've tested draft a bit, so far so good.
Question, is export always meant to give raw data, not data according to tables?
When do you plan to add fitlers and groups?
When do you think you'll be able to get this one out of draft?

We're thinking of RC for Monday, but unsure how much you have to do on this one.

2023-07-21 23:26 UTC, dstrukt approved these changes
Overall, looks really solid, there's some more finessing of labels and UI I'd like to do, but I don't want to hold up the release to make these minor tweaks.

Especially if our RC deadline is monday, this is something @dennisreimann and I could easily do a follow up PR to address.

2023-07-24 00:24 UTC, NicolasDorier commented
it's bit tight, so let's merge this one and incrementally improve on dstrukt feedback

2023-07-24 00:24 UTC, merged

2023-07-24 00:29 UTC, NicolasDorier commented
> is export always meant to give raw data, not data according to tables?`

@pavlenex  I don't know what you mean, but the CSV export is exporting the raw data, because all other structures can be trivially created again through Excel. The idea is to provide just enough feature to be useful for simple cases, delegating complex cases to Excel.

Filtering for now is only on date, I believe allowing some simple client side filters on the raw data.
We can do that in minor release or major release later.

About Grouping: The summary tables that you see is grouping. If what you want is letting the user drag and drop components to make their own group, I wished to do that but the existing open source components for pivot table just sucks and aren't maintained anymore.

2023-07-24 18:50 UTC, dstrukt commented
> it's bit tight, so let's merge this one and incrementally improve on dstrukt feedback

Sounds good - will make an issue with some of the remaining items post-release. Great work!

2023-08-01 21:21 UTC, JamesMessick1965 commented
Good