Refactor logic for calculating due amount of invoices
btcpayserver/btcpayserver pull request #5174
Opened 2023-07-13 13:32 UTC by NicolasDorier

The logic to calculate if an invoice is overpaid or not, and how much a payment method still need to pay was overly complicated.

This refactor introduce two concept: Gross amounts and Net amounts.

* For the exact amount of the payment, you can use "Gross Payment Amount". This term is widely used to describe the total or overall amount of money transferred before any deductions or fees are taken into account.

* For the amount of the payment that goes into paying the amount (the exact amount minus the fee), you could use "Net Payment Amount". This term usually refers to the amount of money actually received after all deductions or fees have been subtracted from the gross amount.

2023-07-14 08:29 UTC, Kukks requested changes
I appreciate the direct decimal usage instead of Money.  Makes code simpler to read. 

In general this change makes everything nicer, except for possible major bugs if you forget to call UpdateTotals in a sensitive location. 

I would suggest to build calls to it when loading, setting the invoice entity, when updating, payments, etc.


I'm also worried on plugins probably catastrophically failing on loading and crashing btcpay.

2023-07-14 08:29 UTC, Kukks commented on BTCPayServer.Tests/FastTests.cs
> +            var entity = new InvoiceEntity();
can we set a currency to entity to make things clearer

2023-07-15 02:58 UTC, NicolasDorier commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +            entity.UpdateTotals();
what do you mean "Update totals with the logs". This is the `ToEntity`. Basically, we call the `UpdateTotals` after building the entity from the database object.

2023-07-15 03:01 UTC, NicolasDorier commented
We shouldn't be concerned to break plugins. As all plugins access all BTCPay Server classes, we can't just freeze everything.

That said, before the major release, we'll need to try to load all the plugins and see what explode.

2023-07-15 03:05 UTC, NicolasDorier commented
> , except for possible major bugs if you forget to call UpdateTotals in a sensitive location.

Yeah actually tests caught those problems. I think it should be OK as we never really modify `InvoiceEntity`, but yeah this is a shotgun.

2023-07-17 03:14 UTC, NicolasDorier commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +            entity.UpdateTotals();
Actually, it doesn't work. Because we need to set the payments via `ToEntity` before calling UpdateTotals.
In this particular case it works, because there is no payments.

I'll see what I can do to avoid shotguns

2023-07-18 09:32 UTC, Kukks commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +            entity.UpdateTotals();
Ah, sorry, I misread the method name it was listed under

2023-07-18 12:30 UTC, NicolasDorier commented on BTCPayServer/Services/Invoices/InvoiceRepository.cs
> +            entity.UpdateTotals();
I removed this `Clone` method completely, we actually don't need it.

2023-07-19 09:47 UTC, merged

2023-07-23 06:15 UTC, siwatanejo commented
> Imagine that you need to pay exactly 0.123456789 BTC (9 decimals) for an invoice given the rate.

Sounds like this should have been the root cause to be fixed? If that is the amount to pay, BtcPayServer should round to the 8th decimal, so show 0.12345679 to the user to pay?

Just my 2cents here, I'm not pretending to be more knowledgeable than you guys.