POS: Handle flexible price items in cart view
btcpayserver/btcpayserver pull request #5238
Opened 2023-08-07 20:46 UTC by dennisreimann

Allows to set prices for minimum and custom amount items and allows to add multiple of them to the cart. This keeps track of the individual items on a per price basis

Closes #5218. Fixes #5212.

![](https://user-images.githubusercontent.com/886/258312226-bbf7064c-38a5-403b-baee-01ea6b8adbd0.gif)

2023-08-08 21:04 UTC, Kukks requested changes

2023-08-08 21:04 UTC, Kukks commented on BTCPayServer/Services/Apps/AppService.cs
> -        public static bool TryParsePosCartItems(JObject? posData, [MaybeNullWhen(false)] out Dictionary<string, int> cartItems)
this will break some plugins, can you create an overload instead

2023-08-08 21:59 UTC, dstrukt commented
So we ultimately decided to support custom amounts?

2023-08-08 22:00 UTC, dstrukt approved these changes
tACK.

Going to do some more browser testing, as that seems to be the biggest issue we've had.

2023-08-08 22:30 UTC, dennisreimann commented on BTCPayServer/Services/Apps/AppService.cs
> -        public static bool TryParsePosCartItems(JObject? posData, [MaybeNullWhen(false)] out Dictionary<string, int> cartItems)
Re-added the original implementation and kept the new one as an addition that we now use internally.

2023-08-09 07:30 UTC, Kukks commented on BTCPayServer/Services/Apps/AppService.cs
> +        public static bool TryParsePosCartItems(JObject? posData, [MaybeNullWhen(false)] out List<PosCartItem> cartItems)
Let's do it later, but to reduce double code we can make `public static bool TryParsePosCartItems(JObject? posData, [MaybeNullWhen(false)] out Dictionary<string, int> cartItems)` use this method internally

2023-08-09 07:31 UTC, merged