Display wallet balance in default currency
btcpayserver/btcpayserver pull request #5281
Opened 2023-08-28 14:58 UTC by vbouzon

![image](https://github.com/btcpayserver/btcpayserver/assets/2089905/b9ae4145-91a8-4fc8-bfca-40afaae31ed5)

2023-08-28 19:46 UTC, dennisreimann requested changes

2023-08-28 19:46 UTC, dennisreimann commented on BTCPayServer/Components/WalletNav/Default.cshtml
> +            @String.Format("{0} {1} {2}",@Model.Balance, @Model.Network.CryptoCode, @Model.BalanceDefaultCurrency == null ? "" : "("+Model.BalanceDefaultCurrency+")")
You can leave the oroginal part as it was and add an if for the default currency. You can also inject the `DisplayFormatter` and use it's `DisplayFormatter.Currency` method to format the value (displayed with currency code, not with the symbol).

2023-08-28 19:46 UTC, dennisreimann commented on BTCPayServer/Components/WalletNav/WalletNav.cs
> +                    balanceDefaultCurrency = String.Format(_currencies.GetCurrencyProvider(defaultCurrency), "{0:N} {1}", Math.Round(((balance.Available ?? balance.Total).GetValue() * rate.BidAsk.Bid
The formatting can be removed here then and you can simply pass the default currency amount to the view.

2023-08-29 05:25 UTC, vbouzon commented on BTCPayServer/Components/WalletNav/Default.cshtml
> +            @String.Format("{0} {1} {2}",@Model.Balance, @Model.Network.CryptoCode, @Model.BalanceDefaultCurrency == null ? "" : "("+Model.BalanceDefaultCurrency+")")
Thanks for the tips. I updated and I also took advantage to use the formatter for the original part. Here the result

**Before**
![Screenshot 2023-08-29 071756](https://github.com/btcpayserver/btcpayserver/assets/2089905/3e8a971c-27c5-46fe-8c2a-ef0a67511da0)

**After**
![Screenshot 2023-08-29 071718](https://github.com/btcpayserver/btcpayserver/assets/2089905/b0a8b692-3e19-4d22-8421-5a9c0b0a6b90)
![Screenshot 2023-08-29 071648](https://github.com/btcpayserver/btcpayserver/assets/2089905/edbfd566-eb1d-4702-ab06-e555f6497b96)

2023-08-29 05:26 UTC, vbouzon commented on BTCPayServer/Components/WalletNav/WalletNav.cs
> +                    balanceDefaultCurrency = String.Format(_currencies.GetCurrencyProvider(defaultCurrency), "{0:N} {1}", Math.Round(((balance.Available ?? balance.Total).GetValue() * rate.BidAsk.Bid
It should be okay now.

2023-08-29 05:32 UTC, dennisreimann commented on BTCPayServer/Components/WalletNav/Default.cshtml
> +
```suggestion
            @DisplayFormatter.Currency(Model.Balance, @Model.Network.CryptoCode)
            @if (!string.IsNullOrEmpty(Model.BalanceDefaultCurrency))
            {
                <span>(@DisplayFormatter.Currency(Model.BalanceDefaultCurrency.Value, Model.DefaultCurrency))</span>
            }
```

2023-08-29 05:32 UTC, dennisreimann commented on BTCPayServer/Components/WalletNav/WalletNav.cs
> +                var balance = await wallet.GetBalance(derivation?.AccountDerivation);
It is unnecessary to get the balance twice, can you combine this with the `balanceString` above?

2023-08-30 14:34 UTC, dennisreimann approved these changes

2023-08-30 16:56 UTC, dstrukt approved these changes
tACK - LGTM - Nice work!

2023-09-01 06:29 UTC, merged

2023-09-21 20:12 UTC, naskovasilev86 reviewed
fail: Microsoft.AspNetCore.Server.Kestrel: Connection id "0HMTLA4GB8L4I", Request id "0HMTLA4GB8L4I:00000002": An unhandled exception was thrown by the application.
System.Net.Http.HttpRequestException: Response status code does not indicate success: 429 (Too Many Requests).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at BTCPayServer.Services.Rates.ExchangeRateHostRateProvider.GetRatesAsync(CancellationToken cancellationToken) in /source/BTCPayServer.Rating/Providers/ExchangeRateHostRateProvider.cs:line 23
   at BTCPayServer.Components.WalletNav.WalletNav.InvokeAsync(WalletId walletId) in /source/BTCPayServer/Components/WalletNav/WalletNav.cs:line 82
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, Object component, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCoreGeneratedDocument.Views_UIWallets__Nav.__Generated__WalletNavViewComponentTagHelper.ProcessAsync(TagHelperContext __context, TagHelperOutput __output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_UIWallets__Nav.ExecuteAsync() in /source/BTCPayServer/Views/UIWallets/_Nav.cshtml:line 10
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.RenderPartialViewAsync(TextWriter writer, Object model, IView view)
   at Microsoft.AspNetCore.Mvc.TagHelpers.PartialTagHelper.ProcessAsync(TagHelperContext context, TagHelperOutput output)
   at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
   at AspNetCoreGeneratedDocument.Views_Shared__NavLayout.ExecuteAsync() in /source/BTCPayServer/Views/Shared/_NavLayout.cshtml:line 32
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|28_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.BTCPayMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/BTCpayMiddleware.cs:line 98
   at BTCPayServer.Hosting.GreenfieldMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/GreenfieldMiddleware.cs:line 50
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at BTCPayServer.Hosting.HeadersOverrideMiddleware.Invoke(HttpContext httpContext) in /source/BTCPayServer/Hosting/HeadersOverrideMiddleware.cs:line 30
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)