Plugins: Add hook for resolving Lightning Address
btcpayserver/btcpayserver pull request #5322
Opened 2023-09-13 16:34 UTC by dennisreimann

Allows plugins to provide Lightning Addresses, which aren't provided on the store level already. If the LNM Address lookup in the core database fails, the plugin hook is invoked with the username portion, which can then resolve the LNURL-Pay request for the Lightning Address.

Using this, I can provide Lightning Addresses for LNbank wallets. The counterpart in LNbank looks like this:

```csharp
namespace BTCPayServer.Plugins.LNbank.Hooks;

public class ResolveLightningAddressHandler : IPluginHookFilter
{
    public string Hook { get; } = "resolve-lnurlp-request-for-lightning-address";

    private readonly WalletRepository _walletRepository;
    private readonly LinkGenerator _linkGenerator;

    public ResolveLightningAddressHandler(
        WalletRepository walletRepository,
        LinkGenerator linkGenerator)
    {
        _walletRepository = walletRepository;
        _linkGenerator = linkGenerator;
    }

    public async Task<object> Execute(object args)
    {
        var obj = (LightningAddressResolver)args;
        var username = obj.Username;
        var wallet = await _walletRepository.GetWallet(new WalletsQuery
        {
            LightningAddressIdentifier = new[] { username },
        });
        if (wallet == null) return obj;

        var httpContext = obj.HttpContext;
        var request = httpContext.Request;
        var metadata = new Dictionary<string, string>
        {
            ["text/identifier"] = $"{username}@{request.Host}"
        };
        var lnurlRequest = new LNURLPayRequest
        {
            Tag = "payRequest",
            CommentAllowed = 2000,
            Metadata = JsonConvert.SerializeObject(metadata.Select(kv => new[] { kv.Key, kv.Value })),
            Callback = new Uri(_linkGenerator.GetUriByAction(
                action: nameof(LnurlController.LnurlPay),
                controller: "Lnurl",
                values: new { walletId = wallet.WalletId }, request.Scheme, request.Host, request.PathBase) ?? string.Empty)
        };

        obj.ResolveLNURLPayRequest(lnurlRequest);

        return obj;
    }
}
```

2023-09-14 08:17 UTC, Kukks requested changes

2023-09-14 08:17 UTC, Kukks commented on BTCPayServer/Plugins/LightningAddresssResolver.cs
> +    public HttpContext HttpContext { get; }
I would exclude the HttpContext since you can almost always use the HttpContextAccessor

2023-09-14 09:13 UTC, dennisreimann commented on BTCPayServer/Plugins/LightningAddresssResolver.cs
> +    public HttpContext HttpContext { get; }
Updated in [cc89e23](https://github.com/btcpayserver/btcpayserver/pull/5322/commits/cc89e230dbfa5cd2f6f3390d57e04448d43f88b0)

2023-09-14 10:53 UTC, Kukks approved these changes

2023-09-14 10:53 UTC, merged

2023-09-20 09:02 UTC, Djritz04 approved these changes