Unify list views
btcpayserver/btcpayserver pull request #5399
Opened 2023-10-13 14:29 UTC by dennisreimann

Unifies the table display and most of the mass action functionality for:

- Invoices
- Payment Requests (no mass actions yet)
- Wallet Transactions
- Pull Payments (no mass actions yet)
- Payouts

Closes #3473.

2023-10-18 03:03 UTC, dstrukt commented
Is this ready for review?

2023-10-18 03:22 UTC, dennisreimann commented
> Is this ready for review?

Yes, curious to hear what ou think :)

2023-10-19 18:51 UTC, dstrukt requested changes
This looks fantastic, and the consistency updates are incredible!

# Still reviewing

Discussed a few things on the last design call, so documenting a few items

- [ ] Experiment with keeping the table headers fixed on scroll to keep the actions visible on long page scrolls

- [ ] As discussed, we should probably hide (mass) actions if there are no options available, in this case the `Cancelled` state for the Payouts

<img width="1042" alt="Screen Shot 2023-10-18 at 11 54 09 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/def180fa-a19f-48e6-b13e-ec22119c40fd">

## For discussion:

- Connecting the selection and the (mass) action is valuable and the direction to move, but  are the updated actions obviously enough in their current placement (top right of the table)?

2023-10-20 08:22 UTC, dennisreimann commented
Wow, the sticky header part was way trickier than expected, but got it working now :D

2023-10-26 09:53 UTC, dennisreimann commented on BTCPayServer/Controllers/UIInvoiceController.UI.cs
> +                return NotSupported("No invoice has been selected");
Pulled this up, because it can be applied to all mass actions.

2023-10-26 09:53 UTC, dennisreimann commented on BTCPayServer/Views/UIInvoice/ListInvoices.cshtml
> -        });
Removed this because we can leverage Bootstrap's `collapse` functionality. The row click got generalized into site.js

2023-10-27 08:46 UTC, Kukks approved these changes
I reviewed it as best as I could, but this touches everything everywhere. Maybe we need to develop reusable components to make this less of a chore in the future, especially because plugins will need the same mods to be in line

2023-10-29 18:42 UTC, dstrukt approved these changes
tACK, Chrome FF Desktop .. and mobile iOS Safari, works pretty well on mobile despite the sizing/scrolling

Think this is as far as we can push this at the moment functionally. I might make some aesthetic, alignment, etc.. changes in the future, but agree with @Kukks, would be great to make a reuseable component so we can keep this functionality consistent where it make sense.

Great job!

2023-10-29 18:52 UTC, dennisreimann commented
I find it hard to see how we can turn it into a reusable component while dealing with the complexity/diversity of the content we want to display.

The changes this PR introduces unified the display and functionality with just a few custom `mass-action` table classes, which is about as lean as it gets. I don't see how we can abstract this without basically adding components for tables/rows/cells, which would simply preapply those classes. Imho the added complexity wouldn't yield much benefit.

2023-11-02 07:12 UTC, merged