Migrate to OpenAPI 3.1
btcpayserver/btcpayserver pull request #5400
Opened 2023-10-13 20:27 UTC by ai-oleynikov

This PR updates OpenAPI version from 3.0 to 3.1 in accordance with this guide: https://www.openapis.org/blog/2021/02/16/migrating-from-openapi-3-0-to-3-1-0

The only changes I made are:
- deletion of `"nullable": false` as this keyword is now deprecated, and nulls are rejected by default anyway
- replacement of `"type": "<some-type>", "nullable": true` with `"type": ["<some-type>", "null"]`
- replacement of `"minimum": 0, "exclusiveMinimum": true` with `"exclusiveMinimum": 0`
- replacement of `"example"` with `"examples"` keyword inside `Schema Objects`

2023-10-13 20:34 UTC, ai-oleynikov commented on BTCPayServer/wwwroot/swagger/v1/swagger.template.apps.json
> +                        "description": "Crowdfunding app data",
This one change is unrelated to the migration to OpenAPI 3.1. I just couldn't ignore it. "Crowdfunding app" sounds more natural. Feel free to revert this change if you disagree though.

2023-10-19 10:15 UTC, dennisreimann approved these changes
LGTM

2023-10-27 08:47 UTC, Kukks commented
The swagger schema test fails. See CheckSwaggerIsConformToSchema

2023-10-27 08:47 UTC, Kukks requested changes
The swagger schema test fails. Please check CheckSwaggerIsConformToSchema

2023-10-27 10:56 UTC, dennisreimann commented
It looks like the Newtonsoft `JSchema` package has problems parsing th OpenAPI 3.1 spec. Updated the lib and tried [various approaches](https://www.newtonsoft.com/jsonschema/help/html/LoadingSchemas.htm), but it fails with `Error when resolving schema reference '#/$defs/info'. Path 'properties.info', line 11, position 13`, which one can also replicate with their [JSON Schema Validator](https://www.jsonschemavalidator.net/) (select the `openapi.json` from the dropdown).

2023-11-03 11:03 UTC, dennisreimann commented
Rebased and tried to make the schema validation work by removing the [`$id` attribute](https://json-schema.org/understanding-json-schema/structuring#dollarid), which prevented that the references worked in general. But now there is still an error with nested `$defs`: `Could not resolve schema reference '#/$defs/parameter/dependentSchemas/schema/$defs/styles-for-path'. Path '$defs.parameter.dependentSchemas.schema.allOf[1]'`

@ai-oleynikov Any idea how we can resolve this?

2023-11-21 09:16 UTC, dennisreimann commented
@ai-oleynikov Any idea how we can resolve this?

2023-12-20 13:25 UTC, pavlenex commented
ping @ai-oleynikov still interested in helping with this one, if so can you check ^

2023-12-20 15:20 UTC, ai-oleynikov commented
Sorry for my disappearance! I'll work on fixing this today and report back if I have any issues I can't resolve.

2023-12-21 01:39 UTC, ai-oleynikov commented
The problem seems to be that JSchema doesn't support the current version of the JSON Schema spec.

https://www.jsonschemavalidator.net/ says the following

> An online, interactive JSON Schema validator. Supports JSON Schema Draft 3, Draft 4, Draft 6, Draft 7 and Draft 2019-09.

Therefore. it can't parse JSON Schema 2020-12. The error messages @dennisreimann shared above indicate that JSchema is unable to resolve references containing $defs, likely due to the [changes](https://json-schema.org/draft/2020-12/release-notes#embedded-schemas-and-bundling) in the behavior of $defs introduced in JSON Schema 2020-12.

Unfortunately, the OpenAPI Initiative doesn't provide a JSON Schema for OpenAPI 3.1 using spec versions other than 2020-12. All their [schema files](https://github.com/OAI/OpenAPI-Specification/tree/gh-pages/oas/3.1/schema) are written using this version.

I'm not sure what can be done here, except replacing JSchema with another JSON Schema validator that supports the current version of the spec :thinking:

2023-12-27 23:55 UTC, ai-oleynikov commented
This package seems to support JSON Schema dratf 2020-12: https://www.nuget.org/packages/JsonSchema.Net

2024-12-10 10:06 UTC, closed without merging