NFC improvements
btcpayserver/btcpayserver pull request #5509
Opened 2023-11-24 15:01 UTC by dennisreimann

Moves most of the NFC code out of the LNURL component and on Vue app level, so that 

- it keeps the scanning active even on the result page, so that the native scanning functionality does not take over in case the card is held too long on the scanner. Closes #5507
- it can provide more prominent visual feedback on NFC operations. Closes #5508

Downside: I had to duplicate that code in V1 and V2, as the shared partial/component isn't used anymore. However, this can also be seen as a good thing moving forward, as it got rid of some plase where we were using a check f the componnet is used in V2 context.

![v1](https://github.com/btcpayserver/btcpayserver/assets/886/5fee1cf2-1cf3-4690-9b5a-dccb9fcb158a)

2023-11-24 15:07 UTC, Kukks commented
If we're going into this direction, please take a look at https://github.com/Kukks/btcpayserver/tree/ultra-nfc

2023-11-26 02:35 UTC, rockstardev commented
Great job all around @dennisreimann! Here are my observations, illustrated by a video:

[Video Link](https://github.com/btcpayserver/btcpayserver/assets/5191402/5688e7ea-dc08-4893-978b-cff29b493edb)

- The issue of navigating out of checkout when holding the NFC card over the device after payment completion is resolved and works great (#5507).
- The placement of the toast notification is good, but since it doesn't expire, it eventually obstructs the rest of the UI.
- On the first device with a smaller screen, as you can see in the video, I'm unable to turn off NFC, leaving me stuck with the message. Unfortunate.
- Even after successful payment, the "Paid out" message remains on the dialog, which detracts from the overall look.

To streamline this and move forward with the merge, my suggestion is to relocate the toast-container into CheckoutEnd.cstml. We can then display errors and successes within that area for Lightning. Also we use a regular div instead of a fixed or floating toast, which will shift the Scanning NFC button downwards. This should work well with all the large-screen devices we're currently using, ensuring visibility of any errors.

Post-AfroBitcoin, when we have more time, we should regroup to brainstorm and refine the UI/UX for this feature.

2023-11-26 02:36 UTC, rockstardev requested changes
Just changing error/success div from toast into regular div that shift Scanning NFC button down and I would merge this.

2023-11-26 03:10 UTC, rockstardev commented
Also, a question for @dennisreimann and @Kukks – when debugging locally on regtest, how do you handle it? 

When I connect to the internal lightning node, I only see the option to pay with LNURL, not Lightning. Additionally, I'm lacking NFC scanning functionality (I connect with browser on the POS terminal over an IP like 192.168.1.50).

2023-11-27 07:32 UTC, dstrukt approved these changes
Just wanted to poke around - everything looks great - agree with @rockstardev, would be nice to revisit in the future to refine a few things!

2023-11-30 09:17 UTC, merged