Allow users with CanViewPaymentRequests to view payment requests
btcpayserver/btcpayserver pull request #5551
Opened 2023-12-12 10:31 UTC by dennisreimann

I originally tried to reproduce #5549, which I couldn't, but came across this problem where a store user with role `Guest` wasn't able to access the list of payment requests, even though that item appears in the nav list. The `CanViewPaymentRequests` permission on th list action is correct, but access was prevented by the `CanModifyStoreSettings` policy requirement on the controller level, which is adjusted here.

2023-12-13 09:57 UTC, Kukks requested changes

2023-12-13 09:57 UTC, Kukks commented on BTCPayServer/Controllers/UIPaymentRequestController.cs
> +        [Authorize(Policy = Policies.CanModifyPaymentRequests, AuthenticationSchemes = AuthenticationSchemes.Cookie)]
No, AFAIK this should be anonymouse and users can cancel these?

2023-12-13 10:15 UTC, dennisreimann commented on BTCPayServer/Controllers/UIPaymentRequestController.cs
> +        [Authorize(Policy = Policies.CanModifyPaymentRequests, AuthenticationSchemes = AuthenticationSchemes.Cookie)]
I think you are right and this is the user facing cancellation, so it'd need to `[AllowAnonymous]`. This was broken before then, because it inherited the policy from the controller level, which I simply moved here. Will check and correct it.

2023-12-14 08:26 UTC, dennisreimann commented on BTCPayServer/Controllers/UIPaymentRequestController.cs
> +        [Authorize(Policy = Policies.CanModifyPaymentRequests, AuthenticationSchemes = AuthenticationSchemes.Cookie)]
Resolved in [1f11dae](https://github.com/btcpayserver/btcpayserver/pull/5551/commits/1f11dae33aa5ccd4f8580f06aaa9719652f0f763).

2023-12-14 10:16 UTC, Kukks approved these changes

2023-12-14 11:42 UTC, merged