Store Email Settings: Improve configuration
btcpayserver/btcpayserver pull request #5629
Opened 2023-12-28 16:52 UTC by dennisreimann

This works with the existing settings and provides better guidance about the different store email cases. Closes #5623.

## No Fallback

- Either the SMTP settyings on the server level are not configured or the "Disable stores from using the server's email settings as backup" policy is active. 
- Requires configuration of SMTP settings on the store level: No option for using the server fallback.

![no-fallback](https://github.com/btcpayserver/btcpayserver/assets/886/fc3c3902-6944-4db4-80dd-a11693e5c1bf)

## Fallback is present and used

- Toggle indicates the availability of providing custom SMTP settings for the store
- By default the server's SMTP settings will be used

![uses-fallback](https://github.com/btcpayserver/btcpayserver/assets/886/32d10026-55db-41a5-9108-27c7141147be)

## Fallback is present but custom settings are provided

![with-fallback-but-custom](https://github.com/btcpayserver/btcpayserver/assets/886/662db991-196b-4d2c-a0ea-d8a9cb6a6375)

2023-12-28 17:59 UTC, dennisreimann commented on BTCPayServer.Tests/SeleniumTests.cs
> +            s.Driver.ScrollTo(By.Id("Settings_Server"));
```suggestion
            s.Driver.ScrollTo(By.Id("QuickFillDropdownToggle"));
```

2024-01-06 20:54 UTC, dstrukt approved these changes
This is so much better!

I didn't run it through a rigorous technical review, but functionally it worked as expected.

Will be a nice quality of life improvement for admins - tACK!

2024-01-09 09:02 UTC, Kukks approved these changes

2024-01-11 19:08 UTC, dennisreimann commented
Feedback from design call: @pavlenex suggested to move (or mirror) the policy setting on the server SMTP setup view.

I think we should also invert the wording to make it "enable" instead of "disable" on the server level, as this makes it easier to think about it.

2024-01-15 14:06 UTC, dennisreimann commented
## Server policies 

![n1](https://github.com/btcpayserver/btcpayserver/assets/886/f2fd539c-eab7-49da-87b8-d33674e418a7)

## Store email settings

![n2](https://github.com/btcpayserver/btcpayserver/assets/886/5adb1abe-b727-4bc0-94a3-bca2dc4a9b5a)

2024-01-18 18:01 UTC, dstrukt commented
Few nits:

- [ ] Shouldn't this be under `Email Settings` instead of `Notification Settings` in the Server Policies?

Copy suggestion, but don't necessarily know if it's any better, but is more consistent with the custom messages..`Use the Server's SMTP settings across all stores to send emails. This can be customized at the store level.` cc @pavlenex 

Otherwise, tACK!

2024-01-18 18:05 UTC, dstrukt requested changes
Just flagging the above, this could be shipped as is!

2024-01-26 08:37 UTC, dennisreimann commented
As discussed yesterday. This is now ready to be merged. 

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/000d85d6-fa3f-47f5-9938-d0daaea2e6cc)

2024-01-26 09:28 UTC, merged