Payments Report: Add POS data columns
btcpayserver/btcpayserver pull request #5630
Opened 2023-12-29 07:13 UTC by dennisreimann

Extends the payments report data with subtotal, tip and discount amounts. This works for keypad and cart sales. Closes #5290.

![data](https://github.com/btcpayserver/btcpayserver/assets/886/f78445af-bec8-438f-8f6e-279a002d3427)

2023-12-30 19:47 UTC, dstrukt approved these changes
If I understand the scope of the PR, functional tACK!

2024-01-09 09:05 UTC, Kukks commented on BTCPayServer/Services/Reporting/PaymentsReportProvider.cs
>              values.Add(invoiceBlob.Currency);
```suggestion
            values.Add(currency);
```

2024-01-09 09:09 UTC, Kukks requested changes
I don't know how I feel about this, it's so specific to the POS that it would be a shame to pollute such a wide-scoped report. I would see if if is possible to create a dedicated report that extends this one.

2024-01-09 19:47 UTC, dstrukt commented
> I don't know how I feel about this, it's so specific to the POS that it would be a shame to pollute such a wide-scoped report. I would see if if is possible to create a dedicated report that extends this one.

That's valid. Makes future plug-in (tip splitting, podcast splits, whatever other stuff people come up..) more easily extendible, but can also see the case for simply including the core POS data breakdown here as well.

2024-02-02 10:59 UTC, pavlenex commented
> I don't know how I feel about this, it's so specific to the POS that it would be a shame to pollute such a wide-scoped report. I would see if if is possible to create a dedicated report that extends this one.

So you're suggesting we have a dedicated app report or a pos report where we could display data for the POS app in particular? I agree with you on that one if so, thinking about `refund` report we want to have, this probably shouldn't be in the main one as it's quite app-specific from what I understood.

2024-02-05 00:07 UTC, NicolasDorier commented
I believe that we should allow the ability to add or remove columns in the report page.
The backend just fetch all the data, and the front end hide/show columns based on user's preferences.

2024-02-05 06:30 UTC, pavlenex commented
@NicolasDorier Could we display all data including refunds & tips with that approach? I think that's quite sensible idea for this problem, and would allow people to customize things, we're getting a lot of complaints in general that people aren't getting info they used to from the reporting, I am still working on their specific feedback.

2024-02-06 21:00 UTC, dstrukt commented
cACK to showing/hiding columns as per @NicolasDorier's suggestions, seems like an elegant approach to customizing the view for the user's use case

cc @dennisreimann are we in a position to do this with tables? imagine it'll just be an additional bootstrap column with some kind of `+` button with a dropdown of potential items to add. conceptually it seems like it might work, but without actually looking at the view concretely (might do this evening and edit my post), it's hard to say

2024-06-26 14:26 UTC, dennisreimann commented on BTCPayServer/Services/Reporting/PaymentsReportProvider.cs
>                  new ("Rate", "amount")
```suggestion
                new ("Rate", "amount"),
```

2024-06-26 14:29 UTC, dennisreimann commented on BTCPayServer/Services/Reporting/PaymentsReportProvider.cs
> +                values.Add(currency);
```suggestion
                var currency = invoiceBlob.Currency;
                values.Add(currency);
```

2024-06-26 14:37 UTC, closed without merging