Admins can approve registered users
btcpayserver/btcpayserver pull request #5647
Opened 2024-01-05 10:17 UTC by dennisreimann

High-level changes:

- Introduces the `RequiresUserApproval` flags for the server policies
- Introduces the `RequiresApproval` and `Approved` flags for the user
- Introduces the `UserService.TryCanLogin` method for checking the various aspects of whether or not a user is allowed to sign in (approval, email confirmation, lock out state) and uses it consistently
- User list reflects the toggle states (approval, email confirmation, lock out) better and omits indicators in case a setting isn't required (e.g. don't show a user is approved when their approval wasn't required on account creation)
- Adds support for (un)approving via the Greenfield API
- Cleans up the account controller

Closes #5548.

## Policies

I made it so that the sub-settings for registration aren't displayed, if public registration isn't available.

![policies](https://github.com/btcpayserver/btcpayserver/assets/886/fb998a46-8aec-46a6-9152-3dc61f7b530d)

## Users List

Here the requirements for confirming the email address and approval only existed when `unapproved@btcpay.local` registered, so these indicators are only shown for that user.

![users](https://github.com/btcpayserver/btcpayserver/assets/886/37f615f1-d246-4e40-a6b6-42ef45f53c54)

## Unapproved user login

![unapproved](https://github.com/btcpayserver/btcpayserver/assets/886/a014a91c-9a7d-4b34-90eb-fe656b46d2af)

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer.Tests/BTCPayServerTester.cs
> +            // reset test server policies
This was made to ensure a consistent setup. It helps in case the individual tests do not (re)set the policies themselves or when the server policies were edited during development.

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer.Tests/SeleniumTester.cs
> +            // reset test server policies
This was made to ensure a consistent setup. It helps in case the individual tests do not (re)set the policies themselves or when the server policies were edited during development.

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (!UserService.TryCanLogin(user, out var message))
Added this in places where the basic checks were missing.

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (!UserService.TryCanLogin(user, out var message))
Added this in places where the basic checks were missing.

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer/Models/ServerViewModels/UsersViewModel.cs
> +            public bool? EmailConfirmed { get; set; }
Renamed `Verified` to `EmailConfirmed` to make it more precise.

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer/Services/PoliciesSettings.cs
> +        }
Inverted the property for the view, because it makes it easier to reason about from that perspective.

2024-01-05 10:27 UTC, dennisreimann commented on BTCPayServer/Services/PoliciesSettings.cs
> +        }
Inverted the property for the view, because it makes it easier to reason about from that perspective.

2024-01-05 20:18 UTC, dstrukt commented
Amazing - going to try to break it this evening!!

2024-01-09 09:12 UTC, Kukks requested changes
I haven't reviewed the entire thing yet but the first thing that comes to mind is:
Can we reuse the authorization policies we have in place instead of so much custom logic? 

* If the server has a policy for user approval, assign a role to the user "PendingApproval"
* Create a policy "CanLogin", that checks the user's roles

2024-01-11 07:04 UTC, NicolasDorier commented
code review ACK.

@Kukks there isn't actually lot's of custom logic. The only place that check for the property is actually  [APIKeysAuthenticationHandler.cs](https://github.com/btcpayserver/btcpayserver/pull/5647/files#diff-5a05a94dc966aa5c9f63431786c5e0cb4fad8b0c331d36515ab97ff4d663b408) for the API and the HTTP POST Login.

There is lots of code impacted mainly because there is a new Greenfield Route for this, and some UI changes, which can't really be better.

2024-01-11 07:07 UTC, NicolasDorier commented
@dennisreimann the greenfield API can be used through Basic auth rather than API, so you need to also `BasicAuthenticationHandler`

2024-01-11 07:12 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIAccountController.cs
> +                    if (policies.RequiresUserApproval)
If there is both `RequiresConfirmedEmail` and `RequiresUserApproval`, then the only message shown will be about user approval.

2024-01-11 07:19 UTC, NicolasDorier commented on BTCPayServer/Services/UserService.cs
> +        public static bool TryCanLogin(ApplicationUser? user, out string? error)
```suggestion
        public static bool TryCanLogin([NotNullWhenAttribute(true)] ApplicationUser? user, out string? error)
```

This way, if the method returns `true` you don't have to check `user` for null and can remove stuff like `user!`

2024-01-11 07:21 UTC, NicolasDorier commented on BTCPayServer/Services/UserService.cs
> +        public static bool TryCanLogin(ApplicationUser? user, out string? error)
Just a note for this method, I would prefer if you used a discriminated unions pattern via records rather than sending error back as a string, this way the caller can check what error is this without having to parse the error string.

That said, don't change it now this is fine.

2024-01-11 10:23 UTC, dennisreimann commented on BTCPayServer/Controllers/UIAccountController.cs
> +                    if (policies.RequiresUserApproval)
Fixed in 51df12d.

2024-01-11 10:55 UTC, dennisreimann commented
> the greenfield API can be used through Basic auth rather than API, so you need to also BasicAuthenticationHandler

Added in 0ac5e25.

2024-01-11 18:35 UTC, dennisreimann commented
Feedback from design call: We should have an additional email which informs the user about approval.

2024-01-12 16:37 UTC, dennisreimann commented
Now an email is sent on approval: "Your account has been approved and you can now [login here](#loginlink)".

2024-01-15 12:55 UTC, pavlenex commented
I've asked two third-party hosts who use custom roles to provide us more details on what they use so we can flash these out more precisely, will update here when I get a reply.

2024-01-15 16:27 UTC, dennisreimann commented
Added a notification for the admins, which leads to the user details view, where they can approve the new user.

![Bildschirmfoto vom 2024-01-15 17-09-46](https://github.com/btcpayserver/btcpayserver/assets/886/126b1446-d8ce-4471-90e4-0645d5be4712)

2024-01-16 06:40 UTC, dstrukt commented
> Added a notification for the admins, which leads to the user details view, where they can approve the new user.
> 
> We could use a new notification icon for that, @dstrukt
> 
> ![Bildschirmfoto vom 2024-01-15 17-09-46](https://private-user-images.githubusercontent.com/886/296813916-126b1446-d8ce-4471-90e4-0645d5be4712.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzNzY2MTQsIm5iZiI6MTcwNTM3NjMxNCwicGF0aCI6Ii84ODYvMjk2ODEzOTE2LTEyNmIxNDQ2LWQ4Y2UtNDQ3MS05MGU0LTA2NDVkNWJlNDcxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNlQwMzM4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODdlOTc0NjIwYWRkYWIyYmU0OTE0NWM0ZWYwNWMzMTRiOTJlMTY2NjBkY2Q2YTc1NzdiYWVjY2I2MjA2MzUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0_SwpXh9BQgG0z1iVKIBXOZZqpl8LDAcLL-CplDNFSY)

I think we could probably reuse the "Account" or profile icon (from the sidebar) for the time being.

2024-01-16 08:04 UTC, dennisreimann commented
Thought so too, but wanted to check this first, because the other notification [icons](https://design.btcpayserver.org/design/icons/) have a different style (rounded and colored).

2024-01-16 11:59 UTC, pavlenex commented
Upon testing this PR, I was a bit confused, since now we introduce three properties for users:

- Verified (Email verification successful)
- Approved (Approved by admin)
- Enabled (Active)

While I don't think they're confusing in terms of naming, the UI for approving and enabling users isn't unified. To approve the user you need to open user view, where as to enable them, you can do that from users list which leads to a bit of ambiguity of admins enabling users (since UX is in place), thinking they've approved them.

I don't have a solution on how this can be solved, but logging it so we can discuss it on a dev call.

2024-01-18 00:16 UTC, dstrukt commented
> Amazing - going to try to break it this evening!!
> 
> First thoughts are the various checkmarks/Xs.
> 
> Feels like the Enabled/Approved/Verified (think this is for the email verificiation IIRC) rows could all be consolidated into a Status column:
> 
> `Disabled` (red), `Awaiting Email Verification`(yellow), `Pending Admin Approval`(yellow), or `Active` (green - for enabled) .. The middle 2 could be wordsmithed a bit, but you get the idea.
> 
> Obviously outside of the scope of this PR, but wanted to float the idea while things are in flux. Especially as my brain starts to tune out when I see a tic-tac-toe board with more than 3+ users 😂

@pavlenex To address your concern, still think consolidation of ideas as just the Status of a user makes the most sense, imo.

A user is either `Pending Approval`, `Pending Email Verification`, `Disabled`, or `Active` (passed 1 of the first 2 stages).

2024-01-18 14:14 UTC, dennisreimann commented
![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/98c9d809-3a1d-4587-bdb7-c3aba0317498)

2024-01-18 18:16 UTC, dstrukt commented
Love it - can parse the state of the user and then make a determinate action! Are we missing the `Reject` functionality as well in the ss above though? 

Was great before, but with the latest changes, will give it a final proper review this evening!

Last thought, in the future, we'll probably want to distinguish the style of a status vs. a label vs. a tag, etc.. a bit more so they don't all appear so similar - noticed it more as we clean up some of the views.

2024-01-19 22:16 UTC, dstrukt commented
> > are we missing the Reject functionality as well in the ss above though?
> 
> I think that could be simply the "Remove", right?

Ahh true, valid point!

2024-01-19 22:16 UTC, dstrukt approved these changes
All the latest changes look great - functional tACK!

2024-01-20 14:38 UTC, pavlenex reviewed
UX-wise these improvements are amazing, much better than I hoped, and something that can only be experienced through testing.

It seems there's no distinction between disapproved and disabled UX wise, which I think is good, but if someone was to create a plugin that would now allow users who haven't paid an invoice to log in, which state should be used in that case, disapproved or disabled or even technically it doesn't really make a big difference?

2024-01-20 15:00 UTC, dennisreimann commented
> if someone was to create a plugin that would now allow users who haven't paid an invoice to log in, which state should be used in that case, disapproved or disabled or even technically it doesn't really make a big difference?

Technically it doesn't make much difference for the end user, because they won't be able to log in. The wording for the failure messages is different though (need approval vs. locked out).

But from the admin perspective there is a hierarchy: If the approval policy is active, users need approval before they can even be disabled. I think it makes sense that way and the workflow for the use case you described would be, that an admin would first need to approve a user and the user would then need to pay the invoice to be enabled — granted the plugin takes care of setting the initial user state to disabled until an invoice is paid.

2024-01-20 21:02 UTC, dstrukt commented
Agreed, good way to frame the status.

Additional thought I had while reviewing this, and I suppose it's a bit of scope, but could use more discussion in a design call, is the user `Type`. It could arguably also be its own column and more explicitly defined, e.g. currently we have `Server Admin` OR no label. It could also be helpful for the sake of ordering, and/if we introduce other Server User types .. `Ambassador`, `Maintainer`, etc..

2024-01-22 20:28 UTC, dstrukt commented
Follow up thought on the CTA above, could arguably shorten `Resend verification email` to `Resend email` to get a little space back, as the context + the CTA are clear enough. Minor nit.

2024-01-26 09:50 UTC, pavlenex commented
@dennisreimann I've made a table comparing what you outline vs what one of the ambassadors proposed.


Permission | Bitcoin People | D11's Suggestion
-- | -- | --
Owner |   |  
btcpay.store.canmodifystoresettings | ✅ | ✅
btcpay.store.cantradecustodianaccount | ✅ | ✅
btcpay.store.canwithdrawfromcustodianaccount | ✅ | ✅
btcpay.store.candeposittocustodianaccount | ✅ | ✅
Store Admin / Brand Admin |   |  
btcpay.store.canmodifystoresettings | ✅ | ❌
Employee |   |  
btcpay.store.canmodifyinvoices | ✅ | ✅
btcpay.store.canmodifypaymentrequests | ✅ | ✅
btcpay.store.cancreatenonapprovedpullpayments | ✅ | ✅
btcpay.store.canviewpayouts | ✅ | ✅
btcpay.store.canviewpullpayments | ✅ | ✅
Store Manager |   |  
btcpay.store.canviewstoresetting | ✅ | ❌
btcpay.store.canmodifyinvoices | ✅ | ✅
btcpay.store.webhooks.canmodifywebhooks | ✅ | ✅
btcpay.store.canmodifypaymentrequests | ✅ | ✅
btcpay.store.canmanagepullpayments | ✅ | ✅
btcpay.store.canmanagepayouts | ✅ | ✅
btcpay.store.canviewcustodianaccounts | ✅ | ✅
btcpay.store.candeposittocustodianaccount | ✅ | ✅
Employee Readonly |   |  
btcpay.store.canviewinvoices | ✅ | ❌
Guest |   |  
btcpay.store.canviewstoresettings | ❌ | ✅
btcpay.store.canmodifyinvoices | ❌ | ✅
btcpay.store.canviewcustodianaccounts | ❌ | ✅
btcpay.store.candeposittocustodianaccount | ❌ | ✅

<br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration: none;">

2024-01-29 05:35 UTC, NicolasDorier commented on BTCPayServer.Tests/SeleniumTester.cs
> +            // reset test server policies
Why is it present in `SeleniumTester`? The reset is already done by `BTCPayServerTester.StartAsync`

2024-01-29 05:39 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (User.Identity is { IsAuthenticated: true } && string.IsNullOrEmpty(returnUrl))
it isn't more readable than `User.Identity.IsAuthenticated`

2024-01-29 05:45 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (result.IsLockedOut)
I think it can't happen anymore, because `TryCanLogin` check for it

2024-01-29 05:51 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIServerController.Users.cs
> +            if (user.RequiresApproval && viewModel.Approved.HasValue && user.Approved != viewModel.Approved)
`user.Approved != viewModel.Approved` seems superflous, as after you set `approvalStatusChanged`.

2024-01-29 05:52 UTC, NicolasDorier commented on BTCPayServer/Controllers/UIServerController.Users.cs
> +            bool? approvalStatusChanged = null;
please just condense this into a single boolean `isUpdated=false` and you set it like this `isUpdated |= await _userService.SetUserApproval(user.Id, viewModel.Approved.Value, Request.GetAbsoluteRootUri())`

2024-01-29 09:06 UTC, dennisreimann commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (User.Identity is { IsAuthenticated: true } && string.IsNullOrEmpty(returnUrl))
It's because the IDE hinted at a potential null pointer problem with `User.Identity`. But agree and will revert this.

2024-01-29 10:08 UTC, dennisreimann commented on BTCPayServer/Controllers/UIServerController.Users.cs
> +            bool? approvalStatusChanged = null;
I made it like this, because depending on what changed, different methods need to get called later on in the code. If the `adminStatusChanged` we invoke `_userService.SetAdminUser`, the `approvalStatusChanged` is handled by `_userService.SetUserApproval` and `propertiesChanged` will invoke `_UserManager.UpdateAsync`.

2024-01-29 10:12 UTC, dennisreimann commented on BTCPayServer/Controllers/UIServerController.Users.cs
> +            if (user.RequiresApproval && viewModel.Approved.HasValue && user.Approved != viewModel.Approved)
Done in 12b9d7e.

2024-01-29 10:13 UTC, dennisreimann commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (result.IsLockedOut)
Done in 12b9d7e.

2024-01-29 10:13 UTC, dennisreimann commented on BTCPayServer/Controllers/UIAccountController.cs
> +            if (User.Identity is { IsAuthenticated: true } && string.IsNullOrEmpty(returnUrl))
Done in 12b9d7e.

2024-01-30 00:33 UTC, NicolasDorier approved these changes

2024-01-31 05:45 UTC, merged