Crowdfund : Add Buyer information / Additional information(forms) like POS
btcpayserver/btcpayserver pull request #5659
Opened 2024-01-13 13:02 UTC by Nisaba

Add the ability tho get buyer information or additional information via forms to a crowdfunf.
Same thing than POS.

2024-01-13 19:31 UTC, dstrukt commented
Thanks for the PR! Will take a look this weekend - tagging @dennisreimann for review as well.

2024-01-16 11:31 UTC, dennisreimann commented on BTCPayServer/wwwroot/crowdfund/app.js
> +                    window.location.href = this.srvModel.formUrl;
This could be condensed to just formURL, also in the view model.

2024-01-16 11:40 UTC, Nisaba commented on BTCPayServer/wwwroot/crowdfund/app.js
> +                    window.location.href = this.srvModel.formUrl;
HasFormExtraValues boolean is set in the Crowdfundplugin.cs file, depending on the settings.
In this file, we don't have access to controller to get the Url.Action method.
Would need extra code more complicated I think...

2024-01-16 13:55 UTC, dennisreimann commented on BTCPayServer/wwwroot/crowdfund/app.js
> +                    window.location.href = this.srvModel.formUrl;
I updated it in d3dab94.

2024-01-16 13:59 UTC, dennisreimann requested changes
Currently it only works for the "no perks" case. If there are perks, they need to be selected first and afterwards the form would need to be filled.

2024-01-16 16:50 UTC, Nisaba commented
OK, noted.
I will fix this before the end of this week.

2024-01-17 07:14 UTC, dennisreimann commented
Please also add a test for both cases (pers and no perks), so that we can ensure the crowdfunding with form case will also be considered moving forward. Imho that's important, because the flow is very JS heavy and can easily be missed.

2024-01-19 19:27 UTC, Nisaba commented
@dennisreimann fix for the perk has been made. You can check it.
I have to add tests; i hope this week-end...

2024-02-06 13:01 UTC, dennisreimann approved these changes
tACK. Thanks for the contribution!

2024-02-20 22:24 UTC, dstrukt approved these changes
tACK - LGTM.

+1 Thank you for the contribution - great work!

2024-02-21 13:41 UTC, Kukks approved these changes

2024-02-21 13:41 UTC, merged