remove decimals for Colombian (COP) and Argentina's Peso (ARS)
btcpayserver/btcpayserver pull request #5710
Opened 2024-01-29 18:13 UTC by TChukwuleta

Fix for issue #5708 

Remove decimal places for COP and ARS currencies

2024-01-29 18:48 UTC, Kukks requested changes

2024-01-29 18:48 UTC, Kukks commented on BTCPayServer/wwwroot/pos/common.js
> +            const excludeDecimalPlaces = ['COP', 'ARS'].includes(currency);
This should not be hardcoded in the js but rather decides based on divisibility, which is set in a currency service in c#.

2024-01-29 18:51 UTC, TChukwuleta commented on BTCPayServer/wwwroot/pos/common.js
> +            const excludeDecimalPlaces = ['COP', 'ARS'].includes(currency);
Noted @Kukks. Would look into it

2024-01-29 18:59 UTC, matman7x approved these changes

2024-01-30 01:23 UTC, NicolasDorier commented
why does `numberFormatInfo.CurrencyDecimalDigits` doesn't returns 0 for those two currencies?

2024-01-30 19:53 UTC, TChukwuleta commented
@NicolasDorier 

numberFormatInfo (a method under system.Globalization) has default value for CurrencyDecimalDigits to be 2

I am not sure if  or how it is tied to currencies

2024-01-31 01:26 UTC, NicolasDorier commented
@TChukwuleta , please instead of doing this hack here, add those currencies to https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer.Rating/Currencies.json

Then extend the test `RoundupCurrenciesCorrectly` to make sure COP and ARS have the right `CurrencyDecimalDigits`

2024-02-02 06:08 UTC, NicolasDorier commented on BTCPayServer.Rating/CurrencyNameTable.cs
> +                            if (new RegionInfo(culture.LCID).ISOCurrencySymbol.Equals("ARS") || new RegionInfo(culture.LCID).ISOCurrencySymbol.Equals("COP"))
Remove this, you shouldn't have anything hard coded.

2024-02-02 06:10 UTC, NicolasDorier commented on BTCPayServer.Rating/Currencies.json
> -      "divisibility":2,
https://en.wikipedia.org/wiki/Argentine_peso it says there is 2 subunit.

2024-02-02 06:11 UTC, NicolasDorier commented on BTCPayServer.Rating/Currencies.json
> -      "divisibility":2,
https://en.wikipedia.org/wiki/Colombian_peso it says there is 2 subunit

2024-02-02 06:21 UTC, NicolasDorier commented on BTCPayServer.Tests/FastTests.cs
> -                (0.0m, "0.00 USD", "USD")
Note that you should add a test on `CurrencyNameTable.Instance.GetNumberFormatInfo` after as well.

`GetNumberFormatInfo` is using the json file, but the formatting come from CultureInfo from the OS.

The OS says ARS and COP have 2 decimals, and wikipedia seems to agree, so I am not sure why it should be changed.

2024-02-02 06:23 UTC, NicolasDorier commented
Please just add a test on the `GetNumberFormatInfo` https://github.com/btcpayserver/btcpayserver/pull/5710#discussion_r1475590651 in the same test method (below after the loop).

2024-02-02 07:14 UTC, TChukwuleta commented on BTCPayServer.Tests/FastTests.cs
> -                (0.0m, "0.00 USD", "USD")
Well according to the issue, https://github.com/btcpayserver/btcpayserver/issues/5708#issue-2102859157, they no longer run cents

2024-02-02 08:16 UTC, merged