Onboarding: Invite new users on store level
btcpayserver/btcpayserver pull request #5719
Opened 2024-02-02 16:12 UTC by dennisreimann

Includes the updates from #5714 and can be rebased once that PR is merged.

- Add Store Manager and Employee roles
- Roles: Add default order and improve display
- Store users: Invite non-existing users
- Store users: Allow to change user role in place (before you had to remove and re-add the user)

## Roles
![roles](https://github.com/btcpayserver/btcpayserver/assets/886/cc5285c9-3e6e-49b1-8506-520f0fa3eb95)

## Inviting users

![invite](https://github.com/btcpayserver/btcpayserver/assets/886/70ac7c08-8f07-457b-b2c0-a6342d92d12a)

![invite-accepted](https://github.com/btcpayserver/btcpayserver/assets/886/efc80556-7dcd-4005-90bb-0157cdf16576)

2024-03-02 01:30 UTC, dstrukt requested changes
First pass looks good functionally, few thoughts:

- [ ] Think we should change the `Set Password` CTA copy to `Create Account` imo, once the invitation is accepted.

- I don't love the long invite link, think it could be treated like an address, in that it's copyable and better formatted, but the current iteration works and satisfies all the required functionality. I realize this may deserve a mock to play with a few ideas that clean it up .. so maybe we can address this when we add expiration(s) to the invites? (unless this functionality was nACK'd)

- I do like the look of the `Scope` tags, and love that you differentiated them via colors, which is sufficient for this PR. However I'm wondering if we should be doing more to push the look of certain things, e.g. the Server Admin gets a crown, or the Server level has a server icon / Store has a store icon, etc.. thoughts?

Still trying to break this, but haven't been able to yet, the above are minor nits and considerations! Awesome work!

2024-03-04 17:15 UTC, pavlenex commented
Began testing but ran into two problems thus far:

1. Store owner doesn't get any notification or email if an invited successfully registered.
2. Seems like permissions are not working correctly, I've invited user as a manager, but he only had guest access and no ability to view store settings.

There are some things in the logs, but unsure what they're saying and if they're PR related:

```
2024-03-04 21:06:48.493 +05:00 [INF] Root Path: /
2024-03-04 21:06:49.908 +05:00 [INF] Connection to NBXplorer's database successful, dashboard and reporting features activated.
2024-03-04 21:06:49.910 +05:00 [INF] SSH settings detected, testing connection to root@127.0.0.1 on port 21622 ...
2024-03-04 21:06:50.109 +05:00 [INF] Checking if any payment arrived on lightning while the server was offline...
2024-03-04 21:06:50.166 +05:00 [INF] SSH connection succeeded
2024-03-04 21:06:50.418 +05:00 [INF] Processing lightning payments...
2024-03-04 21:06:50.518 +05:00 [INF] Starting listening NBXplorer (BTC)
2024-03-04 21:06:50.533 +05:00 [INF] Start watching invoices
2024-03-04 21:06:50.589 +05:00 [INF] Starting payment request expiration watcher
2024-03-04 21:06:51.000 +05:00 [INF] 0 pending payment requests being checked since last run
2024-03-04 21:06:51.080 +05:00 [INF] BTC: Checking if any pending invoice got paid while offline...
2024-03-04 21:06:51.113 +05:00 [INF] BTC: 0 payments happened while offline
2024-03-04 21:06:51.113 +05:00 [INF] Connected to WebSocket of NBXplorer (BTC)
2024-03-04 21:07:20.487 +05:00 [INF] New admin xxxh@icloud.com registered
2024-03-04 21:09:06.872 +05:00 [ERR] Unexpected exception in TimingPipeFlusher.FlushAsync.
System.IO.IOException: The encryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (14): Bad address
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.TimingPipeFlusher.FlushAsync(MinDataRate minRate, Int64 count, IHttpOutputAborter outputAborter, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2FrameWriter.WriteGoAwayAsync(Int32 lastStreamId, Http2ErrorCode errorCode)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.UpdateConnectionState()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
--- End of stack trace from previous location ---
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.ConcurrentPipeWriter.FlushAsyncAwaited(ValueTask`1 flushTask, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.PipeWriterHelpers.TimingPipeFlusher.TimeFlushAsyncAwaited(ValueTask`1 pipeFlushTask, MinDataRate minRate, IHttpOutputAborter outputAborter, CancellationToken cancellationToken)
2024-03-04 21:09:06.894 +05:00 [ERR] Unhandled exception while processing 0HN1SCKE349O6.
System.IO.IOException: The encryption operation failed, see inner exception.
 ---> System.ComponentModel.Win32Exception (14): Bad address
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.WriteSingleChunk[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Net.Security.SslStream.WriteAsyncInternal[TIOAdapter](ReadOnlyMemory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.Pipelines.StreamPipeWriter.FlushAsyncInternal(Boolean writeToStream, ReadOnlyMemory`1 data, CancellationToken cancellationToken)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.IO.Pipelines.StreamPipeWriter.CompleteAsync(Exception exception)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter`1.DisposeAsync()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.DuplexPipeStreamAdapter`1.DisposeAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Https.Internal.HttpsConnectionMiddleware.OnConnectionAsync(ConnectionContext context)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.HttpConnection.ProcessRequestsAsync[TContext](IHttpApplication`1 httpApplication)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(IAsyncStateMachineBox box, Boolean allowInlining)
   at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
   at System.Threading.Execution [...]

2024-03-06 06:40 UTC, dstrukt commented
> 1. Store owner doesn't get any notification or email if an invited successfully registered.

Can confirm, great catch!

> 2. Seems like permissions are not working correctly, I've invited user as a manager, but he only had guest access and no ability to view store settings.

I couldn't repro this one.

2024-03-06 18:28 UTC, dennisreimann commented
> Store owner doesn't get any notification or email if an invited successfully registered.

Now they do and I've included managers as well, so owners and managers will get notifications and emails about a new user accepting the invite to a store. Done in b57336f.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/3872dcf1-5ac9-422e-96aa-21cd45026765)

> Seems like permissions are not working correctly, I've invited user as a manager, but he only had guest access and no ability to view store settings.

Yes, in the UI we mostly had `CanModifyStoreSettings` as a policy requirement. I've changed this in fa00c58 to make the read views available with the `CanViewStoreSettings` permission. This is a rather big change and will most likely interfere with the refactoring in #5782 — I think it will be best to first merge @kukks' PR and then rebase this one.

Nevertheless the general functionality can be tested already as both problems have been addressed.

> There are some things in the logs, but unsure what they're saying and if they're PR related:

These look like some kind of more general connection problem, which is most likely unrelated to the changes here.

2024-03-07 09:21 UTC, pavlenex commented
Yeah under no circumstances should such low-permission role such as guest have insight into such important info like store settings.

2024-03-07 09:23 UTC, dennisreimann commented
Their only practical permission would then be `canmodifyinvoices` and I wonder if we should simply remove the `Guest` role then and migrate them to `Employee`, so that we clean up everything as well.

2024-03-07 09:49 UTC, pavlenex commented
@dennisreimann I'm afraid I don't have an answer to that. It does sound tempting to clean up those roles, but the `guest` role has been in there forever, and afaik there may be people building with API utilizing it. I'm unsure what sort of complexities will be involved to clean it up without breaking things up?

2024-03-14 15:01 UTC, Kukks approved these changes
i didn't see anything bad, although some preferences of mine don't match but that's fine (like the prefix subject stuff)

2024-03-14 15:11 UTC, dennisreimann commented on BTCPayServer/Controllers/UIStoresController.LightningLike.cs
>          [HttpGet("{storeId}/lightning/{cryptoCode}")]
Agreed, but let's have a separate refactoring PR for that.

2024-03-15 08:58 UTC, dennisreimann commented
@pavlenex Thanks to @kukks we now have readonly form-versions.

I've also added a better way of changing a user's role and tests for that. Can be user-tested again.

2024-03-19 13:58 UTC, merged