UI: Move section navigation to sidebar
btcpayserver/btcpayserver pull request #5744
Opened 2024-02-09 13:58 UTC by dennisreimann

Proof of concept for the new sidebar structure, including the active section navigation. As discussed in yesterday's design meeting — this changes the navigation for the Store Settings and Server Settings, so that we can discuss it.

I think it works very well, we'd onlty need to ensure that plugins also update/migrate.

## Desktop

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/aa94b77a-9509-4d91-84c1-465a64013fa9)

## Mobile

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/e69c9a5e-b7e0-40ef-a690-2a024f70f1d4)

2024-02-09 18:35 UTC, dstrukt commented
So I think most of this functionality is covered, but just running through it myself, and on the PR for posterity and testing:

- [ ] The sub-navigation should not be active if the parent element `Wallet`, `Settings`, etc.. is not `active`:

<img width="175" alt="Screen Shot 2024-02-09 at 10 13 40 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/fd3ca04d-5785-4da3-8de8-6c1945dbc705">

- [ ] Clicking on the parent `Settings` will land you on the first item in the sub-navigation list:
- [ ] Which will allow us to keep the main CTA(s) consistent at the top right:

<img width="837" alt="Screen Shot 2024-02-09 at 10 29 53 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/37d23574-ab0c-4bb7-bc18-85eab43d5311">

- [ ] Then you navigate to one of the subpages, and the same main CTA is in the top right corner:
<img width="1049" alt="Screen Shot 2024-02-09 at 10 16 25 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/5f0abeda-26cc-4055-921f-47e20b108b79">

- [ ] Then you navigate a page deeper, with the CTAs still in the right, just a few more / different:
<img width="791" alt="Screen Shot 2024-02-09 at 10 31 50 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/15640a20-4052-4094-b3ff-4c6c6dc23358">

- [ ] One thing to note is the padding/margins, if no sub-navigation, the margin below is only `24px` or `32px`. If sub-navigation, the margin below is 16px to ensure a little bit of spacing, if nothing additional is added. We could ensure that everything has a default margin below this case if we also bump it up to `24px`. The only thing to consider here is scrolling, these top sections should stay fixed, like our other views to ensure consistency. I believe you'll notice these details once implemented:
<img width="735" alt="Screen Shot 2024-02-09 at 10 29 42 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/c12ed3b9-3ef7-40ec-adb2-b7aba914bfce">

2024-02-10 01:17 UTC, dennisreimann commented
Thanks for the detailed feedback! Yes, all of these are valid and open points.

Wanted to provide it to get a better feel for this as a potential approach — there are indeed lots of details to work on of we go for it and I'd rather do it once my other PRs are done, because it would most likely resuot in larger conflicts if we do them alongside each other. 

So think of this in its current form more like something that'll help us evaluate this approach. I for one like the result and would +1 it.

2024-02-10 11:13 UTC, pavlenex commented
Tried to build but got this.
<img width="846" alt="Screenshot 2024-02-10 at 16 11 50" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/ce8860ef-81c8-4ec2-bea2-d11a43f422ff">

2024-02-10 11:54 UTC, dennisreimann commented
@pavlenex try a `dotnet clean && dotnet restore` and then do another build. This looks like there's something cached and I changed those methods.

2024-02-10 12:51 UTC, pavlenex commented
> `dotnet clean && dotnet restore`

Yeah tried that multiple times, nuked everything volumes, and even folders and images, but will give it another try.

2024-02-11 02:32 UTC, dstrukt commented
Will try to build it either tomorrow or Monday morning and see I run into the same errors. I've also been having trouble with some builds, dependencies, etc...

2024-02-11 08:06 UTC, dennisreimann commented
Something is broken, CI is failing too. Will fix.

2024-02-14 11:35 UTC, dennisreimann commented
> 4. The only additional consideration here is do we keep the parent item active as well (colors in the sidebar), or just the current page?

I'd say only the current page — if we want to be fancy, we could also highlight the icon of the active section, but not it's associated main page name.

> Finally, I'm not sure we'll want to do this for all the pages this could apply to, as this PR would become quite large, but it could be added to a section at a time (plugins, wallet, etc..) if we find we like the updated navigation structure!

Yes, if we tackle everything (moving CTA's etc.) this will be a larger undertaking. Let's settle on the approach while we wait for the other open PRs to be finished, as this will touch many views.

2024-02-14 18:41 UTC, dstrukt commented
> I'd say only the current page — if we want to be fancy, we could also highlight the icon of the active section, but not it's associated main page name.

Let's keep it the way it is then!

> Yes, if we tackle everything (moving CTA's etc.) this will be a larger undertaking. Let's settle on the approach while we wait for the other open PRs to be finished, as this will touch many views and tests.

Maybe we just tackle the `Store Settings` first in a single PR, and see how it feels for a whole section.

2024-02-20 14:30 UTC, dennisreimann commented
Given the extend of the changes I think it would be worthwhile to do this combined with #5581 once most of the other PRs are done. While this is on hold we can decide on the details.

2024-02-25 17:49 UTC, pavlenex commented
Gave it a quick try, must say it's growning on me, a lot of user-testing and some of the cleanups wrt settings naming should be done. Can't say for sure if this is the way to go, but the more I used it, the more I liked it, looking forward to what the team things, and then we should do some user-tetsting with community. 

Approach ack.

2024-04-02 15:56 UTC, dennisreimann commented
Rebased and added the account pages. Now all pages with subnavigation are working and we can get to the details once we decide this is something for v2.0

2024-05-02 17:55 UTC, dennisreimann commented
Decision from the design meeting: Deploy a test version, gather feedback and consensus from team members and afterwards ask testers for additional feedback.

2024-05-03 16:56 UTC, dennisreimann commented
@dstrukt I think I changed most of it — can you give it another look and see if I missed pages or details?

2024-05-03 17:42 UTC, dstrukt commented
Will take a look today on @ndeet's deployment (thank you!)!

2024-05-03 18:26 UTC, dennisreimann commented
It's not deployed yet, we'll figure that out next week.

2024-05-12 05:43 UTC, dstrukt commented
Have been testing the deployed branch, overall this is a very solid change and improvement imo!

There are definitely things that could be improved (and it should be highlighted this isn't the final form when sharing):

adding the breadcrumbs to the sub-pages on the create views, etc.. to help the user keep track of where they are

or more minor, but nice QOL upgrades i.e. keep the scroll position on the left sidebar for the Server Settings or Account, but given we have to refresh, vs. a PWA type reload, it's probably not possible.

the Account menu is a little inconsistent now as well, and makes me think for both Server Settings / Account, we could mirror the functionality of the Store Settings, in that the default page is the general page, and everything else is more specific

anyway, just some quick thoughts, still thinking over more as i click through it

2024-05-14 15:40 UTC, dennisreimann commented
> adding the breadcrumbs to the sub-pages on the create views, etc.. to help the user keep track of where they are (when navigating 2-3 level deep sub-pages)

Can you take care of this?

> or more minor, but nice QOL upgrades i.e. keep the scroll position on the left sidebar for the Server Settings or Account, but given we have to refresh, vs. a PWA type reload, it's probably not possible.

Done in a0232f2.

> the Account menu is a little inconsistent now as well, and makes me think for both Server Settings / Account, we could mirror the functionality of the Store Settings, in that the default page is the general page, and everything else is more specific

- I think for Account it works, as it lands on the Update Account page. Which page should it be otherwise?
- Server Settings: The closest I can think of is the Policies page. Right now we land on the Users page ­— whall I change this to be Policies or something else?

2024-05-14 19:56 UTC, dstrukt commented
> Can you take care of this?

I'm confident with a basic template/example, I could carry it across multiple views - but without, I can certainly try!
 
> * I think for Account it works, as it lands on the Update Account page. Which page should it be otherwise?

Landing page is correct, I just mean the little modal we currently pop-up is a little different than the others (which works perfectly fine), but similar to SS, it would be out of scope, but probably something worth making consistent in future updates.  

> * Server Settings: The closest I can think of is the Policies page. Right now we land on the Users page ­— whall I change this to be Policies or something else?

Good point, I think in the future rolling details about the Server / BTCPay version, etc.. maybe combing Policies, etc.. could be the way to go, but out of scope, so what we're doing currently is sufficient!

Still poking around on the deployed branch!

2024-05-22 09:47 UTC, dennisreimann commented
This PR can now be user-tested on https://testing.btcpay.tech/

@pavlenex @dstrukt @ndeet @NicolasDorier @Kukks

2024-05-23 19:49 UTC, dennisreimann commented
@dstrukt In 0f51afc I added breadcrumbs to Invoices, Forms and Roles. You can take it from here and if you want to adjust the breadcrumbs in general, see this commit in the design repo: btcpayserver/btcpayserver-design@828b7ab66683e1a5f5dbd54a9a36382358f89875

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/e7c03670-4e04-4903-b844-3829c11a3ab8)

2024-05-28 01:38 UTC, dstrukt requested changes
## STILL WORKING!

Submitting to not lose progress.

Updated all of the breadcrumbs I could, found a few issues along the way:

- [ ] Opening `Manage Plugins` expands the Server Settings list and should not

<img width="267" alt="Screen Shot 2024-05-27 at 5 56 35 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/b3cdfea1-71d9-4bc2-bdc6-b1d80fe45445">

- [ ] Couldn't manage to figure out `Pull Payments` breadcrumbs, looks like the way we pull in the Store ID is a little unique in this view? Not sure.

2024-05-28 05:25 UTC, dstrukt commented
Making changes like this:

<img width="1490" alt="Screen Shot 2024-05-27 at 10 15 11 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/2ef70a06-4cc2-4fd8-a940-e2538baf1509">

2024-05-28 05:59 UTC, dennisreimann commented
@dstrukt Thanks, I fixed the Plugins case and added the breadcrumbs to the pull payment views. Keep on going :+1:

2024-05-28 08:14 UTC, dstrukt commented
- [ ] Getting a 404 when attempting to set the `2FA` breadcrumb on the `Register` sub-page, and not 100% sure why

<img width="1388" alt="Screen Shot 2024-05-28 at 12 56 38 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/d0d5a804-e965-4ae0-8438-301d879e6453">

otherwise, i think that covers the breadcrumbs, but might help to have another set of eyes

2024-05-29 05:19 UTC, dstrukt commented
> * [ ]  Getting a 404 when attempting to set the `2FA` breadcrumb on the `Register` sub-page, and not 100% sure why
> 
> <img alt="Screen Shot 2024-05-28 at 12 56 38 AM" width="1388" src="https://private-user-images.githubusercontent.com/6250771/334324037-d0d5a804-e965-4ae0-8438-301d879e6453.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5NjAwMDQsIm5iZiI6MTcxNjk1OTcwNCwicGF0aCI6Ii82MjUwNzcxLzMzNDMyNDAzNy1kMGQ1YTgwNC1lOTY1LTRhZTAtODQzOC0zMDFkODc5ZTY0NTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMDUxNTA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWRkMGEwMWRjMDFkNGNmYmM1MjRiMDc5YjMyZDU3OGJlZjhhZjNjYzk5YjAzN2Y0YjMzMThhYmI5NDkyNzBhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.CQ844JGWjJrLjJB8oVkQvjFJtkFC5upzLCgT8hoGl-s">

Fixed all but this one so far.

2024-05-30 18:30 UTC, dstrukt approved these changes
tACK - LGTM!

2024-06-19 13:22 UTC, Kukks approved these changes

2024-06-19 13:23 UTC, merged