Admin overview of the stores on the instance
btcpayserver/btcpayserver pull request #5745
Opened 2024-02-09 16:35 UTC by dennisreimann

Draft for #5674 as discussed in yesterday's design meeting. WIP state and more like a POC currently, but wanted to get this out to discuss this more practically.

## Users

The user list now features an overview of stores per user as proposed in #5674.

![users](https://github.com/btcpayserver/btcpayserver/assets/886/042f5080-cf2c-4863-b800-85664fe59fdc)

## Admin Stores Overview

The Admin Stores Overview is the opposite way of looking at that list, but with the stores being the primary items.

![stores](https://github.com/btcpayserver/btcpayserver/assets/886/082859e6-499b-4f1f-9ae1-3d8bebe3cb70)

2024-02-09 18:10 UTC, dstrukt commented
Awesome, hyped to get builds of these to keep iterating!

2024-02-12 20:31 UTC, dstrukt commented
Thinking through this more this week, but immediate thoughts:

## For the Admin Stores overview:

- Search

- Store Logo (if exists)
- Store Creation Date
- Store Website (if exists)
- Store Balance (perhaps?)
- Store Status (Archived / Active)


## Open Questions:

- Do we want to support mass actions on this view (for archiving, removing, etc..)?
- Do we want to support filters (users, roles, status)
- Do we want to push the Archived Stores into this view, just at the bottom of list, or treat it like the Invoice view .. might help consolidate the number of views.

2024-02-13 06:01 UTC, pavlenex commented
I recommend that we approach this in two different PR's, because store overview on a user level is tagged for 1.13, and pretty much has consensus on the approach, where as ad admin overview within store still needs discussion and is tagged for 1.14, though it's great to see them in one PR as well, easier to thinker about the UX.

2024-02-16 07:52 UTC, pavlenex commented
In private conversation @rockstardev and @Kukks cACk this approach. 

Kukks did point out that if we intend to refine roles further, we'd have to re-work roles to have ability to be set at a server level, since currently we can't do that, as they're on a store level. For example, a potential use-case here is:
1. Server Admin, who can maintain server and plugins but not access store 
2. Server Support who can access stores but not touch Server Settings or plugins
Currently we don't have those abilities, so in initial approach, only Server Owners would have that option to edit stores, but we need to refine it and make it customizable.

Rockstar mentioned that our plan to roll this out in two stages in 1.13 and 1.14 is okay, since the second stage, of giving ability to Store Owners involves some sensitive and perhaps unwanted UI power for store owners, we should announce it in 1.13. notes that Store Owners upgrading to 1.14 will get that ability, just to give users a bit of time to get used to possibly disruptive updata and prepare them.

2024-02-16 10:45 UTC, dennisreimann commented
Ok, so the scope of this PR should be offering the overview of stores on the admin's users list only?

Shall there be links to the stores as well? If so we need to define the capabilities of admins when accessing a store that doesn't belong to them. With the current state of this PR they can manage everything like the store owner, but I think as a temporary measure we could come up with something like a "virtual store role", with which we grant them only limited access. /cc @Kukks

2024-02-16 10:50 UTC, pavlenex commented
@dennisreimann What's wrong with just giving them `Guest` access in 1.13 and in 1.14 `Owner` access over stores?

2024-02-16 11:02 UTC, dennisreimann commented
Nothing wrong, I just wanted to clarify what it should be like in this PR :)

2024-02-20 14:22 UTC, dennisreimann commented on BTCPayServer/Components/StoreSelector/Default.cshtml
> +                *@
Hide the link for now, but keep the functionality as we'll need it in the follow-up PR.

2024-02-20 14:22 UTC, dennisreimann commented on BTCPayServer/Controllers/UIServerController.cs
> +        public async Task<IActionResult> ListStores()
This is the action that is not linked to. Let's keep it nevertheless, so that it is present for the follow-up PR and easier to discuss what the series of PRs will bring as a whole.

2024-02-20 14:22 UTC, dennisreimann commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                    : await _storeRepository.FindStore(storeId, userId, isAdmin);
Optimization as this is called multiple times, depending on how many `permission` attributes are used on the page. Do not query the DB on every hit of this method.

2024-02-20 14:22 UTC, dennisreimann commented on BTCPayServer/Security/CookieAuthorizationHandler.cs
> +                        if (paymentRequest != null && _httpContext.GetPaymentRequestData()?.Id != paymentRequest.Id)
No need to set the data if it has already been set. Also see the optimization above.

2024-02-20 14:22 UTC, dennisreimann commented on BTCPayServer/Security/GreenField/GreenFieldAuthorizationHandler.cs
> +                            var store = await _storeRepository.FindStore(storeId, userid, isAdmin);
Provides the same access on the API-level as in the UI: Admins get `Guest` access to foreign stores.

2024-02-20 14:22 UTC, dennisreimann commented on BTCPayServer/Services/Stores/StoreRepository.cs
> +            }
Authorization-wise this is the key part: If an admin user isn't part of the store's users list, then they will be granted `Guest` access.

2024-02-20 14:24 UTC, dennisreimann commented
Updated according to the comments:

- Admin is granted `Guest` access to foreign stores
- Link to admin stores overview is removed — I kept the code/actions so that it is present for the follow-up PR and easier to discuss what the series of PRs will bring as a whole.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/6a6fc0e7-882c-42d8-baf7-4e750f6ba7bc)

2024-02-21 14:37 UTC, pavlenex commented
cACK, up to @Kukks to give it a look code-wise and @rockstardev if he wants as well. Then we proceed according to plan, 1.13 we announce admins will have owner access and execute in 1.14. 🚀

2024-02-21 14:38 UTC, Kukks requested changes

2024-02-21 14:38 UTC, Kukks commented on BTCPayServer/Services/Stores/StoreRepository.cs
> +        public async Task<StoreData?> FindStore(string storeId, string userId, bool isAdmin = false)
this doesn't feel great. I propose we split this part out of this PR   to get the foundation merged

2024-02-22 12:38 UTC, Kukks commented on BTCPayServer/Services/Stores/StoreRepository.cs
> +        public async Task<StoreData?> FindStore(string storeId, string userId, bool isAdmin = false)
I want to change the inner workings. Please separate this code into a separate pull request so I can merge this

2024-02-22 13:28 UTC, dennisreimann commented on BTCPayServer/Services/Stores/StoreRepository.cs
> +        public async Task<StoreData?> FindStore(string storeId, string userId, bool isAdmin = false)
Done in f6878b5.

2024-02-23 08:51 UTC, Kukks approved these changes

2024-02-23 08:51 UTC, merged