changing check box to toggle in various setting views
btcpayserver/btcpayserver pull request #5769
Opened 2024-02-20 05:45 UTC by TChukwuleta

Resolves #5734 changing check boxes to toggles in various setting views

2024-02-20 17:57 UTC, TChukwuleta commented
> Thanks for picking this up!
> 
> Small request - could you make a short list (could literally be the page titles) of the places you've made changes? I can reference the code/file changes, but it makes it a little easier on the review

Hey @dstrukt 

I have updated the PR description with the list of places that the changes were made

2024-02-24 16:39 UTC, pavlenex requested changes
Thanks for tackling this.
Took a look, most if it looks good, left a comment for some that don't look good ,on some places we need to reverse the logic, for example the item editor in POS doesn't really make sense.
I am unsure if you even touched it in this PR
<img width="319" alt="Screenshot 2024-02-24 at 21 37 49" src="https://github.com/btcpayserver/btcpayserver/assets/36959754/f825c003-5fd4-4a36-90b3-d92fc4ece894">

2024-02-24 16:39 UTC, pavlenex commented on BTCPayServer/Views/Shared/EmailsBody.cshtml
> +                            <div class="d-flex align-items-center">
This checkbox needs to be enabled by default, since we want TLS to be enabled, unless user disables it.

2024-02-24 16:39 UTC, pavlenex commented on BTCPayServer/Views/UIManage/NotificationSettings.cshtml
> +                    <div class="col">
Some of the notifications should be on by default, currently they're all off, I'd rather we put them all on and user can disable what they want.

2024-02-24 17:47 UTC, TaylorMadeUSMC commented
Someone please please help me I don’t understand any of what I’m doing

2024-02-26 03:44 UTC, TChukwuleta commented on BTCPayServer/Views/UIManage/NotificationSettings.cshtml
> +                    <div class="col">
Hey @pavlenex, so the toggling is speaking to not receiving new notification. 

That means by default they are to receive new notification for each of those. Enabling all of them would mean no notification would be sent to the user for each of those, is that the case?

2024-02-26 04:47 UTC, TChukwuleta commented
> Thanks for tackling this. Took a look, most if it looks good, left a comment for some that don't look good ,on some places we need to reverse the logic, for example the item editor in POS doesn't really make sense. I am unsure if you even touched it in this PR <img alt="Screenshot 2024-02-24 at 21 37 49" width="319" src="https://private-user-images.githubusercontent.com/36959754/307536461-f825c003-5fd4-4a36-90b3-d92fc4ece894.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg4OTk2NTAsIm5iZiI6MTcwODg5OTM1MCwicGF0aCI6Ii8zNjk1OTc1NC8zMDc1MzY0NjEtZjgyNWMwMDMtNWZkNC00YTM2LTkwYjMtZDkyZmM0ZWNlODk0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI1VDIyMTU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmNjM0ZTlkZGVkNTIwNmE1MzQ5OTE5YWM2NDE5ZGNkNzBjZjhmNTVjMTA1MGFmZWZiY2E0MzRiYTdjZDA1NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c8LiKFFSO-tvvaPrIcTAZB6ZNi_F6xfV4-dffUclzZA">

Nah, didn't change the item editor, but what's the expectation with the editor settings?

2024-02-26 07:07 UTC, pavlenex commented on BTCPayServer/Views/UIManage/NotificationSettings.cshtml
> +                    <div class="col">
If so that logic should be reversed, we cannot "enable to disable" things. Enabled toggle means option is active, disabled toggle means it's deactivated.

2024-02-26 07:09 UTC, TChukwuleta commented on BTCPayServer/Views/UIManage/NotificationSettings.cshtml
> +                    <div class="col">
alright. sure

2024-02-26 23:26 UTC, TChukwuleta commented on BTCPayServer/Views/UIManage/NotificationSettings.cshtml
> +                    <div class="col">
Updated and reversed the logic

2024-02-28 19:20 UTC, dstrukt commented
That covers it. The intention was to improve that inverted logic as you've put it @pavlenex.

Giving this another test this evening, but the first run through looked good functionally!

2024-02-29 10:18 UTC, dennisreimann requested changes

2024-02-29 10:18 UTC, dennisreimann commented on BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
> +                <input asp-for="SortPerksByPopularity" type="checkbox" class="btcpay-toggle me-2" style="transform: scale(0.8);" />
Why the `transform`?

2024-02-29 13:47 UTC, TChukwuleta commented on BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
> +                <input asp-for="SortPerksByPopularity" type="checkbox" class="btcpay-toggle me-2" style="transform: scale(0.8);" />
majorly to adjust the size of the toggle. I made the toggles smaller in size so that the view is not distorted

2024-03-02 01:21 UTC, dstrukt commented on BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
> +                <input asp-for="SortPerksByPopularity" type="checkbox" class="btcpay-toggle me-2" style="transform: scale(0.8);" />
agree we shouldn't adjust scale here, esp. one off instances, however, if we did think it could be scaled down slightly, it should be consistent across all views

2024-03-02 03:18 UTC, TChukwuleta commented on BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
> +                <input asp-for="SortPerksByPopularity" type="checkbox" class="btcpay-toggle me-2" style="transform: scale(0.8);" />
okayyyy. This is noted. would revert

2024-03-03 06:46 UTC, TChukwuleta commented on BTCPayServer.Client/Models/EmailSettingsData.cs
> +    public bool DisableCertificateCheck { get; set; } = true;
Hello @dennisreimann so I tried using v-model, and v-bind to try and invert the position of the toggle for this particular email settings data, but not successful with it, would you advice me to do the inversion from controller level

2024-03-03 06:49 UTC, TChukwuleta commented on BTCPayServer/Views/Shared/Crowdfund/UpdateCrowdfund.cshtml
> +                <input asp-for="SortPerksByPopularity" type="checkbox" class="btcpay-toggle me-2" style="transform: scale(0.8);" />
Removed the transform property

2024-03-03 07:41 UTC, dennisreimann commented on BTCPayServer.Client/Models/EmailSettingsData.cs
> +    public bool DisableCertificateCheck { get; set; } = true;
For the settings classes you can see what I did in particular here: https://github.com/btcpayserver/btcpayserver/pull/5731/files#diff-9dbbc35c5967b386aa57ceca0860638984a66d73f27490e14644892490c788feR19

You'd add a new property, which is `JsonIgnore`d and you can modify the getter and setter to invert the original property's value.

2024-03-03 07:43 UTC, TChukwuleta commented on BTCPayServer.Client/Models/EmailSettingsData.cs
> +    public bool DisableCertificateCheck { get; set; } = true;
Sweet. I'd do that now.

2024-03-03 08:24 UTC, TChukwuleta commented on BTCPayServer.Client/Models/EmailSettingsData.cs
> +    public bool DisableCertificateCheck { get; set; } = true;
Done that @dennisreimann.

Thank you

2024-03-04 17:17 UTC, dennisreimann approved these changes
tACK. @TChukwuleta I unified the toggles (mainly in terms of CSS classes being used) and fixed some things with the Checkout Appearance and POS/Crowdfund editor. Can you give it another pair of eyes again, so that we ensure everything works as supposed to?

2024-03-04 17:25 UTC, TChukwuleta commented
Alright. Doing that now @dennisreimann

2024-03-04 17:41 UTC, TChukwuleta commented
All good @dennisreimann

2024-03-05 04:30 UTC, dstrukt approved these changes
tACK - looks good - appreciate the changes @TChukwuleta!

2024-03-07 18:19 UTC, dstrukt commented
Re-reviewing for a last pair of eyes - but it should be good to go, will get this in evening!

2024-03-14 13:25 UTC, pavlenex approved these changes
tACK, all previous concerns I had are now addressed, good work @TChukwuleta 🎉 
This PR needs to be rebased to resolve a conflict and then it's up to @dennisreimann to merge it if it's okay for him code-wise.

2024-03-14 14:16 UTC, merged