Reposition the camera scan icon in the wallet > send functionality
btcpayserver/btcpayserver pull request #5790
Opened 2024-02-26 06:40 UTC by TChukwuleta

Resolves #5784 

Reposition the camera scan icon in the wallet > send functionality and also changing the camera icon to a scan qr icon.

2024-02-26 21:49 UTC, dstrukt approved these changes
LGTM!

cc @dennisreimann for code coverage

2024-02-27 11:38 UTC, dennisreimann requested changes
Just some minor adaptions: Let's unify this to our custom icon and keep the input validation message.

2024-02-27 11:38 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletSend.cshtml
> +
```suggestion
            <span asp-validation-for="Outputs[0].DestinationAddress" class="text-danger"></span>
```

2024-02-27 11:38 UTC, dennisreimann commented on BTCPayServer/Views/UIWallets/WalletSend.cshtml
> +                <button type="button" id="scanqrcode" class="btn btn-secondary only-for-js" data-bs-toggle="modal" data-bs-target="#scanModal" title="Scan BIP21/Address with camera"><i class="fa fa-q
```suggestion
                <button type="button" id="scanqrcode" class="btn btn-secondary only-for-js" data-bs-toggle="modal" data-bs-target="#scanModal" title="Scan BIP21/Address with camera">
                    <vc:icon symbol="scan-qr"/>
                </button>
```

2024-02-28 08:36 UTC, dennisreimann approved these changes
Adjusted the icon size, so that the stroke line doesn't look blurry. tACK

2024-02-28 08:38 UTC, dennisreimann commented
![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/fcc37aff-6237-41e1-bc9e-7de454e2de29)

2024-02-28 09:41 UTC, merged

2024-03-05 17:03 UTC, bwirsche commented on BTCPayServer/Views/UIWallets/WalletSend.cshtml
> +
>how do I pull my own bitcoin