update csv export to include full date and time in 12 hour format
btcpayserver/btcpayserver pull request #5922
Opened 2024-04-10 06:44 UTC by TChukwuleta

Resolves #5915

2024-04-10 07:11 UTC, Kukks requested changes
This is a breaking change so extra care should be considered.  Maybe we need to see what the old export on the invoices page used to export first

2024-04-10 07:22 UTC, TChukwuleta commented
This is the csv export view prior to this requested change. In 24 hours format:

![image](https://github.com/btcpayserver/btcpayserver/assets/47084273/e9bdb5be-76ca-456e-9aa9-a2980da4284f)

2024-04-12 10:45 UTC, dennisreimann commented on BTCPayServer/wwwroot/js/store-reports.js
> +    modifyFields(srv.result.fields, data, 'datetime', v => v ? moment(v).format("dddd, MMMM Do YYYY, h:mm:ss a"): v);
To not break the curent format I'd suggest to simply use proper ISO format with added timezone info, like this: 

```suggestion
    modifyFields(srv.result.fields, data, 'datetime', v => v ? (new Date(v)).toISOString().replace('T', ' '));
```

Not sure if `v` is a `Date` already, if so it could be `v.toISOString()`.

2024-04-15 01:51 UTC, NicolasDorier commented on BTCPayServer/wwwroot/js/store-reports.js
> +    modifyFields(srv.result.fields, data, 'datetime', v => v ? moment(v).format("dddd, MMMM Do YYYY, h:mm:ss a"): v);
we shouldn't do string manipulations to format dates when we have a library to do things properly.

2024-04-15 01:56 UTC, NicolasDorier commented
@TChukwuleta I think you only have to change `'YYYY-MM-DD hh:mm:ss'` to `'YYYY-MM-DD HH:mm:ss'`. This format is making sure excel recognize the cells as date.

2024-04-15 03:21 UTC, merged