Setting up defailt exchange provider
btcpayserver/btcpayserver pull request #5979
Opened 2024-05-11 03:23 UTC by TChukwuleta

Resolves #5653, allowing admin to setup default exchange provider

2024-05-11 12:55 UTC, NicolasDorier commented
It will need a few changes and go after https://github.com/btcpayserver/btcpayserver/pull/5976, but I can take it from here.

I think we will need to talk to @dstrukt. This UX is simple, but lacking flexibility as it only allows to change the recommended exchange for the default currency.

On one side, maybe we don't really care about the lack of flexibility. An admin changing this setting will probably change it once in his life, as all his merchants should use the same default currency.

On the other side, it doesn't allow an admin to change the recommended exchanges for other currencies.

2024-05-11 13:05 UTC, TChukwuleta commented
I think the flexibility would be good one to have.

I have a follow up question, if an admin has merchants in different countries (say Nigeria and  Ghana), how would the currencies be managed if the intentions is for all the merchants to use the same default currency

2024-05-15 00:24 UTC, NicolasDorier commented
@pavlenex @dstrukt we will need some guidance here

So from https://github.com/btcpayserver/btcpayserver/pull/5976, it is possible to take whatever exchange is recommended for the selected currency. (rather than forcing the same exchange for all currencies)

This PR aims at allowing the admin to setup the recommended exchange for the default currency.

The good side is that this is simple to understand.

The bad side is that it doesn't allow the customization of recommended exchange for non default currency. 

I am tempted to keep it simple like this PR, as our original goal is to allow local admin to streamline the experience for their local merchant. (ie, for the default currency)

2024-05-16 19:13 UTC, dstrukt commented
Discussed on today's design call. Not sure if @dennisreimann is going to implement the additional dropdown solution we discussed, so will leave it to him add any additional context, or leave it to @TChukwuleta, but thought I'd provide an update.

2024-05-16 20:30 UTC, TChukwuleta commented
Thanks @dstrukt

2024-05-17 07:34 UTC, dennisreimann commented on BTCPayServer/Views/UIServer/Policies.cshtml
> +                <input asp-for="DefaultCurrency" placeholder="@StoreBlob.StandardDefaultCurrenc" class="form-control" currency-selection />
```suggestion
                <input asp-for="DefaultCurrency" placeholder="@StoreBlob.StandardDefaultCurrency" class="form-control" currency-selection />
```

2024-05-17 07:35 UTC, dennisreimann commented on BTCPayServer/Views/UIServer/Policies.cshtml
> +            var currencyInput = document.getElementById("currencyInput");
```suggestion
            var currencyInput = document.getElementById("DefaultCurrency");
```

2024-05-17 07:55 UTC, dennisreimann approved these changes
tACK. Ideally we'd also combine this with the rate provider recommendations, e.g. Kraken for EUR — but I think this is more complex and would involve some more JS.

2024-06-28 13:22 UTC, NicolasDorier commented on BTCPayServer/Views/UIServer/Policies.cshtml
> +            exchangeDiv.classList[currencyInput.value.trim() !== "" || '@Model.DefaultCurrency' !== "" ? "remove" : "add"]("d-none");
There is a XSS vulnerability here. It needs to be wrapped with `@Safe.Json`

2024-06-28 13:28 UTC, NicolasDorier commented
There is a vulnerability, and it doesn't work for me.

I selected JPY and recommendation `Bitflyer`, but the recommendation is still `Bitbank`.

2024-07-02 13:16 UTC, NicolasDorier requested changes
XSS vulnerability, and not actually changing the recommendation.

https://github.com/btcpayserver/btcpayserver/pull/5979/files/d331ec3f3f02d0ee84d61aae024cbd8177245780#r1658737631

2024-07-02 13:27 UTC, TChukwuleta commented
Going to look at this

2024-07-03 06:23 UTC, TChukwuleta commented on BTCPayServer/Views/UIServer/Policies.cshtml
> +            exchangeDiv.classList[currencyInput.value.trim() !== "" || '@Model.DefaultCurrency' !== "" ? "remove" : "add"]("d-none");
Wrapped it. You can also retry setting up a default exchange provider @NicolasDorier

2024-09-07 08:49 UTC, pavlenex commented
@TChukwuleta What's the status on this one?

2024-09-07 09:43 UTC, TChukwuleta commented
Hey Pav.. I got this resolved already. 

But let me work on the pipeline failure.

Sure totally agree to moving to 2.0.1

2024-09-12 12:37 UTC, TChukwuleta commented
Hey @NicolasDorier  Could you take another look at this and also test. Thanks

2025-03-07 20:50 UTC, closed without merging