User: Add name and image URL
btcpayserver/btcpayserver pull request #6008
Opened 2024-05-25 18:57 UTC by dennisreimann

More personalization options, prerequisite for btcpayserver/app#3.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/0a162e58-afff-4274-a739-e171eb26c3a1)

2024-05-26 19:15 UTC, dstrukt requested changes
Amazing, functional tACK!

Nit: 

- [ ] Rename `Image` label to `Profile Picture` (my preference) or `Profile` label

- [ ] How are we handling horizontal, non square 1:1 images? Think a 1:1 might be a little more clean, compared to what we're currently doing:

<img width="604" alt="Screen Shot 2024-05-26 at 12 12 53 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/4f572ddd-e4eb-409e-9a34-d31797f612cf">

I was curious how you handled the case in which there is no profile picture (mostly for the app to have a default filler image, which I think would look best), but I do like that it's hidden until you upload an image. Having a default image for the mobile app could be a nice edge case scenario. Regardless either work, just a thought as I review.

2024-05-28 17:44 UTC, dstrukt approved these changes
tACK - LGTM!

Thanks for the changes!

2024-06-13 03:52 UTC, louieo commented
My first PR review here as you suggested @dennisreimann. tACK - the changes look good to me!

<img width="1251" alt="Screenshot 2024-06-13 at 1 43 40 PM" src="https://github.com/btcpayserver/btcpayserver/assets/31303385/9e48bcd8-e351-4ffc-bb00-58651345f2df">

I did however try uploading a larger image (1.3MB jpg) and my profile pic was not set and there was no error message. Is the file size limited and should there be an error message displayed if above max size?

2024-06-13 04:56 UTC, dstrukt commented
> I did however try uploading a larger image (1.3MB jpg) and my profile pic was not set and there was no error message. Is the file size limited and should there be an error message displayed if above max size?

Great catch, I'd think we should probably limit the file size or reduce the file size / dimension upon upload for specific assets (profile picture, logos, etc..)!

2024-06-13 07:25 UTC, dennisreimann commented
Thanks, the validation was present, but the check for whether the state is valid had to be moved. Fixed it.

![grafik](https://github.com/btcpayserver/btcpayserver/assets/886/5e9eee77-b2bc-472b-865e-a13fa5908a06)

2024-06-26 00:54 UTC, NicolasDorier commented
@dennisreimann please look my two commits

2024-06-26 01:09 UTC, NicolasDorier commented
Note for [6041](https://github.com/btcpayserver/btcpayserver/pull/6041): you are using MailboxAddressValidator to validate in the controller.
However, this validate addresses in this form: Firstname Lastname <blah@example.com> as well as blah@example.com.
I am not sure what happen if you attempt to use Firstname Lastname <blah@example.com> from the API. (The UI has an additional validator at the VM side)

2024-06-26 08:34 UTC, NicolasDorier commented on BTCPayServer/Controllers/GreenField/GreenfieldUsersController.cs
> +            if (!string.IsNullOrEmpty(request.Email) && !request.Email.IsValidEmail())
cool, forgot we had this extension method

2024-06-26 08:39 UTC, merged