explore plugins
btcpayserver/btcpayserver pull request #6032
Opened 2024-06-05 00:52 UTC by TChukwuleta

Resolves #4905 

Things to review:

Explore Plugins List View

 Manage Plugins List View

 Plugin Detail View modal (image section is still open to discussion)
 
  Adds Manage and Explore links to the left sidebar
  
  Would continue on it as conversations unveil.
  
  Cc. @dennisreimann  @dstrukt @pavlenex

2024-06-05 02:23 UTC, dstrukt commented
Visual reference for these changes & the corresponding issue https://github.com/btcpayserver/btcpayserver/issues/4905: 

<img width="1537" alt="Screen Shot 2024-05-28 at 9 28 26 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/304b8dc5-5691-43f9-9238-850faf351f1d">

<img width="808" alt="Screen Shot 2024-05-28 at 9 27 48 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/1fd37fd4-2624-4d2f-ad9f-a20d6f948bf9">

<img width="955" alt="Screen Shot 2024-05-28 at 9 27 27 AM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/683b2124-e9b8-4615-8dfe-2057b64242aa">

2024-06-05 03:07 UTC, dstrukt requested changes
# STILL REVIEWING! - WILL REMOVE

# Explore View

- [ ] Need to replace the sidebar explore icon

- [ ] Horizontally center the logo and the title/description
<img width="471" alt="Screen Shot 2024-06-04 at 8 35 37 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/da9deeae-c762-407c-b074-f1c2d6159e09">

- [ ] let's round the border radius of the app asset (16px), not sure what the size would be off the top of my head

- [ ] let's put the search above the tabs in order

- [ ] i realize we use the `card` class for structure, but let's kill the background color and border on the app card

- [ ] we'll probably want to hide the Upload Plugin a bit further down considering it's a pretty experimental feature atm

# Plugin Details Modal

- [ ] let's bump the size up to the `xl` modal

- [ ] I'd like to bump the modal body padding up a size, from the current `16px` to perhaps `32px`? not sure if we'll need to make a new class to support this
<img width="1292" alt="Screen Shot 2024-06-04 at 10 40 30 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/669196d1-8d61-45ea-be30-f7175232e9d2">

- [ ] let's kill the Version & Developer name under the plugin title, and push them to the right hand side menu
- [ ] we can also push the `Dependencies` over there too
- [ ] we can also push the Sources / Documentation over there as well
- [ ] might need to reduce the padding above the description and below the title with this adjustment
<img width="829" alt="Screen Shot 2024-06-04 at 11 04 11 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/46dfcf9d-7ed2-4d47-84b5-02d218a8f1e8">

- [ ] let's align the main CTA button to the top of the container, should be easier with just the title / CTA
<img width="553" alt="Screen Shot 2024-06-04 at 8 27 36 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/1860acac-05ea-4f4a-b0f3-bba0d8b2ddb8">

# Thoughts / Suggestions:

Assuming we can:

- [ ] might want to add a support section?
- [ ] support for screenshots?

2024-06-06 03:53 UTC, dstrukt commented
> Yay, is going to be very nice! I don't have much to add to dstrukt's feedback, just keep in mind that we might want to incorporate the new subnav and breadcumb pattern here too once #5744 is merged. E.g. for listing the categories as subnav items under Explore.
> 
> One more thing I noticed is that the Manage page has the headline "Installed Plugins" with no content in case there are no plugins installed. Maybe we can fix this here too.

Agree 100% with the latter, but wrt the sidebar tabs, I wonder if we could get away with not displaying in the sidebar if we don't think it adds value / to keep the sidebar cleaner.

2024-06-07 07:36 UTC, TChukwuleta commented
@dstrukt made the correction. 

You can take another look

2024-06-07 23:05 UTC, dstrukt commented
This is looking great! Screenshots for those following along:

<img width="1519" alt="Screen Shot 2024-06-07 at 5 04 10 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/1a2f5b47-75ed-4df5-b7b2-98c82a0a21d1">

<img width="1504" alt="Screen Shot 2024-06-07 at 5 03 59 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/2beed084-9991-4a13-b153-955183d7ad29">

Will submit another round of review here shortly, there are a few other things, but this is going very quickky!

2024-06-08 04:00 UTC, dstrukt requested changes
# Search

- [ ] should keep the search result in the Search bar after submit
- [ ] should only show 1 result, independent of the Recent/Popular/etc.. sections
- [ ] should probably also hide the Upload button, when showing Search results (we'll figure out a better location for Plugin uploading)
<img width="612" alt="Screen Shot 2024-06-07 at 9 54 18 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/a9c21fd4-9d50-42a6-a78b-b04896a216cc">


# Explore

- [x] let's bump the size of the icon up to `76px `or `80px` from `64px`

- [x] let's change from `rounded-1` to `rounded-4` class on the plugin icon

# Detail Modal

- [ ] let's knock the bottom border opacity (on the right side) from 0.5 -> 0.1
- [ ] let's hide the `:last-child` bottom border as well


# Mobile

- [x] I think this section is probably okay, but we should make this responsive for the more extreme cases
<img width="469" alt="Screen Shot 2024-06-07 at 5 24 08 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/30a897b3-a80b-4ff1-ac8f-c2d44643ce20">

- [x] We should break this on mobile such that either the stats appear above the images, or visa versa
<img width="456" alt="Screen Shot 2024-06-07 at 5 24 05 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/a53a149f-d9a8-4fcb-860e-6d2f3ec280c9">



# Open Questions

- [x] What else do we need to do to pull/update real plugin image assets?

2024-06-08 13:16 UTC, TChukwuleta commented
@dstrukt regarding pulling/updating real plugin image assets, on the plugin builder project,  when creating a plugin, we can allow an upload..

Then on the settings users can also update the plugin image, so that when we are pulling all information, we can also retrieve the plugin image, and if there is none, we'd use the btcpay logo as default

2024-06-08 19:02 UTC, dstrukt commented
> I think plugin owner socials (twitter, nostr, mail) can be added, but that part is optional, so was thinking how we'd fit it in the modal

I think we could probably add them to the right hand list, e.g.

Twitter     `@name` (link to twitter)
Nostr        `xpub` OR `View`? (links to nostr)
Mail         `email@domain.com` (mailto: link)

As for the page, I figured we might have like `Popular`, `Recent Uploads`, and `Recently Updated`, or something along those lines ultimately, but I don't know if we have any metrics to accurately depict the `Popular`.

`Recent Uploads` should be easy enough, if within the last month? maybe last week in the future if plugins pick up

`Recently Updated` could be the same, but if a new version change happens .. but not 100% sure if we have the capacity to do this?

However, if any of this is too complicated at this stage, we can always just dump All of the plugins out on this view, and add the categories and these sections in later.

cc @pavlenex @dennisreimann any thoughts on the above?

Defer to you on this.

if you'd rather me just drop it there to respond

2024-06-18 06:43 UTC, dennisreimann commented
I've added the review icons and updated the explore one in #5744. They'll become available here once that PR is merged and we can rebase this one.

2024-07-05 14:17 UTC, pavlenex commented
@TChukwuleta I've tried running this PR locally, but I am not getting any plugins, am I doing something wrong? Can someone remind me what I have to do for plugin list be visible locally?

2024-07-05 15:39 UTC, TChukwuleta commented
@pavlenex  do you have any plugin installed?

that section is for installed plugins. 

THe explore navbar contains all other plugins

2024-07-05 17:01 UTC, pavlenex commented
@TChukwuleta I just clicked on `Manage Plugin` in the sidebar, there's no other option?

2024-07-05 17:04 UTC, pavlenex commented
Hey @TChukwuleta Whose idea was to separate this? I think it's confusing to have it under different views, currently it's not. @dstrukt is this how we designed it?

2024-07-05 17:52 UTC, dstrukt commented
> Hey @TChukwuleta Whose idea was to separate this? I think it's confusing to have it under different views, currently it's not. @dstrukt is this how we designed it?
> 
> At first glance things look really nice. A big improvement.but manage and explore separation was a big unclarity for me, and I would assume it'll be for everyone. I am curious if there was a reason those two were separated?

The distinction and separation was discussed a few times in the past. 

The overarching motivation being, you're either looking for a plugin, or you're managing an existing plugin. It helps create a clear delineation of action for both, e.g. when searching, all you do is "Install", but managing, you're upgrading/unistalling/resetting/configuring settings, etc.. so that all of these options are not in the same view / UI.

Most app stores, plugin stores, etc.. break it into this architecture. It could be framed "Installed / Not Installed", or however we'd like, but essentially it is the same. 

I'm away from my computer atm, but tried my best to be succinct.

2024-07-05 18:27 UTC, TChukwuleta commented
> Hey @TChukwuleta Whose idea was to separate this? I think it's confusing to have it under different views, currently it's not. @dstrukt is this how we designed it?
> 
> At first glance things look really nice. A big improvement.but manage and explore separation was a big unclarity for me, and I would assume it'll be for everyone. I am curious if there was a reason those two were separated?
> 
> So on my end:
> 
> * Not convinced explore/manage separation is a good idea or UX improvement.
> * Would like to have X to close plugin preview pop up
> * Would prefer (but not a deal breaker) that I don't have to press enter in search to filter plugin, and getting back to a default page requires me to empty a search and press enter again
> * Do we expect to have categories or just popular and recent
> * How do we sort popular, based on what?
> * I somehow managed to break server by clicking "install" entire styling got nuked, to replicate try to install more than one plugin without restarting
> 
> <img alt="Screenshot 2024-07-05 at 19 09 13" width="1440" src="https://private-user-images.githubusercontent.com/36959754/346188862-fbdf9462-2d35-4ad0-9ceb-45877b8812e7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDM5MTIsIm5iZiI6MTcyMDIwMzYxMiwicGF0aCI6Ii8zNjk1OTc1NC8zNDYxODg4NjItZmJkZjk0NjItMmQzNS00YWQwLTljZWItNDU4NzdiODgxMmU3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE4MjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0OWVjMzJhZDE3M2ZiMDMwMzg1ZWU1NjNkMjc4YjNlZmQ1NTdmYjZhZDdjMzE0YzI2YzAxOGQwZDgwZjU1OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HyzjZLNRQV_UlEuEgIrdO3nbLqZvGoCBJ8upTabqJRc"> <img alt="Screenshot 2024-07-05 at 19 10 58" width="1439" src="https://private-user-images.githubusercontent.com/36959754/346189002-9f471616-3dde-4e44-8ec4-44cecd0c6e36.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAyMDM5MTIsIm5iZiI6MTcyMDIwMzYxMiwicGF0aCI6Ii8zNjk1OTc1NC8zNDYxODkwMDItOWY0NzE2MTYtM2RkZS00ZTQ0LThlYzQtNDRjZWNkMGM2ZTM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE4MjAxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjZmJkYTkwMTA5MTY4ZjlhZjI0M2UxMTg5NGQ4NzY2YmZhY2RiZGJhYjU4NmYzOWQxMDllN2FhMjQ5OGI3MDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8ql_0GDTmNLDUoNw-6zvwYx7xqZ-Yt--v-lfb6TnlBU"> Server logs say just this:
> ```
> warn: PayServer:      Torrc file is not found
> warn: PayServer:      Torrc file is not found
> ```

Noted some of your point.. 
Would make the necessary UI improvement.

Conversations around categories are not yet settled in. But the goal is to have it included.

2024-07-12 14:41 UTC, TChukwuleta commented
@pavlenex  You can have another look at the search functionality and the modal closure.

How do you suggest that popular flog is handled?

2024-07-30 17:02 UTC, TChukwuleta commented
Hey @dennisreimann 
Could you help review these PRs? so that I can test out the popular section and also the plugin image if any was uploaded.

https://github.com/btcpayserver/btcpayserver-plugin-builder/pull/14

https://github.com/btcpayserver/btcpayserver-plugin-builder/pull/13

2024-09-07 08:52 UTC, pavlenex commented
Where are we with this PR? I think the scope here is to add redesign explore functionality and it seems it's there.

It seems it's waiitng for @dennisreimann code review, @dstrukt final UI review and then @NicolasDorier can take a final and decide if we want this in 2.0.0. Imo this one is nice visual feature and a good improvement, as long as it's scoped and easy to review we can do it for 2.0.0, otherwise 2.0.1

2024-09-07 08:56 UTC, pavlenex commented
Actually let's do this one for 2.0.1 we have too many things on our plate now.

2024-09-07 17:51 UTC, dstrukt commented
ACK

Yeah I think that's wise, I still owe @TChukwuleta quite a few things that got pushed back due to App and Riga, so I'll be revisiting this so we can get the plugin UI/UX work wrapped up.

2024-09-09 10:19 UTC, dennisreimann approved these changes
tACK. I've changed a few minor things, the most notable is adding a background to the items in the explore list. Other than that, I unified some of the things across Explore and Manage and removed the Upload from the Explore page.

@dstrukt feel free to adapt this if you don't like it, my impression was that adding the background helps to distinguish the individual items.

2024-09-12 05:00 UTC, dstrukt requested changes
Still think we need another round of fairly involved changes IMO, but trying to be thorough so we can knock these changes out and get this merged asap.

# STILL REVIEWING / WILL ADD PHOTOS

# Sidebar

- [ ] I don't think we should have a status icon for the `Manage` section on the sidebar

- [ ] I'm not sure the plugins that are installed are being added to the Sidebar, I have the Whitepaper and FileSeller enabled currently, and I don't see them.

# Explore & Manage Views

- [ ] We should probably turn the "plugins are third-party, etc.." warning notification to descriptive text, having to dismiss / the loudness of the notification is a bit annoying imo

# Explore View

- [ ] The category `All` should be hidden when searching.

- [ ] Let's put `Recent` first, and cap it at 9?

# Detail Modal

- [ ] If a plugin is installed, we should see `Remove / Disable Plugin` on the Explore view CTA

- [ ] Do we want to add Socials, etc...?

# Manage View

- [ ] We should format the Plugins that are pending install too, esp. if this is going to be a  standard view

- [ ] We should probably allow the user to see the Details modal from the Manage view, and the CTA should be `Uninstall / Remove`

2024-09-13 15:51 UTC, TChukwuleta commented
Hey @dstrukt  you could give it another view, made an update.


> * [ ]  I'm not sure the plugins that are installed are being added to the Sidebar? I have the Whitepaper and FileSeller enabled currently, and I don't see them.

Not all plugins were added to the sidebar. Its been like this, thought it was the plan.

> * [ ]  Should plugins be hidden from this view if they're already installed? Or should we give some indication that they're already installed if we keep them? Thoughts cc @dennisreimann?

So what I did was to exclude the installed plugin but now that you have mentioned it I think it is a good idea to keep them, just with a different button text say uninstall/Disable.

> * [ ]  Do we want to add Socials, etc...? 

This should be good to go, someone can update their social details on the builder and it should reflect

> * [ ]  We should probably allow the user to see the Details modal from the Manage view, and the CTA should be Uninstall / Remove

In that case would there be need for the buttons that are vertically stacked on the right?



Things to review based on latest push:

Manage should have a default message, if no plugins, that pushes people to the Explore view (might already, but I started installing, so need to confirm this)

The Server Settings accordion is expanded when the Explore view is selected, shouldn't be expanded

 The category All should be hidden when searching.

 Let's actually kill the background color on the cards, looks better without imo

We should probably turn the "plugins are third-party, etc.." warning notification to descriptive text, having to dismiss / the loudness of the notification is a bit annoying imo

 Let's put Recent first, and cap it at 12? (for even divisibility on mobile)
 
 We should include a link / CTA to Submit your own or to the Plugin builder repo/site

2024-09-16 19:29 UTC, dstrukt commented
> Not all plugins were added to the sidebar. Its been like this, thought it was the plan.

Yes, you're correct. I guess I thought those added a sidebar item. On additional thought, it might be something worth trying to encourage for some plugins, as it makes figuring out the Settings a bit easier than poking around in the rest of the UI to find them? cc @pavlenex @dennisreimann 

> This should be good to go, someone can update their social details on the builder and it should reflect

Oh nice, they just must have been added for the plugins I tested!

> In that case would there be need for the buttons that are vertically stacked on the right?

Hmm, good question, I guess not stacked, but horizontal - will confirm on review

> We should format the Plugins that are pending install / delete too, esp. if this is going to be a standard view [Screenshot]

I guess it's specifically for the Pending Actions section. We shouldn't have duplicates, but just the label `Pending Actions` and the card(s) formatted underneath that section.

i.e:
<img width="1386" alt="Screen Shot 2024-09-11 at 9 42 13 PM" src="https://github.com/user-attachments/assets/b3e1de8d-7c08-4797-8d35-15f8ed94595d">
<img width="1386" alt="Screen Shot 2024-09-11 at 9 42 13 PM" src="https://github.com/user-attachments/assets/5cd01ba5-8173-4bce-ac41-fdd9cd387127">


## Minor nits (sorry, i know i'm extremely particular, but I think this is it!):

- [ ] This shouldn't change to the error state when there are disabled plugins, let's leave the icon, until we have a more elegant solution

<img width="170" alt="Screen Shot 2024-09-16 at 12 23 00 PM" src="https://github.com/user-attachments/assets/db554d95-705f-41d1-af9f-5d16734b3cfb">

- [ ] We should treat the `Disabled Plugins` section like the `Pending Actions` section and use the cards

<img width="1426" alt="Screen Shot 2024-09-11 at 9 56 52 PM" src="https://github.com/user-attachments/assets/9a4a80c2-2767-49c7-bfb3-21f91a4b95ce">

- [ ] Let's reduce the bottom margin on these cards to `mb-2` from `mb-4`

![Uploading Screen Shot 2024-09-16 at 11.44.25 AM.png…]()

- [ ] Perhaps we kill the left padding on the card, so that the items sit flush to the left of the container? cc @dennisreimann might have a better suggestion for how to properly handle this case

<img width="1060" alt="Screen Shot 2024-09-16 at 11 45 46 AM" src="https://github.com/user-attachments/assets/d4874b2d-2fa2-4886-9bcc-1afdbe82fd2f">

- [ ] `rockstardev` is still white, but it's a link to his twitter account, we should make any of these links the brand green

<img width="116" alt="Screen Shot 2024-09-16 at 11 47 22 AM" src="https://github.com/user-attachments/assets/e4e1fa78-bd17-48b3-b237-591cc3c91eec">

- [ ] On mobile, let's format the button(s) to the left

<img width="505" alt="Screen Shot 2024-09-11 at 8 51 02 PM" src="https://github.com/user-attachments/assets/7e186a52-b8ff-4119-ba01-db2661b653b3">

 - [ ] We might want to add the current version of BTCPay in the alert message, we have it listed in the footer, but many may not realize this (and in the future we should probably find a better place for it), but I think this error message strikes a nice balance at the moment.
 
<img width="1765" alt="Screen Shot 2024-09-16 at 12 23 10 PM" src="https://github.com/user-attachments/assets/ace5fc50-cd24-440d-ac57-2b18d9e34d3b">

## Bigger topic worth formalizing:

- [ ] Should we have an additional label / sorting for BTCPay Reviewed or Created

- [ ] Should plugins be hidden from this view if they're already installed? Or should we give some indication that they're already installed if we keep them? Thoughts cc @dennisreimann?

2024-09-17 15:33 UTC, dennisreimann commented
> On additional thought, for the future, it might be something worth trying to encourage for some plugins, as it makes figuring out the Settings a bit easier than poking around in the rest of the UI to find them?

I'm not sure and guess it's in the best interest of the plugin developer to expose relevant functionality via the navigation. In cases like the whitepaper plugin it doesn't really make sense to surface an extra UI, I'd say.

>  This shouldn't change to the error state when there are disabled plugins, let's leave the icon, until we have a more elegant solution

We introduced the error state to make admins aware that some plugin got disabled. I still think this should happen as it might even be a payment relevant plugin that got disabled.

> Should plugins be hidden from this view if they're already installed? Or should we give some indication that they're already installed if we keep them?

Having an indicator would be nice imho.

2024-09-24 04:53 UTC, dstrukt requested changes
Will bring up any other changes we might need in tomorrow's Design Call:

- [ ] the formatting on this is broken
<img width="1367" alt="Screen Shot 2024-09-23 at 9 40 45 PM" src="https://github.com/user-attachments/assets/8ff4a591-d646-41df-aa8e-421ffdcaca09">

2024-09-26 19:22 UTC, rockstardev commented
I reviewed this PR, and I think we should revisit it as a whole team before we invest more time and effort. This definitely needs to be brought up during a team-wide dev call to ensure we're all on the same page.

To highlight one key issue, take a look at the comparison between the old and new versions of the homepage:

- **Old version:**  
  ![image](https://github.com/user-attachments/assets/929d9571-1f1d-4149-b487-6d11465182fc)

- **New version:**  
  ![image](https://github.com/user-attachments/assets/40b63617-f977-4c9c-a205-7663e5109201)

In the new version, a lot of important data is missing. In the old version, each plugin clearly listed its creator and included a link to the repository with the source code. Now, that information is hidden behind a click, and all plugins default to the BTCPay logo, which increases confusion - it should be clearly stated and obvious that BTCPay doesn't develop plugins and take any responsibility.

I’ll go through the codebase to figure out the best way to proceed. Feel free to DM me on Mattermost if any discussions come up about this.

2024-09-26 19:24 UTC, rockstardev requested changes
I reviewed this PR, and I think we should revisit it as a whole team before we invest more time and effort. This definitely needs to be brought up during a team-wide dev call to ensure we're all on the same page.

To give the most obvious example, take a look at the comparison between the old and new versions of the homepage:

- **Old version:**  
  ![image](https://github.com/user-attachments/assets/929d9571-1f1d-4149-b487-6d11465182fc)

- **New version:**  
  ![image](https://github.com/user-attachments/assets/40b63617-f977-4c9c-a205-7663e5109201)

In the new version, a lot of important data is missing. In the old version, each plugin clearly listed its creator and included a link to the repository with the source code. Now, that information is hidden behind a click, and all plugins default to the BTCPay logo, which increases confusion - it should be clearly stated and obvious that BTCPay doesn't develop plugins and take any responsibility.

I’ll go through the codebase to figure out the best way to proceed. Feel free to DM me on Mattermost if any discussions come up about this.

2024-09-26 20:11 UTC, TChukwuleta commented
Hey Uncle @rockstardev just wanted to point out some things.

>  all plugins default to the BTCPay logo, which increases confusion 
> 

On the plugin builder, the goal is for each publishers to upload logo for each plugin, and there there is no logo that has been updated, the logo would be defaulted to BTCPay logo

>  it should be clearly stated and obvious that BTCPay doesn't develop plugins and take any responsibility.
> 

This can be included

2024-09-26 21:37 UTC, dstrukt commented
Appreciate the feedback @rockstardev. Agree we need to get on the same page wrt plugins, would love to be in that call as well.

However, wrt to what we show, we can certainly add more plug-in details to the Explore view (perhaps re-add the author), but think we should try to keep it minimal and only expose what is absolutely essential, as the `Before` is quite noisy/redundant, and this is a Search/Exploration view, not the management view of plugins. 

As @TChukwuleta has pointed out, that image asset is intended for the unique plug-in creator to help further differentiate their plugins (but this requires a bit of co-ordination from the creators). More disclaimers, etc.. can easily be added as well.

Regardless can make the case for any of these things in the call. Looking forward to hearing everyone's thoughts!

2024-09-27 02:47 UTC, rockstardev commented
Sure, let's plan to jump on a call to discuss the details. In the meantime, I'm trying to clear up the backlog of PRs on: https://github.com/btcpayserver/btcpayserver-plugin-builder/pulls

I'll also look into proposing alternative implementation here in preparation for our discussion.

2026-03-18 11:55 UTC, pavlenex commented
@TChukwuleta I think this one can be closed?

2026-03-18 12:58 UTC, TChukwuleta commented
Yes it can be.. 

we'd be moving all changes to plugin builder and use iframe in place

2026-03-18 12:58 UTC, closed without merging