Notificationlist
btcpayserver/btcpayserver pull request #6050
Opened 2024-06-12 16:44 UTC by TChukwuleta

Resolves #3871 

@dstrukt did Include the store column, as not all notifications are associated with a store.

But outside of that, open to review.

2024-06-12 23:52 UTC, dstrukt requested changes
Overall, this looks great! Awesome work!

# General

- [ ] let's kill the `ms-3` class on all of the buttons
- [ ] we could increase the `gap-3` to `gap-4` at the parent form level

these spacing changes could help solve some of the problems below

- [ ] For the types, let's combine the User related ones to `User Updates`
- [ ] combine Payout+External Payout -> `Payouts`
- [ ] `New Version` to `BTCPay Server Updates` or `Server Updates`
- [ ] `Plugin Update` to `Plugin Updates`

# Mobile

- [ ] Ideally the tabs sit flush to the left
- [ ] Also, it would be nice if everything sat on the same line
<img width="515" alt="Screen Shot 2024-06-12 at 4 53 45 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/b50799b9-0f04-4a90-82a3-c688c3c047a4">

- [ ] Some things get cut off on the tablet breakpoint, not sure what we can do about this?
<img width="923" alt="Screen Shot 2024-06-12 at 4 54 09 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/bcc5c31b-d838-4741-b0d3-172d23f66ecd">

- [ ] there's an in-between state between tablet and mobile where the options are hidden, minor, but worth noting

<img width="610" alt="Screen Shot 2024-06-12 at 5 46 01 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/54d4f055-dbfc-4a19-9e49-ad2eea0cec73">

Otherwise, I think we're good to go!

@dennisreimann It'd be great to get another pair of eyes on this, and @pavlenex it'd be great to get a functional review from you!

2024-06-13 08:57 UTC, TChukwuleta commented
Alright. Will update later accordingly

Thank you

2024-06-13 15:32 UTC, dennisreimann reviewed
Code LGTM so far. The addition of the store ID to the notifications will be very helpful for the app as well.

2024-06-13 15:32 UTC, dennisreimann commented on BTCPayServer/Controllers/UINotificationsController.cs
> +using Amazon.Runtime.Internal.Transform;
This might have slipped in.

2024-06-13 19:04 UTC, dstrukt commented
> * The All/Unread switch could have the primary class for highlighting instead of secondary. There's no CTA on that page and imho that toggle has the most important functionality.

Completely agree, and was going to do a follow up design component issue, but if we can tackle here, that'd be great!

2024-06-14 05:53 UTC, TChukwuleta commented
made the update

2024-06-14 22:42 UTC, dstrukt requested changes
Thanks for the changes, it looks excellent! All of my requested changes look good - last 2 nits and we're good! Great work! 

- [x] let's make the active tab our `primary` green / variable, not the darker green

<img width="476" alt="Screen Shot 2024-06-14 at 4 38 37 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/f47b1f11-d2aa-41e1-9050-f6f5c8485764">


- [ ] can we kill the `gap-4` class on mobile breakpoint to tighten up the height?

<img width="500" alt="Screen Shot 2024-06-14 at 4 39 50 PM" src="https://github.com/btcpayserver/btcpayserver/assets/6250771/b53e7455-1543-4836-8d7c-c717fb8ee082">

Otherwise, this looks good to go!

Requested re-review from @dennisreimann in case he has anything else.

2024-06-15 04:10 UTC, dstrukt commented
Tested the latest, DM'd a quick fix, will approve after!

2024-06-15 14:12 UTC, dstrukt approved these changes
tACK - LGTM

2024-06-17 09:51 UTC, dennisreimann approved these changes
tACK, good job!

2024-06-19 18:16 UTC, dstrukt commented
Was this a new review request @pavlenex? Or due to the potential merge conflicts from the sidebar PR? cc @dennisreimann

2024-06-19 18:20 UTC, dennisreimann commented
Will rebase this and update with the changes from the sidebar/subnav PR tomorrow.

2024-06-20 13:13 UTC, dennisreimann approved these changes

2024-06-30 10:28 UTC, NicolasDorier commented
Seems good, @TChukwuleta can you squash the commits, and put a proper commit message?

2024-07-02 08:55 UTC, merged