Add updated image upload support on Crowdfund plugin
btcpayserver/btcpayserver pull request #6254
Opened 2024-09-26 14:33 UTC by TChukwuleta

Resolves #6242 

By changing the featured image from an input field to a custom upload

2024-09-26 16:52 UTC, dstrukt commented
Beautiful, will get this reviewed here shortly!

2024-09-26 22:03 UTC, dstrukt commented
tACK - looks great!

When you run into a validation issue (i.e. not inputting a description), it removes the uploaded images - technically, is there any way we can keep the image until it's explicitly removed (even on refresh)?

I'm not sure if we do this elsewhere, possibly the Point of Sale products, but @dennisreimann might be able to weigh in.

If not, consider this a tACK, and will update my review.

Great job!

2024-09-26 22:08 UTC, dstrukt reviewed
See above.

2024-09-27 05:39 UTC, TChukwuleta commented
I don't think it is possible to pass file back to the view, unless the file has been uploaded (has url), because at this point the file hasn't been uploaded (this is done after validation checks)

![image](https://github.com/user-attachments/assets/b569fc07-48fa-45e9-a3ef-1925b1f7be68)

For POS the image has a CTA button to upload which is different from the save button for the form, do you think we should do something similar.  @dstrukt 

Cc. @dennisreimann

2024-09-27 07:47 UTC, dennisreimann requested changes

2024-09-27 07:47 UTC, dennisreimann commented on BTCPayServer/Storage/Services/FileService.cs
> +
If we abstract this (which is a good idea I think), we should make the max file size an argument and also rephrase th evalidation messages to use "image" instead of "logo".

2024-09-27 07:47 UTC, dennisreimann commented on BTCPayServer/Plugins/Crowdfund/Controllers/UICrowdfundController.cs
> +                newSettings.MainImageUrl = await _uriResolver.Resolve(Request.GetAbsoluteRootUri(), new UnresolvedUri.FileIdUri(imageUpload.file.Id));
This should be in an else clause then, right?

2024-09-27 07:47 UTC, dennisreimann commented on BTCPayServer.Abstractions/Contracts/IFileService.cs
> +    Task<(bool success, string response, IStoredFile file)> UploadImage(IFormFile file, string userId);
This interface is a bit unusual I'd say. Can you rework it to be mor elike what we e.g. have in `UserService.TryCanLogin`?

Somethink like: `Task<IStoredFile>(IFormFile file, string userId, out string error)`

2024-09-27 07:47 UTC, dennisreimann commented on BTCPayServer/Plugins/Crowdfund/Controllers/UICrowdfundController.cs
> +             [FromForm] bool RemoveLogoFile,
This should come last, do not reposition the existing command argument.

2024-09-27 07:47 UTC, dennisreimann commented on BTCPayServer/Plugins/Crowdfund/Controllers/UICrowdfundController.cs
> +                newSettings.MainImageUrl = await _uriResolver.Resolve(Request.GetAbsoluteRootUri(), new UnresolvedUri.FileIdUri(imageUpload.file.Id));
Also: Do not assign the resolved URL, but rather `new UnresolvedUri.FileIdUri(imageUpload.file.Id)`.

Resolve it when handing out the data to the view/API response.

2024-09-27 16:24 UTC, TChukwuleta commented on BTCPayServer.Abstractions/Contracts/IFileService.cs
> +    Task<(bool success, string response, IStoredFile file)> UploadImage(IFormFile file, string userId);
Hey @dennisreimann  I have updated it.. I created a new response model.. async process doesn't work with ref. 

You can review.

2024-09-28 06:22 UTC, dstrukt approved these changes
Alright, sounds good, then tACK - LGTM!

2024-09-30 17:00 UTC, dennisreimann reviewed
One more note: The image needs to get resolved here as well: https://github.com/btcpayserver/btcpayserver/blob/master/BTCPayServer/Controllers/GreenField/GreenfieldAppsController.cs#L435

2024-10-01 07:42 UTC, TChukwuleta commented
Hey @dennisreimann  the image has been resolved in the greenfield API

2024-10-01 12:05 UTC, dennisreimann approved these changes
tACK.

I've made a few adjustments, can you double-check them, @TChukwuleta?

2024-10-01 15:42 UTC, TChukwuleta commented
Ermm.. I notice that the crowdfund public link is now visible even without a description. Just wanted to point that out. 

I dont know if that's the case now @dennisreimann 

If it is, I noticed that the View button then disappears when I tried to update and description validation fails.


![image](https://github.com/user-attachments/assets/a01e88c5-b584-4cd6-9e11-fcc57b7603f2)

2024-10-01 16:02 UTC, dennisreimann commented
> Ermm.. I notice that the crowdfund public link is now visible even without a description. Just wanted to point that out.

Yes, you are right, should be fixed now.

2024-10-01 16:03 UTC, TChukwuleta commented
Okay. I'd take another look

2024-10-01 16:36 UTC, TChukwuleta commented
tACK.  All is fine now @dennisreimann

2024-10-03 01:39 UTC, merged